### ISSUE TITLE
[Quest] Anatoly Will Talk

### ISSUE THREAD

**Issue by Xpd1** [Stormforge-gg/Bugtracker-Fordring#1002]
**Description**: 
As i was supposed to escort Tatjana back to the camp (After tranquilizing her) i got off the mount to heal my friend and i was no longer able to remount. She just stood AFK here completely unable to interact with and after waiting for half an hour she neither moved nor did respawn. I think i managed to bug the quest out for entire server.

**Current behaviour**:
Tatjana just sits AFK after demounting while escorting her back and is no longer interactable with.
**Expected behaviour**: 
Unsure, probably should be allowed to remount or not be allowed to dismount at all.

**Revision**: 
I dont know what this means

**Comment by Wolffenstein** [comment]
Fixed in rev 1416.
