### ISSUE TITLE
[Quest] [Zone] [NPC] Return to Angrathar (Horde) - Numo Spiritbreeze 

### ISSUE THREAD

**Issue by GittyBruce** [Stormforge-gg/Bugtracker-Fordring#1004]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Numo Spiritbreeze is missing from Kor'Kron Vanguard after completing Return to Angrathar (Horde).
**Current behaviour**:
Angrathar Gate Quest Chain Removes Flightmaster NPC
**Expected behaviour**: 
>After a player completes [Return To Angrathar (Horde)](https://wowwiki-archive.fandom.com/wiki/Quest:Return_To_Angrathar_(Horde)), all NPCs will phase out of existence for that player and will no longer be available. Except for Numo Spiritbreeze, he will remain for flight services.

https://wowwiki-archive.fandom.com/wiki/Kor'kron_Vanguard

**Comment by Wolffenstein** [comment]
Fixed in rev 1418.
