### ISSUE TITLE
[NPC][Bloodmyst Isle] Bloodcursed Voyager

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1005]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
For some reason all of the sound effects that normally happen when an ability hits (see: iconic Sinister Strike sound) do not happen when you hit these guys.

https://youtu.be/5JAJz9v6pPs

Edit: The next one I killed had the same issue. The one after did not have this issue. The one after that did have this issue. Bizarre.

**Comment by Cold-Martijn** [comment]
I can reproduce this, but have no clue what could cause this.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
