### ISSUE TITLE
[Item] Small Barnacled Clam

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1006]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
It is currently possible for these to be empty. They should always have one clam meat in them, with a chance for other things. This should go for all clam items that are openable.

**Comment by FX-SF** [comment]
Some Slime -covered bags from oozes can  exhibit the same lack of contained items.

**Comment by Wolffenstein** [comment]
Fixed in rev 1454.
