### ISSUE TITLE
[NPC][Bloodmyst Isle] Webbed Creature

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1007]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The mobs that come out of these do not immediately aggro to you. In fact, you have plenty of time to run away so they never aggro.

They should immediately aggro.

**Comment by Vishiswaz** [comment]
More importantly: THESE DO NOT APPEAR TO BE RESPAWNING

**Comment by Cold-Martijn** [comment]
fixed in a future revision.
