### ISSUE TITLE
Argent Dawn Parachutes!

### ISSUE THREAD

**Issue by Secare69** [Stormforge-gg/Bugtracker-Fordring#1011]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Attempting to give parachutes to argent dawn members for "Parachute's for the Argent Crusade" impossible. as gargoyles not picking crusaders up and dropping them, thus removing the parachute.
**Current behaviour**:
Gargoyles not picking crusaders up and dropping them, thus removing the parachute.
**Expected behaviour**: 
Gargoyles picking crusaders up and dropping them, thus removing the parachute.
**Revision**:

**Comment by Cold-Martijn** [comment]
I made this working before, did it really break or should I just adjust the timer to let crusaders be picked up more often?

**Comment by Exorcista** [comment]
To be fair, on every server i've played the "fix" they implement is just whenever one of the guards enters combat it insta loses the chute making this quest more doable, but idk id preffer the actual event to happen lol

**Comment by Cold-Martijn** [comment]
> 

No, I ofcourse did the proper one. Please do test again, to make sure it works.

**Comment by Exorcista** [comment]
> 

gmates where saying was still broken early

**Comment by Cold-Martijn** [comment]
> 

please confirm if it works when the server is revision 1437 or higher. You can check it with the ingame command .server info
they should grab crusaders once in a while.....

**Comment by Exorcista** [comment]
confirmed working/doable today rev 1461

**Comment by Cold-Martijn** [comment]
> 

working sounds good, doable sounds bad. is it to your knowledge blizzlike? :) thanks for feedback!

**Comment by Exorcista** [comment]
> > 
> 
> working sounds good, doable sounds bad. is it to your knowledge blizzlike? :) thanks for feedback!

idk i never played retail, but was there when some gmates (i did the quest when was "undoable") where doing it and they could complete it, i did saw 1-2 gargoyles taking guards up
