### ISSUE TITLE
Betrayal - Zul'Drak

### ISSUE THREAD

**Issue by Secare69** [Stormforge-gg/Bugtracker-Fordring#1012]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When going to fight Drakuru, there's about 6 of him!
**Current behaviour**:
Several elite drakuru, all fighting you at once.
**Expected behaviour**: 
Only one drakuru!
**Revision**:

**Comment by Vishiswaz** [comment]
The issue is that the Drakuru that spawns as part of this quest chain isn't despawning after RP.
