### ISSUE TITLE
Of keys and Cages(Howling Fjord) does not share credit when in a party

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1013]
Description: While doing the quest ''Of keys and cages'' in Howling Fjord, the quest does not give credit for party members when opening cages.

Current behaviour: When opening cage, party members don't get credit.

Expected behaviour: Party members quest should advance when another member opens a cage

Revision:

**Comment by Tereneckla** [comment]
Fixed soon™
