### ISSUE TITLE
[Spell][Priest] Renew

### ISSUE THREAD

**Issue by fondlez** [Stormforge-gg/Bugtracker-Fordring#1015]
[Spell][Priest] Renew

**Description**: 
The cast from Priest's Renew spell alone is sufficient to gain aggro from a party member against a hostile target. 

**Current behaviour**:

The moment the combat log text appears with "%s gains Renew", but the heal has not even ticked once on the party member, the hostile target can switch aggro target to the Renew caster.

While the above unexpected behavior was only noticed on the Priest Renew, it may be affecting other Heal over Time ("HoT") player spells.

**Expected behaviour**: 

Excluding special behavior from scripts or some abilities, an increase in threat should be due to specific and measurable threat-ful activity such as healing causing half the threat of the amount healed.

All else being equal, no aggro target change should be possible from just casting a HoT spell like Renew. It needs to actually heal/tick first before threat calculations sufficient to cause an aggro target change can happen.

**Revision**: 
AtlantissCore WoTLK rev. 1406, c2bc13648d2a 2022-06-05 14:57:27 +0200 (lfg_fix branch) (Unix, Debug, Static)

**Comment by fondlez** [comment]
This does not seem to be a general issue of aura gain. Even when buffing during the start of a pull, I do not get the same aggro change. It is as if there's a specific hidden threat value for the aura gain of Priest's Renew. 

This leads to the ridiculous situation where Power Word Shielding as the combat starts - a very threatful activity because of the attribute changes to the player unit - effectively has _less_ threat than simply the cast of a spell that does nothing at all.

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
