### ISSUE TITLE
[Quest][Howling Fjord] Adding Injury to Insult

### ISSUE THREAD

**Issue by Majst** [Stormforge-gg/Bugtracker-Fordring#1016]
This quest does not complete unless you either do the majority damage or killing blow to the mob, and I am unsure which it is but it should not act this way. You are supposed to kite him to the npcs waiting to kill him and help you with it, and since it is a solo quest they are supposed to do the majority of the damage and commonly will get the killing blow.

**Comment by Tereneckla** [comment]
Fixed soon
