### ISSUE TITLE
[Quest][Howling Fjord] Alpha Worg

### ISSUE THREAD

**Issue by reetarded** [Stormforge-gg/Bugtracker-Fordring#1017]
When you accept the quest, the buff that the quest giver gives you to actually be able to see garwal transforms you out of your worg costume, and when you go back into your worg costume it removes the buff. The buff shouldn't be removed while changing forms.

I also cannot find him even with the buff, Garwal does not seem to exist anywhere he is supposed to. The quest seems like it is absolutely incompletable from what I see.

Edit: after sitting for 10 min he patted into me. From what I can tell he is patting in an area that is considered grizzly hills, but as soon as your cross the zone into grizzly hills your buff is removed from being able to see him, so you cannot go down there and kill him and the only way is to sit there until he pats into you in the howling fjord part of his patrol.

Edit2: Also leaving zone with buff on would cause your worg costume to disappear from your inventory.

**Comment by Tereneckla** [comment]
Fixed soon™
