### ISSUE TITLE
[Dungeon][NPC] Void Lord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#1018]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Killing Void Lord (the one that replaces Zuramat if the group kills him but wipes) before destroying void sentries doesn't despawn them. They persist and keep on shooting shadow bolt volleys until the group wipes. I don't know if the same issue exist in the case of Zuramat, because we actually destroyed all void sentries before killing him.

**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1461.
