### ISSUE TITLE
[Quest] [Dragonblight] Reclusive Runemaster and Mysteries of the Infinite

### ISSUE THREAD

**Issue by rathodkanishk** [Stormforge-gg/Bugtracker-Fordring#1019]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

[Mysteries of the Infinite] and [Reclusive Runemaster] in Dragonblight are currently bugged or behaving poorly.

**Current behaviour**:

[Mysteries of the Infinite] 
After placing the hourglass, and completing the quest objective, the quest would not complete. I tried doing this while in a part of 3 (where the other 2 got it completed but I didn't). After abandoning and re-accepting the quest, I tried to do it solo and still wasn't able to complete it. 

[Reclusive Runemaster]
This quest requires us to bring the quest NPC down to under 20% and wait until he reveals information to us. We performed the said objective, but the NPC never gave us the info and hence didn't complete the quest for us.

**Expected behaviour**: 

[Mysteries of the Infinite] 
Once the quest enemies have been killed and the hourglass has been successfully defended, the quest should complete (even if you are in a party) 

[Reclusive Runemaster]
This quest requires us to bring the quest NPC down to under 20% and wait until he reveals information to us. When he is under 20% he should reveal the said info and the quest should complete after which we can kill him.

**Comment by Tereneckla** [comment]
Reclusive Runemaster is fixed.
Please open separate issues for each bug in the future

**Comment by Tereneckla** [comment]
Fixed soon™
