### ISSUE TITLE
[Npc][Vendor] Duchess Mynx <Ebon Blade Quartermaster>

### ISSUE THREAD

**Issue by DraxerTABC** [Stormforge-gg/Bugtracker-Fordring#1020]
**Description**:  Duchess Mynx <Ebon Blade Quartermaster> isn't selling the Revered Reputation enchant Arcanum of Torment.

**Current behaviour**: Duchess Mynx isn't selling the Revered Reputation enchant Arcanum of Torment.

**Expected behaviour**: Duchess Mynx should be selling Arcanum of Torment.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1421.
