### ISSUE TITLE
Hunter Flare travel time

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1022]
**Description**:  Hunter's Flare is not working correctly.

**Current behaviour**: Flare is fired in the chosen location and travels to that location landing on the ground. The flare doesn't show stealthed targets until the animation has completed and the aoe light is on the targeted location.

**Expected behaviour**:  Flare should INSTANTLY reveal stealth in the AoE radius as soon as the shot is fired, not 1-10 seconds for the animation to finish. Imagine trying to flare on a rogue and he sees it and just moves out before the animation cancels -_-

**Revision**:

**Comment by slicplaya** [comment]
![WoWScrnShot_060522_192611](https://user-images.githubusercontent.com/6567001/172084461-eaf276ec-85aa-4fd8-a6ad-5ae4304c46ad.jpg)
![WoWScrnShot_060522_192614](https://user-images.githubusercontent.com/6567001/172084466-e6cd8cc9-99db-4839-8e20-e42a8441cb8f.jpg)
![WoWScrnShot_060522_192617](https://user-images.githubusercontent.com/6567001/172084467-c594de6a-2def-41d9-997e-bfc2022288cb.jpg)

**Comment by NatsumeLily** [comment]
I found this
https://github.com/dalaranwow/dalaran-wow/issues/1206

But also found 
https://www.wowhead.com/spell=1543/flare#comments:id=159529
![image](https://user-images.githubusercontent.com/15247730/172112944-183bdde4-4c27-404f-9ef0-d19a76ae55b0.png)

Might have been changed at some point between patches but I don't know.

**Comment by zinro** [comment]
This is to do with "spell batching" just like a agile rogue should be able to move away from Mage Blizzard ring edge before stealth breaks in between spell batch ticks.

**Comment by slicplaya** [comment]
I've legit played huntard for over a decade, and I can assure you, it's instant(the animation of flare isn't but the area of coverage is). Look at this video for an example. The rogue instantly comes out of stealth. https://clips.twitch.tv/UgliestRamshackleLettuceCurseLit

You can still(through spell batching) vanish and cheapshot in the flare, but it shouldn't have a legit 1-2 second delay plus 1-5 second animation travel delay. That would literally make the skill completely useless.

**Comment by slicplaya** [comment]
> I found this [dalaranwow/dalaran-wow#1206](https://github.com/dalaranwow/dalaran-wow/issues/1206)
> 
> But also found https://www.wowhead.com/spell=1543/flare#comments:id=159529 ![image](https://user-images.githubusercontent.com/15247730/172112944-183bdde4-4c27-404f-9ef0-d19a76ae55b0.png)
> 
> Might have been changed at some point between patches but I don't know.

This is true, as there is a rough 1 second delay inbetween old flares dissipating and a new one being cast. The crap i'm experiencing is legit 1-5 seconds delay because of the Flare animation travel time. Test it.

**Comment by Wolffenstein** [comment]
Fixed in rev 1435.

**Comment by slicplaya** [comment]
> Fixed in rev 1435.

Ty sir. Amazing speed btw.
