### ISSUE TITLE
[PET][DEATH KNIGHT] Incorrect behavior and status

### ISSUE THREAD

**Issue by Hotsmite** [Stormforge-gg/Bugtracker-Fordring#1023]
Description:
Death Knight pet (Ghoul) is the only one i've had the chance to test, but i assume its a pet behavior in general... So i strongly encourage checking out other classes aswell (Hunter, Warlock and Mage)

Current behaviour:
First issue: Status (aggressive, defensive or passive) resetting to aggressive on dismount and sometimes randomly (tho it is definitely a trigger of some kind i just havent caught) aswell as when spawned, tho i do not know if when spawned case is due to it being a new ghoul and default behavior is set to aggressive

Second issue: Petattack, right now the pet will attack on right click, party member (tank in dungeons as far as i've noticed) attacking and sometimes randomly aswell (might be on spell use, but havent been able to narrow down every single way yet)

Expected behaviour: 
First issue: Default pet status should be passive or defensive and save whatever status the player gave it last

Second issue: Petattack should only be happening through either pet bar clicking, keybound (also petbar), /petattack macro, aggressive status and defensive status ONLY if player/pet is hit by hostile target - just want to make it known that petattack should work regardless of status

Disclaimer:
I am not 100% sure these are bugs, but i've played a fair bit with pets and right now its attacking right, left and center causing alot of ninja pulling in dungeons

**Comment by Wolffenstein** [comment]
Fixed in rev 1428.
