### ISSUE TITLE
Laughing Sisters Do Not Give XP

### ISSUE THREAD

**Issue by xXOXONXx** [Stormforge-gg/Bugtracker-Fordring#1025]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
([Quest] Laughing Sisters)
([NPC] Laughing Sister) do not give experience points when killed.
**Expected behaviour**: 

**Revision**:

**Comment by Tereneckla** [comment]
Fixed in a revision soon to come
