### ISSUE TITLE
Son's of Hodir Exaulted Rep - Cannot see the Greater Inscriptions on the Vendor.

### ISSUE THREAD

**Issue by Ekt1112** [Stormforge-gg/Bugtracker-Fordring#1026]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
You can see the greater enchants when you are less then exalted rep, but you cannot once you are. Attached picture shows the change between Revered and Exalted. 
**Expected behaviour**: 
The exalted reputation enchants should be visible on vendor and only purchasable buy those who meet the requirements.
**Revision**: 
![128ee3dfac](https://user-images.githubusercontent.com/106929784/172109915-d7f9acef-4b06-437e-bf7e-ac52085ec87c.png)

**Comment by Wolffenstein** [comment]
Will be available from revision 1421.
