### ISSUE TITLE
[Class][Spell] Death Knight, Horn of Winter overriding

### ISSUE THREAD

**Issue by Nihaobeachez** [Stormforge-gg/Bugtracker-Fordring#1027]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Rank 1 Horn of Winter currently overrides Horn of Winter Rank 2

**Current behaviour**: Rank 1 Horn of Winter currently overrides Horn of Winter Rank 2

**Expected behaviour**: Rank 1 Horn of Winter should not override Horn of Winter Rank 2

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
