### ISSUE TITLE
[Rogue] Stealth

### ISSUE THREAD

**Issue by zinro** [Stormforge-gg/Bugtracker-Fordring#1028]
**Current behaviour**:
Applying Poisons to his/her own weapons while being stealthed breaks stealth.

**Expected behaviour**: 
Should not break stealth. https://wowwiki-archive.fandom.com/wiki/Poisons
Patch 1.10.0 (2006-03-28): Applying Rogue poisons will no longer break Stealth.

**Revision**: 
EDIT: clarify my sleepy report.

**Comment by slicplaya** [comment]
4Hed

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
