### ISSUE TITLE
Hunter skill: Master's Call doesn't work - Vital

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1029]
**Description**:  Master's Call doesn't even effect the player when cast **when pet is out of combat** but player isn't. This is an extremely vital skill for PvP and many other situations.
**Current behaviour**: Master's call doesn't effect the player when cast, or teammate, but it does effect the pet and gives immunity. There isn't even a immunity master call buff on the targets, only the pet.

**Expected behaviour**: When Master's call is cast on a friendly target or the player, the pet rushes to the target and removes ALL snares, roots, and movement impairing effects and makes them BOTH IMMUNE for the duration.

**Revision**:

**Comment by slicplaya** [comment]
It seems through spamming the skill, it only fails every few so often. hrmm

**Comment by Wolffenstein** [comment]
Fixed in rev 1425.
