### ISSUE TITLE
[Talent][Hunter] Endurance Training

### ISSUE THREAD

**Issue by aayboe** [Stormforge-gg/Bugtracker-Fordring#1031]
**Description**: 
Tested to see if Hit Points (HP) of character and pet increased after specializing Endurance Training, row 1 Beast Mastery.
HP did not increase.

**Current behaviour**:
Hit Points does not increase specializing Endurance Training.

**Expected behaviour**: 
Increase HP of character and pet speccing Endurance Training.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1439.
