### ISSUE TITLE
Quest bugged - Unable to be completed

### ISSUE THREAD

**Issue by Sukkerfugl** [Stormforge-gg/Bugtracker-Fordring#1032]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest name: Reclusive Runemaster
https://www.wowhead.com/quest=12150/reclusive-runemaster
**Current behaviour**:
Currently the NPC dies when attacked.
**Expected behaviour**: 
The NPC is supposed to become untargetable and "give up" and announce the name of the new Magnataur warleader. 
**Revision**: 
The NPC needs to be fixed so that he doesn't die when brought to 0% hp but instead stops at 5% or whatever, and tells you his secret so you can get the quest completion.

**Comment by Tereneckla** [comment]
Fixed
