### ISSUE TITLE
[Quest][Icecrown] Amped For Revolt - Fringe Science Benefits

### ISSUE THREAD

**Issue by Vaash** [Stormforge-gg/Bugtracker-Fordring#1034]
([NPC] Rizzy Ratchwiggle)

**Description**: 
The quest requires you to talk to said NPC to board flying machine and bomb Scourge's Forces below.

**Current behaviour**:
Said NPC can't be talked to so you can't board the flying machine

**Expected behaviour**: 
NPC should be allowing playing to talk to her to board flying machine

**Revision**:

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/256

duplicate.
