### ISSUE TITLE
Parts for the job in new agamand

### ISSUE THREAD

**Issue by GGlitchboi** [Stormforge-gg/Bugtracker-Fordring#1035]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Parts for the job in new agamand where you have to kill Shoveltusks
**Current behaviour**:
the drop rate is 0% i think, 30 min of farming groups of 5-6 mobs drop nothing!!
**Expected behaviour**: 
every group Shoveltusks should at least drop 3 Ligament...
**Revision**:

**Comment by Tereneckla** [comment]
You were unlucky, but I increased the drop rates a bit
