### ISSUE TITLE
[PET] Pet "freezes" after dismounting in flight

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1036]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: After dismounting in flight pet freezes in places and player is unable to control it. Very annoying bug.

**Current behaviour**: After dismounting in flight pet freezes in places and player is unable to control his pet.

**Expected behaviour**: Pets should work normally when player dismounts a flying mount.

**Revision**: 1424

**Comment by Nuy** [comment]
> Could you record a video of it happening?

https://www.twitch.tv/videos/1496463079

You can see that even pet ability bar disappeared and pet become controllable again after few seconds. It doesn't always bug out like that and sometimes when it does you don't regain control over your pet until you remount and dismount again.

**Comment by Wolffenstein** [comment]
Should be a bit better after next update
