### ISSUE TITLE
Rivenwood Captives (Howling Fjord) doesn't share credit with group members when freeing allies from webs.

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1037]
**Description**:  Party members don't get credit when another party member frees someone from the webs.

**Current behaviour**: Party members dont increment the quest when other members free webbed ppl.

**Expected behaviour**: party member quest should increment when other members free webbed ppl

**Revision**:

**Comment by Tereneckla** [comment]
Fixed soon™
