### ISSUE TITLE
Apply Heat and Stir (Howling Fjord) Success chance is too low.

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1039]
**Description**: The success chance for creating the potion during the quest ''Apply heat and Stir'' is way too low. It took me about 50 tries before i successfully completed it.

**Current behaviour**: Success chance is too low.

**Expected behaviour**: Success chance should be increased substantially.

**Revision**:

**Comment by Godmatik** [comment]
I think blizzlike... do you have proof on what the success rate should be?

**Comment by eryczek1615** [comment]
![image](https://user-images.githubusercontent.com/4455568/172443943-a3a145c7-e802-46f2-9c19-0fc85ccd592b.png)
Seems blizzlike

**Comment by ameliandra** [comment]
Well thats unfortunate, but the fact is that even though its not blizzlike, it would still be a nice QoL upgrade to change it to be less horrible.
