### ISSUE TITLE
Parts for the Job (Howling Fjord), drop rate on the ligaments too low.

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1040]
**Description**: The drop rate on shoveltusk ligaments is too low. It took around 50-60 mobs to get all 6 of them.

**Current behaviour**: Drop rate of ligaments is too low.

**Expected behaviour**: The drop rate of ligaments should be increased.

**Revision**:

**Comment by Tereneckla** [comment]
Drop rates are increased in a revision soon
