### ISSUE TITLE
The Book of Runes (Howling Fjord), the chapters don't drop for all group members when one of them drops.

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1041]
**Description**: During the quest ''The book of runes'', when a chapter drops, only a single member of a party can loot it.

**Current behaviour**: When a chapter drops, only 1 member of the party can loot it.

**Expected behaviour**: All party members should be able to loot a chapter when it drops.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
