### ISSUE TITLE
Seeds of the Blacksouled Keepers (Howling Fjord), quest credit isn't shared between party members when someone freezes a spore. Additionally, the quest indicator points to the wrong area on the map.

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1042]
**Description**: When someone in a party freezes a spore, the rest of the party doesn't get quest credit. Also, the quest indicator points to the wrong area to complete the quest. It points to camp winterhoof instead of the quest area.

**Current behaviour**: Freezing a spore doesn't increment the quest for everyone in the party. The quest indicator points to the wrong area.

**Expected behaviour**: Freezing a spore should increment the quest for everyone in the party. Quest indicator should point to the proper area. 

**Revision**: 
![seeds](https://user-images.githubusercontent.com/13498094/172174400-fae13f15-5c1b-4053-bc18-95ccd9ce3299.jpg)

**Comment by Tereneckla** [comment]
Fixed soon™
