### ISSUE TITLE
[Core] Client Crashes or DCs during Flight Truncate Flight Path

### ISSUE THREAD

**Issue by GittyBruce** [Stormforge-gg/Bugtracker-Fordring#1044]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If the client crashes or, if the server crashes while the player is in flight, then on restart the flight truncates at the next flight master. Player is charged for full flight.
**Expected behaviour**: 
Flight path should continue until their selected destination.
**Revision**:

**Comment by Exorcista** [comment]
confirming this, also freezes sometimes when landing to destination, like phasing and you have to relog

**Comment by Cold-Martijn** [comment]
im decently sure this is not a bug. logging out (crashing client, crashing server, alt f4, whatever) should stop at the next possible flightmaster i believe.

**Comment by Exorcista** [comment]
> im decently sure this is not a bug. logging out (crashing client, crashing server, alt f4, whatever) should stop at the next possible flightmaster i believe.

tbh it happens to me quite often when in vanilla zones only, never happened in NE for example
