### ISSUE TITLE
Rogue crit and Agility not scaling correctly or working at all. 

### ISSUE THREAD

**Issue by frescajr1** [Stormforge-gg/Bugtracker-Fordring#1047]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Rogue is not only 5-6% below crit while leveling. Agility is not playing into the factor. currently 8% crit according to agility and level 23 rogue with 2.7% crit which is below even passive crit. Please view both of the screen shots.
**Current behaviour**:
https://gyazo.com/0fd3774cab3f10137ea6164344bb40d3

https://gyazo.com/76f76e8f41ba5b321e33b34ff11f68b8
**Expected behaviour**: 

**Revision**:

**Comment by Tereneckla** [comment]
Was your weapon skill maxed out?

**Comment by haephaistoss** [comment]
To me this looks like a low wep skill issue

**Comment by frescajr1** [comment]
i mean do i need to get unarmed up to max skill too?

**Comment by frescajr1** [comment]
because everything has been maxed
