### ISSUE TITLE
[Spell/Talent] Brain Freeze - Frostfire bolts proceed from it can proc another Brain Freeze

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Fordring#1048]
**Currently** 
Frostfire Bolts you cast from a Brain Freeze proc has a chance to proc another Brain Freeze

**How it should work**
Frostfire bolts you cast from Brain Freeze should not allow you to cast another instant one right away, there should be a small internal cooldown to prevent it.

> World of Warcraft: Wrath of the Lich King [Patch 3.3.3]: This talent now allows your next Fireball or Frostfire Bolt to be instant and cost no mana. There is a small internal cooldown to keep the Frostfire Bolt from immediately triggering Brain Freeze again.

**Comment by Wolffenstein** [comment]
And what exactly does "small" mean in this case? 1s? 5s?

**Comment by Wolffenstein** [comment]
Fixed in rev 1429.
