### ISSUE TITLE
Greater blessings fall off of hunter pets when mounting/dismissed

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1050]
**Description**: Greater blessings from paladins are removed when a pet is dismissed or the player mounts.

**Current behaviour**: Greater blessings from paladins are removed when a pet is dismissed or the player mounts.

**Expected behaviour**: The buff should persist through any form of dismounting or dismissing as long as the player is still in the group with the paladin.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1430.
