### ISSUE TITLE
Hearthstone getting used on exiting Wintergrasp

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1051]
**Description**: Hearthstone is getting used when exiting Wintergrasp

**Current behaviour**: Hearthstone is getting used when exiting Wintergrasp

**Expected behaviour**: It shouldn't use the cooldown of Hearthstone when exiting Wintergrasp via the minimap button. Also, as side note, the CD doesn't grey out and show that it's on CD unless relogging. It's hard to test this with a 30 minute cd.

**Revision**:

**Comment by Vishiswaz** [comment]
Nope that's correct. You must be used to bugged servers.

**Comment by Cold-Martijn** [comment]
not a bug, if you check/search the changelog you can see it was added on purpose.

**Comment by slicplaya** [comment]
> Nope that's correct. You must be used to bugged servers.

mentioning bugged servers when there are still many here. hrmm

**Comment by Vishiswaz** [comment]
Um. At what point, while commenting on a bug tracker with nearly 300 open bug reports, many of which are my own, did you think I was implying there are no bugs here?

I was referring to this specific thing, which is bugged on many other servers.
