### ISSUE TITLE
Entering Portals puts Hearthstone on CD

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1052]
**Description**:  Entering Portals puts Hearthstone on CD

**Current behaviour**: Entering Portals puts Hearthstone on CD

**Expected behaviour**: Entering a portal should NOT put your hearthstone on Cooldown. -_-

**Revision**:

**Comment by Vishiswaz** [comment]
Any specific portals you've encountered this with? Dalaran portals? Mage portals? Portals to Blasted Lands from major cities? Wintergrasp portal?

**Comment by slicplaya** [comment]
My friend and I both experienced the CD going through a portal to Orgrimmar from Dalaran.

**Comment by Wolffenstein** [comment]
You probably exited wintergrasp through the minimap icon which puts hearthstone on cooldown
