### ISSUE TITLE
[Quest][NPC][Borean Tundra] The Emissary

### ISSUE THREAD

**Issue by Exorcista** [Stormforge-gg/Bugtracker-Fordring#1054]
**Description**: 
Npc called Leviroth (https://www.wowhead.com/npc=26452/leviroth) Upon being speared, hits like a truck from about 2k to 4k being probably overtuned, also seems to hit faster than it should

**Current behaviour**:

He just one shots the avg player since does so much dmg and super fast

**Expected behaviour**: 

Nerf his dmg , in this video from wotlk player is hit for arround 400-500 as Pala: https://www.youtube.com/watch?v=_SlAheX4b1o

**Revision**:

**Comment by Tereneckla** [comment]
Fix soon to come
