### ISSUE TITLE
Dropping combat after PvP kills is instant and incorrect

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1055]
**Description**: Dropping combat after PvP kills is instant and incorrect.

**Current behaviour**: Currently, after killing someone in PvP combat drops instantly.

**Expected behaviour**: https://wowpedia.fandom.com/wiki/Combat    - In [PvP](https://wowpedia.fandom.com/wiki/PvP), a player will leave combat if they have not attacked or been attacked for 6 seconds, or all the enemy characters that have attacked you are killed.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1432.
