### ISSUE TITLE
The Iron Colossus quest in Storm Peaks is not working.

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1056]
**Description**: When you engage the iron colossus with your jormugandr worm, the colossus constantly fills back up to 100% making the quest impossible to complete.

**Current behaviour**: The quest mob fills back to full health every few seconds.

**Expected behaviour**: The quest mob shouldn't health to full every few seconds.

**Revision**:

**Comment by FX-SF** [comment]
Similar issues: #776 #358 #225
@Evolvee

**Comment by Evolvee** [comment]
@Cold-Martijn ?

**Comment by Evolvee** [comment]
fixed in next rev
