### ISSUE TITLE
[Quest][Event][Howling Fjord] The Jig is Up - event doesn't reset

### ISSUE THREAD

**Issue by OniHouse** [Stormforge-gg/Bugtracker-Fordring#1057]
Current behaviour:
[Bear](https://www.wowhead.com/npc=24547/hozzer) just doesn't reset. Event works 100% but after ["Mad" Jonah Sterling](https://www.wowhead.com/npc=24742/mad-jonah-sterling) jumps down and, bear devours him bear won't reset.

Expected behaviour:
It should reset and go back to his start position and go baack to sleep after Jonah respawn.

Edit: This has been reported before and closed, but it still appears to happen.

**Comment by Cold-Martijn** [comment]
what.. the... fuck... another issue i fixed previously....

**Comment by Cold-Martijn** [comment]
Probably i forgot to send my fix, tweaked it and will be fixed soon when it gets uploaded.
