### ISSUE TITLE
[Quest][Grizzly Hills] We Have the Power

### ISSUE THREAD

**Issue by reetarded** [Stormforge-gg/Bugtracker-Fordring#1059]
Both rune-smith durar and rune-smith kathorn are not dropping the power cell when killed.

Edit: figured out it does not drop in group and only drops when solo, needs to be fixed.

Edit2: they did not drop it when someone else helped attack the mob even when not partied, to get it to drop the person has to do all the damage to the mob themself it looks like. Some weird parameters to get the quest item to drop for this quest.

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
