### ISSUE TITLE
[Class][Rogue] Stealth

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1065]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Stealth currently isn't being broken by taking fall damage. It should. All damage should break stealth.

**Comment by NatsumeLily** [comment]
https://wowwiki-archive.fandom.com/wiki/Fall_damage?oldid=2113369

"Fall damage no longer causes [rogues](https://wowwiki-archive.fandom.com/wiki/Rogue) to lose [Stealth](https://wowwiki-archive.fandom.com/wiki/Stealth)."

![image](https://user-images.githubusercontent.com/15247730/172306688-49eba1ef-f937-417e-8d52-5e29cd8e548a.png)
https://www.wowhead.com/spell=1784/stealth#comments:id=522868

**Comment by Vishiswaz** [comment]
Well. Interesting. Alright then.
