### ISSUE TITLE
[Talent][Priest] Grace

### ISSUE THREAD

**Issue by asprintab** [Stormforge-gg/Bugtracker-Fordring#1067]
**Description**: 
https://wotlkdb.com/?spell=47517 does not to apply https://wotlkdb.com/?spell=47930

**Current behaviour**:
Casting flash heal, greater heal, or pennance does not apply the grace buff/debuff.

**Expected behaviour**: 
After the heal heals, grace would be applied

**Revision**:  AtlantissCore WoTLK rev. 1435, 5d295acbc5ad 2022-06-06 22:25:19 +0200 (master branch) (Unix, Debug, Static)

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/172387627-d392fac6-00ad-46e3-8e2e-cbda91143f45.png)
Works fine for me.
