### ISSUE TITLE
[Quest][Grizzly Hills] Free at Last!

### ISSUE THREAD

**Issue by reetarded** [Stormforge-gg/Bugtracker-Fordring#1070]
This quest does have a low chance of turning the runed giants friendly, but you are supposed to be able to keep retrying on the same mob over and over again while it is weakened, and not only being allowed to use the zapper on elite versions. You are supposed to zap the same mob like 6 times over and over until it becomes friendly.

**Comment by Tereneckla** [comment]
Fixed soon™
