### ISSUE TITLE
[Zone] Nothshire Valley [NPC] Diseased Young Wolf - As a warlock, the NPC is neutral to player but hostile to Imp.

### ISSUE THREAD

**Issue by Nash124** [Stormforge-gg/Bugtracker-Fordring#1071]
[Zone] Nothshire Valley
[NPC] Diseased Young Wolf
If you walk near the NPC with your Imp, the Imp gets targeted and attacked by the NPC, despite being on passive/defensive. This doesnt happen when the player stays near the NPC. Therefore the NPC is hostile towards the Imp but Neutral towards the player.

**Comment by Wolffenstein** [comment]
Fixed in rev 1444.
