### ISSUE TITLE
frost mage issues

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1079]
Some issues I've noticed lvling on Fordring.

- frostbite / fingers of frost not proccing together
- 3x fingers procs being consumed in certain scenarios
- fireball proccing triggers (maybe fixed)
pet cast bar is being interrupted when using ability
- wele dmg (too high?)
- dead pet cannot be dismissed and cannot summon new pet until dead pet despawns
- clearcasting not applying to spells quickly
- clearcasting consume time (blizzard notibly)
- winter's chill application delay
- blizzard interruption by auto-attack

Some of these issues probably need more context.

**Comment by Wolffenstein** [comment]
One report = one issue please and without elaborating im not going to even dive into it
