### ISSUE TITLE
[Quest][Zul'Drak] Hazardous Materials

### ISSUE THREAD

**Issue by reetarded** [Stormforge-gg/Bugtracker-Fordring#1083]
This quest up in voltarus has you collect 5 boxes of harvested blight crystals in the building, but there are only 5 spawns and they take a decent amount of time to respawn. If you are leveling with 4 people you have to wait for 4 whole rotations of the 5 boxes to respawn, I think the respawn should be lowered to accommodate groups and if multiple people are doing the quest at the same time.

**Comment by Tereneckla** [comment]
Fixed soon™
