### ISSUE TITLE
[Quest] Foolish Endeavors (11705)

### ISSUE THREAD

**Issue by seitzcasey** [Stormforge-gg/Bugtracker-Fordring#1084]
**Current behaviour**:
Gentry Dies after a short while which fails the quest.

**Expected behaviour**: 
Gentry doesn't die and Saurfang kills the mobs

**Revision**: 
1435

**Comment by Soufly** [comment]
Varidus gains the shield on him,thats why he is dying slowly... please fix.

**Comment by Tereneckla** [comment]
Fixed soon™
