### ISSUE TITLE
[Quest][Hellfire Peninsula] Natural Remedies

### ISSUE THREAD

**Issue by ZzioO** [Stormforge-gg/Bugtracker-Fordring#1086]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description*https://tbc.wowhead.com/quest=10351/natural-remedies*: 

 using quest item doesn't spawn questmob:

**Comment by Tereneckla** [comment]
Fixed soon™
