### ISSUE TITLE
Heroic Dungeons are overtuned to the point, that it feels like mythic+ 25

### ISSUE THREAD

**Issue by wedris** [Stormforge-gg/Bugtracker-Fordring#1089]
**Description**: 
I've talked through this in discord, but here is an example
http://puu.sh/J4wt2/caff06c204.jpg
this is the Brann event. 
We couldn't do it, because if you fall behind once (this is the point of this fight) you are not able to get back. There is no way.
Also the constant ticking damage is just not ok, for certain healers to heal (pala is completely in the shitter there).

The same happenens with almost all trash in every dungeon so far.
DK's are getting shredded (60%+ armor DR + CD) // warriors without shield block are just dead meat 

Some modifier are not really scaling well (attack speed + dmg increase), so you get clapped with 90%+ DR as tank.
I've done 4 dungeons now, and all of them were with a holy Paladin.
Druid for example (in violet hold), is not able to heal a boss. They do too much damage - as described above - and they are not tank healers. So you wipe 99% of the time.

If you check the mechanics here + comments:
https://www.wowhead.com/npc=29315/erekem#abilities;mode:heroic

Boss does something specific if you kill a mob (stormstrike). This spell goes to the point you take 20-30k damage in 1-2s depending on your current armor / cds up. So you are not able to kill 1 add and after that the other (chain heal exists and does too much to get 1 low).
But if you tank all 3 at the same time, you take also too much damage (constant melee hits + bloodlust from boss/adds).

If more examples are needed to nerf dungeons across the board, tell me which I should test and I provide it, because currently this feels awful to play.

**Comment by wedris** [comment]
I also received this from a guildie:
"can you bring up the snake boss in gundrak being bugged?
The stuns don't go away when you break the people out"

**Comment by wedris** [comment]
Another Dungeon: Halls of Stone
"Hos last boss lightning shield triggers on casts
Only supposed to be on melee hits"

**Comment by FX-SF** [comment]
@wedris Create new tickets for both these issues and pls follow the format. If you have any questions, feel free to ask me or others in discord

**Comment by Amun12** [comment]
I agree about HoS (tribunal), it's extremely difficult and needs some nerfing. As for trash, some of them could probably use nerfing, however in many cases you could use crowd control to minimize damage on your tanks (sheep, trap, fear, shackle, repentance, chains of ice etc...).

**Comment by Wolffenstein** [comment]
None of the things you mentioned are a result of tuning, it looks like some things are just bugged and i would appreciate proper reports about them rather than one giant assumption post

**Comment by Wolffenstein** [comment]
Pushed fixes in 1442. If there's any new ones please open a separate issue for each one

**Comment by wedris** [comment]
https://www.twitch.tv/videos/1497131073

**Comment by Exorcista** [comment]
tried Brann in HOS today heres my take:

-Dwarfs cleaving 20k? Sure any heal can heal that in current gear pfff get gud
-Fire beam ticks hit 6k and you have to move instantly!
-Dwarfs also charge repeatedly and can pick all of them the same target thus 1shotting anyone since theyr charge hits 3k++
-If you're a Druid you will aggro all packs just by hots aggro, Pala cant heal this event AT ALL

**Comment by Nihaobeachez** [comment]
Did HoS without issue, even with 4 Melees on Bran event. Sounds more like skill issue tbh. Nobody was geared
