### ISSUE TITLE
[Stormwind][Fishing] Fish randomly get away without the blobber making any movement

### ISSUE THREAD

**Issue by Nash124** [Stormforge-gg/Bugtracker-Fordring#1091]
When you start fishing the old bobbers sometimes do not disappear and seem to cause problems with the current fishing process: The fish "get away" but the bobber didnt move at all.
At some point you have to wait for all bobbers to disappear to be able to fish normally again.

Additionally, unlike all other professions, fishing skill does not increase with x3.

Video: Starts with some issues, ends with the problem occurring more frequently.
(if video > 2min long, skip first 50 seconds - youtube is progressing very slowly today)
https://youtu.be/2U8QYylnfYU

**Comment by FX-SF** [comment]
similar to #992 

I am told from discord:
- Increased chance to level up per catch is increased x3. 
- You will not level up x3 on any catch.

**Comment by Viryll** [comment]
So the blobber problem works like this:
Use fishing to spawn #1st blobber.
Use fishing to spawn #2nd blobber.
Game should ignore w/e happens to first blobber. What happens in game if your first blobber catches a fish and it gets away. It will cancel your 2nd blobber.
