### ISSUE TITLE
[Quest][Zul'Drak] Parachutes for the Argent Crusade

### ISSUE THREAD

**Issue by Pudjero** [Stormforge-gg/Bugtracker-Fordring#1092]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Sky terrors arent pulling crusaders to the sky so quest is kinda of uncompletable

**Current behaviour**:
Sky terrors arent pulling crusaders to the sky so quest is kinda of uncompletable
**Expected behaviour**: 
Sky terrors must pull crusaders to the sky so they will use parachute and player could use parachute bag on him again 

**Revision**: https://www.wowhead.com/quest=12740/parachutes-for-the-argent-crusade

![изображение](https://user-images.githubusercontent.com/66913785/172397991-c64b5c84-37d1-4dfc-a1be-13a1041baf5d.png)

As we see on screenshot they just fly around and dont interact with crusaders

**Comment by Wolffenstein** [comment]
Should be fixed in rev 1437.
