### ISSUE TITLE
[Zone][NPC] Drak'tharon Keep Scourge Brutes and troll defenders 

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1094]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Scourge Brutes and troll defenders that fight them at the last corridor don't go back to their original spots after players wipe on them.

**Current behaviour**: Scourge Brutes and troll defenders that fight them at the last corridor don't go back to their original spots after players wipe on them.

https://www.wowhead.com/npc=26623/scourge-brute

**Expected behaviour**: Scourge Brutes and troll defenders that fight them at the last corridor should go back to their original spots when players wipe on them.

**Revision**: 1445

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
