### ISSUE TITLE
frostbite / fingers of frost not proccing together

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1095]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
frostbite and fingers of frost have a 15% chance to proc off freezing spells, and should proc together.
**Current behaviour**:
Frost effects have a 15% chance to apply frostbite and a 15% chance to apply fingers of frost, but these effects can proc individually.
**Expected behaviour**: 
When Fingers procs, you should get a frostbite proc, assuming no mob immunitys / player DRs.

Reference: https://www.youtube.com/watch?v=OR-bIxvAzR0
**Revision**:

**Comment by Wolffenstein** [comment]
i dont understand this report

**Comment by Wolffenstein** [comment]
Fixed in rev 1448.
