### ISSUE TITLE
Fire Upon the Waters ID: 12243 not working

### ISSUE THREAD

**Issue by GGlitchboi** [Stormforge-gg/Bugtracker-Fordring#1098]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Fire Upon the Waters quest where you kill captain shely in the boat
in new hearthglen- dragonblight
**Current behaviour**:
when you set the folly on fire the crow supposed to become distracted for 2 min
**Expected behaviour**: 
the duckhands did not get distracted, so you can slip past them to the captain
**Revision**:

**Comment by Tereneckla** [comment]
Fixed soon™
