### ISSUE TITLE
[Item] Mana Agate

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1099]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I just got this item as a drop off the rare mob Vultros. That should not be possible.
![WoWScrnShot_060722_112115](https://user-images.githubusercontent.com/78314117/172418869-b943f9af-7bf5-4cc1-b2a4-331184c2463d.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 1446.
