### ISSUE TITLE
boss / elite mob CC immunity

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1100]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bosses and elite mobs have inconsistent immunities to CC.

**Current behaviour**:
Bosses and elite mobs will randomly be able to be effected by cc (tried with stuns / roots / slows). 
For example, the last boss of utgarde keep Ingvar the Plunderer can be stunned / rooted / slowed in his second form. His first form does not have this characteristic. Group kill quests will also have this inconsistency. A 2 player quest in Dragonblight is significantly harder than a 5 player quest because the mob is immune to all forms of CC. Every boss in zuldrak arena excluding the last one can be stunned / slowed / rooted.

**Expected behaviour**: 
Most bosses should not be effected by CC. Elite mob inconsistency feels strange.
**Revision**:

**Comment by Wolffenstein** [comment]
There is no general rule or implementation, which means every mob that you suspect to have incorrect immunties need to be reported individually.

Ingvar undead form immunities will be fixed in rev 1446.
