### ISSUE TITLE
[Inscription] Incorrect loot from milling

### ISSUE THREAD

**Issue by EtheriousNW** [Stormforge-gg/Bugtracker-Fordring#1101]
Description: 

Milling, a sub-skill of Inscription, is used to make pigments from herbs which can be obtained via the Herbalism skill. Five herbs of the same type are consumed per milling attempt and produce 1-4 pigments, with the most common result being a single pigment milled. Higher level herbs may also occasionally produce rarer pigments.

Current behaviour:

At the moment, whenever you are doing Milling on Flower, you are geting one type of the pigments, which shouldnt be the case. (Whenever you get the rare pigments , the 100% Drop chance Pigments are not dropping)

Expected behaviour:

Whenever you do the Milling, you should get 100% the common Pigments, and bonus chance of geting the rare pigments from the same flowers drops
 i`ll take Adders tongue as Example, so, whenever u Mill 5 Adders Tongue, you  need to get 100% Azure Pigments 2-4 (The common ones), and there is a bonus chance of 50% to get additional Icy pigments (the rare pigments) 2-4

**Revision**:  1445

**Comment by EtheriousNW** [comment]
"The number of Drops are correct, just Azure pigments needs to be 100% on every 5 milled flowers, you shouldnt loose the Azure pigments because of the Icy pigments Drop"

**Comment by Wolffenstein** [comment]
Fixed in rev 1448.
