### ISSUE TITLE
Winter's Chill application delay

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1103]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Winter's Chill should apply to mobs immediately upon receiving frost damage.
**Current behaviour**:
Winter's Chill has a small delay before application after the target is damaged by frost attacks.

**Revision**:

**Comment by Wolffenstein** [comment]
Delay is intended
