### ISSUE TITLE
[Talent][Priest] Improved Power Word: Fortitude

### ISSUE THREAD

**Issue by Str3g4ttO** [Stormforge-gg/Bugtracker-Fordring#1105]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
It seems that the talent "<a href="https://tbc.wowhead.com/spell=14767/improved-power-word-fortitude" target="_blank">Improved Power Word: Fortitude</a>" doesn't work properly.
When I activate it (Rank 2) the spell "<a href="https://tbc.wowhead.com/spell=1244/power-word-fortitude" target="_blank">Power Word: Fortitude</a>" should increase Stamina by 10 points (at my level) instead of the base 8 points of the spell.

The info window of the spell tells that the Stamina will be increased by 10 points (correctly) but the actual value added to my Stamina is of 8 points.
It can be seen on the Buff itself, and in che Character window (Base Stats tab)

**Current behaviour**: 
The spell "<a href="https://tbc.wowhead.com/spell=1244/power-word-fortitude" target="_blank">Power Word: Fortitude (Rank 2)</a>" increase the Stamina by 8 points even though the talent "<a href="https://tbc.wowhead.com/spell=14767/improved-power-word-fortitude" target="_blank">Improved Power Word: Fortitude (Rank 2)</a>" is active

**Expected behaviour**: 
The spell "<a href="https://tbc.wowhead.com/spell=1244/power-word-fortitude" target="_blank">Power Word: Fortitude (Rank 2)</a>" should increase the Stamina by 10 points (8 + 30%) because the talent "<a href="https://tbc.wowhead.com/spell=14767/improved-power-word-fortitude" target="_blank">Improved Power Word: Fortitude (Rank 2)</a>" is active

**Revision**:

**Comment by Vishiswaz** [comment]
The buff tooltip is not accurate.

Check your character's stats before and after.

**Comment by Godmatik** [comment]
This is blizzlike and has existed since vanilla, the buff icon will not visually reflect the gain from talents, but you do gain the extra stamina.

**Comment by haephaistoss** [comment]
Buff tooltips in wotlk don't update.

Check your actual values
