### ISSUE TITLE
 [Quest][NPC](Grizzly Hills) Filling the Cages/Budd

### ISSUE THREAD

**Issue by OniHouse** [Stormforge-gg/Bugtracker-Fordring#1108]
Description:
[Budd](https://www.wowhead.com/npc=26422/budd) (NPC ID : 26422)'s stealth doesnt work, so when he tries to stun/sap the trolls he gets seen instead and starts fighting them. If you try to sap the mob for him, he will still fail his sap, freak out and run away > despawn.

Current behaviour:

Budd cant stealth properly and this gets seen when trying to sap mobs.

Expected behaviour:

Budd uses stealth properly, doesnt get seen and stuns/sap[s the mob so you can capture it with the quest item cage.

**Comment by OniHouse** [comment]
a workaround for anyone who happens to see this before it gets fixed: Kill a troll and wait for it to respawn > instantly tell Budd to sap it when it respawns > he will succeed because it takes a few seconds for mobs to be able to aggro on anything after spawning (including budd)

**Comment by nevrozac** [comment]
Issue was still present on 12th June which I assume was a later revision than 1470 which shouldhave contained a fix

Budds ability wouldn't work when he was further from a troll than around 10-15yards. When he would be close enough to use the ability he wouldn't enter stealth to stun a target but instead he would run towards it and get attacked which prompted him to enter combat
