### ISSUE TITLE
[Dungeon][NPC][Drop] Gul'darah

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#1112]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  I believe there is a loot bug related to this boss specifically.( as it only happened to me twice and both times here), It doesn't matter if you need,greed or pass items, the loot doesn't get distributed, it remains on the corpse and can be freely looted off it.

**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1452.
