### ISSUE TITLE
dead water elemental dismiss bug

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1113]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When your water elemental dies, it cannot be dismissed. This also prevents you from summoning a new pet. Possibly affects other pets, but only tested with water elemental.

**Current behaviour**:
Trying to dismiss the pet by clicking the frame --> dismiss does not work. Using the script 
          /script PetDismiss()
also does not work on a dead pet.
**Expected behaviour**: 
The script or frame dismiss should work, then a new pet can be summoned.
**Revision**:

**Comment by Wolffenstein** [comment]
I can reproduce not being able to dismiss but i can resummon the mob just fine, am I missing something?
