### ISSUE TITLE
Wintergrasp completion honor while dead

### ISSUE THREAD

**Issue by Topsquad** [Stormforge-gg/Bugtracker-Fordring#1115]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Wintergrasp completion honor while dead
**Current behaviour**:
Currently it is most likely like you don't get any honor from Wintergrasp while being dead
**Expected behaviour**: 
Well, obviously, in case you got the rank of course you should indeed get honor.
**Revision**:

**Comment by Wolffenstein** [comment]
Will be fixed in rev 1451.
