### ISSUE TITLE
[Quest][Bloodmyst Isle] Razormaw

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1116]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
1. Razormaw hits for WAY too hard for a level 21 2-person group quest.
2. It appears to be flying in the ground as opposed to standing on it.

**Comment by Vishiswaz** [comment]
.... I alt-tabbed back into the game to find Razormaw spawned and my toon dead.

**Comment by Vishiswaz** [comment]
I think the issue is if you die to him and he is no longer in combat, before he despawns he looks like he's flying on the ground.

**Comment by Cold-Martijn** [comment]
Reduced his damage multiplier drastically and tried to fix the animation. Works for me now.
If he hits like a wet noodle now, don't blame me, but make a new report please.
