### ISSUE TITLE
[Quest][Icecrown] Scourge Tactics

### ISSUE THREAD

**Issue by reetarded** [Stormforge-gg/Bugtracker-Fordring#1120]
One of the most bottlenecked quests I've experienced so far. If there is multiple people questing in the zone like there usually will be for the opening icecrown quest chain, this quest takes forever.

The webs need to respawn more quickly, and they do not share credit in a party so every person in the group has to free 8 on their own. Leads to a giant backup of 6 people flying around trying to tag these things.

**Comment by Wolffenstein** [comment]
Fixed in rev 1457.
