### ISSUE TITLE
[Dungeon][Occulus] Flying mobs have too far of an aggro range

### ISSUE THREAD

**Issue by reetarded** [Stormforge-gg/Bugtracker-Fordring#1121]
As title states, the flying dragons and whelps around the instance have kind of an insane aggro range, I've ran multiple occuluses so far and everytime the group is just pulling mobs while flying on their drakes to every platform. I don't mean to make it so low that you have to fly through them to aggro, but they could use a bit of a reduction.

**Comment by Wolffenstein** [comment]
ID - 50539 Aggro Drakes (SERVERSIDE)
Effect 0: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 0 x 0,00
Targets (22, 38) (TARGET_SRC_CASTER, TARGET_UNIT_NEARBY_ENTRY)
Radius (Id 23) 40,00

Working as intended, they have a 5s periodic aura that makes them aggro onto nearby enemies (40yd).
