### ISSUE TITLE
Sons of Hodir Shoulder Enchant items reusable

### ISSUE THREAD

**Issue by pealda** [Stormforge-gg/Bugtracker-Fordring#1122]
**Description**: 
The exalted level shoulder enchant items purchased from the Sons of Hodir quartermaster appear to be reusable. Tested Greater Inscription of the Crag only.
**Current behaviour**:
The item is not consumed upon use.
**Expected behaviour**: 
The item IS consumed upon use.
**Revision**:

**Comment by Wolffenstein** [comment]
Fix is already pending
