### ISSUE TITLE
 [Spell][Rogue] Distract

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1124]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
~~If you engage with a mob that had Distract used on it just before, the mob acts as if it is rooted in place.~~

~~What should happen: A mob, when aggro'd, loses the Distract effect entirely, including the immobility.~~

~~Never mind. There's a bug but that's not it. Apparently it's specific to the mobs at the Tranquil Gardens Cemetery in Duskwood.~~

These mobs seem to be rooted in place when you first aggro them, they will not run to you for several seconds. I noticed this with both Skeletal Warriors, Skeletal Mages (when interrupted), and the Insane Ghoul.

~~I'm not sure if this is or isn't related to using Distract.~~ Yes, it is only happening when I use Distract on the mob first.

I'm not sure if it's specific to only these mobs.

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
