### ISSUE TITLE
Hunter Master's Call didn't work with this skill

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1125]
**Description**: Master's Call didn't remove the slow or make my character free of impairment.

**Current behaviour**: It's not removing the debuff or making me immune to the movement impairment

**Expected behaviour**: It should remove ALL movement impairing effects and make the hunter and pet immune for X duration.

**Revision**:

**Comment by Wolffenstein** [comment]
From what I remember from Discord it's about Wild Growth (55066). That spell does not have MECHANIC_SNARE, meaning it does not get removed by spells such as Master's Call or Blessing of Freedom (blizzlike).
