### ISSUE TITLE
First Aid can be interrupted by nothing

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1128]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Sometimes, when I use a bandage (last one I used this happened with was Heavy Wool Bandage), the channeling effect starts and immediately stops, only giving me the debuff and none of the heals. I did not take any damage. I didn't have a DoT. I wasn't even in combat.

**Comment by Godmatik** [comment]
Did you happen to tab target something else? I believe there is a global bug with channeling spells at the moment.

**Comment by Vishiswaz** [comment]
I was not targetting anything.

**Comment by Wolffenstein** [comment]
no idea how to reproduce
