### ISSUE TITLE
[Spell][Northrend Cloth Scavenging] Bonus Frostweave Cloth drops are FFA 

### ISSUE THREAD

**Issue by reetarded** [Stormforge-gg/Bugtracker-Fordring#1130]
When the bonus cloth drops, it is free for all in groups when there is multiple tailors. This kind of leads to toxic races to loot mobs first, prioritizing looting over helping the group finish the pack of mobs in random dungeon finder groups.  This really should be made so each tailor takes turns getting a bonus drop, like round robin or group loot.

**Comment by NatsumeLily** [comment]
Just so Wolf knows (bet he does), this would be a suggestion.
Since the way it now is blizzlike.

**Comment by Wolffenstein** [comment]
intended
