### ISSUE TITLE
Pet skill: Heart of the Phoenix

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1137]
**Description**: Heart of the Phoenix cooldown is used even when the pet is still alive.

**Current behaviour**: Heart of the Phoenix cooldown is used even when the pet is still alive.

**Expected behaviour**: The cooldown shouldn't be able to be used when the pet is still alive.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
