### ISSUE TITLE
[Quest][Howling Fjord] Alpha Worg

### ISSUE THREAD

**Issue by Ojren** [Stormforge-gg/Bugtracker-Fordring#1141]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Alpha Worg](https://www.wowhead.com/quest=11326/alpha-worg)
On the start of this quest you get buff that allows you to see needed NPC enemy Gorwal. If you leave local zone it dissapears but should reappear when you reenter zone. If you abandon quest you should use [Worg Disguise](https://www.wowhead.com/item=33618/worg-disguise) to speak with NPC that gives quest . Currently there is no way you can finish quest if you accidently leave local zone, since you can no longer speak with quest giver and item that allows to speak with NPC dissapears on quest start

**Current behaviour**:
1.DIsguise dissapears on the start of the quest(so you cant speak with quest giver again)
2. [NPC]( https://www.wowhead.com/npc=24273/watcher-moonleaf ) that should give you disguise doesnt give one(when you press dialog to give one it does nothing)
3. Buff that is needed to see quest target dosnt reapply if you leave local zone
**Expected behaviour**: 
1. Disguise should dissapear only after turning in this quest
2. [NPC](https://www.wowhead.com/npc=24273/watcher-moonleaf) should give disguise if you lost it and still hasnt completed this quest
3. Buff should reapply on local zone reenter if you still has this quest active

**Revision**:

**Comment by Tereneckla** [comment]
Fixed soon™
