### ISSUE TITLE
Death Knight Pet Def Attack

### ISSUE THREAD

**Issue by dontfaket30** [Stormforge-gg/Bugtracker-Fordring#1142]
**Description**: Death Knight Pet Def Attack, if pet is in def mode, he will auto attack someone and comes back to DK. 

**Current behaviour**:
[https://youtu.be/89Rqlyf8IEQ](url)

**Comment by Wolffenstein** [comment]
I can't reproduce this on local. Have you tried checking if it still behaves like that if your spells are not on auto cast?
