### ISSUE TITLE
No rep rewards in Utgarde Keep, The Occulus

### ISSUE THREAD

**Issue by pealda** [Stormforge-gg/Bugtracker-Fordring#1143]
[//]: # ([Zone] Utgarde Pinnacle, The Occulus, normal mode)
[//]: # ([NPC] All npcs in the zones)

**Description**: 
Killing NPCs in these two dungeons does not yield reputation reward on normal mode.

**Comment by Godmatik** [comment]
Utgarde Keep in a lvl 69-70ish dungeon and shouldn't give rep, unless it is heroic.

If Occulus (lvl 78-80 dungeon) doesn't give rep, that is indeed a bug

**Comment by pealda** [comment]
Ah, mixed up the two. Meant to type Pinnacle, brain fart.

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
