### ISSUE TITLE
[Quest] [Gundrak] One of a Kind

### ISSUE THREAD

**Issue by blumentopfy** [Stormforge-gg/Bugtracker-Fordring#1149]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Quest item ("Drakkari Colossus Fragment") doesn't drop

**Current behaviour**: Doesn't drop (been in there twice)

**Expected behaviour**:  Should drop lmao

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed
