### ISSUE TITLE
 [NPC] [Dungeon] Anub'Arak burries way too often

### ISSUE THREAD

**Issue by blumentopfy** [Stormforge-gg/Bugtracker-Fordring#1150]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Anub'Arak burries way too often, we literally almost wiped in a normal run because healer went oom after like 5-6 burries

**Current behaviour**: He burries way too often

**Expected behaviour**:  He should burry maybe 2-3 times in normal modes, not sure if it was %HP-gated, but if you watch videos on YT, there is no way this fight should take 5 minutes in a normal run

**Revision**:

**Comment by Godmatik** [comment]
He buries every 25% of his health, that is Blizzlike and intended

**Comment by Wolffenstein** [comment]
Blizzlike at 3.0
