### ISSUE TITLE
[Dungeon][NPC] Hadronox takes too long to go up the tunnel

### ISSUE THREAD

**Issue by blumentopfy** [Stormforge-gg/Bugtracker-Fordring#1151]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  He takes way too long to go up the tunnel!

**Current behaviour**: He takes about 3-5 minutes to go up the tunnel, people leave all the time in that dungeon! I suspect he deals the amount of damage that he does to players when in reality he should be 1shotting all the spiders (maybe increased ASPD too)

**Expected behaviour**: He should rush up the tunnel in 30-45 seconds, maybe a minute MAX

**Revision**:

**Comment by NatsumeLily** [comment]
#341 Reported. 

Blizzlike.
