### ISSUE TITLE
pre-dungeon druid form lost as teleporting out of the dungeon -> it's raining trees from the sky

### ISSUE THREAD

**Issue by everleee** [Stormforge-gg/Bugtracker-Fordring#1153]
**Description**: I don't keep my pre-dungeon druid form as i teleport out of the dungeon.

**Current behaviour**: I'm flying with my druid in flight form, get teleported to a dungeon with dungeon finder and as i teleport out of the dungeon, i have lost the flight form and am falling to my death.

**Expected behaviour**:  If i recall, you're supposed to keep your pre-dungeon form as you teleport out.

**Revision**: Keep the form of outside of the dungeon as it is, and not end up being a falling tree from the sky.

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
