### ISSUE TITLE
[NPC] Bleeding Hollow Tormentor

### ISSUE THREAD

**Issue by fondlez** [Stormforge-gg/Bugtracker-Fordring#1155]
**Description**: 
Bleeding Hollow Tormentor casts Fear on itself instead of an enemy unit.

**Current behaviour**:
See above.

**Expected behaviour**: 
Casts Fear on an enemy unit and never itself.

**Revision**: 
AtlantissCore WoTLK rev. 1461, 76457a7eb01c 2022-06-08 12:09:06 +0200 (master branch) (Unix, Debug, Static)

**Comment by Godmatik** [comment]
Was supposedly fixed here, but guess not.

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/582

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
