### ISSUE TITLE
[Quest][Item] Break the Blockade/Petrov's Cluster Bombs

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Fordring#1157]
**Description**: 
[Petrov's Cluster Bombs](https://www.wowhead.com/item=33098/petrovs-cluster-bombs) =33098 AoE during [Break the Blockade](https://www.wowhead.com/quest=11153/break-the-blockade) =11153 isn't working, only hit the precise target in the center of it

https://youtu.be/u22pDxW8oC8

**Revision**: 
1461

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
