### ISSUE TITLE
[NPC][Stonetalon Mountains] Deepmoss Hatchling

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1158]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
These NPCs, which spawn as a part of the quest Deepmoss Spider Eggs when you loot the egg objects, are not targetable, and therefore not killable. https://youtu.be/s17tZv3yKV8

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
