### ISSUE TITLE
No BOE Blues dropping from Heroic Dungeons

### ISSUE THREAD

**Issue by Tetrahydrx** [Stormforge-gg/Bugtracker-Fordring#1159]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There are no BoE blues dropping in Heroic dungeons, for example the "Librarian Paper Cutter" from Halls of Lightning.
**Current behaviour**:
No drops at all seen from any guildie in multiple heroic dungeons.
**Expected behaviour**: 

**Revision**:

**Comment by Godmatik** [comment]
This appears to only affect the item level 200 BoE blues that drop from all the heroics. 

The other lower level BoEs seem to drop just fine.

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
