### ISSUE TITLE
[Quest: Scourge Tactics] [Zone: Icecrown]

### ISSUE THREAD

**Issue by shinzo69** [Stormforge-gg/Bugtracker-Fordring#1160]
**Description**: 
Quest: https://www.wowhead.com/quest=13008/scourge-tactics
NPC/Progression: https://www.wowhead.com/npc=30274/freed-crusader

(This is one of the first 3 quests to gain Argent Crusade Rep.)

**Current behaviour**:
The Chance of the Web turning into Quest Progression (Webbed Crusader Freed) is very low. Atm. there are around 10 people hanging around here cause the A) Spawnrate + B) Chance of Quest Progression is too low. After destroying 14 of those webs i've only got 2 NPC freed. (and this took me 30min)

**Expected behaviour**: 
Higher Spawnrate of Webbed Crusader + higher Chance of freeing them.

**Comment by Wolffenstein** [comment]
My bad, I made the web chances reversed. Should be better now.
