### ISSUE TITLE
Quest mob "Simmer" in Borean Tundra is not spawning. 

### ISSUE THREAD

**Issue by Sukkerfugl** [Stormforge-gg/Bugtracker-Fordring#1163]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest mob "Simmer" in Borean Tundra is not spawning. 
**Current behaviour**:
Not Spawning.
**Expected behaviour**: 
Spawning.
**Revision**: 
Spawn the mob.

**Comment by Wolffenstein** [comment]
he does respawn but the bug is his respawn time is way too long (20 min)

**Comment by Wolffenstein** [comment]
Fixed in rev 1470.
