### ISSUE TITLE
[Quest][Storm Peaks] Hot and Cold

### ISSUE THREAD

**Issue by reetarded** [Stormforge-gg/Bugtracker-Fordring#1165]
The Hot and Cold daily in storm peaks will bug a bit. After you use an essence of ice on a smoldering scrap and pick up the item, if you throw your next essence of ice quickly it will fly back to the smoldering scrap you just picked up until the frost nova around the smoldering scrap despawns even though there is nothing there except the frost nova.

**Comment by Wolffenstein** [comment]
Fixed in rev 1483.
