### ISSUE TITLE
[NPC][The Deadmines] Edwin VanCleef

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1169]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
He's overtuned. Hitting for way too hard compared to other mobs in the dungeon. Most groups fail to complete because of this.

**Comment by Cold-Martijn** [comment]
I just did Deadmines for the first time, I disagree that he is overtuned.

**Comment by Vishiswaz** [comment]
I had a group with two healers and two tanks (not queued that way, just what our classes can be since it doesn't really matter at that level) and we wiped 5 times and quit. He hits way harder than everything else in the dungeon, not even close. Everyone but me was level 20 or higher.

**Comment by Drevil-Dion** [comment]
Never had any issues when i ran DM a few times VC died with no issues and was a easy fight with a single healer.

**Comment by Wolffenstein** [comment]
Fixed in rev 1483.
