### ISSUE TITLE
[NPC] Borean Tundra

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Fordring#117]
**Descriptif**:
![image](https://user-images.githubusercontent.com/62518101/162591976-5d3a3e9b-aa40-42cf-8592-fa66bbda05cd.png)
https://www.wowhead.com/npc=25430/magmothregar

**Current behaviour**:
npc=25430 unusual movement

**Expected behaviour**: 
https://youtu.be/ggpF1kLzUNk?t=6

**Revision**: 

-

**Description**: 
![touu](https://user-images.githubusercontent.com/62518101/162592011-6bc7bde8-5295-4221-a45f-d0d5a34efbe8.png)
https://www.wowhead.com/npc=24567/den-vermin

**Current behaviour**:

npc=24567 unusual movement

**Descriptif **: https://www.wowhead.com/npc=25198/winterfin-gatherer
![murl](https://user-images.githubusercontent.com/62518101/162592135-3c808046-1398-45c8-8230-7d361e98eb09.png)

**Current behaviour**:
npc=25198 unusual movement

-

**Descriptif**:
https://www.wowhead.com/npc=25217/winterfin-warrior
https://www.wowhead.com/npc=25216/winterfin-oracle

**Current behaviour**:
npc=25217 movement too fast
npc=25216 movement too fast

-
**Descriptif**:  https://www.wowhead.com/npc=25488/wooly-rhino-calf
                           https://www.wowhead.com/npc=25487/wooly-rhino-matriarch

**Current behaviour**:

npc=25488 unusual movement/they are too crowded they constantly touch each other
npc=25487 unusual movement/they are too crowded they constantly touch each other

-

**Descriptif**:  https://www.wowhead.com/npc=25228/risen-crypt-lord
![image](https://user-images.githubusercontent.com/62518101/162593013-4a0c91ba-8034-4809-a896-26a1abed9bec.png)

**Current behaviour**: 

npc=25228 once revived moves towards combat are bad

-

**Descriptif**:

https://www.wowhead.com/npc=25668/vengeful-taunka-spirit
https://www.wowhead.com/npc=25715/frozen-elemental
https://www.wowhead.com/npc=25452/scourged-mammoth

**Current behaviour**:  
npc=25668 unusual movement/they are too crowded they constantly touch each other
npc=25715 unusual movement/they are too crowded they constantly touch each other
npc=25452 unusual movement

**Comment by therealCrysis** [comment]
Confirmed, yet minor issue.
