### ISSUE TITLE
[Zone][Wintergrasp] Wintergrasp towers and walls models

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1172]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Wintergrasp towers and walls models don't get restored when each WG battle starts. They still can't be passed by vehicles and can be damaged by them like they're still there but players can simply run through them like they're not there.

**Current behaviour**: Wintergrasp towers and walls models don't get restored when each WG battle starts. 

**Expected behaviour**: Wintergrasp towers and walls models should get restored when each WG battle starts. 

**Revision**: 1461

**Comment by NatsumeLily** [comment]
This one is a strange bug. We had something similar happen to us on the ptr.
I was with Vishiswaz when we had it happen to us. He couldn't see the wall and could pass through it, but I saw the wall and couldn't pass through it. 

We figured it was GM mode but here is a similar thing.
