### ISSUE TITLE
[Zone][Wintergrasp] Bonus honor on destroying southern tower missing

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1174]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The defenders don't get awarded bonus honor for destroying a southern tower.

**Current behaviour**: The defenders don't get awarded bonus honor for destroying a southern tower.

**Expected behaviour**: The defenders should get awarded bonus honor for destroying a southern tower.

**Revision**: 1461

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/172968166-9eb5a0e5-4859-43ad-bdd5-ca0de6ed7703.png)
I just tested it, you get +750 honor for each tower destroyed when the battle ends
