### ISSUE TITLE
Serious problem on harbs

### ISSUE THREAD

**Issue by goldin2021** [Stormforge-gg/Bugtracker-Fordring#1176]
**Description**: 
Serious lack of herbs and 0 Crystallized Life from herbs even in max herbs same 
**Current behaviour**:
Lack of herbs Nodes in general in all zones in Northend
**Expected behaviour**: 
To have northrend full of nodes as it should be thx :)

**Comment by Godmatik** [comment]
Confirmed that crystallized life seems to be missing from herb loot table. 

I won't comment on herb respawn rate though, it does appear low, but that could be intended/blizzlike.
