### ISSUE TITLE
[NPC] Sirfreldar Storm Maiden

### ISSUE THREAD

**Issue by seitzcasey** [Stormforge-gg/Bugtracker-Fordring#1182]
**Description**: 
Storm shield damage is being applied to attack DOT and casts, not melee attacks.

**Revision**: 
1474

**Comment by Wolffenstein** [comment]
Proc flag 0x00100000, chance = 100, charges - 0
=================================================
  1048576 (0x100000) - Take Any Damage
=================================================

Seems blizzlike
