### ISSUE TITLE
[Honor is for the Weak][Icecrown]

### ISSUE THREAD

**Issue by blumentopfy** [Stormforge-gg/Bugtracker-Fordring#1183]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Quest where you control the shades is bugged, you can't really assassinate the lookouts properly

**Current behaviour**: The assassination only deals ~20-25% of the HP and they also regenerate for some reason, which results in having to spam the button like 10 times

**Expected behaviour**: Assassination should 1shot (that's what it was like on other servers) or at the very least the lookouts shouldn't regenerate almost as much HP as you can deal

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1483.
