### ISSUE TITLE
[Quest: Precious Elemental Fluids] [Zone: Icecrown]

### ISSUE THREAD

**Issue by shinzo69** [Stormforge-gg/Bugtracker-Fordring#1186]
**Description**: 
Quest: https://www.wowhead.com/quest=12510/precious-elemental-fluids
Questitem: https://www.wowhead.com/item=38323/water-elemental-link
Gets Dropped by: https://www.wowhead.com/npc=16570/crazed-water-spirit

**Current behaviour**:
The Droprate for the Questitem is way too low. We need 9 of those to complete the quest and after 30min I got 2 during constantly camping the area.

**Expected behaviour**: 
Droprate should be higher.

**Comment by shinzo69** [comment]
Maybe im just unlucky. After opening this Issue I got all other 7 items dropped one by one.

**Comment by Tereneckla** [comment]
You sadly just got unlucky
