### ISSUE TITLE
Looting emblems from bosses

### ISSUE THREAD

**Issue by Cold-Martijn** [Stormforge-gg/Bugtracker-Fordring#1188]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Emblems should automatically be "looted" on kill of a boss.
**Current behaviour**:
you need to manually loot the boss
**Expected behaviour**: 
automatic looting/distributing emblems to your currency tab
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1481.
