### ISSUE TITLE
[Spell][Hunter] Misdirection

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Fordring#1192]
**Description**: 
Misdirection is triggered by non damaging spells. Aswell on damaging spells, it is triggered when the spell is casted and not when the damage casted by the spell is applied. Because of that Misdirection is triggered by Volley when casted in an area without enemies.

**Current behaviour**:
When Misdirection is applied to a Target and the Hunter uses abilites like **Kill Command** or **Volley** in an area where it deals no dmg, Misdirection is triggered (see Videos)

https://streamable.com/n6ypy4 - MD + Kill Command 
https://streamable.com/f4k0nb - MD + Volley

**Expected behaviour**: 
Misdirection should only be triggered when Damage is applied by abilities that deal damage.

_The current party or raid member targeted will receive the threat caused by your next damaging attack and all actions taken for 4 sec afterwards._

**Revision**: 
https://db.rising-gods.de/?spell=34477

**Comment by Wolffenstein** [comment]
Fixed in rev 1483.
