### ISSUE TITLE
[Class][Talent] Warlock, Decimation (63158)

### ISSUE THREAD

**Issue by Nihaobeachez** [Stormforge-gg/Bugtracker-Fordring#1194]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Decimation is a Talent in the Demonolgy Tree which reduces the Casttime of Soulfire, if you hit a Target at or below 35% Health with Shadowbolt. Incenerate or Soul Fire

**Current behaviour**: Currently it doesnt procc if you kill the target with named Spells above. My Lock is only 53 so far, so i can only speak for Shadowbolt.

**Expected behaviour**: It should procc if you kill the target with Shadowbolt, Incenerate or Soul Fire

**Revision**: 1474

**Comment by Wolffenstein** [comment]
Fixed in rev 1491.
