### ISSUE TITLE
Converted Hero

### ISSUE THREAD

**Issue by Gengaro** [Stormforge-gg/Bugtracker-Fordring#1195]
[//]: # Link: https://www.wowhead.com/npc=32255/converted-hero

[//]: # Zone: Icecrown
[//]: # NPC: Converted Hero
[//]: # Spell: Blizzard / Frostfire Bolt / Frostbolt / Ice Nova / Water Elemental Frost Nova
[//]: # Talent: Improved Blizzard

**Description**:  Converted Heroes are not slowable (can not be CC'd), the Scourge Banner-Bearers who roam close to them are slowable (can be CC'd)

**Current behaviour**: Not slowable with spells

**Expected behaviour**: Slowable with all spells and rootable

**Revision**: Crowd Control effects should work on these

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/172970681-8a22f1ad-7f12-4572-b2c2-4fc3db5bda07.png)
