### ISSUE TITLE
Hunter Deterrence is still not correct

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1196]
**Description**: Deterrence is not parrying attacks from certain mobs. Maybe deterrence isn't parrying attacks at 100%? Maybe it's not parrying from behind? I don't know what it is, but something is definitely off.

**Current behaviour**:
![image](https://user-images.githubusercontent.com/6567001/172974257-b105909c-9e09-4801-bb42-c509729e2174.png)
Maybe deterrence isn't parrying attacks at 100%? Maybe it's not parrying from behind? I don't know what it is, but something is definitely off.

**Expected behaviour**: When activated, increases parry chance by 100%, reduces the chance ranged attacks willhit you by 100% and grants 100% chance to deflect spells.

**Revision**:

**Comment by Wolffenstein** [comment]
Maybe fixed in rev 1511.

**Comment by slicplaya** [comment]
Sorry, I didn't know that when revisions are posted, they're not exactly live/patched yet.
