### ISSUE TITLE
[NPC][Drop] Gan'arg Analyzer

### ISSUE THREAD

**Issue by shammybr** [Stormforge-gg/Bugtracker-Fordring#1198]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The mob Gan'arg Analyzer is not dropping the recipe [Schematic: Field Repair Bot 110G] for a 360 engineer.

**Current behaviour**:
Killed around 500 Gan'arg Analyzers and the item didn't drop (367 engineering).

**Expected behaviour**: 
Gan'arg Analyzers should drop the item if you are an engineer, with a decent droprate. The great majority of comments on wowhead (https://www.wowhead.com/item=34114/schematic-field-repair-bot-110g#comments) tells they killed from 5 to, at max, 200 mobs. I killed around 5 in the oficial TBC Classic and it dropped real quickly.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1485.
