### ISSUE TITLE
The quest Waterlogged Recipe that you sometimes receive when completing the Dalaran fishing daily isn't repeatable when it should be.

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1202]
**Description**: When completing the Dalaran fishing dailies, occasionally one of the rewards will be a quest item which when turned in grants Dalaran Cooking Awards. It should be repeatable, but curerntly when I try to start it for a second time, it simply says that it has already been completed.
The comments in the link provided should show that the quest should indeed be repeatable.
https://www.wowhead.com/quest=14203/waterlogged-recipe

**Current behaviour**: The quest Waterlogged Recipe isn't repeatable.

**Expected behaviour**:  The quest should be repeatable.

**Comment by Tereneckla** [comment]
Fixed soon™

**Comment by Tereneckla** [comment]
I know, but still. Ty
