### ISSUE TITLE
Clearcasting Proc Mage (arcane)

### ISSUE THREAD

**Issue by Greenbelters** [Stormforge-gg/Bugtracker-Fordring#1204]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  I play Arcane and the clearcasting proc doesn't get used, or it does and stays up as though it has procced. this doesn't happen every time but still often enough to cause confusion and problems.

**Current behaviour**: buff displaying proc is visible, spells are cast without cosuming buff.

**Expected behaviour**: buff should disappear after spellcast and spellcast should not consume mana

**Revision**:

**Comment by reetarded** [comment]
I have noticed some times the clearcasting proc does not get consumed, I don't what causes or fixes it though
