### ISSUE TITLE
Engineering Issue

### ISSUE THREAD

**Issue by flackolacko** [Stormforge-gg/Bugtracker-Fordring#1205]
**Description**: 
When you get to northrend and you are able to skill engineering by scrapping the Mechanical mobtypes you don't gain any skill ups from it.

**Current behaviour**:
If you scrap 50 yellow mobs (scrapping is like skinning but for engineers) you don't gain any skill ups and you should be able to go from 375 to 450 by just scrapping mobs of various lvls. 

**Expected behaviour**: 
You should be able to gain skill ups from scrapping mobs. It's the mechanical version of skinning. And the required lvl of the proffesion should be moblvl * 5

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1490.
