### ISSUE TITLE
[Item] Formula: Runed Adamantite Rod

### ISSUE THREAD

**Issue by Methi2** [Stormforge-gg/Bugtracker-Fordring#1212]
Can't find the actual respawn timer of this onem but seen there was a change on the forge plan yesterday https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1197

Formula for Runed Adamantite Rod timer is very very long (at least on Vodesiin, alliance side) and prevent all enchanter to level up past TBC level while waiting of it to be sold by PNJ. As XP is boosted AND craft leveling on vanilla and TBC content is boosted, I feel the plans might as well be boosted.

https://tbc.wowhead.com/item=25848/formula-runed-adamantite-rod
https://tbc.wowhead.com/npc=19004/vodesiin

Sorry if this is indented behavior on a WOTLK server.

Regards

**Comment by s1cfuk** [comment]
Same goes for NPC Rungor at Stonebreaker Hold.

**Comment by Wolffenstein** [comment]
Fixed in rev 1490.
