### ISSUE TITLE
[NPC][Darnassus] Darnassus Sentinel

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1213]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This Darnassus Sentinel in Rut'theran Village needs its waypoints fixed when it goes over the raised portion of the dock to the flight path.
![WoWScrnShot_061022_094326](https://user-images.githubusercontent.com/78314117/173079068-afc3c137-90b5-4f2a-86bd-bb6f01df059d.jpg)

**Comment by Tereneckla** [comment]
Fixed soon™
