### ISSUE TITLE
Feign Death

### ISSUE THREAD

**Issue by Kripp0** [Stormforge-gg/Bugtracker-Fordring#1215]
**Current behaviour**:Feign death does not show the cooldown of it.

**Expected behaviour**: Once the FD effect drop from your character,a cooldown timer should start.

**Revision**: 
Make a hunter,use feign death.

**Comment by Soufly** [comment]
Edit: Its random,sometimes is working,sometimes it doesnt.

**Comment by slicplaya** [comment]
I can confirm this. The Skill is used, but doesn't actually Feign Death, and it goes into CD without showing the icon greyed out and on cooldown.
