### ISSUE TITLE
Warsong Gulch HUGE BUG

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1218]
**Description**: When you die in Wsg, there's no spirit healer, you can't res, and you can't retrieve your body.
![WoWScrnShot_061022_084953](https://user-images.githubusercontent.com/6567001/173103613-9516e91d-94e7-488b-b927-2ba6dcdc9f17.jpg)

**Current behaviour**: When you die in Wsg, there's no spirit healer, you can't res, and you can't retrieve your body.

**Expected behaviour**:  There should be a Spirit healer to RES! -_-

**Revision**:

**Comment by Wolffenstein** [comment]
they should be back now hopefully
