### ISSUE TITLE
[Quest][Icecrown] Tirion's Gambit

### ISSUE THREAD

**Issue by ZymNW** [Stormforge-gg/Bugtracker-Fordring#1219]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

Tirion is not spawning outside of the cathedral of darkness

Fix the Tirion spawn so players can talk to him to start the RP event

**Comment by nevrozac** [comment]
NPC Highlord Tirion Fordring 31044 is missing from his spawn location at Cathedral of Darkness Icecrown for quest Tirion's Gambit 13403
https://www.youtube.com/watch?v=-OVz8CXtI6w&ab_channel=ZaricZhakaron

**Comment by nevrozac** [comment]
He has respawned, not sure if due to a fix or because of restarts

**Comment by nevrozac** [comment]
Chosen Zealot NPCs 32175 missing from inside the Cathedral. They are supposed ot be lined in front of most tables, but only very few sparseley show up. Check mentioned video above

**Comment by Cold-Martijn** [comment]
Fixed soon.

**Comment by Cold-Martijn** [comment]
fixed in rev 1597
