### ISSUE TITLE
[Item][Trinket] Soul Preserver doesn't reduce spell cost by correct amount

### ISSUE THREAD

**Issue by Barcaz** [Stormforge-gg/Bugtracker-Fordring#1220]
**Current behaviour**: At the moment my resto druid spells spell are getting their cost reduced by 640. 

**Expected behaviour**:  It should be 800.

**Comment by Wolffenstein** [comment]
Cannot reproduce, works fine for me

**Comment by Barcaz** [comment]
> Cannot reproduce, works fine for me

![image](https://user-images.githubusercontent.com/51231110/173152347-fec604d4-1492-41c4-9655-2aeb933ec3cf.png)
It was working fine after the update, but some reason a while after that this is what happened.Here is the proof.

**Comment by Barcaz** [comment]
K i got it no freaking idea what is the logic behind that interraction but it happens when i have talisman of troll divinity equiped
