### ISSUE TITLE
On use trinkets

### ISSUE THREAD

**Issue by Soufly** [Stormforge-gg/Bugtracker-Fordring#1221]
**Current behaviour**: If u have 2x ''on use'' trinkets with similar effects,after u use the first one,the second one has only 20 sec cd.

**Expected behaviour**: On use trinkets with similar effects should share the same CD.
usage of trinket 1 - 2m CD
usage of trinket 2 should be after 2m(a.k.a useless)

**Revision**: 
Make a character,get 2x one use trinkets with let say attack power(1m 30 sec,or 2m,doesnt matter).

**Comment by Wolffenstein** [comment]
Can you give specific examples of such trinkets?

**Comment by Soufly** [comment]
![Capture](https://user-images.githubusercontent.com/36957911/173124604-8fe84e34-6b6b-4574-9fd7-9574eb404c3b.PNG)
The second trinket is https://wotlkdb.com/?item=38081

**Comment by Soufly** [comment]
I had 2 others trinkets earlier,one with 1m 30sec and other with 2m.... same thing.

**Comment by Wolffenstein** [comment]
I'm not entirely convinced that's a bug, need proof for those particular items

**Comment by Secare69** [comment]
Trinkets always worked like this?
If you use one it has 20sec cd on other to stop u stacking on use, it never should put them on same cd?

**Comment by Soufly** [comment]
gonna make a harder research,closing for now
