### ISSUE TITLE
 [Class][Spell] Shaman, Thunderstorm knockbacks even Bosses

### ISSUE THREAD

**Issue by HiKO0711** [Stormforge-gg/Bugtracker-Fordring#1222]
**Current behaviour**:
U can Knockback even Dungeonbosses with Elemental Shamans Thunderstorm (without Glyph)
**Expected behaviour**: 
U can knockback everything but no Bosses
https://www.wowhead.com/spell=51490/thunderstorm

**Comment by Wolffenstein** [comment]
Which boss did you knockback? The ones I tried are immune.

**Comment by HiKO0711** [comment]
First one at Nexus, 2nd one at Utgarde

**Comment by Wolffenstein** [comment]
Fixed in rev 1498.

**Comment by HiKO0711** [comment]
was at first boss utgarde and was ok!
