### ISSUE TITLE
[NPC][Wetlands] Naela Trance

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1224]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Needs her waypoints slightly adjusted so she doesn't do this:
![WoWScrnShot_061022_134513](https://user-images.githubusercontent.com/78314117/173122481-908e2536-e8c6-459e-bc9d-3c014f9baf33.jpg)

**Comment by Tereneckla** [comment]
Fixed soon™

**Comment by Vishiswaz** [comment]
Nope, now there are two broken NPCs.
![WoWScrnShot_061122_142734](https://user-images.githubusercontent.com/78314117/173200475-eb17128a-dda6-4121-8b1b-647900abccb1.jpg)
