### ISSUE TITLE
[NPC][Shadowmoon Valley] Sanctun of the Stars Flightmaster Bug

### ISSUE THREAD

**Issue by Exorcista** [Stormforge-gg/Bugtracker-Fordring#1226]
**Current behaviour**: Flightmaster at Sanctum of the Stars in Shadowmoon Valley doesn't let you fly even when being sided with Scryers

![WoWScrnShot_061022_141102](https://user-images.githubusercontent.com/6818405/173126736-1184bcda-46c1-426b-9675-cab593c67aa9.jpg)

**Expected behaviour**:  Being able to fly/use his services while being Scryers

**Revision**:

**Comment by Tereneckla** [comment]
Fixed soon™
