### ISSUE TITLE
[Quest][Netherstorm]Recharging the Batteries

### ISSUE THREAD

**Issue by subi900** [Stormforge-gg/Bugtracker-Fordring#1227]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: When lowering the health of a "Phase Hunter", the message "The Phaser Hunter is very weak." appears and you can use the "Battery Recharging Blaster" to get the needed "energy"

**Current behaviour**: "The Phase Hunter is very weak." message appears but the "Battery Recharging Blaster" does not do anything when using it on this Phase hunter.

**Expected behaviour**: "The Phase Hunter is very weak." message appears and by using the "Battery Recharging Blaster" on the Phase Hunter, you get needed energy for the quest.

**Revision**:

**Comment by Tereneckla** [comment]
Fixed soon™
