### ISSUE TITLE
[DK][FlyPaths][Kalimdor] All Opened

### ISSUE THREAD

**Issue by ImCasual** [Stormforge-gg/Bugtracker-Fordring#1228]
**Description**: 
Idk if it's a bug but i assume that is. Yesterday I used a low level Scroll of Recall of Inscription and get lost (ok it's correct), went to Ashevalle and notice that I had all FP opened at Kalimdor side. 
Im Draenei DK and just left Starter area, went to Outland, SW and IF. There is zones that even at others char at account I didn't get the FP.

**Expected behaviour**: 
I believe there would be no FP

**Comment by Wolffenstein** [comment]
Works as intended for death knights
