### ISSUE TITLE
BATTLEGROUND SPIRIT HEALERS!

### ISSUE THREAD

**Issue by Topsquad** [Stormforge-gg/Bugtracker-Fordring#1229]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The spirit healers in battlegrounds are non available right now and you can't ressurect any more once your corpse got looted
**Current behaviour**:
^this
**Expected behaviour**: 
Well, there should be spirit healers and you should be able to get rezzed once every 30 seconds
**Revision**:

**Comment by Vishiswaz** [comment]
Can you specify which battlegrounds you had this issue with, and if you were Horde or Alliance?

**Comment by Wolffenstein** [comment]
Should be better now
