### ISSUE TITLE
[Quest][NPC] Wanton Warlord

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#1230]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  

**Current behaviour**:  Grom'thar is missing his abilities and remains outside the ring when summoned.

**Expected behaviour**:  He should move into the ring and use his abilities https://www.wowhead.com/npc=27002/gromthar-the-thunderbringer#abilities

**Revision**:

**Comment by Tereneckla** [comment]
Fixed soon™
