### ISSUE TITLE
[Core] Mobs running to get help in instances

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1232]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
It appears that at least some of the times, when mobs run away in fear towards one of their allies, the ally does not actually engage in combat, and then the mob just kind of stands there, and you get stuck in combat with them until you go kill them. I saw this first in BFD (no screenshots) and then Stockades, screenshots here:
![WoWScrnShot_061022_153031](https://user-images.githubusercontent.com/78314117/173144304-43094978-c9bc-4123-b24b-2b6bdf949a61.jpg)
![WoWScrnShot_061022_153053](https://user-images.githubusercontent.com/78314117/173144316-8800b13d-14c4-454f-b8da-8536802afdee.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 1581.
