### ISSUE TITLE
 [Celestial Steed] Broken

### ISSUE THREAD

**Issue by Md-Knox** [Stormforge-gg/Bugtracker-Fordring#1233]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Casts  [Celestial Steed] but wont mount when WG is up and running 

**Expected behaviour**: 
It should let you mount as it acts as a flying and a ground mount

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1498.
