### ISSUE TITLE
Mind Flay fizzles sometimes for no reason

### ISSUE THREAD

**Issue by ExXxtract** [Stormforge-gg/Bugtracker-Fordring#1234]
Spell tends to fizzle sometimes when used for no reason. The character does the hand animation and the cast bar appears for a moment but spell doesn't go off. It is basically the same interaction like when the spell "misses" but there are no indication of spell "missing", it just doesn't happen. I've been fighting lower level adds on top of having extra hit % from SP talents so there is no way the spell is "missing" as often as it does. I've seen similar interaction on some servers on Gunship fight when trying to use Mind Flay on mobs that are on the other ship. The spell just fizzles (doesn't go off) even though it is not counted as spell missing.

**Comment by Vishiswaz** [comment]
This is a global bug with all channeled spells specifically. Not regular cast spells.

**Comment by ExXxtract** [comment]
Will it get fixed eventually?

**Comment by Minnona** [comment]
Can confirm it too, happens quite a lot to me.
