### ISSUE TITLE
Skinning Issue

### ISSUE THREAD

**Issue by ExXxtract** [Stormforge-gg/Bugtracker-Fordring#1235]
**Description**:  Creatures not being able to be skinned due to loot.

**Current behaviour**: Decent amount of times (30%-40%), the message appears that creature can't be skinned because it hasn't been looted, even though it has been looted already.

**Expected behaviour**: Mobs that are eligible for skinning should be able to get skinned after they get looted.

**Revision**:

**Comment by NatsumeLily** [comment]
Are you in a group while trying to skin them?

**Comment by Kuszki** [comment]
Noticed the same issue, but only a few times.

**Comment by Vishiswaz** [comment]
It probably had loot for other members of your group. This isn't like some other servers where you can see the loot on a mob for another party member.

**Comment by Kuszki** [comment]
> It probably had loot for other members of your group

Its understandable, but i was not in party - just solo leveling. In party its obvious.

**Comment by ExXxtract** [comment]
I can confirm that this is happening even when solo leveling.

**Comment by Kuszki** [comment]
I can provide some info:
- problem can be reproduced on [Primordial Drake](https://wotlk.evowow.com/?npc=28378)
- this npc drops quest item [Proto Dragon Bone](https://wotlk.evowow.com/?item=42106) (probably item is dropped, but invisible, so after looting everything there is still quest item to loot)
- if player does not have proper quest, item is invisible and mob is not looted

I think this might be the issue - mob can drop hidden quest item while player does not have connected quest.

![WoWScrnShot_061822_122243](https://user-images.githubusercontent.com/6035437/174457822-f34fa073-c28f-421c-b109-ad3dd88dce76.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 1537.
