### ISSUE TITLE
Player is paired with person on ignore list through RDF

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Fordring#1237]
Title

Revision : 
1487

**Comment by Vishiswaz** [comment]
Gigantic bug, hope this is fixed ASAP

**Comment by angarus21** [comment]
> Gigantic bug, hope this is fixed ASAP

Bug is a bug, no matter if it's big or not

**Comment by Vishiswaz** [comment]
no shit
