### ISSUE TITLE
Deterrence is not working on PvE in dungeons

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1239]
**Description**: 
![image](https://user-images.githubusercontent.com/6567001/173167433-f81ec1ea-5a99-45da-a429-2813f9c0d246.png)
I have many more examples

**Current behaviour**: For some reason it's just not parrying in dungeons

**Expected behaviour**: It should parry melee attacks 100%

**Revision**:

**Comment by slicplaya** [comment]
![Capture](https://user-images.githubusercontent.com/6567001/173170171-4d5aa5ef-842e-4f0a-95c1-aee1b7e01b48.JPG)

**Comment by slicplaya** [comment]
As you can see, in dungeons, Deterrence doesn't work on almost literally everything.

**Comment by Wolffenstein** [comment]
Maybe fixed in rev 1511.
