### ISSUE TITLE
Emblem of heroism not auto looting

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1240]
**Description**:  Emblem of heroism not auto looting

**Current behaviour**: Emblem of heroism not auto looting

**Expected behaviour**: It should auto loot.

**Revision**:

**Comment by Vishiswaz** [comment]
You need to give examples of where this happened, or the devs won't be able to find the issue.

**Comment by slicplaya** [comment]
Every single heroic instance all day on every single boss except the first one Meathook in culling of Strat.

**Comment by slicplaya** [comment]
I will provide examples tomorrow when i run heroics again.

**Comment by slicplaya** [comment]
I had to remind my party to loot for emblems as they weren't auto looting

**Comment by Wolffenstein** [comment]
"sometimes" does not help me at all

**Comment by slicplaya** [comment]
Since the "revision" I've only had one boss auto loot and that was Meathook in culling of Stratholme. No other boss has auto loot to the group once touched by a party member. Or were you intending every player to touch the boss to loot emblems and shards?
