### ISSUE TITLE
truesight ice blinders and helm enchant bug

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1244]
**Description**: When attempting to place Arcanum of Torrent on the goggles it says no charges remain and won't allow me to enchant the helmet.

**Current behaviour**: When attempting to place Arcanum of Torrent on the goggles it says no charges remain and won't allow me to enchant the helmet.
![WoWScrnShot_061022_233631](https://user-images.githubusercontent.com/6567001/173176496-30df7fcc-3dc2-4362-8d01-4c34f50f8465.jpg)

**Expected behaviour**: I should be able to enchant the goggles.

**Revision**:

**Comment by slicplaya** [comment]
the bug/error is with the enchant itself. i just tried it on other helms and it says the same thing.

**Comment by slicplaya** [comment]
https://user-images.githubusercontent.com/6567001/173179776-d03cd8e2-e1a7-47fa-bc0c-5e35e742fa5c.mp4

**Comment by Wolffenstein** [comment]
buy a new one
