### ISSUE TITLE
The Fate of Bloodbane quest is undoable

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1245]
**Description**:  The Fate of Bloodbane quest is undoable, as upon accepting the quest, and heading under the citadel, it doesn't phase into the death knights and him.

**Current behaviour**: As you can see below, the hulk terrors are still showing up because I didn't phase into the next part of the chain. I've tried dropping the quest and picking it up multiple times.

**Expected behaviour**: Upon accepting the quest "The Fate of Bloodbane" a player should phase into that scenario upon entering under the citadel to attempt to reach him/fight him.
![image](https://user-images.githubusercontent.com/6567001/173180975-dd82a0db-b94f-4006-89ea-ba0632a16143.png)

**Revision**:

**Comment by Exorcista** [comment]
Can confirm, just encountered this phasing bug, 3/4 of my grp coudn't do it, they sayd they did the Arthas quest so maybe it caused a phasing issue, they can't see Bloodbane or any npc, meawhile i didn't do arthas chain and was able to do it

**Comment by slicplaya** [comment]
I had to go get the phased ghost boy quest chain in East Ice crown at the whelps and pit with humanoids to get the zone to phase in correctly.
