### ISSUE TITLE
[PVP][BG] No spirit healers to res in Eye of the Storm (Possibly other bgs as well)

### ISSUE THREAD

**Issue by Trunkz629** [Stormforge-gg/Bugtracker-Fordring#1246]
No spirit healers to res in Eye of the Storm battleground (Possibly other bgs as well)

**Comment by noxy1212** [comment]
Also after last crash you cannot capture bases and flag doesnt spawn.

**Comment by Wolffenstein** [comment]
Hopefully fixed now
