### ISSUE TITLE
[NPC][Drop] Trash Mobs culling of stratholme normal

### ISSUE THREAD

**Issue by valipolarbear** [Stormforge-gg/Bugtracker-Fordring#1247]
**Description**: 
Glitched item level 200 items
https://prnt.sc/oBWC57Xrgjud
The glitched item name :  Spaulders of Elder's Square
**Current behaviour**:
They drop from culling of stratholme normal, theres also another glitched item called Trade District Knife
**Expected behaviour**: 
They should not drop there  from trash mobs since the max ilevel is 187.
**Revision**: 
Remove them from drop pool?

**Comment by Wolffenstein** [comment]
Fixed in rev 1504.
