### ISSUE TITLE
[Item]Crusader's Square Pauldrons missing stats

### ISSUE THREAD

**Issue by Nihaobeachez** [Stormforge-gg/Bugtracker-Fordring#1249]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Couldnt find it in changelog. 187 BoE Item with missing Stats  https://wotlk-twinhead.twinstar.cz/?item=37115

**Current behaviour**: Missing Stats

**Expected behaviour**: Should have Stats

**Revision**: 1487

**Comment by Wolffenstein** [comment]
delete your cache
