### ISSUE TITLE
Group Loot Broken

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Group loot does not work at all in RDF. All loot is given to the first person to loot the body, if you stand back and heal people you'll never get any bodies to loot afterwards. If you run in and loot enemies as they fall, you get everything.
**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by seitzcasey** [comment]
Can confirm. Am Healer. Get no loot.

**Comment by NatsumeLily** [comment]
What dungeon level range are you talking about?

Vanilla - Group loot 
Tbc and Wotlk - Need before Greed

If it's Tbc or Wotlk, there is a chance it's not working. Need before greed was super bugged in beta, and it might not be doing round robin for items below the threshold.

**Comment by Weuyn** [comment]
I was a little bit mad when i posted. Yeah to be specific it#s all white and grey items that are bugged. Greens and above are all rolled correctly but white and grey items go to whoever touches the body first.

Its supposed to be that only gold is looted this way, where first looter collects the gold (and then that gold is split). But potions, cloth, vendor trash etc is also being affected! Think of the poor healers.
