### ISSUE TITLE
Army of the Dead and CoH

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1251]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The ghouls summoned by army of the dead eat CoH targets. They definitely shouldn't be being targetted
**Current behaviour**:

**Expected behaviour**: 
COH should ignore army of the dead
**Revision**:

**Comment by Wolffenstein** [comment]
Proof?

**Comment by Weuyn** [comment]
its hard to get video proof from 11 years ago, but it has never worked this way on any private server I have played on before. It makes the spell useless while army is up since it only hits 1 person instead of 5 or 6 with glyph.

It might be that the smart heal part of CoH is not working, but that is hard to tell since raids are not out yet.

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
