### ISSUE TITLE
Prophet Tharon'ja rain of fire broken

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1254]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Last boss in drek'tharon keep doesn't cast rain of fire property
**Current behaviour**:
he channels his rain of fire cast, and a single meteor comes down, sometimes nothing at all. - damage dealt
**Expected behaviour**: 
SHould deal damage and last a while
**Revision**:

**Comment by Wolffenstein** [comment]
blizzlike bug
