### ISSUE TITLE
The kal'uak fishing derby event doesn't start.

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1255]
**Description**:  The kal'uak fishing competition should start on saturday 14:00 server time but the event doesn't start.

**Current behaviour**: The fishing event doesn't launch.

**Expected behaviour**: The fishing event start and can be completed normally.

**Comment by netbean2** [comment]
It is not supposed to be ingame 👎 
with a little google research : https://wowpedia.fandom.com/wiki/Kalu'ak_Fishing_Derby => The Kalu'ak Fishing Derby was a [fishing](https://wowpedia.fandom.com/wiki/Fishing) [event](https://wowpedia.fandom.com/wiki/Event) held every Saturday between 14:00 and 15:00 server time by the [Kalu'ak](https://wowpedia.fandom.com/wiki/Kalu%27ak). The objective was to be the first player to catch a  [[Blacktip Shark]](https://wowpedia.fandom.com/wiki/Blacktip_Shark) and bring it to [Elder Clearwater](https://wowpedia.fandom.com/wiki/Elder_Clearwater) in Dalaran.[[1]](https://wowpedia.fandom.com/wiki/Kalu'ak_Fishing_Derby#cite_note-1) It was introduced with [Patch 3.3.0](https://wowpedia.fandom.com/wiki/Patch_3.3.0).

**Comment by 666franz666** [comment]
The interesting Thing is, that you can catch the Blacktip Shark, but the Kalu'ak [NPC]Elder Clearwater in not there to bring it to him.
