### ISSUE TITLE
Prayer of Mending not smart healing

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1256]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Prayer of mending is supposed to jump to the lowest hp party member in range, instead of just randomly like it does now (was changed for wrath)
**Current behaviour**:
PoM just bounces randomly
**Expected behaviour**: 
It should prioritize people with low HP

Don't have video evidence, but here is a github merge for TrinityCore 11 years ago to fix this same issue and an mmo champion thread from 2009 saying how awesome it is for jumping only between those taking damage.
https://github.com/TrinityCore/TrinityCore/pull/27105
https://www.mmo-champion.com/threads/684952-Resto-Shaman-or-Holy-Priest

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
