### ISSUE TITLE
[Dungeon][NPC][Drop] Loken

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#1258]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  

**Current behaviour**:   Quest item "Loken's Tongue" seems to drop everytime you kill Loken, even after compliting the quest (or even before picking it up).

**Expected behaviour**:  It should drop only while you are on a quest for it.

**Revision**:

**Comment by Tereneckla** [comment]
Fixed soon™
