### ISSUE TITLE
Draeneis not getting expertise when switching to human

### ISSUE THREAD

**Issue by Gidanne** [Stormforge-gg/Bugtracker-Fordring#1259]
**Description**:  Switched from Draenei to Human with the racial change, but when i equipped a mace, it gave no expertise

**Current behaviour**: Does not give expertise when using a 2 handed mace

**Expected behaviour**:  +3 to my expertise

**Comment by Wolffenstein** [comment]
Works fine for me, just tested it. Try relogging.
