### ISSUE TITLE
[Core] RDF status lost after dying in completed instance

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1262]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I completed an RDF group (Razorfen Kraul) and the other 4 party members left. I hung around, trying to complete a quest. I died. When I released spirit, the dungeon finder icon on my minimap disappeared, along with the message "You are no longer queued in the Dungeon Finder". When I resurrected into RFK, the instance was a new one, with all the mobs up, and when I exited the instance, I was in The Barrens at the RFK instance portal instead of at my teleport location.

The RDF group should not end from releasing spirit, even if the instance is "completed".

**Comment by Wolffenstein** [comment]
If all party members leave an LFG group and you exit the instance the LFG group ceases to exist. Intended.
