### ISSUE TITLE
[NPC] Reginald Arcfire

### ISSUE THREAD

**Issue by Soufly** [Stormforge-gg/Bugtracker-Fordring#1265]
**Current behaviour**: Reginald Arcfire(engineering auction house in dalaran) is up.

**Expected behaviour**: 
He should be unavailable until patch 3.2.

**Revision**: 
https://www.wowhead.com/npc=35607/reginald-arcfire

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
