### ISSUE TITLE
[Item] Festival Lane Girdle randomized stats not present

### ISSUE THREAD

**Issue by Dopp0** [Stormforge-gg/Bugtracker-Fordring#1269]
**Description**: Festival Lane Girdle dropping in CoS has no randomized stats - Maybe this is a general thing for similar items? But this is my first time seeing 'empty' items on this server so far so maybe it's an isolated case for this item

**Current behaviour**: No stats are appended to the item

**Expected behaviour**: The stats should be randomized like other similar items
**Revision**: 1504

![image](https://user-images.githubusercontent.com/93954647/173206311-de85e5f3-5fa1-4719-968e-9fe7c6cee4a8.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
