### ISSUE TITLE
[Feature Request] BG Queue Announcer Disable

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1272]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While it's great that there's now a chat announcement when a BG pops, we should have the ability to disable these messages with a dot command.

**Comment by NatsumeLily** [comment]
Turn off this setting and you should no longer see the messages. 
![image](https://user-images.githubusercontent.com/15247730/173710919-31f2b94d-3914-410d-8174-6b5ab531375b.png)

**Comment by Vishiswaz** [comment]
Closing due to new server core.
