### ISSUE TITLE
[Spell][Warrior] Spell Reflection

### ISSUE THREAD

**Issue by MafiaK1** [Stormforge-gg/Bugtracker-Fordring#1275]
Description: Reflection is shown but does 0 damage on Spells ( DoTs work )

Current behaviour: Reflect is shown in Combat Log and on the Avatar, Spell gets bounced back but without damage.

Expected behaviour: Same as above but with damage.

Revision: 1504

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/173244869-0ccc5c04-657f-42fd-8c4b-0fbccf0975e4.png)
?

**Comment by MafiaK1** [comment]
![1](https://user-images.githubusercontent.com/8547863/173247880-18baef2c-87e0-470a-a0c7-03ea5b6ed567.JPG)
![2](https://user-images.githubusercontent.com/8547863/173247883-9c347eea-bc78-4007-968c-f36d7aee7ec4.JPG)
![3](https://user-images.githubusercontent.com/8547863/173247885-60ba698c-8fd7-4d12-9807-0c15a3d08163.JPG)

also in Ahn'kahet: The Old Kingdom if you reflect Spellflinger they should get alot of dmg and yourself some aggro but nothing. 
on one screen i reflected a frostbold and he gets arcane shock and dmg Oo

**Comment by slicplaya** [comment]
Is your log showing reflected dmg and such?

**Comment by MafiaK1** [comment]
![sunwell](https://user-images.githubusercontent.com/8547863/173351304-1a19210c-bdd1-4dd0-b2d0-2726f9bcbd23.JPG)
![storm](https://user-images.githubusercontent.com/8547863/173351324-6c1b9c41-2906-40f0-be4a-6334e38f16b7.JPG)

I checked my warrior on Old sunwell, if i reflect there. Dmg shows above the mob and also in recount.
One the second screen it doesnt do it on this server ( and this time reflect worked )

Also compared my Settings on both Servers and its 1 to 1.
Hopefully im not the only one who doesnt get the reflected dmg above the mob and maybe that fixes the threat + dmg?

**Comment by Amun12** [comment]
Killing a player with spell reflect doesn't count as killing blow in bgs, pretty sure it should. Yellow numbers (damage done from spells) don't seem to pop either, when you reflect a spell.
