### ISSUE TITLE
[Quest][Borean Tundra] Get Me Outa Here!

### ISSUE THREAD

**Issue by owliepecks** [Stormforge-gg/Bugtracker-Fordring#1278]
**Description**: When doing this quest with a group, I received the notification to begin the quest and accepted. Upon completing the quest, I did not receive credit- only the person who originally triggered the quest got credit.

**Current behaviour**: Group members do not receive credit for completing the escort quest. Accept quest when someone triggers it while in a group, do the quest objective, do not receive credit and therefore cannot complete/turn in quest, resulting in having to do the escort a second time.

**Expected behaviour**: Accept quest when someone triggers it while in a group, do the quest objective, complete and turn in the quest.

**Revision**:

**Comment by Tereneckla** [comment]
Fixed soon™
