### ISSUE TITLE
[Core] Mob engineering giving skill points

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1280]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Was reported in #1205. 

I don't think mob engineering should give skill ups. I can't find any proof it should or any talk about it at all. You would think that profession guides would tell you to level that way but they don't mention it. 

Mob herbalism and mob mining should act the same way, no skill ups when doing it. Found this comment while checking those.
https://www.wowhead.com/npc=19188/raging-colossus#comments
![image](https://user-images.githubusercontent.com/15247730/173210931-91e615cc-0191-4f0a-81f6-e2588a8dafc3.png)

**Revision**:

**Comment by NatsumeLily** [comment]
https://wowpedia.fandom.com/wiki/Mob_engineering
Doesn't say anywhere on that page that it give skill points.

**Comment by NatsumeLily** [comment]
https://www.wowhead.com/npc=114/harvest-watcher#comments
![image](https://user-images.githubusercontent.com/15247730/173211131-18dee007-244a-45e2-9491-a05af25b0b6d.png)
This guy says they can be "mined" for parts, thats it. Nothing about it giving skill points.

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
