### ISSUE TITLE
Hunter SV spec talent 'Entrapment' doesn't work on moving targets

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1281]
**Description**:  Hunter SV spec talent **Entrapment** doesn't work on targets moving through a trap that's been placed outside of the mob hit box or trap target searching radius.

**Current behaviour**: 

https://user-images.githubusercontent.com/6567001/173211147-31de9bcd-4e06-49af-986e-b954b8f33d3e.mp4

There is definitely something Wonky going on with it. It doesn't fail every time, but it is closer to 80%. If you place a trap in a target or within the trap search radius, it works always. The same issue occurs with Frost trap as well. 

**Expected behaviour**: At any point in a traps duration, when specced with Entrapment, a target should be ensnared for the duration if the trap triggers when crossed through whether the target is stationary or not.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
