### ISSUE TITLE
Appeasing the Great Rain Stone (Oracles Daily)

### ISSUE THREAD

**Issue by Gidanne** [Stormforge-gg/Bugtracker-Fordring#1282]
**Description**:  You are supposed to use Lafoo to find shiny treasures but it is either bugged or the drop chance is nonexistent because it takes me over 40 mins just to finish it.

**Current behaviour**: Extremely low drop chance as it always spawns bugs instead making this quest a snoozefest

**Expected behaviour**: Shiny Treasures drop chance normally is wayyy higher than it is right now on this server

**Comment by Tereneckla** [comment]
Fixed soon™
