### ISSUE TITLE
[Spell][DK] Ghoul loses health after switching presence

### ISSUE THREAD

**Issue by strzala** [Stormforge-gg/Bugtracker-Fordring#1283]
**Description**: Ghoul loses most of his HP after switching dk presence. Health is not regenerating to full after that.

**Current behaviour**:
Switching DK Presence makes Ghoul loses his hp.

**Expected behaviour**: 
Presence does not makes dk pet loses his hp
**Revision**: 
1504

**Comment by haephaistoss** [comment]
Ghoul should stay the same hp %, but the max hp of which it is a given % should change

**Comment by Wolffenstein** [comment]
Fixed in rev 1515.
