### ISSUE TITLE
Line of sight bug in Warsong Gulch

### ISSUE THREAD

**Issue by foffos** [Stormforge-gg/Bugtracker-Fordring#1284]
Description: you can can target and cast spells to target from downsite to upside the alliance respawn zone

Current behaviour: 
![WoWScrnShot_061222_115801](https://user-images.githubusercontent.com/26709267/173228047-0c349ee2-4b3d-4827-b431-d2414afc3835.jpg)
![WoWScrnShot_061222_115758](https://user-images.githubusercontent.com/26709267/173228050-906c462d-9e35-4086-81f2-84d267ff49dc.jpg)
![WoWScrnShot_061222_115753](https://user-images.githubusercontent.com/26709267/173228053-7732087e-e616-4937-8f05-aeaaa38cca21.jpg)

Expected behaviour: the line of sight should block you from casting

Revision:

**Comment by Wolffenstein** [comment]
blizzlike
