### ISSUE TITLE
deep freeze (stun immune) does not benefit from shatter

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1285]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Deep freeze should benefit from the talent shatter, which increases critical strike chance against frozen targets by 50%.
**Current behaviour**:
Deep freeze parses very low crit rate, seeing numbers that look like no shatter interaction.
**Expected behaviour**: 
Since deep freeze is only useable on bosses when you have a fingers proc, should always have the +50% crit chance.

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
