### ISSUE TITLE
Invisibility (mage) vision

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1286]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While under the effects of invisibility, you should not be able to see enemy targets.
**Current behaviour**:
Can see enemy targets while invisible.

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
