### ISSUE TITLE
[Hunter][Pet][Spell] Rabid

### ISSUE THREAD

**Issue by Soufly** [Stormforge-gg/Bugtracker-Fordring#1287]
Current behaviour:My devilsaur is using Rabid on CD if he has it on ''autocast''.

Expected behaviour: The pet should use his ''autocast'' abilities only when he is ordered to attack or when he is attacked in defensive stance.

Revision:
Make a BM hunter,get a devilsaur and put Rabid on autocast.

Edit: I tried to relog,dismiss+summon or just get another pet ... still casting it on CD.

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
