### ISSUE TITLE
[DRUID][Swiftmend] Not consuming hots

### ISSUE THREAD

**Issue by Sashathegeek** [Stormforge-gg/Bugtracker-Fordring#1288]
**Description**:
I don't have glyph of swiftmend and in dungeons, my swiftmend doesn't consume hots. I'm not sure if its a weird interaction with glyphs or its broken.

**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by Wolffenstein** [comment]
Can't reproduce, works fine for me.

**Comment by Sashathegeek** [comment]
It only does this in dungeons for me, with glyph of rapid rejuv and other rejuv glyph.
