### ISSUE TITLE
[Item] Recipe: Elixir of Major Defense (22909)

### ISSUE THREAD

**Issue by seitzcasey** [Stormforge-gg/Bugtracker-Fordring#1289]
**Description**: 
Required recipe for elixir master quest line. wow head comment indicates ~5min restock but I waited at vendor [NPC] Daga Ramba (19837) for 20+ minutes with no restock

https://tbc.wowhead.com/item=22909/recipe-elixir-of-major-defense#comments

**Revision**: 
1504

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
