### ISSUE TITLE
[Dungeon] Black Morass

### ISSUE THREAD

**Issue by seitzcasey** [Stormforge-gg/Bugtracker-Fordring#1293]
**Description**: 
Portals stop after the 7th portal.
[Item] Essence of Infinity doesn't give to all available recipients. Also not 100% drop (Not sure if it should)

Required Dungeon for Elixir Master

**Revision**: 
1504

**Comment by Vishiswaz** [comment]
This dungeon has not yet been ported from Atlantiss.

**Comment by Godmatik** [comment]
> [Item] Essence of Infinity doesn't give to all available recipients. Also not 100% drop (Not sure if it should)

Blizzlike - low drop chance and the item is not shared for all recipients that have the Alchemy quest.
