### ISSUE TITLE
occulus - drake channeling interrupt

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1294]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**:
drake channelling cannot be interrupted by moving, or alternative methods like /stopcasting.
**Expected behaviour**: 
When moving, channeled drake abilities should be cancelled.

**Comment by Wolffenstein** [comment]
Fixed in rev 1511.
