### ISSUE TITLE
[Zone][NPC][Spell]The Nexus heroic, Keristrasza (26723) missing Intense Cold Debuff (48094)

### ISSUE THREAD

**Issue by Nihaobeachez** [Stormforge-gg/Bugtracker-Fordring#1295]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Keristrasza should apply Intense Cold Debuff to everyone. 

**Current behaviour**: Keristrasza doesnt apply the Intense Cold Debuff (48094) anymore, did work earlier but its broken now somehow

**Expected behaviour**:  Should apply Intense Cold Debuff 

**Revision**: 1504

**Comment by Wolffenstein** [comment]
works fine

**Comment by FX-SF** [comment]
It does not work correctly in heroic mode. People tell me to move and i say you dont need to. then they all agree, theres no debuff. This happens often

**Comment by nevrozac** [comment]
Confirm that aura is not correctly applied to players when engaging the boss. No idea how to reproduce however
