### ISSUE TITLE
[Spell][Rogue] Shadow dance

### ISSUE THREAD

**Issue by Erslol** [Stormforge-gg/Bugtracker-Fordring#1297]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: using Vanish/Stealth removes the Shadowdance effect

**Current behaviour**: using Vanish/Stealth removes the Shadowdance effect

**Expected behaviour**: using Vanish/Stealth should not remove the Shadowdance effect

**Revision**: 1504

**Comment by NatsumeLily** [comment]
Since you forgot the proof. 
video min 3:50 - 4:30
http://www.warcraftmovies.com/movieview.php?id=164521

From https://github.com/TrinityCore/TrinityCore/issues/8324

More proof and a bug that might pop up. https://www.engadget.com/2010-03-27-the-daily-blues.html

**Comment by Erslol** [comment]
> Since you forgot the proof. video min 3:50 - 4:30 http://www.warcraftmovies.com/movieview.php?id=164521
> 
> From [TrinityCore/TrinityCore#8324](https://github.com/TrinityCore/TrinityCore/issues/8324)
> 
> More proof and a bug that might pop up. https://www.engadget.com/2010-03-27-the-daily-blues.html

Thanks, but I didn't think it needed proof :D

**Comment by haephaistoss** [comment]
everything does

**Comment by NatsumeLily** [comment]
Fixed in 1551. 
![image](https://user-images.githubusercontent.com/15247730/175343782-24dacf3c-f0ee-4a95-92e9-b92ad5bd2129.png)
