### ISSUE TITLE
[Spell] CC Spell Delay

### ISSUE THREAD

**Issue by Erslol** [Stormforge-gg/Bugtracker-Fordring#1298]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  CC spells should have a delay between casting and application on target

**Current behaviour**:  Tested on rogues spells - effects are applied instantly 

**Expected behaviour**: CC spells should have a delay between casting and application on target.  Usually it's 100-250 ms.

**Revision**: 1504

Without CC spell delay rogues can't do a standart pvp tricks, like vanishing Blind, Stun, Deep freeze and others "instant" abilitys

**Comment by haephaistoss** [comment]
Should be possible to sap each other and cc each other because of this

**Comment by slicplaya** [comment]
Spell batching ftw

**Comment by slicplaya** [comment]
Silencing shot has a travel time and isn’t instant here. 🤦🏽‍♂️
