### ISSUE TITLE
[Shadowmoon Valley][Quest] I was A lot of things...

### ISSUE THREAD

**Issue by subi900** [Stormforge-gg/Bugtracker-Fordring#1300]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Quest "I was a lot of things..." does not work

**Current behaviour**: When using "Ornok's Boar Whistle, the boars nearby do not react to get you the required shadowmoon tuber.

**Expected behaviour**: When using "Ornok's Boar Whistle, a boar nearby will come and dig up a shadowmoon tuber for you.

**Revision**:

**Comment by Exorcista** [comment]
Quest: https://tbc.wowhead.com/quest=10514/i-was-a-lot-of-things

You need to use it when boars are really close to the tubbers, but still its buggy, sometimes i did it with them on top of the tubber and they ignored it
