### ISSUE TITLE
[Spell] "A more powerful spell is already active"

### ISSUE THREAD

**Issue by Erslol** [Stormforge-gg/Bugtracker-Fordring#1303]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: This mechanic is missing. A more powerful spell should not be replaced by weak (diminishing returns).

**Current behaviour**: Rogues can cast second Sap right after first

**Expected behaviour**:  Rogues can cast second Sap after half of duration first.  If trying to cast - "A more powerful spell is already active" on screen.

**Revision**: 1504

This should work the same for mage Sheep and warlock Fear

Proofs:
1) https://youtu.be/vCvfQoKfMBQ  0:13

2) https://youtu.be/jiaX4nuWgR0    9:06

Sorry for my english. Using translator.

**Comment by Vishiswaz** [comment]
To be clear: This is only in PvP where there is diminishing returns on CC.
