### ISSUE TITLE
 [It Could Be Anywhere!] Quest - Ring Not droping

### ISSUE THREAD

**Issue by dontfaket30** [Stormforge-gg/Bugtracker-Fordring#1305]
**Description**:   [It Could Be Anywhere!] Quest ring not droping. I have been killing over 400-500 mobs/ads now in basin and still no ring. 

stuck with 4-5 hours with this quest.

**Comment by dalaraz** [comment]
i have the same experience atm,im not so deep in kills but after like 200 mobs no ring
