### ISSUE TITLE
Warsong Gulch Speed bug

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1309]
**Description**: Warsong Gulch Speed buff can be picked up by pets.

**Current behaviour**: Currently, while attempting too run into the buff, a hunter's pet can pick up the buff
![Capture](https://user-images.githubusercontent.com/6567001/173294951-dc787cb6-2c64-40c0-84c7-9faacf07365a.JPG)

**Expected behaviour**: Only players should be tagged to pick up the buff when within proximity.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1515.
