### ISSUE TITLE
[Item] Recipe Formula: Enchant Shield - Major Stamina

### ISSUE THREAD

**Issue by KuupoKop** [Stormforge-gg/Bugtracker-Fordring#1310]
**Description**: [Item] Recipe Formula: Enchant Shield - Major Stamina respawn timer is off

**Current behaviour**: This recipe is sold by Madame Ruby in Shattrath city. It is an essential recipe for enchanters to use while leveling. According to comments from 2010 on Wowhead ( http://www.wowhead.com/item=28282/formula-enchant-shield-major-stamina#comments ) this recipe should be restocking every 10-15 minutes. Currently it is not.

**Expected behaviour**: Recipe should be restocking every 10-15 minutes.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1520.
