### ISSUE TITLE
[Quest][Sholazar Basin] Gods like Shiny Things

### ISSUE THREAD

**Issue by bigdeekpumper** [Stormforge-gg/Bugtracker-Fordring#1312]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  This quest is currently bugged and it seems impossible to complete.

**Current behaviour**: I activate my bag to summon  the quest companion (Lafoo), he goes to the shiny spots hes supposed to dig but he never ever gets the quest objective. 

**Expected behaviour**: he's supposed to dig the quest objetive on these shiny points, spawning an interactive "Glowing Gem" object to gather the shiny treasure from, as seem here: https://www.youtube.com/watch?v=o20_MYn6vpg

**Revision**: 1504

**Comment by jorgehurtadodmx** [comment]
It works, you need to dig lots of places, some have roaches, some have treasures. You have to pick up that treasures.

**Comment by bigdeekpumper** [comment]
I can confirm its indeed working on rev 1566.
