### ISSUE TITLE
Hunter snakes from (Snake trap) break cc still even if the target scatered or traped

### ISSUE THREAD

**Issue by mehdimedkouri** [Stormforge-gg/Bugtracker-Fordring#1315]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
As a pvp player, i found this issue really matter for hunters or specially survival hunter, every pvp hunter use the glyphe :  [Glyph of Solace] for scater and freezing trap to remove any damage/dot over time effects from the target , and the bug that i'm talking about is when your snakes from  [Snake Trap] bleed your target and even after scatering or traping that target , the bleeds from  [Snake Trap] doesn't get remove which allow to break every cc! 
**Current behaviour**:
I found this really annoying for the fact that I'm playing survival hunter in order to root people that are trying to eat my trap with  [Snake Trap] but then i just break my own cc with my own spell which supose not to happen
**Expected behaviour**: 
I hope this bugged issue get fixed immediately cuz it's still stops me to play arena, and there is not only this bug about hunter, ive seen many bugged things specially about trap inside arena, but i reported this one cuz it's important to get fixed
**Revision**:

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/173388355-da7c77bf-1f3c-48f7-9cb2-19e3b50d0720.png)
Wrong bugtracker, this isn't Mistblade.
