### ISSUE TITLE
Death Knight Umholy Ghoul issue

### ISSUE THREAD

**Issue by Vitezica** [Stormforge-gg/Bugtracker-Fordring#1318]
[//]: # ([Spell][Class] Reise Dead) 

**Description**: From time to time, when questing, doing dungeons etc my pet ghoul just instantly takes massive damage and gets down to 1/3 of his HP. Now it started to happen even in Orgrimar, just searching in AH. I also noticed when people are giving buffs such as priest stamina buff, my pet gets to 1/3 of his hp. This makes ghoul very easy to kill and he very often dies from random AOE in dungeons, simply because he instantly loses 2/3 of his hp for no reason.

**Current behaviour**: takes random damage out of nowhere and goes to 1/3 of its HP

**Expected behaviour**: Should stay at full hp if not being attacked or damaged

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1515.
