### ISSUE TITLE
 [Item] Design: Shifting Twilight Opal (41747)

### ISSUE THREAD

**Issue by Radian758** [Stormforge-gg/Bugtracker-Fordring#1319]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**: The design for Shifting Twilight Opal is available from Dalaran jc vendor.

**Expected behaviour**: Should be unavailable until patch 3.1.

**Revision**: 
https://www.wowhead.com/item=41747/design-shifting-twilight-opal

**Comment by Wolffenstein** [comment]
Removed
