### ISSUE TITLE
PvP graveyard resurrects unholy ghoul, even after swapping to frost

### ISSUE THREAD

**Issue by AyfoAF** [Stormforge-gg/Bugtracker-Fordring#1323]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: If I join a wintergrasp as Unholy, summon my permanent ghoul and then swap to Frost: the pet will immediately despawn. However when I am resurrected at the graveyard the permanent ghoul will respawn with me, including access to pet action bar / spells (stun, leap, etc) despite being in frost and having no talent points in that part of the unholy tree. 

The pet remained with me for over 40 minutes. I finished wintergrasp (several deaths, pet remained) I queued up for a battleground (got stomped, several deaths, pet kept respawning with me at each EOTS gy) I entered an rdf heroic (the pet was there for the first 2 bosses of Azjol-Nerub and then despawned after the big drop towards the final boss Anub'arak). At no point did I swap back / forth between specs other than the initial Unholy -> Frost at the beginning of wintergrasp almost an hour earlier

**Current behaviour**: If you have a permanent Unholy ghoul summoned at any point in PvP (battleground / wintergrasp) the spirit healer will resurrect the ghoul with you, even if you do not have the talent

**Expected behaviour**: Frost shouldn't have access to abilities they don't have talented

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1520.
