### ISSUE TITLE
Skinning Issue

### ISSUE THREAD

**Issue by fattyd0e** [Stormforge-gg/Bugtracker-Fordring#1326]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Skinning Block from looted corpse 

**Current behaviour**: When attempting to skin enemies that i look i get an error message that indicates that the body needs to be looted first. the body has been looted but i am not able to skin the body. 

**Expected behaviour**: should be able to skin the enemy after looting. 

**Revision**:

**Comment by fattyd0e** [comment]
I should point out that i am out solo farming for leather. so it is not related to being in a party and not everyone looting. 

Happening Primarily with the spiders in Zul'Drak

**Comment by Vishiswaz** [comment]
You should specify the NPCs this happens with. Their name, not just "the spiders".

**Comment by fattyd0e** [comment]
It isn't just limited to the spider in Zul'drak. issue occurs with the dragon in Nexus, Dragons in Violet Horde, Dragons in Utgarde Keep, Wolves in Utgarde Pinnacle and Keep, Boars in Borean Tundra. Mammoth in Borean Thundra, Gorrilas in Sholazar.

It is any creature there is a 40% chance that you are not able to skin them due to a loot bug.

**Comment by Wolffenstein** [comment]
Fixed in rev 1537.
