### ISSUE TITLE
Greater blessing of Wisdom/pet bug

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1328]
**Description**:  Casting greater blessing of wisdom on mages in close proximity to hunter pets also buffs the pet with it.
![Capture](https://user-images.githubusercontent.com/6567001/173464217-a34adf89-e02b-467b-8fd2-eb81d885a8fb.JPG)

**Current behaviour**:

**Expected behaviour**: Hunter pets should not get buffs from mages buffed.

**Revision**: 1514

**Comment by NatsumeLily** [comment]
I think hunter pets should be treated as a warrior class for blessings, but don't know anything beyond that.

**Comment by Godmatik** [comment]
On other private Wrath servers for greater pally blessings:

DK Ghouls share with Rogue
Hunter pets share with Warrior
Warlock pets share with Warlock

I have no idea if this is how it is supposed to work though.

**Comment by Wolffenstein** [comment]
Fixed in rev 1520.
