### ISSUE TITLE
Wintergrasp spirit healers not working after WG ends

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1330]
**Description**: Wintergrasp spirit healers not working after WG ends

**Current behaviour**: Wintergrasp spirit healers not working after WG ends

**Expected behaviour**: The resurrection spirit healers should still persist at the horde/alliance spawn points after WG ends.

**Revision**: 1514

**Comment by Godmatik** [comment]
Proof? I'm fairly sure they shouldn't be there after a WG battle ends.

They originally existed but were removed after this report was made:

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/744

**Comment by slicplaya** [comment]
Took me awhile, but I did find this from blizz server. https://www.youtube.com/watch?v=2O9yr8Z2WOc&t=1082s You'll notice it ends, and he reses instantly while dead and the spirit healer remains. It's possible since this is a later expansion they changed the ressing methods. I will look for more.

**Comment by slicplaya** [comment]
After a wintergrasp ends and PvP is still ensuing, you shouldn't be punished for finishing out a fight by having to spirit fly back and wait 2+ minutes to resume gameplay.
