### ISSUE TITLE
Battle in Valhalas: Fallen Heroes Quest will not reappear

### ISSUE THREAD

**Issue by AgentMalice** [Stormforge-gg/Bugtracker-Fordring#1331]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
([Quest][Icecrown] Battle in Valhalas: Fallen Heroes)
([NPC] Geirrvif)

https://wotlk-twinhead.twinstar.cz/?quest=13214

**Description**: 
I did the pre-requisite "Battle in Valhalas" from the Bone Witch and turned it in to the Geirrvif.  After i was able to pick up the quest and continue the quest line.

**Current behaviour**:
I failed the following quest "Battle in Valhalas: Fallen heroes" so I abandoned it to pick up later.  Now, I cannot pick it up from Geirrvif.  She shows as Neutral yellow and has no quest available for pickup.

**Expected behaviour**: 
I should be able to pick up the quest still from Geirrvif.

**Revision**:

**Comment by nevrozac** [comment]
Confirm that the game doesn't register wether the fight has concluded or not. Player is not given completion credit and the NPC Geirrvif 31135 that gives the quest remains in a spectator stance as if the fight were still going on. 
Considering that I have managed to finish this quest line on a different character I suspect the bug occurs only after someone has already completed the quest after a restart and further completion by other players bugs out

**Comment by slicplaya** [comment]
I can't even talk to her to get the arena chains.

**Comment by iblgts** [comment]
I also have the same problem, was able to do the quest the first time then I failed it and decided to do it later with a party. When I had to abandon it to get the quest again, [NPC] Geirrvif cannot be interacted with anymore.
