### ISSUE TITLE
Can't fish up Lurker Below in Serpentshrine Cavern

### ISSUE THREAD

**Issue by ameliandra** [Stormforge-gg/Bugtracker-Fordring#1332]
**Description**:  Fished for about 20 minutes with 450 fishing with a +20 fishing rod and a +100 bait and The Lurker Below never showed up. Every time i successfully fished in the Strange Pool, it would disappear and then reappear a few seconds afterwards.

**Current behaviour**: Luker Below can't be fished up.

**Expected behaviour**:  Luker Below should be able to be fished up.

**Comment by Godmatik** [comment]
The TBC dungeons/raids haven't been ported over from Atlantiss Core yet, will probably be fixed once Wolf gets around to it

**Comment by salt-die** [comment]
Can confirm this. Fishing Lurker needed for "Salty" title.
