### ISSUE TITLE
[Quest][Zul'drak] Rampage

### ISSUE THREAD

**Issue by Exorcista** [Stormforge-gg/Bugtracker-Fordring#1333]
**Current behaviour**:  Akali from quest (https://www.wowhead.com/quest=12721/rampage) is bugged out, cannot free him while doing the clicking on the altars

**Expected behaviour**:  You be able to free him and thus completing the quest + unlocking 2 more quests. Ref video:  https://www.youtube.com/watch?v=cfKUxE8xFAw

**Comment by jorgehurtadodmx** [comment]
Many people have reported that it doesn't work in world chat, me included.
Clicking on altar does nothing when it should work.

**Comment by Exorcista** [comment]
> Many people have reported that it doesn't work in world chat, me included. Clicking on altar does nothing when it should work.

it just never does, and i need that quest for the Zul Drak quest achieve lol

**Comment by Exorcista** [comment]
@Wolffenstein /pray

**Comment by Exorcista** [comment]
> This is still an issue as of rev 1548
> 
> @Exorcista You can currently get the quest achievement "The Empire of Zul'Drak" without completing this quest. ![image](https://user-images.githubusercontent.com/105084838/175047306-3b0b3ef7-9cfc-4c0b-982e-1a5d747e3fb4.png)

i have no clue how, i trully did all quests even drop ins, the one for inside dungeon(even if they dont count had to try...)
