### ISSUE TITLE
Song of Wind and Water (Oracles Daily Quest)

### ISSUE THREAD

**Issue by Gidanne** [Stormforge-gg/Bugtracker-Fordring#1336]
**Description**: You should use the drums to transform into an elemental and devour spirits

**Current behaviour**: Transforming into a water elemental works, but when you absorb a storm elemental, you cannot use abilities thus making the quest impossible to complete.

**Expected behaviour**:  You should be able to use abilities regardless of which form you take

**Comment by talanted94** [comment]
It also changes abilities to cat form ones on druid after reloading ui

**Comment by FX-SF** [comment]
Similar to issue #1496

**Comment by Wolffenstein** [comment]
Fixed in rev 1572.
