### ISSUE TITLE
[Core] Deaths in the Frozen Sea teleport to wrong Graveyard

### ISSUE THREAD

**Issue by hederob** [Stormforge-gg/Bugtracker-Fordring#1337]
**Description**: 
Deaths in the Frozen Sea teleport to wrong Graveyard
**Current behaviour**:
When I died in the Frozen Sea near Howling Fjord, my ghost appeared in the Borean Tundra's graveyard near Death's Stand.

![WoWScrnShot_061422_014218](https://user-images.githubusercontent.com/25690905/173511699-4e282f49-0c34-4f6a-a241-6cd1a488f394.jpg)

**Expected behaviour**: 
I should be appearing at a more nearby graveyard, such as one in Howling Fjord.
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1520.
