### ISSUE TITLE
[Item][Trinket] Spark of Life and Forge Ember don't proc from hots casts

### ISSUE THREAD

**Issue by Barcaz** [Stormforge-gg/Bugtracker-Fordring#1339]
**Current behaviour**: Spark of LIfe and Forge Ember can't proc from casting/applying hots only from casting direct heals,tested on resto druid. 

**Expected behaviour**: They should have a chance to proc on every healing gcd for resto druid.

**Comment by NatsumeLily** [comment]
Spark of Life -
![image](https://user-images.githubusercontent.com/15247730/173626408-7565b61a-5c6f-45b8-a231-bf83a3a4c7f8.png)
![image](https://user-images.githubusercontent.com/15247730/173626728-2e3b9512-242d-40f8-8911-241e62a60bfa.png)
It should proc when casting HoTs, not the ticks but the application. 

Forge Ember -
![image](https://user-images.githubusercontent.com/15247730/173628899-b1c9eb48-1eba-42df-9757-72983d1320fa.png)
![image](https://user-images.githubusercontent.com/15247730/173628953-a07b3edb-10f7-42d9-9d10-3d6b6acc9b61.png)

**Comment by Barcaz** [comment]
![image](https://user-images.githubusercontent.com/51231110/173630207-21e30469-31f3-4299-ba4a-2531326bf6d7.png)
too if i doesn't proc from hots cast just the application as NatsumeLily it can't be anywhere close to 60 mp5 and would've been counted as one of the worst trinkets for resto druid. Nearly every tooltip with similar text like for example omen of clarity that says it can proc from healing spells count hots casts and it makes no sense for it to be just from direct heals.
