### ISSUE TITLE
[Core] Need before greed restrictions for vanilla dungeon finder

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1342]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Just found out the Need before Greed armour restrictions are in vanilla dungeons. 

The restrictions from need before greed should not apply for vanilla dungeon finder.

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/588#issuecomment-1132303891
![image](https://user-images.githubusercontent.com/15247730/173623237-b3bf0c35-db99-4619-81d6-c64f0744ecce.png)

**Revision**:

**Comment by Vishiswaz** [comment]
It might not be blizzlike to include them on Vanilla dungeons but it is a good thing to keep. Many other servers do it the way it is now, and I don't think Warriors should be gaining the ability to Need on Cloth.

**Comment by NatsumeLily** [comment]
It solves more problems than it creates. It's a shit show trying to level healers in dungeon finder. There is almost no healing or even int leather, mail, or plate gear.

**Comment by Vishiswaz** [comment]
There isn't a lack of healers in vanilla dungeons currently. There's a lack of tanks.
