### ISSUE TITLE
[Item] Festival Lane Girdle - should not drop

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Fordring#1351]
Festival Lane Girdle has a chance to drop in Culling of Strat dungeon from trash mobs, but should not exist.

Looks like a crappy prototype belt that Blizz removed/never fully developed before releasing Wrath.

https://wotlkdb.com/?item=37699

![Festival](https://user-images.githubusercontent.com/37913400/173717697-ed0aabc4-12bf-46f9-93c7-83dfdcbca862.png)

**Comment by Wolffenstein** [comment]
They added it to the loot tables in cata because they probably realized it was missing back in wotlk. I added it because whatever at this point, if you delete cache it should have proper stats

**Comment by Godmatik** [comment]
I feel like the stats need to be revisited then - only intellect and spirit on a plate piece makes sense for Cata (since intellect = spell power, and spirit was an actual regen stat for holy pallies), but not for Wrath.
