### ISSUE TITLE
Wild Hunt is completely broken making BM unplayable competitively

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1354]
**Description**:  Wild Hunt is completely broken after mounting/dismissing pet. 
![WoWScrnShot_061422_231702](https://user-images.githubusercontent.com/6567001/173760886-14e9b599-3e1d-4c4d-bb27-0716dd3798a8.jpg)
![WoWScrnShot_061422_231728](https://user-images.githubusercontent.com/6567001/173760964-137cd376-17e3-4548-a49c-43af5d0378e8.jpg)
![WoWScrnShot_061422_231742](https://user-images.githubusercontent.com/6567001/173760988-cd52f515-ced4-4432-a32a-421cf41d18ed.jpg)
As you can see in the 3 above pictures, the first does NOT have Wild Hunt talented. the dps is 365.3.
The second picture has Wild hunt talented and the dps increases to 384.8.
The final picture has Wild Hunter talented but I had removed the pet and recalled it and the dps is back to 365.3, rendering the talent completely useless and the BM spec lacking.

**Current behavior**: Wild Hunt is completely broken after mounting/dismissing pet. Adding any additional pet talent makes Wild Hunt "Count" again, but as soon as the prior, i.e. dismissing pet or mounting(removing it from active play), the talent is rendered useless.

**Expected behavior**: Wild Hunt should give the statistical contributions from the hunter's gear to the pet whether the pet is dismissed or not. 

**Revision**: 1514

**Comment by Viryll** [comment]
You can get the buff back by using aspect of hawk and removing it.

**Comment by Wolffenstein** [comment]
Fixed in rev 1538.
