### ISSUE TITLE
Crit Immunity not correct?

### ISSUE THREAD

**Issue by Secare69** [Stormforge-gg/Bugtracker-Fordring#1359]
**Description**: Just got crit by Azjol'nerub last boss on Heroic difficulty, despite having 5.67% crit resist combined through defence rating and resilience. 

**Current behaviour**: Being crit despite over defence crit cap

**Expected behaviour**:  Being immune to crit. First 2 links are my prot paladins defence rating and resilience, adding to 5.67% reduced chance to be crit, 3rd is boss still critting me.

**Revision**: 
![1](https://user-images.githubusercontent.com/106936607/173861254-fa482672-e319-4923-a9c5-0b6633ae3f4f.png)
![2](https://user-images.githubusercontent.com/106936607/173861257-7c93cdea-e4d4-42b1-a189-50a496557fa9.png)
![3](https://user-images.githubusercontent.com/106936607/173861419-87f59eb2-fa23-4e1b-96e1-6b4a7f79f893.png)

**Comment by slicplaya** [comment]
Maybe it’s mistakenly only attributed to players as the other resil stats are. Hrmm
