### ISSUE TITLE
[Spell][Priest]Shadow Word: Death

### ISSUE THREAD

**Issue by Felis097** [Stormforge-gg/Bugtracker-Fordring#1360]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**: 
Skill deals damage to caster when target is still alive and when it's killed

**Expected behaviour**: 
Skill should not deal damage to caster if target is killed

**Comment by fondlez** [comment]
Just tested it at level 80 and I cannot replicate that with Shadow Word: Death (Rank 4). It works as expected.

**Comment by Felis097** [comment]
> Just tested it at level 80 and I cannot replicate that with Shadow Word: Death (Rank 4). It works as expected.

I'm using Shadow Word: Death (Rank 2), I'm not 80 yet, both rank 1 and 2 give dmg to me when i kill target, i asked another priest to test it, he said he takes dmg too when he kills target with it

**Comment by Pawlld** [comment]
https://www.wowhead.com/wotlk/spell=32379/shadow-word-death

**Comment by Wolffenstein** [comment]
Fixed in rev 1536.
