### ISSUE TITLE
[Warlock] Lock imp in Dungeons

### ISSUE THREAD

**Issue by Tzeentch123** [Stormforge-gg/Bugtracker-Fordring#1362]
**Description**: 
When put on autocast for his invis he will go invis and destealth on next combat, also not cast any other of his ability be it toggled on auto on or off. Disabling autocast on invis fixes the issue, imp will then cast firebolts / buff shield and follow you around.
**Current behaviour**:
^
**Expected behaviour**: 
When in stealth should either remain stealth and be unable to cast other things or stay stealth and cast his buff im not sure. As it is imp stealth is unusable on my client.
**Revision**:

**Comment by NatsumeLily** [comment]
Did you have the imp on passive? 
If the imp is on passive, it should keep Phase Shift while in combat. It will also do nothing while in Phase Shift.

**Comment by Tzeentch123** [comment]
tested it on random mobs in open world by myself, imp on defensive with invis (and his other spells) on autocast will not cast anything, if I disable autocast on invis he will use his other abilities. If I disable autocast on everything but invis he still wont use it. If I press the button to make him go invis he will destealth on next mob acting like he will melee him (since his other spells arent on autocast) but wont actually melee, while on passive he will stay stealth and do nothing as you said.
