### ISSUE TITLE
[Death Knight] Unholy ghoul dropping health whenever DK's stamina changes

### ISSUE THREAD

**Issue by AyfoAF** [Stormforge-gg/Bugtracker-Fordring#1366]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: When playing Unholy Death Knight, my ghoul sits at about 16k hp in unholy presence, swapping to frost presence causes my stamina to change, dropping the ghoul's hp to 5k out of 17k. Likewise if i heal up my pet (arena pre-game death coil spam) and then swap to unholy presence it drops down to 5k out of 16k. 

Using scroll of stamina on myself = pet hp drops to 5k. 
Using scroll of stamina on pet = pet is fine, no problem
Getting Mark of the Wild buff increases my stamina = pet drops to 5k hp
Warrior commanding shout on myself / pet = pet is fine no problem (commanding shout is flat hp, not stamina)

So its only when my stamina changes that the pet's health recalculates to almost-dead

**Current behaviour**: Unholy ghoul resets to 5k health anytime the Death Knight's stamina value changes

**Expected behaviour**: Pet's health should stay at its pre-change 17k value.

**Revision**:

**Comment by Wolffenstein** [comment]
Should be fixed in rev 1515.
