### ISSUE TITLE
channeling cast interruption

### ISSUE THREAD

**Issue by tii86** [Stormforge-gg/Bugtracker-Fordring#1368]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Channeling spells such as blizzard are interrupted when tab targeting while auto-attack is enabled.
**Expected behaviour**: 
Tab targeting should not cause cast interruptions.
**Revision**:

**Comment by slicplaya** [comment]
The same happens with Volley as well, and probably all channeled skills(haven't tested)

**Comment by Wolffenstein** [comment]
Fixed in rev 1523.
