### ISSUE TITLE
[Quest][Dustwallow Marsh] Triage

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1371]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The NPCs that you heal during this quest are healing on their own. They shouldn't.

**Current behaviour**:
The mobs are acting like other mobs do when they are not in combat: They rapidly heal. However, that completely defeats the point of the quest, which is to use your bandage quest item on them before their slowly decreasing HP hits zero.

**Expected behaviour**: 
The mobs' HP slowly approaches 0, at which point, they die. Using the quest item on them stops this process.

**Revision**: 
1514

**Comment by Wolffenstein** [comment]
Fixed in rev 1526.
