### ISSUE TITLE
[Item] Heirloom and enchants

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1373]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: It seems enchanting heirloom shoulders and maybe helm is making the item soulbound. 
![image](https://user-images.githubusercontent.com/15247730/174016590-73e824b3-0c66-4634-bc73-c675ced90a4a.png)

**Expected behaviour**: Enchanting any heirloom should never make it soulbound. 
Any enchant you do enchant it with that has a level requirement is simply disabled until the character reaches that level. 

![image](https://user-images.githubusercontent.com/15247730/174017134-19000607-2273-4729-bd00-3697cfe93c3c.png)
https://www.wowhead.com/forums/topic/heirloom-enchants-140679

The same thing should happen for profession specific enchants. They will be disabled until that character reaches that profession skill requirement. 

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1531.
