### ISSUE TITLE
[RAID][BOSS][NPC] Malygos hitbox

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1374]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Something is wrong with Malygos hitbox. It's way too large compared to his model so you can melee him from like 15 yards away and he eats sparks when they're still like 10 yards away from him.

**Current behaviour**: Malygos hitbox is too big.

**Expected behaviour**: Malygos hitbox should more or less match red circle under him.

**Revision**: 1514

**Comment by Wolffenstein** [comment]
Melee hitbox is correct, matches the sniffed values. The spark range might be bugged

**Comment by Wolffenstein** [comment]
Should be better in rev 1527.
