### ISSUE TITLE
[RAID][BOSS][NPC] Malygos sparks and Death Grip

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1375]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: DK's Death Grip doesn't work on spark that is rooted what's not correct.

**Current behaviour**: DK's Death Grip doesn't work on spark that is rooted.

**Expected behaviour**: DK's Death Grip should work on spark that is rooted.

**Revision**: 1514

**Comment by Wolffenstein** [comment]
Uhh i think that's just how Death Grip works, no?

**Comment by NatsumeLily** [comment]
You can not death grip rooted targets. You might have it backwards, you want to death grip then root the spark.

**Comment by Nuy** [comment]
> You can not death grip rooted targets. You might have it backwards, you want to death grip then root the spark.

I have never heard of such interaction. Can you provide any proof for it? Video from WotLK era would be best.

**Comment by NatsumeLily** [comment]
> > You can not death grip rooted targets. You might have it backwards, you want to death grip then root the spark.
> 
> I have never heard of such interaction. I'm pretty sure you CAN Death Grip a target that is rooted. Can you provide any proof for it? Video from WotLK era would be best.

I don't have any video or hard hard proof (for wotlk anyway). First off for this specific interaction on this boss, multiple guides and sources say the death knight grips and then chains of ice (or another root). 

For death grip on rooted targets. Found some comments across the years. 

https://github.com/dalaranwow/dalaran-wow/issues/326 - From another wotlk servers bugtracker
![image](https://user-images.githubusercontent.com/15247730/174452280-86c4dcbf-97c6-40eb-b068-f9e0e89aebcf.png)

https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/57637873 - 2010, this would be cata
![image](https://user-images.githubusercontent.com/15247730/174452337-ea429813-9728-4d91-ba05-571ac43fc8fe.png)

http://macro-wow.com/macro/deathgrip-plus-chains-of-ice/ - 2013
![image](https://user-images.githubusercontent.com/15247730/174452370-002c12b5-dd26-43a5-a4a5-39f63892288c.png)

https://forum.wow-freakz.com/FIXED-Death-Knight-Spell-Death-Grip-vs-LoS-corners-t424688.html -2016
![image](https://user-images.githubusercontent.com/15247730/174452399-53bb3997-3623-4c77-9a4d-0ea753fc4011.png)

https://www.mmo-champion.com/threads/2106072-Death-Grip-fail-issue - 2016
![image](https://user-images.githubusercontent.com/15247730/174452421-daab9164-106d-4421-9af5-3eb25a9cdbd9.png)
