### ISSUE TITLE
[The Nexus] Keristraza No Mechanic

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1376]
**Description**: 
The final boss of the nexus does not have her signature stacking frost damage mechanic
**Current behaviour**:
The fight is just a tank and spank with only breath and tail swipe mechanics working
**Expected behaviour**: 
She is supposed to afflict the party with a stacking debuff that drops when you move.
**Revision**:

**Comment by Exorcista** [comment]
can confirm this, its 2 hcs i go there and she doesnt do the debuff

**Comment by Wolffenstein** [comment]
Hopefully fixed in rev 1527.
