### ISSUE TITLE
[Quest][Howling Fjord] It goes to 11...

### ISSUE THREAD

**Issue by Exorcista** [Stormforge-gg/Bugtracker-Fordring#1378]
**Current behaviour**: Quest https://www.wowhead.com/quest=11421/it-goes-to-11 , harpoons or the houses targeted not always award credit, might be a hitbox or a reset issue on them, had to hit each house at least 5 times in the rooftops to get the credit and spawn the drake riders

**Expected behaviour**:  Should award credit on 1st hit

**Comment by jorgehurtadodmx** [comment]
I experienced the same problem days ago, at least one of the houses you need to hit takes a while to be targeted correctly or not at all (abandon quest and take again)
