### ISSUE TITLE
[Quest][Icecrown]Free Your Mind

### ISSUE THREAD

**Issue by fondlez** [Stormforge-gg/Bugtracker-Fordring#1379]
**Description**: 
Party credit for this quest is not working.

**Current behaviour**:
When in a party, group members do not get credit for fighting the named mobs and another party member using the Sovereign Rod on the body, yet the body disappears immediately after and spawns a neutral (unattackable?) NPC in its place which also disappears shortly after.

**Expected behaviour**: 
Since quest conditions are invalidated after a single party member follows instructions, the quest should progress all in a party when progressed by one.

**Revision**: 
AtlantissCore WoTLK rev. 1522, 8d3e3e7cd845 2022-06-16 11:25:09 +0200 (master branch) (Unix, Debug, Static)

**Comment by Evolvee** [comment]
fixed in next rev
