### ISSUE TITLE
[NPC][The Botanica] Warp Splinter

### ISSUE THREAD

**Issue by Alandiel** [Stormforge-gg/Bugtracker-Fordring#1383]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/npc=17977/warp-splinter despawns after trying to heal himself with treants.
**Current behaviour**:
Eating treants(even if they are all dead) despawns boss.
**Expected behaviour**: 
https://www.wowhead.com/npc=17977/warp-splinter should heal for each living treant he ate.
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1527.
