### ISSUE TITLE
Dying Curse procs

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Fordring#1389]
**Description**: 
I have allready reported this when Beta was launched, you closed my report saying its fixed. Since then I have tested it 20x more times on Beta and now on Fordring fresh, again. Still the same results.
**Current behaviour**:
Dying Curse procs, upon entering world (loging in), crafting, dividing crystalized (Earth,Water, Fire, etc) into Eternal ( Earth,Water, Fire, etc), Changing zones in Northrend all over the place, clicking on soulwell to pickup hs, equiping tabard, etc..
**Expected behaviour**: 
At least it should not be procing while logining in and changing zones, if the rest is impossible to fix.
**Revision**: 
Here are my previous reports that relate to this. 
(All of these examples in issues bellow apply to DC only now, since Lightweave Embroidery is fixed).
https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/182
https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/194

**Comment by Exorcista** [comment]
this happens to most proc trinkets still, like sundial too
