### ISSUE TITLE
Flying Machine Camera Problem

### ISSUE THREAD

**Issue by Burdza** [Stormforge-gg/Bugtracker-Fordring#1390]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
After mounting up on a Flying Machine, camera positions on players Torso/Legs
**Expected behaviour**: 
Camera stays centered on players head.
**Revision**:

**Comment by Wolffenstein** [comment]
What Flying Machine? Can you provide a vehicle or quest name at least?

**Comment by ianc94** [comment]
Sry, i logged in on another github acc, "Flying Machine" is the name of the mount, engineering crafted helicopter (first one that can be crafted)

**Comment by ianc94** [comment]
Sorry for the late response and thank you :)

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/174488711-265e5540-5f6f-4536-ba0a-440e50a5f03c.png)
Can't reproduce
