### ISSUE TITLE
cant ress and dead bugg

### ISSUE THREAD

**Issue by sexybambooe** [Stormforge-gg/Bugtracker-Fordring#1394]
[](url
![WoWScrnShot_061722_192807](https://user-images.githubusercontent.com/107692169/174303799-51090bdd-0852-4def-a95a-e8ca25d13401.jpg)
)

**Comment by Vishiswaz** [comment]
Can you include any details? How did this happen?

Otherwise you can't possibly expect them to figure out how to prevent this
