### ISSUE TITLE
[Fishing[Drop] Pygmy Suckerfish

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Fordring#1395]
**Description**: 
Drop Rate from **Pygmy Suckerfish** from Fishing is too low.

**Current behaviour**:
Drop Rate from  **Pygmy Suckerfish** from Fihsing is around 5% and also Drops sometimes only the Fish itself.

**Expected behaviour**: 
Drop Rate from  **Pygmy Suckerfish** should be between 3%-49% depnding on the Zone (see Link "**...#fished-in** & "**...#comments**"). Also it should Drop with other Fish together (see Link "**...#comments**"). 

**Revision**: 
https://www.wowhead.com/item=40199/pygmy-suckerfish#fished-in - see drop chance per Zone

https://www.wowhead.com/item=40199/pygmy-suckerfish#comments - see comments from 2008

**Comment by Wolffenstein** [comment]
Fixed in rev 1529.
