### ISSUE TITLE
[Warror][Spell] Bladestorm

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#1397]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  ^Swapping 1h weapon and shield with 2h weapon cancels bladestorm. On the other hand, swapping one 1h weapon , two 1h weapons or 2h weapon with another 2h weapons seems to be working and doesn't cancel it. So I guess something that has to do with shields is causing this bug.

**Current behaviour**: Swapping 1h weapon and shield with 2h weapon cancels bladestorm.
**Expected behaviour**:  Swapping 1h weapon and shield with 2h weapon shouldn't cancel bladestorm.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1534.
