### ISSUE TITLE
[Item] Schematic: Jeeves

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Fordring#1402]
[Schematic: Jeeves](https://wotlkdb.com/?item=49050) is available in game, should be available at 3.2

Revision : 1526

**Comment by NatsumeLily** [comment]
While this is indeed a bug, it would be low priority. Since you need epic gems to make it.

**Comment by Vishiswaz** [comment]
> While this is indeed a bug, it would be low priority. Since you need epic gems to make it.

Considering some people got their hands on some epic gems through a few bugs on day 1, this really should get taken care of. It's also not good to allow people to pre-farm for the recipe before the patch.

**Comment by Wolffenstein** [comment]
removed
