### ISSUE TITLE
Reckoning proc melee hits from Prot Paladins goes through deterrence

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1403]
**Description**: Somehow, either do to deterrence not working correctly, or something with overkill hits, or whatever the hell it is, my friend was able to hit through deterrence with melee hits with reckoning to kill me in the duel. Tried multiple times, have been unable to replicate it.
![Capture](https://user-images.githubusercontent.com/6567001/174426756-178d838c-513c-4ee3-b1db-4d4b9ba1d25f.JPG)

**Current behaviour**:

**Expected behaviour**: 100% parry means i should 100% parry the attacks. 100% of the time deterrence is on.

**Revision**: 1526

**Comment by Wolffenstein** [comment]
Retry in rev 1531.
