### ISSUE TITLE
[Raid][Eye of Eternity 10] Spawning too many mobs in 10m?

### ISSUE THREAD

**Issue by kekkerina** [Stormforge-gg/Bugtracker-Fordring#1405]
This may or may not be intentional. On phase 2 of malygos10 four nexus lords are spawning as well as 12-16 scions.  The health values seem correct (2x retail) but as shown in this video from tankspot clearly only 2 lords and 6 or fewer scions spawn in 10man.

https://www.youtube.com/watch?v=xYqJ-8FiXCI

The damage values of the scions arcane barrage also is doing 22k outside of bubble.

It honestly feels like much of the 25man fight was accidently carried over to 10man and the fight feels impossible for us in current gear but hey maybe we are just shit and this was intentional

**Comment by Godmatik** [comment]
Confirmed, 10m should not have same number of mobs in P2 as 25m

**Comment by Wolffenstein** [comment]
Fixed in rev 1529.
