### ISSUE TITLE
[Quest][Icecrown] A Cold Front Approaches

### ISSUE THREAD

**Issue by addi011** [Stormforge-gg/Bugtracker-Fordring#1406]
[//]: # ([Quest][Icecrown] A Cold Front Approaches(https://www.wowhead.com/quest=13070/a-cold-front-approache))
[//]: # ([NPC] [Siegemaster Fezzik](https://www.wowhead.com/npc=30657/siegemaster-fezzik))

**Description**: The Quest "A Cold Front Approaches" cannot be accepted after completing the prequest.

**Current behaviour**: Instead of "Accept" to get the quest, the NPC ask you to "Complete Quest". On clicking that button, nothings seems to happen unfortunately.

**Expected behaviour**: Fixing the right option to accept the quest instead of functionless "Complete Quest" button.

**Revision**: 1526

**Comment by Wolffenstein** [comment]
I completed the quest just fine. Delete cache and try again.

**Comment by addi011** [comment]
@Wolffenstein Clearing cache did not fix the issue unfortunately, I still cannot accept the quest (only offering the "Complete Quest" button without function for me still). I have checked with Dzakoth and Daemonfyre and they both told me that they cannot help me with it, I need to open a bug report here. Appreciate if you have another idea what I can try to fix this on my own. Thanks!
