### ISSUE TITLE
Winter's Chill talent bug with Armors

### ISSUE THREAD

**Issue by Ljolj** [Stormforge-gg/Bugtracker-Fordring#1408]
[//]: # ([Spell]      https://wotlk.evowow.com/?spell=7302 and  https://wotlk-twinhead.twinstar.cz/?spell=18100
[//]: # ([Talent]   https://wotlk.evowow.com/?spell=11180

**Description**: 
Ice armor and Frost armor procing talent Winter's Chill which shouldnt. It clearly says damaging spell.
**Current behaviour**:
Ice armor and Frost armor procing talent Winter's Chill
**Expected behaviour**: 
Ice armor and Frost armor from the mage should not proc Winter's Chill because it is not damaging spell. 

I used spells info from other site because i cant acess wowhead from my country.

**Comment by Wolffenstein** [comment]
Fixed in rev 1531.
