### ISSUE TITLE
Arena queues broken

### ISSUE THREAD

**Issue by cardyb27** [Stormforge-gg/Bugtracker-Fordring#1410]
**Description**:  Arena queues not working properly. Multiple teams were sitting in queue today, all with plus or minus 200 mmr rating of each other (Queues should be instant). Instead we were all sitting in dalaran PVP area, and would eventually get a queue after 12-20 mins. We tried to log off an on, we reformed party, and nothing fixed the queue issues. 

**Current behaviour**:  Long queues, despite having 3 teams  with same roughly same mmr, all in queue at the same time

**Expected behaviour**:  instant queue

**Revision**:

**Comment by haephaistoss** [comment]
Matchmaking shouldn't let same teams go against each other all the time to prevent wintrading, but given the current lack of qs happening it would be worth removing this limitation, I agree. Wintrading shouldn't be left unpunished though, or encouraged in any way.

**Comment by Wolffenstein** [comment]
I increased the bracket range a bit and reduced the discard timers
