### ISSUE TITLE
[NPC][Badlands] Boss Tho'grun (ticket 2)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1412]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Boss Tho'grun, needed for the quest "Tremors of the Earth" doesn't appear to respawn, so only one person can complete the quest per server crash/restart.

**Comment by Vishiswaz** [comment]
Unrelated to my other ticket about this mob, https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1334

**Comment by Vishiswaz** [comment]
Update: He finally spawned. But that took hours. Can someone take a look at his respawn time?

**Comment by Godmatik** [comment]
Did all the followers that are with him get killed as Well? Might have something to do with it

**Comment by Vishiswaz** [comment]
Could be, not sure.

**Comment by Evolvee** [comment]
fixed in next rev
