### ISSUE TITLE
[Hunter] Detterence is not working against melee hits

### ISSUE THREAD

**Issue by wedris** [Stormforge-gg/Bugtracker-Fordring#1414]
We are doing gluth right now, and our hunter is trying to kite the zombies.
He died through detterence, which should give him 100% parry.

**Comment by Nuy** [comment]
Yea, I can confirm Detterence being random as fuck and mobs often hit through it for not good reason. Very annoying buff.

**Comment by Wolffenstein** [comment]
Retry in rev 1531.
