### ISSUE TITLE
[Quest][Dragonblight] The Chain Gun And You

### ISSUE THREAD

**Issue by Exorcista** [Stormforge-gg/Bugtracker-Fordring#1415]
**Current behaviour**: Dragonblight quest: https://www.wowhead.com/quest=12457/the-chain-gun-and-you , even doesn't work/happen, theres no soldiers to rescue spawning thus unable to complete the quest. Also: this a big chain of quests with nice rewards and that helps for Loremaster related achieves

**Expected behaviour**:  Make Terrified soldiers spawn like in: https://www.youtube.com/watch?v=JxdWf1O9k0o

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/174458564-a4228a00-ca91-4138-b89e-33ebc92cf2b8.png)
?

**Comment by Exorcista** [comment]
i swear there was no soldier there at all i was 20min there trying to figure out what was wrong

**Comment by Exorcista** [comment]
![WoWScrnShot_061822_195217](https://user-images.githubusercontent.com/6818405/174460511-5982ed2c-1d6f-4c63-b475-5f6f798257c4.jpg) right side
![WoWScrnShot_061822_195202](https://user-images.githubusercontent.com/6818405/174460512-c7f47dfb-7ea0-408a-8a64-735b7128c5b0.jpg) left side

was just there, no soldier found
