### ISSUE TITLE
[world] Truesilver spawn rate

### ISSUE THREAD

**Issue by kekkerina** [Stormforge-gg/Bugtracker-Fordring#1416]
Any zone that should spawn mithril is spawning truesilver at insane rates making mithril particularly hard to farm. This includes searing gorge(worst offender), badlands, hinterlands, alterac mountains(doesnt spawn anything really) and tanaris

truesilver is supposed to be the rare ore. 

![kek123](https://user-images.githubusercontent.com/106358845/174452790-2f2c80e7-7ba1-40d6-a004-6c3a1a9cc586.png)

**Comment by Godmatik** [comment]
Yes very common bug on stock Wrath, They need to be a rare spawn in place of mithril, not their own nodes.

**Comment by Viryll** [comment]
Problem is stock Wrath is scripted to remember nodes and their types and respawn them after set amount of time. 
How it should work is, you should have about X (10%?) chance per mithril ore respawn to turn into truesilver instead.

**Comment by Vishiswaz** [comment]
Yep, this is just a result of people skipping over the Truesilver instead of mining and vendoring it. It shares a spawn with Mithril. If you mine it, it may come back as Mithril.

**Comment by NatsumeLily** [comment]
Had the same problem the last two wotlk servers I played on (Crystalsong and Sunwell). 

Like Hinterlands would be 2/3 mithril the first lap, then all truesilver the second lap, and again all truesilver the third lap.

**Comment by Exorcista** [comment]
> Yep, this is just a result of people skipping over the Truesilver instead of mining and vendoring it. It shares a spawn with Mithril. If you mine it, it may come back as Mithril.

yea but that math doesnt add up, even if everyone is skipping it, some Mithril should pop, same as every other node, even herbs, its a shared/dynamic spawn rate, you pick X, Y has a rare chance to pop out, not "pick up X and shit well X again pops lol"
