### ISSUE TITLE
[Quest][Stranglethorn Vale] Jungle Secrets

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1417]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
For some reason, Private Thorson won't give me the quest "Jungle Secrets" despite having an exclamation point over his head and I haven't completed it yet.
![WoWScrnShot_061822_165408](https://user-images.githubusercontent.com/78314117/174456801-7d51bbd3-15c2-42db-a543-58052701b805.jpg)

**Comment by Godmatik** [comment]
That's not the location he should be giving the quest, he needs to walk out onto the road in an RP event and get attacked by 2 NPCs, You save him, then he gives the quest. Probably not scripted right here

**Comment by Vishiswaz** [comment]
It's working, just got it after the RP event. Only bug is that it appears as an obtainable quest in the wrong place as a tease, only for it to not actually be available.

**Comment by Evolvee** [comment]
fixed in next rev (hopefully?)
