### ISSUE TITLE
[Zone][NPC][Raid] Malygos 10 man 

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1418]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Malygos 10 man adds have way too much health and deal way too much damage like they have 25 man values. Makes 10 man EoE way harder than it should be. There are also additional adds that shouldn't be there in 10 man. There could be same/similar problem with OS 10 man.

**Current behaviour**: Malygos 10 man adds have way too much health and deal way too much damage like they have 25 man values. There are also additional adds that shouldn't be there in 10 man.

**Expected behaviour**: Malygos 10 man adds should have much less health and deal way less damage than in 25. 

**Revision**: 1526

**Comment by kekkerina** [comment]
already mostly addressed . check discord change log

**Comment by kekkerina** [comment]
the health is correct . its basically exactly 2x retail health
but the amount of adds was the same as 25

**Comment by Nuy** [comment]
> the health is correct . its basically exactly 2x retail health but the amount of adds was the same as 25

11k damage from Arcane Barrage UNDER a dome is clearly overtuned then. Anyway, buffing 10 man content in WotLK to such extent is pointless cause most of the gear there is ilevel 200 (except EoE) and very few items are actually any good/on par with 25 ones. 10 mans are supposed to be easier for more casual players but right now they're pretty much same difficulty as 25 if not harder.

**Comment by Wolffenstein** [comment]
will be reduced after next update
