### ISSUE TITLE
[NPC][Zone] NPC and Workshop problems in Wintergrasp

### ISSUE THREAD

**Issue by gun4axb** [Stormforge-gg/Bugtracker-Fordring#1419]
**Description**: 
Misproperly placed NPC
**Current behaviour**:
Horde NPCs are either scattered. clumped, not spawned in. 
Control over the workshops, graveyards are not accurate as in Horde is holding it but alliance NPCs are there.
**Expected behaviour**: 
I couldn't find any specific information about NPC positioning in any retail databases, but repositioning them shouldn't be a big deal.
**Revision**: 
1526
![image](https://user-images.githubusercontent.com/97943252/174475361-4cdd52b6-a72b-4ec2-bddc-70c8f59e189c.png)
![image](https://user-images.githubusercontent.com/97943252/174475416-c976c2c5-63a7-45d2-8ad7-dd22b47c9972.png)
![image](https://user-images.githubusercontent.com/97943252/174475435-97a270a2-ba7f-4f4d-a702-8189bb421218.png)
![image](https://user-images.githubusercontent.com/97943252/174475457-90350e67-d74b-468d-8957-f1d4e257468b.png)
![image](https://user-images.githubusercontent.com/97943252/174475522-b25b276f-6fed-4709-bb0f-dc2c7f84b838.png)

**Comment by NatsumeLily** [comment]
I think this was already reported. #486
