### ISSUE TITLE
Wlock seed not exploding on death

### ISSUE THREAD

**Issue by EmilHahne** [Stormforge-gg/Bugtracker-Fordring#1420]
**Description**: 
Seed does not explode when mob with the debuff dies.

**Current behaviour**:
Seed does not explode when mob with the debuff dies.

**Expected behaviour**: 
Seed is supposed to explode on mob death as stated in the tooltip "total dmg or dies".

**Revision**
1420 (not sure?)

**Comment by Viryll** [comment]
type .server info to see current revision.

**Comment by Wolffenstein** [comment]
Fixed in rev 1531.
