### ISSUE TITLE
Sacred shield and Combat (arena)

### ISSUE THREAD

**Issue by cardyb27** [Stormforge-gg/Bugtracker-Fordring#1421]
# ([Spell]: Sacred Shield

**Description**: Sacred shield currently will put the paladin in combat. Only direct heals or hots should put the player in combat. Once hots are rolling or a shield is applied, then the 6 second combat timer begins. This significantly alters the wrath meta, by not being able to do simple mana management techniques like, shield, and then wait for combat into drink.

**Current behaviour**: Sacred shield procs put the paladin in combat. 

**Expected behaviour**:  Sacred shield and other hots or shields for that matter, should not be keeping the player in combat. 

**Revision**:

**Comment by Wolffenstein** [comment]
Can you provide proof for that? As far as I know casting any positive buff/ability on a unit in combat should put the caster in combat as well

**Comment by cardyb27** [comment]
I will coordinate tomorrow with a few pvpers and run skirmishes to test things out, I will get screen record software to see if I can catch anything for you. One thing I can say for certain is there is a combat related bug, somewhere, somehow, and I intended to find it!

**Comment by slicplaya** [comment]
But now you can be sapped again xD

**Comment by cardyb27** [comment]
@Wolffenstein Im sorry about video quality, first time doing video edits. While this is not directly linked to sacred shield I now believe that the combat bug issue is related to friendly buffs somehow.

In the video below you will see how i am out of combat, I apply sacred shield to myself, and then beacon of light on myself. The micro second i apply beacon of light on myself i get put in combat ( I assume somehow by the rogue right in front of me?).

I did not cause a direct heal, buff, or attack to anyone, and the moment i apply beacon on myself i get the combat bug. I will be getting more videos like this, but this is the first good example i got today.

Video: https://youtu.be/yQUE9IWVqwY

**Comment by cardyb27** [comment]
> But now you can be sapped again xD I get sapped by alot of my secret rogue admirers :s

**Comment by cardyb27** [comment]
> But now you can be sapped again xD

I get sapped alot by my secret rogue admirers :s
