### ISSUE TITLE
[NPC][Badlands] Shadowforge Surveyor

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1422]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There's one stuck inside a model of a stone thing.
![WoWScrnShot_061922_152926](https://user-images.githubusercontent.com/78314117/174497391-d4c3adb8-4373-412f-9ae8-d50bfdb8bc60.jpg)

**Comment by Evolvee** [comment]
fixed in next rev
