### ISSUE TITLE
[NPC] Acolyte of Vesperon (ID: 31219) - Obsidian Sanctum (10)

### ISSUE THREAD

**Issue by EsreverWoW** [Stormforge-gg/Bugtracker-Fordring#1424]
**Description**: Killing Acolyte of Vesperon (ID: 31219) in Obsidian Sanctum (10) with Vesperon up causes game clients to become unresponsive when inside the instance until the raid encounter is reset.

**Current behaviour**: Upon Acolyte of Vesperon's HP reaching 0, the game client's process becomes unresponsive. Subsequent logins immediately crash upon loading in to the instance while the encounter remains in progress.

**Expected behaviour**: The NPC should die and remove Gift of Twilight without causing game client crashes.

**Revision**: 1526

**Comment by EsreverWoW** [comment]
https://streamable.com/tu7lin

**Comment by Wolffenstein** [comment]
Does this only happen with Acolyte of Vesperon?

**Comment by Wolffenstein** [comment]
Hopefully fixed in rev 1533.
