### ISSUE TITLE
[NPC][Eye of Eternity] Malygos - Phase 3

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1425]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The dragons you mount have 6 abilities. The 2nd ability should cost 50 energy, but server-side it's costing 60 energy. 

![image](https://user-images.githubusercontent.com/15247730/174502754-d9209a45-7507-41f1-83c3-fdd6b2a72717.png)

**Revision**:

**Comment by Vishiswaz** [comment]
This is a bug I've seen on lots of other servers, it would be great if it was fixed here.

**Comment by slicplaya** [comment]
I agree. Changes the fight quite a bit.
