### ISSUE TITLE
[NPC]Anub'arak (Azjol-Nerub Heroic) - permanent combat

### ISSUE THREAD

**Issue by fondlez** [Stormforge-gg/Bugtracker-Fordring#1432]
**Description**: 
The group was permanently in combat after the death of Hadronox. Even after the death of the final boss, the group was still in combat.

**Current behaviour**:
See above. I have not encountered this bug during normal dungeon version, but that could be a coincidence.

**Expected behaviour**: 
Combat needs to drop when no fight is taking place.

**Revision**: 
AtlantissCore WoTLK rev. 1535, 1e6fc97ec32b 2022-06-20 10:33:56 +0200 (master branch) (Unix, Debug, Static)

**Comment by Vishiswaz** [comment]
There's a good chance you were actually stuck since the defeat of the first boss. On other servers, the little adds the first boss summons get stuck in that room. Worth checking.
