### ISSUE TITLE
Skinning issue

### ISSUE THREAD

**Issue by bigdeekpumper** [Stormforge-gg/Bugtracker-Fordring#1435]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Hardknuckle Forager and Hardknuckle Charger in Sholazar Basin aren't skinnable most of the time, even tho i'm playing solo without any group. 

**Current behaviour**: I kill a Hardknuckle Forager, grab all his loot and when i try to skin it says: "Creature must be looted first".

**Expected behaviour**: After looting i should be able to skin them.

**Revision**: 1541

**Comment by CyberRaver** [comment]
this is all mobs also

**Comment by weqbehwbqheb** [comment]
pls fix it cant skin anymore T_T

**Comment by doctornaz** [comment]
+1. Can't skin any dungeon dragonkin in the Nexus.
