### ISSUE TITLE
[Npc][Drop][Item] Scourge Curio not dropping

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1437]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: This item isn't dropping at all lately making it impossible to do JC daily. Please hotfix or people will lose their JC token.

**Current behaviour**: Won't drop from Scourge mobs.

**Expected behaviour**: Should drop pretty fast.

https://www.wowhead.com/item=42108/scourge-curio

**Revision**: 1541

**Comment by 666franz666** [comment]
Yeah, still same problem, wiped out the Scourge in different places for about 90 min and found nothing ...

**Comment by kekkerina** [comment]
worked for me . killed mobs north of dalaran in icecrown and got it 2nd kill

**Comment by Wolffenstein** [comment]
Will be fixed in rev 1546.
