### ISSUE TITLE
[Quest][The Storm Peaks] Sniffing Out the Perpetrator (event not working)

### ISSUE THREAD

**Issue by aguczam** [Stormforge-gg/Bugtracker-Fordring#1441]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
event dont start after using quest item
**Current behaviour**:
event dont start after using quest item
**Expected behaviour**: 
the wolf should go forward and go to the cave
**Revision**:

**Comment by obipwn** [comment]
worked for me on different characters 100%

**Comment by Evolvee** [comment]
horde quest works for me
alliance quest is missing the little RP event at the beggining but also "works"...

need steps on how to reproduce the reported issue

**Comment by aguczam** [comment]
Worked after change of resulution lol thank you for your time
