### ISSUE TITLE
Unable to peel the BUG

### ISSUE THREAD

**Issue by werwe123** [Stormforge-gg/Bugtracker-Fordring#1444]
I want to submit a BUG,Skinning now,will appear a mistake,According to
 "greature must be looted  first"  There are some shell can be successful，There are some not。Monsters have no any item
![QQ截图20220622031358](https://user-images.githubusercontent.com/107953417/174879866-2e7aac7b-8989-4055-b03a-1086a7dc3018.png)

**Comment by werwe123** [comment]
Almost 70% of the monster can't peeling skinning

**Comment by Godmatik** [comment]
Duplicate / already reported.

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1435
