### ISSUE TITLE
Beacon of Light Procs druid clear casting nonstop.

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#1445]
**Description**: Beacon of Light Procs druid clear casting nonstop.  I have a video but it's too large.

**Current behaviour**: Beacon of Light Procs druid clear casting nonstop.

**Expected behaviour**: It should not proc it I have a video but it's too large.

**Revision**: 1541

**Comment by slicplaya** [comment]
Beacon of light, sorry. Was in the middle of a raid.

**Comment by NatsumeLily** [comment]
Strange. Maybe the druid is getting lucky? Otherwise why would beacon of light interact with druid healing at all.

**Comment by Godmatik** [comment]
Omen of clarity literally procs off anything right now so I wouldn't be surprised, however it shouldn't proc from other people's heals

**Comment by haephaistoss** [comment]
That's actually blizzlike:

https://www.wowhead.com/spell=16864/omen-of-clarity#comments

<html>
<body>


  | By 224747 on 2008/10/18 (Patch 3.0.2)This procced off of an inscription recipe. Unfortunately, the next thing I made still took reagents. >.< | By 224747 on 2008/10/18 (Patch 3.0.2) |   |  
-- | -- | -- | -- | --
By 224747 on 2008/10/18 (Patch 3.0.2) |   |  


</body>
</html>By [224747](https://www.wowhead.com/user=224747) [on 2008/10/18](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=409904) (Patch 3.0.2)		
This procced off of an inscription recipe. Unfortunately, the next thing I made still took reagents. >.<

<html>
<body>


0 | lordkarthas on 2008/10/22 (Patch 3.0.2)It procs off crafting bandages as well.
-- | --



</body>
</html>0


[lordkarthas](https://www.wowhead.com/user=lordkarthas) [on 2008/10/22](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=409904:reply=356110) (Patch 3.0.2)

It procs off crafting bandages as well.

**Comment by slicplaya** [comment]
It literally procs like every second while beacon of light is active(even if the paladin and druid isn't healing anything or doing any actions).

**Comment by NatsumeLily** [comment]
> It literally procs like every second while beacon of light is active(even if the paladin and druid isn't healing anything or doing any actions).

Oh, the beacon of light is on the druid?

**Comment by Smokdacave** [comment]
Ppl are already abusing this, clearcasting sometimes procs even faster than your gcd.

**Comment by slicplaya** [comment]
Raid logging server at this point. /shrug

**Comment by Wolffenstein** [comment]
Fixed in rev 1595.
