### ISSUE TITLE
[Betrayal] [Zul'Drak] 

### ISSUE THREAD

**Issue by Uzzyptm** [Stormforge-gg/Bugtracker-Fordring#1447]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Drakuru's Blightbloods reset after fighting him for a minute or so
**Current behaviour**:
Drakuru's Blightbloods reset after fighting him for a minute or so and starts atacking you,I had tto redo the fight about 4 times and the only reason I could complete it was because I played a tank
**Expected behaviour**: 
Drakuru's Blightblood should stay in your control until the boss reaches phase 2
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1556.
