### ISSUE TITLE
[Priest] Spirit of Redemption and Instant-Death Falls

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1448]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Spirit of redemption keeps you alive through instant-death falls, then leaves you at 1 hp right at the bottom of the map, unable to logout, exit game (unless you altF4) or hearth or accept summon (says you are dead). THis happens in Nexus if you fall off, and in Eye of Eternity. 
**Current behaviour**:

**Expected behaviour**: 
You should die and be able to release spirit
**Revision**:

**Comment by NatsumeLily** [comment]
Fixed in 1548.
![image](https://user-images.githubusercontent.com/15247730/175344010-ef56fb01-fc1b-404d-bec7-2f64e1ae0d0b.png)
