### ISSUE TITLE
[Raid][Obsidian sanctum] too many badges dropping

### ISSUE THREAD

**Issue by kekkerina** [Stormforge-gg/Bugtracker-Fordring#1449]
Description

Sartharion 25 is dropping 4 badges even if all drakes are killed so the instance gives 7 badges.

Current behaviour

Sartharion 25 is dropping 4 badges even if all drakes are killed so the instance gives 7 badges.

Expected behaviour

Sartharion should drop 2 badge plus 1 more per drake left alive rather than 4 regardless of drakes killed.

this may affect 10 as well

**Comment by Godmatik** [comment]
I believe the correct amount is 5 badges total (2 for boss, 1 for each drake)
