### ISSUE TITLE
Jewelcrafter dailies are broken

### ISSUE THREAD

**Issue by wedris** [Stormforge-gg/Bugtracker-Fordring#1452]
Titles says it all.
Since yesterday the JC daily is not dropping the item.
Today the same happens with the needed item from the brunnhildar npc's.

**Comment by FX-SF** [comment]
Two recent tickets involving JC dailies:

#1437: Scourge Curio - Fixed and Closed (rev 1546)
#1450: Shipment: Blood Jade Amulet - Open ticket

**Comment by FX-SF** [comment]
appears to be fixed as of rev 1548
