### ISSUE TITLE
Deserter after not accepting a starting ID in heroic RDF

### ISSUE THREAD

**Issue by wedris** [Stormforge-gg/Bugtracker-Fordring#1455]
**Description**: 
queued for rHC dungeon finder, and because I didnt want to accept the ID 2/4 Halls of Lightning I left.
But I received a 30min deserter.
**Current behaviour**:
Deserter after leaving a dungeon that you arent locked to / didnt start from the beginning
**Expected behaviour**: 
you should be able to decline the ID and leave the dungeon group without penalty
**Revision**:

**Comment by NatsumeLily** [comment]
Not a bug. You should get deserter even if you leave after not accepting a dungeon ID lock.
