### ISSUE TITLE
[Dungeon finder] No dungeon in progress counter

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1456]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Dungeon finder queue pop-up is missing boss kill counter for dungeons in progress. 

For example 
![image](https://user-images.githubusercontent.com/15247730/175003535-04af7c07-8af3-4b65-a17e-2c6ba9caed16.png)

I think the dungeon should be hidden and only show boss kill counter for random dungeons, but can't confirm that. 

**Revision**:

**Comment by Cold-Martijn** [comment]
"I think the dungeon should be hidden and only show boss kill counter for random dungeons, but can't confirm that."
I can confirm this.
