### ISSUE TITLE
[Summon Gargoyle][Death Knight] Gargoyle still not scaling with haste

### ISSUE THREAD

**Issue by obipwn** [Stormforge-gg/Bugtracker-Fordring#1457]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Gargoyle does exactly 12 casts under any haste value. Casting time goes down a bit, but the total number is the same, it just flies away earlier (debuff on still on boss but garg flew away).

**Current behaviour**: Gargoyle does exactly 12 casts under any haste value. Casting time goes down a bit, but the total number is the same, it just flies away earlier (debuff on still on boss but garg flew away).

**Expected behaviour**: It should cast way more under haste buffs (Unholy Presence, Engineering glove enchant, Potion of Speed, Heroism etc.).
In my test the cast time was 1.8 sec without buffs, 1.5 with UHP, Engi gloves , Haste Potion. 12 Casts in both tests.

**Revision**: 
No haste buffs, passive haste, 12 casts
![No Haste Buffs 12 casts](https://user-images.githubusercontent.com/14110658/175007960-bf4be698-cf4d-4ec9-a06c-cda23817053a.jpg)

haste buffed
![Haste Amount Buffed](https://user-images.githubusercontent.com/14110658/175007969-aee9ce0e-c0fa-4f5c-a4cc-908620a91684.jpg)

haste buffed garg, still 12 casts
![Cast Amount Haste Buffed Garg](https://user-images.githubusercontent.com/14110658/175007984-205919b5-1569-40ea-a0d5-782edf018ec8.jpg)

**Comment by obipwn** [comment]
was submitted before here:
https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/911

**Comment by Soufly** [comment]
If gargoyle strikes counts as ''caster'' ability,it should go down to 1 sec(gcd cap).

**Comment by Wolffenstein** [comment]
Fixed in rev 1585.

**Comment by obipwn** [comment]
is this live yet?
still doing 12 casts, 2-3 melee hits in several test runs
