### ISSUE TITLE
[Feature Request] 2x Raid emblems for first daily RHC 

### ISSUE THREAD

**Issue by nevrozac** [Stormforge-gg/Bugtracker-Fordring#1460]
Please change daily random heroic dungeon reward from giving 2 extra heroic tier badges to 2 raid tier badges instead.

This is because 
*currently there is no incentive for progressed characters to do heroics anymore
*it is very difficult for new players or alt characters to get geared when que times are so long and the influx of new players cannot support it
*content squish 
*we would appreciate it

**Comment by Godmatik** [comment]
This is a suggestion, not a bug

**Comment by nevrozac** [comment]
Yes. You can read in the title "Feature Request" and it is posted on the github where all requests should be

**Comment by Godmatik** [comment]
This github is for bug reports only, suggestions go to discord

**Comment by haephaistoss** [comment]
thats bs, they belong here very well

**Comment by Godmatik** [comment]
This says otherwise

![bugreport](https://user-images.githubusercontent.com/37913400/175400264-b1453a68-860c-4721-ab35-82e0763585f7.png)

**Comment by nevrozac** [comment]
The only thing that doesnt belong here is your constant nagging and pointless arguments

**Comment by Godmatik** [comment]
I am not arguing, it is simply responding (as I said to you before), but I will make this the final post on the matter, as I tried to do so above when I said devs would handle it as they see fit.

**Comment by nevrozac** [comment]
Request granted starting 29th june.
