### ISSUE TITLE
[NPC] [Forgotten Depths Underking][ID 31039] Mob aggro range

### ISSUE THREAD

**Issue by Uzzyptm** [Stormforge-gg/Bugtracker-Fordring#1464]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There's a problem with this type of mob,because of his increased size he has quite high movement speed(as we know the bigger the creature the slower running animation it has so maybe his increase in movement speed is a counter to that effect) 
**Current behaviour**:
Because of his increased movement speed he never loses aggro range on you EVEN if you are mounted, he chases you forever, I had one chase me all they way from Argent Vanguard to Crusader Bridenbrad near Sindragosa's Fall
**Expected behaviour**: 
Mobs in general chase you forever if the have a way of closing the gap (saw the same thing happened while killing wolves in Crystalsong Forest which have a sprint or Thaddus in Zul Drak) I think mobs need to reset their aggro based on how far they have traveled from their initial patrolling point/spawn Point because this can be abused 
**Revision**:

**Comment by Vishiswaz** [comment]
Leashing has absolutely nothing to do with the speed of the mob. A mob hitting you does not reset its leash, unless you hit it back with something. It's possible perhaps a Thorns/Ret Aura effect could extend the leash?

**Comment by Uzzyptm** [comment]
> Leashing has absolutely nothing to do with the speed of the mob. A mob hitting you does not reset its leash, unless you hit it back with something. It's possible perhaps a Thorns/Ret Aura effect could extend the leash?

I'm a prot warr with the damage shield talent some maybe

**Comment by Uzzyptm** [comment]
This can be closed,it works ok now

**Comment by Vishiswaz** [comment]
@Uzzyptm You can close it yourself since you opened it, just so you know. Where you can go to comment, you'll see a button "close issue"
