### ISSUE TITLE
[Spell] Swiftmend does not consume hots on another players.

### ISSUE THREAD

**Issue by Barcaz** [Stormforge-gg/Bugtracker-Fordring#1465]
**Current behaviour**: Non-glythed Swiftmend does not remove closest to expire hot from friendly targets, it does work fine when its casted on yourself though

**Expected behaviour**: It should remove closest to expire rejuvenation or regrowth from the receiver of the heal, unless you have it glyphed.

**Comment by Wolffenstein** [comment]
Fixed in rev 1554.
