### ISSUE TITLE
Savory Deviate Delight

### ISSUE THREAD

**Issue by benjaminpal** [Stormforge-gg/Bugtracker-Fordring#1467]
[//]: # (https://www.wowhead.com/item=6657/savory-deviate-delight)
[//]: # (Tree of Life (Shapeshift))
[//]: # (Restoration Druid)

**Description**: 
Consuming this item will transform you into either a Pirate or a Ninja for 60 minutes. Fantastic item for gags and fun.

**Current behaviour**:
Using Savory Deviate Delight does cancel Tree of Life shapeshift. 

**Expected behaviour**: 
I should be still in Tree of Life shapeshift and looking like a pirate or ninja. You should use this item and look like a pirate or ninja even in bear form, cat form, moonkin form.

**Revision**:

**Comment by NatsumeLily** [comment]
The buffs this item gives are polymorph effects, which will be removed when shapeshifting. This is the blizzlike interaction. 

But I would implore Wolf to make it so the effects aren't removed by shapeshifting. Since it's not a significant change and would make druids happy.

**Comment by Vishiswaz** [comment]
This is definitely a case of people being used to other servers being bugged and thinking that blizzlike is the bug.

Having said that, I agree with Natsu.

**Comment by benjaminpal** [comment]
I've played original Blizzard servers before not other private server, and I also play druid there. It's not suppose to take you out from shapeshift.

**Comment by Wolffenstein** [comment]
no
