### ISSUE TITLE
[Naxxramas] Eyestalks after Heigan Locked in Combat

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1472]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The eye stalks in the gauntlet after heigan lock people in combat and never drop aggro. THis sucks since it means you have to alt F4 before loatheb if people die and need summons
**Current behaviour**:
above
**Expected behaviour**: 
they should drop combat after a while out of range
**Revision**:

**Comment by Vishiswaz** [comment]
I believe you're supposed to kill them....

**Comment by Exorcista** [comment]
he ment that they just come back up instantly, making that room a pain in the ass to pass by without being in combat, on top of Naxx putting you in combat but all the time

**Comment by Wolffenstein** [comment]
no they should not drop aggro, test it on retail if u want
