### ISSUE TITLE
Unable to Disenchant in Group

### ISSUE THREAD

**Issue by Md-Knox** [Stormforge-gg/Bugtracker-Fordring#1473]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: You are unable to walk into a dungeon and disenchant when the enchanter isn't next to or near the lead/group

**Current behaviour**:unable to disenchant without close proximity

**Expected behaviour**: If an enchanter is inside the dungeon you should be be able to disenchant any drop no matter where the enchanter is in that dungeon 

**Revision**:

**Comment by Vishiswaz** [comment]
Nope, you shouldn't be able to disenchant the item unless the disenchanting person is eligible for the loot. So if they're too far, they aren't eligible for the loot, and therefore you won't be able to see the disenchant option.

Having said that, the distance this server considers you "too far" for loot is WAY too short.

**Comment by Md-Knox** [comment]
That's the whole point if you're inside the dungeon your not to far no matter where you are inside that dungeon as you could be at the start of the dungeon or the end of the dungeon you should still be eligible for the loot if your in a RDF that's how it works but if you run into the dungeon all the rules on this server are thrown out of the window

**Comment by Vishiswaz** [comment]
Not sure if that's how it's supposed to work actually. That is how it works _on other private servers_ but that is not necessarily how it's supposed to be.

**Comment by NatsumeLily** [comment]
I don't know anything about this. But I did find https://www.mmo-champion.com/threads/659039-Loot-range for you guys.

**Comment by Wolffenstein** [comment]
will not be changed without proof
