### ISSUE TITLE
[Item] PATCH 3.3 GLYPHS CURRENTLY AVAILABLE

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1479]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The 3 glyph recipes sold by Larana Drome in Dalaran are Patch 3.3 items but are currently available.

This is Glyph of Eternal Water, Glyph of Quick Decay, and Glyph of Rapid Rejuvenation.

**Comment by NatsumeLily** [comment]
Talents and glyphs should be 3.3.5. 

Otherwise you would have a really fucky system. You would have to go through every glyph and change them to what they did in this patch, even if they're for talents that no longer exist.

**Comment by Vishiswaz** [comment]
Not talking about changing versions of the glyphs. Just matching what's available at the correct patches.

**Comment by NatsumeLily** [comment]
Umm..ok? 

https://wowpedia.fandom.com/wiki/Glyph_of_Life_Tap shouldn't be in the game until 3.1.
https://wowpedia.fandom.com/wiki/Glyph_of_Shadow_Word:_Pain also shouldn't be in the game until 3.1. 

Can you not see the problem this would cause?

**Comment by NatsumeLily** [comment]
And another https://wowpedia.fandom.com/wiki/Glyph_of_Unholy_Blight?oldid=2032087

**Comment by Vishiswaz** [comment]
No? If they weren't in the game until then, they shouldn't be in the game until then.

**Comment by nevrozac** [comment]
Removing glyphs would also require talent system matching 3.0 to keep a normal gameplay environment. Many classes in current 3.35 talent state require these glyphs to be viable.

**Comment by Soufly** [comment]
Glyphs/talents/spells should stay as they are now.

**Comment by haephaistoss** [comment]
out of the question, glyphs are part of the spell system, wtf

**Comment by Vishiswaz** [comment]
Closing due to new server core.
