### ISSUE TITLE
[Quest][Un'Goro Crater] Lost! - QUEST NOT COMPLETABLE

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1480]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This quest is not completable _on the live server only_ because there seems to be a lack of reset mechanics for the NPC involved, Ringo. It appears that if some player starts the escort quest after Lost!, and they do not complete the quest as they are supposed to, Ringo never resets and reappears back in the cave.

This means 1 player per server restart can do this quest, which is not good.

I can't even find out where the last person left Ringo, searched all over...

**Comment by Alandiel** [comment]
Problem is that this quest should fail if you go too far away from Ringo and that should make him despawn and then respawn in his starting position. I noticed that lot of escort quests can't be failed by going too far away from escorted NPC, possibly all of them.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
