### ISSUE TITLE
[Quest][Felwood] Rescue from Jaedenar

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1481]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The aggressive mobs don't attack the escort even though she attacks them. Definitely bugged.

**Comment by Vishiswaz** [comment]
Additionally, Spirit of Trey Lightforge at the end of the escort attacks you but you can't attack him back. Idk if he's supposed to be attackable or if he's not supposed to attack you at all, but this definitely isn't right.

**Comment by Godmatik** [comment]
He should be attackable and the quest should end after you defeat him

**Comment by Vishiswaz** [comment]
Closing due to new server core.
