### ISSUE TITLE
Blue Drops in heroic dungeons

### ISSUE THREAD

**Issue by wedris** [Stormforge-gg/Bugtracker-Fordring#1487]
**Description**: 
Drop chance for blue drops is way too low
**Current behaviour**:
Almost no specific dungeon blue drops from any heroic dungeon that is currently active
**Expected behaviour**: 
There should be at least 1 (if not 2) drop every dungeon run. 
This was the normal rate even on retail.
In gundrak you saw sometimes even 3-4 neck drops. The one with block rating.
**Revision**:

**Comment by Vishiswaz** [comment]
Unless you have evidence that it's wrong, using your memory of other private servers letting items drop like candy is not enough proof of anything.

**Comment by Godmatik** [comment]
Fairly certain the warmane model drop rates of 3-4 blues dropping every heroic is not blizzlike.

**Comment by Soufly** [comment]
Its kinda true that i havent seen most of the blue drops so far,for example https://www.wowhead.com/item=37624/stained-glass-shard-ring?bonus=6710 should drop in AN/AK,but for me the question is: are they in the loot table of the server or no ? :)
