### ISSUE TITLE
runecloth gloves are calld frostweave gloves

### ISSUE THREAD

**Issue by wedris** [Stormforge-gg/Bugtracker-Fordring#1488]
**Description**: 
see the screenshot below
**Current behaviour**:
https://puu.sh/J7ZVI/ab306d1c9c.jpg
**Expected behaviour**: 
runecloth gloves

**Comment by Vishiswaz** [comment]
https://classic.wowhead.com/item=13870/frostweave-gloves

**Comment by Weuyn** [comment]
those damn tailors are scamming us with this 'frostweave' conspiracy. Its all just blue runecloth!! You can't fool us!!!
