### ISSUE TITLE
[NPC][Zul'Drak] Gundrak Bat Rider - Movement & Agrro range

### ISSUE THREAD

**Issue by Wathsup** [Stormforge-gg/Bugtracker-Fordring#149]
**Description**: 
**Gundrak Bat Rider** NPC moves very slow in the air and doesn't aggro Players.
https://www.wowhead.com/npc=29332/gundrak-bat-rider

**Current behaviour**:
**Gundrak Bat Rider** NPC moves very slow in the air and doesn't Aggro when flying by or right onto them. Dont know if that is intended or not (see video).
https://streamable.com/5f0c3e

**Expected behaviour**: 
**Gundrak Bat Rider** NPC should move abit faster and aggro Players who fly to close to them, like a normal NPC. 
Another Comment in the Comment-Section on _WowHead_ _(Comment By [242922] on 29.11.2008)_ says the following:

_"Watch out when flying over their area as they will dismount you and you might fall to your death ;)"._

So maybe this ability can be added aswell in case this is correct.

**Revision**: 
https://www.wowhead.com/npc=29332/gundrak-bat-rider
https://wotlk.evowow.com/?npc=29332#abilities

**Comment by Wolffenstein** [comment]
The speed issue and aggro issues should mostly be solved now, but the AI still needs to be fixed because they just dismount on aggro -.-
