### ISSUE TITLE
[Hunter][Pet] Hit Rating

### ISSUE THREAD

**Issue by Kripp0** [Stormforge-gg/Bugtracker-Fordring#1492]
**Current behaviour**:
Pets do not benefit from their master hit rating.
**Expected behaviour**: 
Pets should benefit from their master hit rating and not miss with their special attacks(still can be dodged/parried,only if they are facing their enemies).
Example:
5% hit for level 80 targets.
6% hit for level 81 targets.
7% hit for level 82 targets.
8% hit for level 83(bosses).
**Revision**: 
1566.

**Comment by Cold-Martijn** [comment]
Fixed in rev 1569
