### ISSUE TITLE
[Strat Undead] Mobs/bosses not spawning on reset all instances. Reset all instances not always working 

### ISSUE THREAD

**Issue by hiddenstump** [Stormforge-gg/Bugtracker-Fordring#1494]
**Description**: HI,
While running stratholme (undead side) It sometimes will not spawn any mobs or bosses after resetting the dungeon. Sometimes it seems to work and there is no issue, but alot of times the instance just looks like its been full cleared while still getting a fresh baron rivendare debuff (timer?). 

**Current behaviour**:
In description 
**Expected behaviour**: 
Dungeon resets like a normal dungeon should, and Mobs/bosses respawn along with doors being shut.
**Revision**:

**Comment by Godmatik** [comment]
Set dungeon difficulty to normal first (instead of heroic), then you will be able to reset properly.

**Comment by hiddenstump** [comment]
Im an idiot. thank you
