### ISSUE TITLE
[Song of Wind and Water] [Sholazar Basin] Half of the quest is bugged!!

### ISSUE THREAD

**Issue by AdonisBS** [Stormforge-gg/Bugtracker-Fordring#1496]
**Description**: 
This is one of the many possible daily quests from the Oracles faction in Sholazar Basin. You have to get to The Stormwright's Shelf, in the northwestern-ish part of the map. You use the "Drums of the Tempest" to become a water elemental and you have to fight the Storm Revenants and when they're at low heath, you use the water elemental's "Devour Wind", killing the target and transforming yourselft into a wind elemental. Now you have to fight the Aqueous Spirits and use "Devour Water" when they're low, transforming back to the water elemental form. You have to devour 3 (three) of each.

**Current behaviour**:
You can transform into the water elemental form just fine but it's main attack "Water Bolt" deals very little damage and it takes too long to kill the Storm Revenants. You can get them to low health and then use the "Drums of the Tempest" to become a water elemental and then devour. But now that you're in wind elemental form you cannot use any of it's abilities so you can't fight nor devour the Aqueous Spirits, making it impossible to finish the quest. If you leave the wind elemental form and use "Drums of the Tempest", you become only the water elemental.
And yes, I have also tried starting the fight againts a Storm Revenant using the water elemental's weak "Water Bolt" all the way to low health and devouring it and the wind elemental fase was still stuck.

**Expected behaviour**: 
What's expected is for the wind elemental form to be able to use it's abilities, weakening the Aqueous Spirits, devouring them and transforming the player back to a water elemental form. Then you just rinse and repeat until you devour 3 (three) of each.

**Comment by Wolffenstein** [comment]
Fixed in rev 1572.
