### ISSUE TITLE
[NPC][Icecrown] Putridus the Ancient ID 32487

### ISSUE THREAD

**Issue by Uzzyptm** [Stormforge-gg/Bugtracker-Fordring#1499]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Two small bugs with this mob
1. Whenever you pass trough K3 NPCSCAN reports him as next to you(maybe an npc scan bug but still you can /target him all the way from Zul Drak /Storm Peaks so that may have something to do with it
2. At the end of his patrol instead of going way back to his original starting location he passes trough the textures and terrain
**Current behaviour**:
https://imgur.com/a/iqfk6Tq
Fiest pic is me targeting him from far away and second one is him passing trough the map
**Expected behavior**: 
Shouldn't be able to target him except when your are close by
He should patrol back to the initial position and not pass trough textures
**Revision**:

**Comment by eryczek1615** [comment]
According to wowhead comment people were able to target him from Dalaran/ Borean Tundra. 
![20220628_080836](https://user-images.githubusercontent.com/4455568/176105788-46b2a87d-9cae-4e8c-9fab-498d2865148b.jpg)

**Comment by Smokdacave** [comment]
i had another issue
>he spawned
>i could target him but not attack or cast spells at him
> he wasn't moving and despawned in a few min
