### ISSUE TITLE
[Spell][DK] Raise Dead - Default Mode

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Fordring#150]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [Raise Dead](https://www.wowhead.com/spell=46584/raise-dead) ghoul (with unholy talent) set to aggressive by default

**Current behaviour**: The controllable raise dead ghoul is being summoned as aggressive by default, also defaults back to aggressive after closing the game/logging out and logging back in.

**Expected behaviour**: Should default to defensive mode when summoned, should also retain the chosen mode when logging out.

**Revision**: 1045

[source](https://youtu.be/O8bMrlYFXS4?t=75)

**Comment by Peglaa** [comment]
Same as shaman wolves used to: https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/1189
