### ISSUE TITLE
[Core][Auction House] Items purchased/returned from Auction House incorrectly soulbound

### ISSUE THREAD

**Issue by yo931** [Stormforge-gg/Bugtracker-Fordring#1500]
Purchased Truesilver Bar and Heavy Grinding stone from the auction house and trade window automatically cancels if you try to trade them. Mailing them will give the error "You cannot mail soulbound items." And vendoring them will give you the error "Merchant does not want this item."

This seems to be happening to other players as well, not being able to disenchant items they purchase from the AH, or not being able to repost items they crafted/posted/returned from the AH.

how to reproduce: buy smth from auction like a green item or material and try to vendor it

**Comment by Kripp0** [comment]
True,i cannot sell BOE's items ... not even sell them on the vendor.

**Comment by werwe123** [comment]
Yes, we also encountered the same problem

**Comment by Cold-Martijn** [comment]
fixed in rev 1571.
