### ISSUE TITLE
[Dungeon][Achievement] COS

### ISSUE THREAD

**Issue by Kripp0** [Stormforge-gg/Bugtracker-Fordring#1501]
**Current behaviour**:
Malganis doesnt count for the achievement.I killed him few times in the last 2 weeks,and still i dont have the achievement.
![WoWScrnShot_062722_173722](https://user-images.githubusercontent.com/36957911/175967405-6bd80561-ee5a-4dae-a450-7bb4b2c82523.jpg)

**Expected behaviour**: 
U should get the achievement.
**Revision**: 

1567.

**Comment by Alandiel** [comment]
You need to wait for combat to end before leaving dungeon. I think it ends after Mal'Ganis teleports.

**Comment by Cold-Martijn** [comment]
fixed in rev 1576
