### ISSUE TITLE
[65871][hunter] shred is parried by deterrance

### ISSUE THREAD

**Issue by Smokdacave** [Stormforge-gg/Bugtracker-Fordring#1504]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
spell=5221 shred is parried by spell=65871 
**Current behaviour**:
![image](https://user-images.githubusercontent.com/73365282/176036663-fe317b9a-9bd3-4986-8cf0-769b443a295f.png)
**Expected behaviour**: 
spell=5221 shred is supposed to hit through spell=65871

**Comment by Cold-Martijn** [comment]
fixed in rev 1573
