### ISSUE TITLE
[Hunter][Pet] Hit Rating... again

### ISSUE THREAD

**Issue by Kripp0** [Stormforge-gg/Bugtracker-Fordring#1506]
Current behaviour:
The pet STILL do not benefit from his master hit rating... with 7% hit they are missing on level 77 with their special attacks..

Revision:
1571

**Comment by NatsumeLily** [comment]
Did the server update? Test it after the server updates...

**Comment by Kripp0** [comment]
ok i will wait few days

**Comment by NatsumeLily** [comment]
Ok, sorry. Server was updated to 1571, so reopen this.

**Comment by Cold-Martijn** [comment]
What pet are you using, and what special attack missed? And what level is your pet?

**Comment by Kripp0** [comment]
![WoWScrnShot_062822_144310](https://user-images.githubusercontent.com/36957911/176170294-8197fada-7f81-482d-9fb8-925b7f4790f2.jpg)
Level 80 wolf with 7% hit attacking from behind level 79 wolf  ...

**Comment by Kripp0** [comment]
![WoWScrnShot_062822_144955](https://user-images.githubusercontent.com/36957911/176171375-6a1be8fb-5c9f-4395-89cf-01ecf4e891b2.jpg)
5 man dungeon

**Comment by Kripp0** [comment]
![WoWScrnShot_062822_212805](https://user-images.githubusercontent.com/36957911/176256059-3ca9ac95-9b02-4e5f-b9d7-53bd6b3d2506.jpg)
OS 25

**Comment by LautaroJMolina** [comment]
Don't know if I should make a new issue instead, but shaman spirit wolves are also missing with auto-attacks, fire elemental from totem is missing with spells. And magma totem misses with aoe pulses.
Pretty sure all these things shouldn't happen, but maybe that's just pserver brain.
Dps simulations from the time also show these things not happening.

**Comment by Kripp0** [comment]
White attacks are supposed to miss,special attacks not if the pets are hit capped and attacking form behind.

**Comment by NatsumeLily** [comment]
Just adding this here. Hit chance should affect auto attack too. At hit cap, a pet should not miss any auto attacks.

**Comment by Cold-Martijn** [comment]
fixed in rev 1593
