### ISSUE TITLE
[NPC] Ferocitas the Dream Eater

### ISSUE THREAD

**Issue by Uzzyptm** [Stormforge-gg/Bugtracker-Fordring#1510]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Gnarlpine Necklace should have 100% drop chance,killed him 12 times and no drops

**Current behaviour**:
Gnarlpine Necklace should have 100% drop chance,killed him 12 times and no drops
**Expected behaviour**: 
This quest item should have a 100% drop chance
**Revision**:

**Comment by Godmatik** [comment]
Works fine for me.

Make sure you didn't already loot the jewel from the necklace and that it's in your bags, make sure you arent in a raid group

**Comment by Uzzyptm** [comment]
> 

Wasn't in any raid group and no i didn't allready have it, I abandoned the quest after a couple of kills

**Comment by Godmatik** [comment]
So how did you fix it?
