### ISSUE TITLE
[Spell][Mage] Arcane Blast [Glyph of Arcane Blast] doesn't stack correctly

### ISSUE THREAD

**Issue by jorgehurtadodmx** [Stormforge-gg/Bugtracker-Fordring#1512]
Description:

Maybe I am wrong but...
Arcane blast buff should do +3% damage per stack, meaning that first proc gives increased 18% damage, second 36%, up to 4 stacks.
The description of the spell, updated with the glyph says that, but the buff(actually debuff) given to the player, doesn't update the info
and says, 15,30,45% stacks. This could mean that we arcane are missing a little bit of damage.

Current behaviour:

15,30,45,60% arcane increased damage after using arcane blast (stacks to 4)

Expected behaviour:

18,36.... % arcane increased damage after using arcane blast(up to 4)
Mana cost shouldn't increase.

Proof:
![bug2](https://user-images.githubusercontent.com/32094091/176265792-21db8531-fb91-4f62-b9c9-4cec24400681.png)
![bug1](https://user-images.githubusercontent.com/32094091/176265806-09367e7c-a279-4623-83c4-71d09ea9de5e.png)

I can make a video but i would have to test it multiple times removing and buying the glyph multiple times, so it's very costly.

https://imgur.com/a/odGOAov
Some photos where it shows current behaviour and expected behaviour

Revision:

**Comment by NatsumeLily** [comment]
Tooltips aren't updated to changes from talents or glyphs.
