### ISSUE TITLE
[Web][Core] Lil' Muru refuses to transfer from Atlantiss to SF.

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#1515]
**Description**: Character transfer testing was just implemented. Lil' Muru, a prize won from defeating Entropius on Karazhan server, does not appear to be in our inventory upon transfer. It was a custom item on Karazhan.

**Current behaviour**: Lil ' Muru does not transfer from Atlantiss to Stormforge.

**Expected behaviour**: Lil' Muru should transfer from Atlantiss to Stormforge.

**Revision**: 1578

![image](https://user-images.githubusercontent.com/105084838/176310929-7f61e0ae-6da0-43fc-b7fa-4cce1c4defc9.png)

**Comment by peterpwn321** [comment]
+1

**Comment by nevrozac** [comment]
This is not a bug. Please use discord to ask for custom content.

**Comment by FX-SF** [comment]
lol was literally told by head GM to post here.
