### ISSUE TITLE
Transfer issue from kara to wotlk 

### ISSUE THREAD

**Issue by dontfaket30** [Stormforge-gg/Bugtracker-Fordring#1519]
My druid was lvl 70 and got promoted to lvl 1 
No gold, had like 800+g 
all items is in mailbox

Picture https://media.discordapp.net/attachments/861265145287147540/991570167928725524/Screenshot_3.png?width=1266&height=676

**Comment by dontfaket30** [comment]
https://prnt.sc/lqyNdIFb-FcJ 
UPDATED from website. Its red and TRUE

I just transfered warlock and everything was perfect

**Comment by CMCalamitas** [comment]
i had the same issue on one of my toons, worked after an hour.

Got this tho: https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1520

**Comment by Emtec** [comment]
Fixed
