### ISSUE TITLE
[Talent][Spell][Warrior] Bloodthirst Missing (Kara transfer bug)

### ISSUE THREAD

**Issue by Madjarid** [Stormforge-gg/Bugtracker-Fordring#1521]
**Description**: 
Bloodthirst not showing up in spellbook after picking the talent in the fury tree. Not visible at the class trainer either.

**Comment by RainingLightning** [comment]
Battle Stance and Heroic Strike aren't available either.

**Comment by nevrozac** [comment]
![rlg](https://user-images.githubusercontent.com/67228392/176977382-2236d157-8053-4f16-aba4-4f54d997a5e6.png)

**Comment by nevrozac** [comment]
![bloodthirst](https://user-images.githubusercontent.com/67228392/176977432-ff7e453d-07d7-4fed-867a-d9193019aa4b.png)

**Comment by nevrozac** [comment]
![heroics](https://user-images.githubusercontent.com/67228392/176977435-24ad7324-0c42-4a4d-9065-68c8744e5751.png)

**Comment by nevrozac** [comment]
All is in order on my end. I reckon you just haven't relogged twice.
