### ISSUE TITLE
Karazhan Transfer - Polymorph Turtle

### ISSUE THREAD

**Issue by addi011** [Stormforge-gg/Bugtracker-Fordring#1522]
**Description**:  I have seen a small issue with the transfer to WOTLK PTR from Karazhan. My mage is now able to do Polymorph Pig instead of Polymorph Turtle (as known on Karazhan TBC).

**Current behaviour**: With transfer to WOTLK, Polymorph Turtle turns to Polymorph Pig.

**Expected behaviour**: With transfer to WOTLK, Polymorph Turtle should stay Polymorph Turtle.

**Comment by Emtec** [comment]
Fixed

**Comment by addi011** [comment]
@Emtec your fix did not seem to work with the live transfers unfortunately. Is it possible to have a look here again? Thanks for all your effort, very happy to play my mage from NW again :-)
