### ISSUE TITLE
[Transfer] Keymaster Achievement doesn't get updated with the keys in your inventory

### ISSUE THREAD

**Issue by Tereneckla** [Stormforge-gg/Bugtracker-Fordring#1524]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/wotlk/achievement=1187/the-keymaster

**Current behaviour**:
No progress on the achievement after transfer, despite having a few of the keys
**Expected behaviour**: 
Appropriate progress
**Revision**:

**Comment by Emtec** [comment]
Fixed
