### ISSUE TITLE
[Spell][Zone] Wintergrasp Catapult's Flame Breath

### ISSUE THREAD

**Issue by CHL90** [Stormforge-gg/Bugtracker-Fordring#1525]
Description: 
Wintergrasp Catapult's Flame Breath seems to scale with level or ilvl making the ability effectively one-shotting everybody. I believe the issue is related to [1572].

Current behaviour:
Flame Breath does 8-9k damage per second. 

Expected behaviour: 
Flame Breath should do 3k damage over 3 seconds

![Wintergrasp Catapult Flame Breath](https://user-images.githubusercontent.com/5501836/176470603-51b026d8-89f5-43e7-a529-e41906f00e94.jpg)
.

**Comment by Wolffenstein** [comment]
already fixed
