### ISSUE TITLE
[Zone] Ruby Dragonshire [NPC] Figid Abomination Attacker (27531)

### ISSUE THREAD

**Issue by seitzcasey** [Stormforge-gg/Bugtracker-Fordring#153]
**Description**:
These NPCs are not in combat with the Ruby Watchers. Zone will be basically unplayable if this isn't fixed as they are elites.

**Current behaviour**:
Ruby Watchers just fly around acting like they're going to attack

**Expected behaviour**: 
Ruby Watchers attack these mobs.

**Revision**: 
1044

**Comment by therealCrysis** [comment]
confirmed in rev rev 1165
