### ISSUE TITLE
[Transfer] Rogue bug

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1531]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: My rogue has the poisons ability, which shouldn't be in the game anymore. 

![WoWScrnShot_062922_170602](https://user-images.githubusercontent.com/15247730/176560867-dab20a6b-a788-4790-8777-6b5771e9fcc8.jpg)

**Revision**:

**Comment by Wolffenstein** [comment]
not a bug
