### ISSUE TITLE
[Hunter] Pet bugs

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1532]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
1. Pets are getting no threat from auto-attacks. This might be happening for all class pets.
2. Auto-cast on Prowl doesn't do anything. Pet should cast prowl whenever it's out of combat, if auto-cast is on. 
3. Auto-cast on Dash (likely Dive too) doesn't do anything. Pet should cast dash whenever it is/needs to run to a target. It should not cast it on CD when attacking the target.
4. ~~Pets aren't moving at 100% run speed, same speed as player.~~ Correction: Only cats (at least my cat is) are the slow ones. And pets run at 114%, but your character speed when not in combat. Which I think is correct. 

Video for #4 https://www.youtube.com/watch?v=7d8GAd9mJQM
Only cat acts like this out of my 3 pets (cat, owl, wind serpent). The owl and wind serpent are correct. 

**Revision**:

**Comment by Kripp0** [comment]
Did a little research,pets should NEVER miss with 8% if they attack from behind.

**Comment by NatsumeLily** [comment]
Update for #3. Only the cat pet won't use Dash if it's on auto cast (cat pet is really buggy).

But "Pet should cast dash whenever it is/needs to run to a target. It should not cast it on CD when attacking the target." is still valid. Pets shouldn't use Dash or Dive on CD if they are at the target attacking it.
