### ISSUE TITLE
Unable to log into account after first logout Website

### ISSUE THREAD

**Issue by Wiffofwaffle1** [Stormforge-gg/Bugtracker-Fordring#1533]
**Description**:  My account will not allow me to log in on stormforge.gg

Created new account > Email Activated account > Auto logged me in > Transferred character from Karazhan > Logged out > Couldn't log in > Reset password with email > Couldn't log in > Reset password with username > Couldn't log in

**Current behaviour**:  Receiving error even after multiple password reset tries. "Wrong Username/Email and password combination. Try again or recover your password." 

**Expected behaviour**: Log me in

**Revision**:

**Comment by Emtec** [comment]
Please write on support@stormforge.gg
