### ISSUE TITLE
[NPC][Drop] Gundrak Raptor not dropping correct loot

### ISSUE THREAD

**Issue by AgentMalice** [Stormforge-gg/Bugtracker-Fordring#1536]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Gundrak Raptors should drop only Borean Leathers or Arctic Furs.

**Current Behavior**: Atm Gundrak Raptors Drops Nerubian Chittin, aswell as their drops are broken, it only drops x1 Borean Leather, might not even have Arctic Furs in the loot Table, havent seen one yet.

**Expected Behavior**: Gundrak Raptors should drop 1-8 Borean Leathers, aswell as 1-2 Arctic Furs, and should not drop any Nerubian Chittins

![image](https://user-images.githubusercontent.com/105992977/176723492-cf7a8608-a13c-4fd6-a6e9-7fd8f77a26e4.png)

[Raptor Skinning from wowhead](https://www.wowhead.com/npc=29334/gundrak-raptor#skinning)

**Revision**:

**Comment by Wolffenstein** [comment]
It should be 1-3 Borean Leather and 1 Arctic Fur - hover over the percentage to see the distribution.

Fixed.

**Comment by AgentMalice** [comment]
![image](https://user-images.githubusercontent.com/105992977/176726119-50982d32-aac6-41ca-8dce-f2ea50c3c119.png)
![image](https://user-images.githubusercontent.com/105992977/176726134-33b61c29-2f01-45a6-9e5f-1a704e09586f.png)
