### ISSUE TITLE
[Transfer] Character deleveled to level 1, changed character appearance, empty inventory

### ISSUE THREAD

**Issue by RainingLightning** [Stormforge-gg/Bugtracker-Fordring#1538]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Level 70 character has been deleveled to level 1. Bag inventory is empty and the gear is missing, and the character's appearance (the facial options that are chosen during character creation) has been changed. Additionally, zone exploration achievements, dungeon achievements, and PVP achievements as well as honor kills are empty, but I believe that is not an oversight/bug as that data is probably not saved.

**Current behaviour**: Level 70 character is now level 1. No items in bag or gear slots. Character customization options (appearance) not the same.

**Expected behaviour**: Level 70 character should remain level 70. All items the character possessed in the bag/bank/gear slots should remain(?). Character should retain the same facial customization options as on Karazhan.

**Revision**:

**Comment by Emtec** [comment]
Fixed
