### ISSUE TITLE
[Quest] Defending Wyrmrest Temple (12372); [Spell] Immolation (49243)

### ISSUE THREAD

**Issue by seitzcasey** [Stormforge-gg/Bugtracker-Fordring#154]
**Description**: 
Can't use 2nd ability "Immolation"

**Current behaviour**:
Trying to activate Immolation displays the message "Can't use that ability while Pacified"

**Expected behaviour**: 
Activating Immolation will work

**Revision**: 
1044

**Comment by therealCrysis** [comment]
Confirmed in rev 1165

**Comment by Smokdacave** [comment]
up
