### ISSUE TITLE
[Shaman] Shaman pets

### ISSUE THREAD

**Issue by LautaroJMolina** [Stormforge-gg/Bugtracker-Fordring#1543]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Both spirit wolves and fire elemental seem to have some issues.

**Current behaviour**:
Spirit wolves are seemingly not being affected by the shaman's hit rating, I have 10.73% melee hit and they still miss, I would assume this is the same issue that affects hunter pets.
Spirit wolves also use their spirit wolf leap on weird targets, for example Sartharion (technically not sarth, but one of the smaller drakes) void blasts.
Also, as of patch 3.1, fire elemental, spirit wolves, mirror images, treants and water elemental should get the warlock/hunter pet aoe avoidance. This doesn't seem to be the case at least with wolves and the elemental, since they tend to die really easily to raid and even dungeon mechanics compared to warlock and hunter pets.
The fire elemental's spells also appear to be behaving weirdly, it regularly misses it's spells and rarely casts.

**Expected behaviour**: 
(I haven't been able to find anything conclusive about some of this "issues")
Spirit wolves should benefit from the caster's hit and not miss melee attacks.
I'm not sure about the leap behavior, but it seems weird that they would instantly leap to an aoe mechanics upon being summoned (ironically, this, coupled with not having aoe avoidance can make them kill themselves instantly on Sarth).
Wolves and fire elemental should have aoe avoidance, otherwise I cant think of another reason why they die so much faster than other pets.
The matter with the fire elemental is what I'm most uncertain about. I haven't been able to find anything conclusive. The best I have is that the dps simulation that I use reports that the elemental doesn't miss with spells, and that it casts fire nova and fire blast (edit spell name) around 8 times per minute. While here it misses spells and casts around half as often.

**Revision**: 
1583

**Comment by Kripp0** [comment]
White attacks are supposed to miss,even if ure capped.Special attacks should not.. if they are used from behind.In your case i believe u need more hit for the fire ele abilities,idk about the wolves tho.

**Comment by LautaroJMolina** [comment]
White attacks miss with that hit rating if they use the dual wielding hit table, idk if hit works the same way for players and pets in this aspect. The guide i looked at from back in the day seem to point at wolfs using the 1h/2h hit table, if that is the case they shouldn't miss. Looking at the in game description of their auto attacks and the fact that they only deal one instance of damage per auto, it would seem they fall under that category and shouldn't miss. Again, i'm not THAT familiar with weird blizz hidden mechanics, so I might be wrong.
Pretty sure fire ele is a guardian so it works differently, it shouldn't get hit from the caster (?), i'm not very familiar with the specifics.
In the damage sims I run the elemental white attacks miss, but spells don't, which is definitely weird. I guess the sims could be wrong, altough the people who developed them were pretty thorough. Again, I wasn't able to find more about this.

**Comment by Kripp0** [comment]
The hit % only affects abilities, not auto attack.. or at least that how it should work.

**Comment by NatsumeLily** [comment]
> The hit % only affects abilities, not auto attack.. or at least that how it should work.

Hit % should also affect auto attacks.

**Comment by Kripp0** [comment]
I mean they will still miss even if ure hit capped*

**Comment by NatsumeLily** [comment]
> I mean they will still miss even if ure hit capped*

Same thing. Pets are hit capped at 8%, which affects auto attacks too and auto attacks won't miss. 

Picture for spirit wolves specifically 
![image](https://user-images.githubusercontent.com/15247730/176962009-775b10ce-7e84-4110-9519-09c954004ca8.png)

**Comment by LautaroJMolina** [comment]
Some stuff I found about fire elemental spell scripting and scaling in the EnhSim source code.

![elementalscripting](https://user-images.githubusercontent.com/64675765/176990717-6e22de59-7cea-4357-9316-77f0f2445ae1.png)
(I didn't go looking for the original posts)

If this is correct, fire elemental also has less mana than it should, currently around 2.3k when I've tested it.
Fire nova cd is kind of weird.
Whatever the case, in game, the elemental sometimes spends close to 10s in between fire nova casts and even more in between fire blasts. The elemental currently casts fire blast and fire nova 7 to 8 times each over the 2 minutes duration. Which seems very far from what was observed back then.
Also all the old discussion posts about EnhSim development that I read just seem to gloss over the fire elemental spells never missing, so maybe they just forgot, and they should actually miss.

**Comment by LautaroJMolina** [comment]
Found a report for the fire elemental scripting on the TrinityCore github issues with more information.

https://github.com/TrinityCore/TrinityCore/issues/16011

Unfortunately I don't know of any world of logs archive, so I can't link to any concrete logs.
