### ISSUE TITLE
[Core] Starting combat with some caster mobs

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1544]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I've noticed this with a handful of mobs and I didn't bother reporting it before, but it's gotten pretty annoying so I'm going to report it now.

When beginning a fight with _some_ caster mobs, specifically by approaching them from behind and then using Cheap Shot as a Rogue, the server has that mob turn around to face me before the Cheap Shot stun technically hits. This means I cannot use backstab.

This should not happen. The order should be Cheap Shot => Stun => Backstab => Stun wears off => Mob rotates. Currently it is Cheap Shot => Mob rotates => Stun => Move to get behind the mob again => Backstab => Stun wears off.

An example mob this happens with so you can test: Darkcrest Sorceress.

**Comment by Vishiswaz** [comment]
Edit: Accidentally confused Ambush with Cheap Shot. I don't Rogue often.

**Comment by Godmatik** [comment]
I notice the same when I use pounce as a druid, however it appears to be a visual bug only, still able to use shred on them even though they are "facing" me when stunned.

**Comment by Vishiswaz** [comment]
Nope, not a visual bug only. On some mobs it's visually bugged, but on some, such as the one I listed above, it will not let you backstab from the direction you should.

Try it on the Darkcrest Sorceresses.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
