### ISSUE TITLE
Pygmy Suckerfish Droprate

### ISSUE THREAD

**Issue by wedris** [Stormforge-gg/Bugtracker-Fordring#1546]
**Description**: 
Pygmy suckerfish is not dropping as much as it should be 
**Current behaviour**:
every 300-500 fish I got so far 2
**Expected behaviour**: 
Here are multiple wowhead comments (https://www.wowhead.com/wotlk/item=40199/pygmy-suckerfish#comments) for the time the patch was live (3.0.8) when they buffed it to 50-80% droprate.
Which would mean every 3rd/4th fish should drop a pygmy. 
School or open water, doesnt matter.

**Comment by Nihaobeachez** [comment]
Guildmate farmed like 3 stacks in 30min. just saying

**Comment by NatsumeLily** [comment]
Were you fishing in pools? 

https://web.archive.org/web/20100310134214/http://www.elsanglin.com/fish/pygmy_suckerfish.html

Sources say out of pools the drop rate is awful (10%), and in pools it is really high.

**Comment by wedris** [comment]
So I fished today, and I noticed something. 
Yes fishing outside of pools should be 10% but this isnt the case here (or at least it wasn't). 
Now the dropchance for open water is below 10% (2 fish in 30 swings).

About the pools. The dropchance is literally 0. I tried to fish in every zone (sholazar / tundra / fjord / grizzly / dragonblight), and not a single pygmy suckerfish.
-----------------------------
Sidenote for Sholazar pools
They drop phantom ghostfish, which I think take the pygmy suckerfish spot for drops (haven't seen a single fishing swing with more than 2 items)
-----------------------------
This was btw before today the case, and the moment I opened the ticket originaly. 
Pools should be 50-70% (except glassfin minnow). This is an offical statement in the 3.0.8 Patchnotes.

The fish was already giga rare, and now its like I fish for Invincible (I'm not joking).
The economy on the server won't be able to deal with that, please fix that they are able to drop in pools.
