### ISSUE TITLE
A bug in a quest in the Argent Vanguard

### ISSUE THREAD

**Issue by sammouros** [Stormforge-gg/Bugtracker-Fordring#1547]
In Argent Vanguard, the quest ''A Cold Front Approaches'' is bugged and i cant complete it. I talk to the quest giver but it doesnt do anything. Thank you

**Comment by Drevil-Dion** [comment]
this quest is working for me

![image](https://user-images.githubusercontent.com/13806368/177581419-cd45be4e-5042-4784-87a0-5167a5dc43fc.png)
