### ISSUE TITLE
Pet scaling from masters stats

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1549]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Related thing with #1506. 
Pets should get hit rating from player. But they should also get spell hit and expertise. If a player is hit capped, the pet should also be capped on hit, spell hit, and expertise. 
Patch 3.2
![image](https://user-images.githubusercontent.com/15247730/176968846-ef0c8576-8784-4f4f-8c95-d0ba51530e2e.png)

Pets should also get 100% of the players crit chance. 

https://web.archive.org/web/20100315095616/http://www.wow-petopia.com/html/guides/stats_scaling.php
![image](https://user-images.githubusercontent.com/15247730/177078243-226b1e35-873f-437b-9a32-f01522e28fec.png)

**Revision**:

**Comment by Cold-Martijn** [comment]
fixed in rev 1593
