### ISSUE TITLE
Trade Bug

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1554]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
If someone tries to open a trade window with you while you have the mailbox or AH window open, no trade window will open and one of you will have to log out before you can try again.
**Expected behaviour**: 

**Revision**:

**Comment by Vishiswaz** [comment]
You don't have to log out, if you walk far away from each other, the phantom trade window closes.

Still an annoying bug though.
