### ISSUE TITLE
[Quest][NPC] Battle at Valhalas, Geirrvif

### ISSUE THREAD

**Issue by apaen** [Stormforge-gg/Bugtracker-Fordring#1555]
**Description**: 
Geirrvif cannot be talked to, to complete the quest Battle at Valhalas. 

**Current behaviour**:
Geirrvif was found ~50m in the air with no quest turn in above her head. Asked GM to see if they could do anything. After Geirrvif was on the ground with no quest turn as well. 

**Expected behaviour**: 
Geirrvif to have a quest turn in enabled to continue that quest line. 

**Revision**:

**Comment by d0pp3l** [comment]
This issue still persists.
