### ISSUE TITLE
Missing Spell After transfer from TBC

### ISSUE THREAD

**Issue by dontfaket30** [Stormforge-gg/Bugtracker-Fordring#1558]
My druid is missing spell Teleport to moonglade after transfer from tbc.
Druid trainers dont have anything to learn.

**Comment by Vishiswaz** [comment]
Did you relog twice like the instructions told you to

**Comment by dontfaket30** [comment]
i have been reloged million times now.

**Comment by MnmZilla** [comment]
I see the issue has been "closed", but has it actually been adressed? I still do not have the *tp to Moonglade spell on my transfered druid.

**Comment by Vishiswaz** [comment]
This doesn't belong on the bug tracker. All transfer related issues go to Emtec.
