### ISSUE TITLE
[Karazhan Transfers] [Riding Skill] [Jafarladin Character]

### ISSUE THREAD

**Issue by ImCasual** [Stormforge-gg/Bugtracker-Fordring#1559]
[Karazhan Transfers] [Riding Skill] [Jafarladin][Terpsicore]
I already had bought artisan fly skill at this and after transfers , i dont have it. I notice some trouble about gold between accounts, but since i have 1k gold . It dosent matter.
Its 2 different accounts, Jafar its mine and Terps of my wife, we had problem only about it.

https://i.im.ge/2022/07/03/uL4du9.jpg (Jafar TBC)
https://i.im.ge/2022/07/03/uL42fK.jpg (Jafar WOTLK)
https://i.im.ge/2022/07/03/uLGI24.jpg (Terps TBC)
https://i.im.ge/2022/07/03/uLGL6C.jpg (Terps WOTLK)

![Jafar TBC](https://user-images.githubusercontent.com/106356832/177039623-a1745245-9124-487f-ac28-d295d3c7dbfb.JPG)
![Jafar WoTLK](https://user-images.githubusercontent.com/106356832/177039624-f1e69c7a-e7ba-4708-b8f9-89afe6cee38f.JPG)
![Terpsicore WOTLK](https://user-images.githubusercontent.com/106356832/177040626-1c982023-05ff-4bae-8466-f3c4db3c1456.JPG)
![Terpsicore TBC](https://user-images.githubusercontent.com/106356832/177040629-c3a58f62-1962-4cba-b6c1-8f69b3453ff7.JPG)

**Comment by Vishiswaz** [comment]
Sounds like you bought the riding skill after the snapshot of the characters were made, to try to get around the gold limit
