### ISSUE TITLE
[NPC][Terokkar Forest] Blackwind Sabercat

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1561]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There is a random level 71 mob in Terokkar I've never seen there before on any other server called Blackwind Sabercat.

It will aggro to players but is unattackable. Please get rid of this nuisance.

**Comment by NatsumeLily** [comment]
I think the only problem here is they are unattackable. 

The mob looks real though. 
https://www.wowhead.com/npc=21723/blackwind-sabercat
https://wowpedia.fandom.com/wiki/Blackwind_Sabercat

**Comment by Vishiswaz** [comment]
Then it's in the wrong place.
![WoWScrnShot_070322_131254](https://user-images.githubusercontent.com/78314117/177051591-09b94753-9426-4535-a037-56d33f242f34.jpg)

**Comment by Vishiswaz** [comment]
Closing due to new server core.
