### ISSUE TITLE
[Quest][Blade's Edge Mountains] Show Them Gnome Mercy!

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1567]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This quest isn't even slightly scripted.

1. There are static floating yellow orbs all around Razaan's Landing. These are things that should spawn upon killing an Ethereal in Razaan's Landing, then float to the center gate and gradually fill the tube.
2. The tube does not fill at all
3. Nexus-Prince Razaan appears to be a static spawn instead of one that only happens when the tube fills
4. He's also in the wrong location.
5. Not sure if there's supposed to be RP, but if there is, I didn't see any.

**Comment by Cold-Martijn** [comment]
fixed in rev 1589
