### ISSUE TITLE
[Spell][Druid]Teleport: Moonglade

### ISSUE THREAD

**Issue by fondlez** [Stormforge-gg/Bugtracker-Fordring#1568]
**Description**: 

The spell Teleport: Moonglade is not auto-learned. 

This also creates complications. Some players associate it with the Bear Form quest, which fresh characters no longer need to do because that is auto-learned. So, they assume it is no longer available. In fact, you can just accept the quest in Darnassus called [Moonglade] (quest id: 5921) from NPC [Mathrengyl Bearwalker] which immediately provides the spell.

In addition, for transfer characters, they would have learned it naturally, usually by completing the quest (though it is not technically necessary to actually have completed the quest, just accepted it). So, therefore for transfer characters obtaining the spell is no longer possible in-game when the quest has already been completed.

**Current behaviour**:

The spell Teleport: Moonglade is not auto-learned.

**Expected behaviour**: 

Teleport: Moonglade should be auto-learned like every other (leveling) spell.

**Revision**: 
AtlantissCore WoTLK rev. 1584, 3e5d1d2ee06d 2022-07-02 18:55:52 +0200 (master branch) (Unix, Debug, Static)

**Comment by MnmZilla** [comment]
How was this fixed, My  transfered druid still does not have the spell :/
