### ISSUE TITLE
[Quest][Blade's Edge Mountains] Fire At Will! - QUEST NOT COMPLETABLE

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1578]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The quest item "Naturalized Ammunition" does nothing, and therefore this quest cannot be done. Not sure if this is gonna prevent me from getting loremaster.

**Comment by Cold-Martijn** [comment]
fixed in rev 1592
