### ISSUE TITLE
Pets crit chance from master

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1582]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Related #1549. Only half of that got fixed. 

Pets should also get 100% of the players crit chance.

**Revision**:

**Comment by obipwn** [comment]
adding to this, ghoul is still getting dodged when dk is hit capped.
263 hit rating on dk should translate to 26 expertise for the ghoul, yet he had >10% dodged attacks on dummy.

also gargoyle still shooting 12 times only under any haste condition. is that patch live yet?

**Comment by Kripp0** [comment]
https://youtu.be/Cp3nIhf2tfk?t=248 13 cast for 30 sec with icc gear... its fine.

**Comment by Kripp0** [comment]
https://bigredrhino.wordpress.com/pet-stats/
