### ISSUE TITLE
Horde took flag in Warsong after theirs was captured.

### ISSUE THREAD

**Issue by 666franz666** [Stormforge-gg/Bugtracker-Fordring#1583]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
A Horde Player took the flag, after we captured theirs and they won the game because of it.
**Current behaviour**:
The Horde Player could take the flag, after a capture.
**Expected behaviour**: 
Noone should be able to take a flag for 12 sec.
From WoWHead:
After a flag is captured, both flags will disappear for 12 seconds, after which they both respawn in their respective bases.
https://de.classic.wowhead.com/guides/classic-wow-warsong-gulch-advanced-intro-rules-timers-wsg#:~:text=After%20a%20flag%20is%20captured,respawn%20in%20their%20respective%20bases.

**Revision**: 
![World Of Warcraft 3 3 5 Screenshot 2022 07 05 - 21 42 34 07](https://user-images.githubusercontent.com/57036752/177405704-a860708b-963b-41cf-9fb0-50f3f786fa13.png)

You can see in the Chat, that we captured theirs, they took yours and after that, the flags got reseted to the bases.
But that didn´t happen, because he was carrying it.

**Comment by NatsumeLily** [comment]
> Noone should be able to take a flag for 12 sec.

20 seconds.
