### ISSUE TITLE
Pets hit chance still not correct

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#1594]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: I have 4.44% (items) + 3%(Focused Aim) + 1(Heroic Presence) = 8.44% hit chance. Rounded down to 8% for pets, my pet should be hit capped and expertise capped. 

But pet is still missing and getting dodged. 
https://www.youtube.com/watch?v=mZ7e0-bKRkI

> adding to this, ghoul is still getting dodged when dk is hit capped.
> 263 hit rating on dk should translate to 26 expertise for the ghoul, yet he's getting dodged attacks on dummy.
> 
> _Originally posted by @obipwn in https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1582#issuecomment-1175966962_

**Revision**: 1593

**Comment by LautaroJMolina** [comment]
Same with shaman wolves

**Comment by obipwn** [comment]
afaik, your pet does not get expertise from heroic presence buff. idk about talents.

however, in my tests i was hitcapped only from gear and still had my pet getting dodged.

**Comment by NatsumeLily** [comment]
It does. 

Or in this case it should, but who knows where the bad script is.
