### ISSUE TITLE
[Class][Skill][Spell] Lockbox respawn timer too long

### ISSUE THREAD

**Issue by MichaelCrow** [Stormforge-gg/Bugtracker-Fordring#1599]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Lockbox respawn times in lockpicking farming areas such as stonetalon mountains or ashenvale for horde have a super duper long respawn timer that isnt blizzlike at all and should be far shorter as theres already a limited number that spawn (4-6 in stonetalon for instance) at a time.

**Current behaviour**: Lockboxes are looted, dont respawn for seemingly 15-30 minutes

**Expected behaviour**: Lockboxes are looted, respawn in a minute or two.

(https://www.wow-professions.com/tbc/lockpicking-leveling-guide-tbc-classic#1)

**Comment by NatsumeLily** [comment]
Might want to change the title. Typo being "too short", should be "too long".

**Comment by Godmatik** [comment]
Possibly related.

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/644
