### ISSUE TITLE
[TGC ITEM SHOP ATLANTISS>SF] Carved Ogre Idol

### ISSUE THREAD

**Issue by Healweed** [Stormforge-gg/Bugtracker-Fordring#1608]
**Description**: 
I bought this trinket during the time where Netherwing was still up (around patch 2.3 which basically Zul'Aman patch) and this was WAYYYY before kara release. When i xfered this shaman from Kara to here i noticed that Carved Ogre Idol got butchered while i still have the item equiped on me which is rather frustrating not able to use something that i bought in the past!
**Current behaviour**:
Have it equiped, does not create a copy of the trinket

**Expected behaviour**: 

After using the trinket, the trinket should create another copy, and consume the current trinket equiped. If bags are full on this process, the trinket created should go into mailbox.
it SHOULD always have a charge and never below 1

[Carved Ogre Idol Butchered](https://youtu.be/gEQDfxvHkaA)

**Revision**: 
1593

**Comment by NatsumeLily** [comment]
Just to clarify. The only thing missing is spell 69777 (https://www.wowhead.com/spell=69777/create-carved-ogre-idol).

There shouldn't be any charges. It's no longer a trinket in Wotlk.

**Comment by Healweed** [comment]
Well this going to the void since with xferes this got cucked hard XD
