### ISSUE TITLE
[Hunter][Combat rating] Block

### ISSUE THREAD

**Issue by Kripp0** [Stormforge-gg/Bugtracker-Fordring#1610]
**Current behaviour**:
All ranged psychical attacks by the hunter have a chance to get blocked...
**Expected behaviour**: 
They should not.
''[Ranged](https://wowpedia.fandom.com/wiki/Ranged) attacks (that is, not [spells](https://wowpedia.fandom.com/wiki/Spell) but attacks like a hunter's  [[Auto Shot]](https://wowpedia.fandom.com/wiki/Auto_Shot)) use the same attack table as melee attacks, but with 0% parry, glance, or block chance for all rows.''
https://wowpedia.fandom.com/wiki/Attack_table

![WoWScrnShot_070922_145517](https://user-images.githubusercontent.com/36957911/178104532-99983eab-b9aa-40fb-8227-cc5c5b2f3b11.jpg)

**Revision**: 
1593.

**Comment by NatsumeLily** [comment]
Not a bug. You can block ranged attacks.

**Comment by Kripp0** [comment]
My attacks are blocked from the dummy/boss.

**Comment by NatsumeLily** [comment]
/sigh...Please look at old info for this expansion and patchs. 

https://wowpedia.fandom.com/wiki/Attack_table?oldid=2071465
![image](https://user-images.githubusercontent.com/15247730/178116701-07edb27e-340c-44b4-b6ff-a1ed50c77602.png)

https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/52471903
![image](https://user-images.githubusercontent.com/15247730/178116719-785fbced-b551-47ab-ad9d-e7f369a9b8b5.png)

You could also find more if you just googled...
