### ISSUE TITLE
DK gargoyle doesnt scale with armor and stamina and have zero aoe avoidance like pets

### ISSUE THREAD

**Issue by tsugha** [Stormforge-gg/Bugtracker-Fordring#1614]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**DK Gargoyle stamina/armor not scaling and zero aoe Avoidance**: 

**any small aoe kills it**:

**Stamina and armor shall scale just like hunter pets**: 

**Revision**:

**Comment by Cold-Martijn** [comment]
fixed in rev 1596
