### ISSUE TITLE
my 1000 gold did not get transferred

### ISSUE THREAD

**Issue by koubeex** [Stormforge-gg/Bugtracker-Fordring#1615]
**Description** : 

i used to have 1009 Gold but did not get transferred with my character ( Atheel ) to Fording
the gold somehow remained on Atlantis server.

**Current behavior**:
gold did not get transferred
**Expected behavior**: 
full transfer of gold at least the allowed 1000.
**Revision**:

**Comment by Godmatik** [comment]
First off - the character is not transferred, a copy is simply made and applied to the Wrath server.

Second - the snapshot of the characters on Atlantiss was done about a month ago by Emtec, so if you moved or earned that gold between then and now - that is why you don't have any.

If you still feel you are owed the gold, you can DM Emtec on Discord, but he can verify with the logs.
