### ISSUE TITLE
[Drop] Not able to loot Emblem of Heroism after Four Horsemen

### ISSUE THREAD

**Issue by owliepecks** [Stormforge-gg/Bugtracker-Fordring#1617]
**Description**:  Last night guild defeated the four horsemen, but we were not able to receive the emblem of heroism because the game said 'chest is already in use' even after the loot master closed out the loot table.

**Current behaviour**: Unable to loot emblem of heroism from chest after four horsemen, an error pops up saying chest is already in use and doesn't go away even if nobody is using the chest

**Expected behaviour**: Should be able to loot emblem of heroism from chest

**Revision**:

**Comment by Godmatik** [comment]
Bug occasionally occurs with any chest that contains badges - Malygos chest has similar issues
