### ISSUE TITLE
Xp boost disabled

### ISSUE THREAD

**Issue by BiscuitMandatory** [Stormforge-gg/Bugtracker-Fordring#1622]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After shutdown my xp boost from shop was disabled when the shop went down.
**Current behaviour**:
i do not get xp boost ingame
**Expected behaviour**: 
more experiance from mobs
**Revision**: 
enable shop and compensate the downtime

**Comment by Emtec** [comment]
Fixed, An announcement will be made a bit later
