### ISSUE TITLE
(Rogue) Killing Spree is bugged, doesn't attack as it should in AOE packs.

### ISSUE THREAD

**Issue by Tetrahydrx** [Stormforge-gg/Bugtracker-Fordring#1624]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
![KS 2](https://user-images.githubusercontent.com/107153005/178734604-af8e0aaa-3c40-4b99-8b61-327dcfb4d840.png)

**Description**: 
Killing Spree should be doing five attacks as the tooltip says. Unfortunately it bugs out on this server, especially on AoE packs with multiple mobs. I assume that this is linked to a range problem, because I have had a situation where I used KS on a flying Alliance player and it only did 1x "Attack" before bugging out and me just hanging in the air without dealing any damage. You can easily test this out by simply standing in front of the lvl 60 AoE pack of dummies in Orgrimmar and pressing Killing Spree, i will link my result here.
**Current behaviour**:
After jumping to another target, Killing spree does not deal any damage - making the Combat spec pretty much useless. Would be best to fix before Ulduar as many people will respec by then.
**Expected behaviour**: 
It should jump to other targets while dealing 5 Attacks, instead of only two for example.
**Revision**:

**Comment by Aithne99** [comment]
So is this Tauri core or ATS core?

**Comment by Tetrahydrx** [comment]
> So is this Tauri core or ATS core?

This bug occured on both Cores, though it seems to be a bit less frequent on the current core.

**Comment by Tetrahydrx** [comment]
The Screenshot I posted is from the Tauri Core

**Comment by Aithne99** [comment]
The screenshot you posted is completely useless, please record it on video or something.

**Comment by Tetrahydrx** [comment]
> The screenshot you posted is completely useless, please record it on video or something.

Sure, no problem.  https://tetraids.px.media/share/16578151580oGaiQwiOySU7H

**Comment by Tetrahydrx** [comment]
https://streamable.com/zyrd53 Here again in better quality
