### ISSUE TITLE
[Class][Talent]Death Knight, PPM/Proccrate of Killing Machine(51123) scuffed

### ISSUE THREAD

**Issue by Nihaobeachez** [Stormforge-gg/Bugtracker-Fordring#1625]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Currently Killing Machine Proccrate is underwhelming. It gives your Frost Strike and Howling Blast 100% Critchance, and Frost Strike is the Main Damage and Runic Power dropping Abiltity. Felt fine on old Core, not too much not too less. Did a 3 Minute Bossfight earlier and had like 4-5 Proccs, which is a huge decrease in DPS compared to before. I tested it only with Rank 5 tho, but technically Rank 5 should have the highest Proccrate. It kinda makes FDK unplayable right now.

**Current behaviour**: Killing Machine doesnt procc often enough. Wrong PPM/Proccrate ?

**Expected behaviour**: More Killing Machine proccs.
If the proc was called from any of the weapons, then within the next 0.25 seconds it can not be called again
2. If the main weapon has dealt normal or critical damage, it can trigger
3. If the left-hand weapon has dealt normal or critical damage, it can trigger
4.If the main weapon's weapon has dealt normal or critical damage, but has not triggered or missed the target, the left-hand weapon as well as normal or critical damage can can trigger
5.4.If the off weapon's weapon has dealt normal or critical damage, but has not triggered or missed the target, the main-hand weapon as well as normal or critical damage can can trigger

**Revision**: 1595? Unless Corechange changed the Rev

**Comment by Aithne99** [comment]
https://www.wowhead.com/wotlk/spell=51130/killing-machine#comments

I've checked the ATS numbers and they were 1/2/4/6/8

https://www.mmo-champion.com/threads/629399-killing-machine-proc

https://www.bluetracker.gg/wow/topic/us-en/14287259120-killing-machine-still-50-percent-proc/

Every single source I can find says that 1/2/3/4/5 are the correct values, which means our implementation is correct and it was bugged on ATS

**Comment by Cwiercpasiec** [comment]
It seems KM has proper PPM now, true. But it seems it just procs from main hand hits. Your link (https://www.mmo-champion.com/threads/629399-killing-machine-proc) contains some proofs it should proc from OH too. Here is possibly proof of this bug
![WoWScrnShot_071422_182341](https://user-images.githubusercontent.com/26198742/179033171-0df8cb70-eb73-448d-bb1e-fd23026c6a25.jpg)
: This is PPM of dual wield with nearly double attack speed (you can see attack speed is 1.33 and silent crusader's base speed is 2.5, I also had some haste proc from trinket)
And now for comparison I simply uneqipped OH:
![WoWScrnShot_071422_183300](https://user-images.githubusercontent.com/26198742/179033695-5f1f5778-37dc-4250-81a1-d54818aa5513.jpg)
 As you can see, PPM is higher without OH (more hits is why its higher, cause DW makes you miss 27% auto attacks). The difference would be even higher if I wouldn't drop Icy Talons form time to time, as I was getting bored.
