### ISSUE TITLE
[Spell][Deathknight] Obliterate low damage

### ISSUE THREAD

**Issue by Lethalzz** [Stormforge-gg/Bugtracker-Fordring#1627]
**Description**: Obliterate doing low damage with both hands after the last core swap/update

**Current behaviour**: Obliterate is not inheriting the correct AP values or wrong damage modifiers
**Expected behaviour**: the spell should do more damage than the current state especially the offhand

**Revision**: 1597

**Comment by Aithne99** [comment]
This is not NEARLY enough info. Are you looking at it with/without diseases?

**Comment by Aithne99** [comment]
Also, the offhand is calculated with exactly half of the base dmg and weapon dmg ratio of the mainhand, so with the same weapons, on average, it will deal half damage.

**Comment by Cold-Martijn** [comment]
I think this is a joke reference to "too many damages".
There was a huge double dip on the Crystalsong core which got fixed eventually.

**Comment by Lethalzz** [comment]
> This is not NEARLY enough info. Are you looking at it with/without diseases?
i did with diseases i even hit 4k crit total with both hands with diseases and trinket procs with nearly 6k attack power .

**Comment by Aithne99** [comment]
I think this report is a "comparative wasntlikethisonats", improper testing, etc.

https://wowpedia.fandom.com/wiki/Normalization
Read this, ask any question you want on discord or anywhere, and then let's discuss this again, because the damage you're describing sounds perfectly reasonable.
