### ISSUE TITLE
[Call Pet][Hunter] Internal Pet Error

### ISSUE THREAD

**Issue by PDmitriy** [Stormforge-gg/Bugtracker-Fordring#1631]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Summoning pet results in "Internal Pet Error". Pet is Earthborer from Ragefire Chasm. Trying to tame new pet results in "You have too many pets already".

For reproducibility: IGN Incognito, Horde

https://wotlkdb.com/?npc=11320

**Current behaviour**: Pet does not summon.

**Expected behaviour**: Pet should be summoned by Call Pet spell.

**Revision**: 
![pet_issue](https://user-images.githubusercontent.com/7281912/178771434-b509f5a3-a7f7-4d3f-9d7d-4572d89daa98.PNG)

**Comment by Aithne99** [comment]
Needs restart
