### ISSUE TITLE
[Anub'Rekhan] Often resets during Locust Swarm

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#1632]
**Description**:Anub'Rekhan, a boss located within the Arachnid Quarter of Naxxramas, seems to have some resetting issues:

- During the fight, he will cast Locust Swarm. 
- During Locust Swarm, he does large amounts of damage to people around him, but is slow. 
- A common strategy for raids is to kite the boss around the outside of the room during Locust Swarm. 

**Current Behavior**:  Often, during his Locust Swarm cast, Anub'Rekhan will reset. 

**Expected Behavior**: Anub'Rekhan should not reset if people are still in combat with the boss (i.e., Ranged DPS or the Main Tank).

**Revision**: Unable to determine at this time (.server revision does not work)

**Video Evidence of Current Behavior:**

- [Start of Locust Swarm](https://youtu.be/OZG3UWQTI88?t=1008)
- [Moment Anub'Rehkan first resets](https://youtu.be/OZG3UWQTI88?t=1019).  (Addon with Blue Square in center left indicates moment he resets, when it disspaears)
- [Start of second Locust Swarm](https://youtu.be/OZG3UWQTI88?t=1190)
- [Moment Anub'Rehkan resets a second time](https://youtu.be/OZG3UWQTI88?t=1199). Be warned, player rage was vocalized after.

**Comment by Cold-Martijn** [comment]
most probably encounter boundaries being too tight.

**Comment by Aithne99** [comment]
You did try to pull him into a retarded location tbf.

**Comment by Aithne99** [comment]
Slightly expanded the encounter boundaries, but try not to be absolutely retarded still. Encounter boundaries are there for a reason, after all.
