### ISSUE TITLE
Lightweave Embroidery bug

### ISSUE THREAD

**Issue by Nyankat1** [Stormforge-gg/Bugtracker-Fordring#1634]
https://wowwiki-archive.fandom.com/wiki/Lightweave_Embroidery

**Description**: 

The lightweave embroidery enchant on the cloak from Tailoring doesnt work anymore when casting hots, only from direct healing spells. 

**Current behaviour**:
Procs only from Direct healing spells

**Expected behaviour**: 
Should proc from any spell cast.

**Revision**: 

Please look into it.

**Comment by Aithne99** [comment]
#1620
