### ISSUE TITLE
[Naxxramas][Tuning] Anub'rekhan Melee Damage

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1642]
**Description**: Switching to Tauri Core has reduced the melee damage of Anub'rekhan by about 20%, and removed his Trash ability. This makes the encounter a lot easier than it was before.

**Current behaviour**: Anub'rekhan only does gentle slaps

**Expected behaviour**: Anub'rekhan does bitch slaps

**Revision**: TC, 20220713

**Comment by Aithne99** [comment]
#1646

I cannot see any evidence of Anub'rekhan having an ability called Trash/Thrash in ATS core, and I cannot see anything referring to such an ability from retail sources.
