### ISSUE TITLE
[Naxxramas][Tuning] Faerlina does less damage than before core switch

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1644]
**Description**: Faerlina does about 20% less damage and swings 20% slower than before the core change. This makes her fight much easier.

**Current behaviour**: Fearlina is giving love taps

**Expected behaviour**: Fearlina should be giving boxer punches

**Revision**: TC, 20220713

**Comment by Aithne99** [comment]
#1625
