### ISSUE TITLE
Death Knight Killing Machine

### ISSUE THREAD

**Issue by MartinBrandstrup** [Stormforge-gg/Bugtracker-Fordring#1645]
[//]: # ([Talent][Class] Killing Machine)

**Description**: 
I do not have any hard stats on this, but it feels like this procs infinitely less than it did pre-core swap.

**Current behaviour**:
Very rarely procs. Speculation that the amount of talent points invested has no influence.

**Expected behaviour**: 
More procs.

**Comment by Aithne99** [comment]
#1625
