### ISSUE TITLE
Death Knight Rune of Cinderglacier

### ISSUE THREAD

**Issue by MartinBrandstrup** [Stormforge-gg/Bugtracker-Fordring#1649]
[//]: # ([Spell][Class] Rune of Cinderglacier)

**Description**: 
Cinderglacier is currently working different than it did pre-core swap.
I have done no research into retail behaviour however.

**Current behaviour**:
Regardless of circumstances only one stack is consumed on using a frost/shadow ability.

**Previous Core behaviour**: 
Using any ability that would consume it removed both stacks if
1) the ability hit multiple targets (Blood Boil/Howling Blast)
2) the ability hits with two weapons (Frost DK Frost Strike/Obliterate)

**Comment by Aithne99** [comment]
Ours is the correct behavior. Any "your next ability deals increased damage" type buff applies to all instances of damage from that single cast.
