### ISSUE TITLE
[NPC] Terokkar Forest

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Fordring#165]
**Description**: https://tbc.wowhead.com/npc=18467/dreadfang-widow
![image](https://user-images.githubusercontent.com/62518101/162828738-cbf8682f-4914-4d49-ac08-0e88af8feeed.png)

**Current behaviour**: under the ground

----------
**Description**: 
https://tbc.wowhead.com/npc=21245/bonechewer-marauder
https://tbc.wowhead.com/npc=21244/bonechewer-messenger

![image](https://user-images.githubusercontent.com/62518101/162831461-4a8beb42-02ce-4aa7-9a0a-20ba36f520b4.png)

**Current behaviour**:  they are motionless, they do not patrol

**Expected behaviour**:  
![image](https://user-images.githubusercontent.com/62518101/162831553-c182547e-0972-48c2-b34b-c7a19006f648.png)
![image](https://user-images.githubusercontent.com/62518101/162832191-28cd2614-f5f3-4ee8-958a-56db578473d3.png)

-----------
**Description**:  https://tbc.wowhead.com/npc=18595/warped-peon
![aaaaaaa](https://user-images.githubusercontent.com/62518101/162832615-ed075bb4-8672-41ca-8f9a-a0cc56c718f0.png)
![image](https://user-images.githubusercontent.com/62518101/162832947-9360f887-2533-4055-bc2f-62d07f7f3e1d.png)

---------
**Description**:  https://tbc.wowhead.com/npc=18595/warped-peon

**Current behaviour**: many peons do not work 
![qqqqqq](https://user-images.githubusercontent.com/62518101/162834525-c27ecfb0-7fd0-4b61-9e26-0696743ba361.png)

**Expected behaviour**:  
https://youtu.be/GnsQ2tyhQac?t=45

-------

**Description**: https://fr.tbc.wowhead.com/npc=18686/auspice-funeste-jurim
![image](https://user-images.githubusercontent.com/62518101/162834757-08e09c15-ceea-48e6-9e99-c088144c4665.png)

**Current behaviour**: moving too fast

-------
**Description**:  https://tbc.wowhead.com/npc=16769/firewing-warlock
![image](https://user-images.githubusercontent.com/62518101/162835351-46b3661e-a074-4aa4-9ce2-a5856581c7ae.png)

**Current behaviour**: Firewing Warlocks does not make an incantation

**Expected behaviour**:  
https://youtu.be/QdIOe9nzDdg?t=24

-------

**Description**: https://tbc.wowhead.com/npc=18477/timber-worg-alpha
![image](https://user-images.githubusercontent.com/62518101/162836112-ee19b688-7ff5-4fe8-8c4a-ae72994cbc49.png)

**Current behaviour**:  under the ground

**Comment by therealCrysis** [comment]
Confirmed in rev 1165
