### ISSUE TITLE
[Naxxramas][Boss] Noth the Plaguebringer is generating 4M threat after blink

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1651]
**Description**: After using his blink and resetting all aggro, Noth will sometimes give a random player in the raid 4 million threat. This trivializes the tanking aspect, as he can be taunted and the tank now has a 4 million threat lead.

**Current behaviour**: Noth really hates someone

**Expected behaviour**: Noth should hate everyone equally.

**Revision**: TC, 20220713

**Comment by Godmatik** [comment]
Was it perhaps a mage that just used mirror image?

**Comment by nikko8085** [comment]
This happened to mages 2 times, and to a disc priest once. I therefore do not think it is tied to Mirror Images.

**Comment by Godmatik** [comment]
Well I very specifically recall a bug on stock where a mage will get exactly 4 million health on a boss after mirror image ends.

**Comment by nikko8085** [comment]
Unless discipline priests have learned Mirror Image, there must be something else causing it as well.
https://www.youtube.com/watch?v=vSJny3crn84&ab_channel=Mateusz
Disc priest gets 4M threat at 2:56

**Comment by nikko8085** [comment]
I had this happen in Gun'drak on Eck for another priest, when Fade expired.

Likely if Fade is up and a threat reset happens then the priest will get 4M threat when Fade expires

**Comment by Aithne99** [comment]
All of these fixed w/ next restart.
