### ISSUE TITLE
[Naxxramas][Boss] Loatheb has become a wet noodle

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1654]
**Description**: Loatheb used to be a challenge before the core switch. He did 100% more melee damage, and attacked every 1.5s. Now he does half the damage, and attacks every 2s (before any attack speed reductions). This trivializes the fight, as a solo tank won't drop below 50% health in the no-healing window

**Current behaviour**: Loatheb hits like a wet noodle

**Expected behaviour**: Loatheb should hit a lot harder

**Revision**: TC, 20220713

**Comment by Aithne99** [comment]
#1646 explains the "100% more" (the thing is, there is no sane "baseline" to compare it to, as there is no easy way to determine how much damage each mob actually dealt on retail). His base attack time currently appears to be 1.25 seconds, not 2

**Comment by nikko8085** [comment]
Alright, the log site was down yesterday, but now we have logs up, so I'll provide some more tangible numbers.
Last reset, Loatheb lived for 4:14, and in that time managed to perform 211 auto attacks. This gives an attack speed of 1.2s, which is after all attack speed slowing debuffs.
This reset he lived for 4:53, and managed to perform 172 auto attacks. This gives an attack speed of 1.7, after all attack speed slowing debuffs. This means the core changed reduced his attack speed by 41% (1.7/1.2). With the logs down, the 2s in the original post were eyeballed, mostly based on it feeling a lot slower than previously.
Of his 211 auto attacks last reset, 120 were directed at Deathnaitt, and 44 managed to hit, dealing an average 4.3k damage.
Of his 172 auto attacks this reset, 172 were directed at Deathnaitt, and 60 managed to hit, dealing an average of 2k damage. These numbers are influenced by the uptime of Power Word: Shield and other defensive cooldowns, so take it with a grain of salt.
This means he has lost 53% damage and 41% attack speed, leading to a total auto attack damage reduction of 78%.
This is what I mean when I say Loatheb has turned into a wet noodle, but if tuning this is not planned, then I won't pursue the issue further.
