### ISSUE TITLE
[Naxxramas][Boss] Loatheb not always casting his healing suppression aura

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1655]
**Description**: Loatheb at one interval didn't cast his healing prevention aura. I do not know what caused him to miss the cast.

**Current behaviour**: Loatheb sometimes misses the no healing aura.

**Expected behaviour**: He should not forget to use his main mechanic.

**Revision**: TC, 20220713

**Comment by Aithne99** [comment]
Possibly fixed, if not, we'll need a video if this still persists after a restart.
