### ISSUE TITLE
[Naxxramas][Boss] Kel'thuzad Frost Blast does too low damage

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1658]
**Description**: The Kel'thuzad Frost Blast damage is too low, it is survivable without healing. I'm unsure if partial resists with Frost Resistance is causing it, or if the damage is just too low.

**Current behaviour**: Kel'thuzads Frost Blast damage is too low

**Expected behaviour**: Kel'thuzads Frost Blast damage should be higher

**Revision**: TC, 20220713

**Comment by Aithne99** [comment]
26% of the target's max health, should go through resists from what I can tell, but there are certain fake damage reductions which will apply (Astral Shift is one of those spells, it is not actually damage reduction, but an absorb).
