### ISSUE TITLE
[Eye of Eternity][Boss] Deep Breath can happen in Phase 3

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1659]
**Description**: Malygos' Deep Breath ability can happen during phase 3 if the phase transition happens while he's moving in to breathe. This will in turn hit all the drakes for quite a bit of damage.
Additionally, his positioning when transitioning to P3 was high up in the air, and he did not fly down as part of the RP event that's supposed to happen.

There was also no RP event with the platform breaking and the raid falling down to be caught on drakes, the players were just immediately on the drakes on the phase transition.

**Current behaviour**: Deep breath can happen during phase 3

**Expected behaviour**: Deep breath should not happen during phase 3

**Revision**: TC, 20220713

**Comment by Aithne99** [comment]
#1638
