### ISSUE TITLE
[Obsidian Sanctum][Boss] Drake health is too high

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1662]
**Description**: The HP of the drakes is around 7M, compared to the 2.8M they had in retail, and 4.5M they had before the core merge. This means they have 250% health compared to retail.

**Current behaviour**: The drakes are very beefy.

**Expected behaviour**: They should be a little less beefy.

**Revision**: TC 20220713

**Comment by Aithne99** [comment]
Can't reproduce. I did change how the raidbuff works, and I did fix Vesperon's low healthmod on 25m, but right now they have 5.6 million health for me, which is what is intended.

**Comment by nikko8085** [comment]
The 7M and 4.5M is after Sartharion is engaged and they get his HP buff.
Are you sure it's intended? That's a very high HP value, and I doubt any guild will be able to down OS3D on the server.
Looking forward to the challenge though!

**Comment by Aithne99** [comment]
For now it's intended, yes.
