### ISSUE TITLE
[Obsidian Sanctum][Boss] Twilight Zone damage is very high

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1667]
**Description**: The Twilight Zone (when entering the portals) have a dot component to staying in the portal. This dot does a lot more damage than what is healable (5k per 0.5-1s, spell ID 57874). It should probably have its damage or frequency reduced by a factor 2.

**Current behaviour**: The Twilight Zone is a death zone to the point where it's better to just avoid it than entering.

**Expected behaviour**: The Twilight Zone shouldn't kill anybody who enters.

**Revision**: TC 20220713

**Comment by Aithne99** [comment]
Exact mob/spell name?

**Comment by MartinBrandstrup** [comment]
It appears to be Sartharion Twilight Controller if I remember correctly and the spell name is Twilight Shift.
