### ISSUE TITLE
[Obsidian Sanctum][Boss] The encounter bugs, remaining in combat if a person exits the raid while a portal is up

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1668]
**Description**: If everybody leaves the raid while a portal is up, Sartharion will reset but the portal and any adds will remain. Only one person can enter the raid (without getting in combat) while everybody else will get a message "Cannot enter while an encounter is in progress".

**Current behaviour**: When everybody leaves the raid, the encounter does not reset.

**Expected behaviour**: When everybody leaves the raid, the encounter should reset.

**Revision**: TC, 20220713

**Comment by MartinBrandstrup** [comment]
What I observed under this incident was that only one person was able to be inside the raid at a time, watching adds and a portal but no boss respawning. Anybody else trying to enter got a "This map cannot be loaded" error message and gets teleported to the top of Wyrmrest.

**Comment by Aithne99** [comment]
I think I might have fixed this? But reply when it happens again. Try to record on video too pls...

**Comment by Aithne99** [comment]
No further complaints so I assume I did indeed fix the problem.
