### ISSUE TITLE
[NPC]Naxxramas - Heigan the Unclean - Teleport Platform Plague Cloud is instant cast

### ISSUE THREAD

**Issue by fondlez** [Stormforge-gg/Bugtracker-Fordring#1671]
**Description**: Heigan the Unclean in Naxxramas will instantly apply some version of Plague Cloud that kills anyone on the platform as soon as he teleports.

**Current behaviour**: Platform Plague Cloud damage is instantly applied immediately after Heigan teleports to the platform. This damage will instantly kill anyone. Neither behavior is Blizzlike.

**Expected behaviour**: As soon as Heigan teleports a system message should occur of "Heigan the Unclean teleports and begins to chanel a spell!". Any players on the platform need to move greater than 20y away otherwise after 3s they will take damage from Plague Cloud. 

As far as I know it is possible to survive one tick of the damage with sufficient non-tank HP. However, I have not researched the details of this in wotlk.

**Revision**: unknown. Previous server revision command no longer exists on live.

**Comment by Aithne99** [comment]
https://www.youtube.com/watch?v=VUlliMso570&t=165s

You can see him turn green instantly. Him instantly turning green means damage will be applied after 2 seconds - which is currently correct on the server.

**Comment by fondlez** [comment]
Your very own evidence shows clearly every single ranged on that platform remained very much alive as Heigan teleported right on top of them. The evidence also shows a druid and holy paladin lost at most 20% hp on teleport then nothing for 3s (02:44 to 02:47). In fact, at least one of the ranged still seemed within 20y of him on the third second.

So, unless someone has already changed the new core since my original report, the server does nothing similar to the above. Anyone on the platform when Heigan teleports will **instantly die**.

Do I really have to open another issue ticket when the evidence is right in front of you and well within the experience of anyone who has ever played any version of Blizzard's Naxxramas?
