### ISSUE TITLE
[Core][Loot]Recipes - Jewelcrafting recipe drops are BoP when they should not be BoP

### ISSUE THREAD

**Issue by fondlez** [Stormforge-gg/Bugtracker-Fordring#1675]
**Description**: As seen via the Random Dungeon Finder, Jewelcrafting recipes are BoP when they should not be BoP. One example is [Design: Thundering Skyflare Diamond], but there were others.

**Current behaviour**: as above.

**Expected behaviour**: jewelcrafting recipe drops should have their correct loot bind.

**Comment by Aithne99** [comment]
1. The Thundering Skyflare diamond recipe is NOT BoP.
2. I have checked other Skyflare diamond recipes, and those that are currently BoP look to be BoP on Classic PTR too. https://www.wowhead.com/wotlk/item=41705/design-effulgent-skyflare-diamond Most of them also still exist on retail right now, and are still BoP to this day (and on retail, this data is stored in the client, not serverside).
