### ISSUE TITLE
[Core] Friends list & /who

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1680]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You can invite people to group from the other faction now! And add them to friends' list! Great!

But they don't ever appear as online in your friends list. And you can't /who them. So. Uh. Could we get that fixed?

**Comment by Aithne99** [comment]
Maybe :D

**Comment by Vishiswaz** [comment]
=O
