### ISSUE TITLE
Shadowfiend dont give mana back as it should

### ISSUE THREAD

**Issue by BiscuitMandatory** [Stormforge-gg/Bugtracker-Fordring#1683]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
shadowfiend dont give as much mana as intended
**Current behaviour**:
gives me as a disco priest around 10% or counted 4 shields on players in dung.
**Expected behaviour**: 
atleast 30-50% mana back.

**Comment by Aithne99** [comment]
Attacked 10 times for me for 421 mana each when I had 8428 mana. That is 5% * 10 = 50%, just make sure that your pet doesn't die or deaggro.
