### ISSUE TITLE
[Shaman] Pet's AoE Avoidance

### ISSUE THREAD

**Issue by LautaroJMolina** [Stormforge-gg/Bugtracker-Fordring#1684]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Shaman pets, both spirit wolves and fire elemental currently don't seem to have aoe avoidance.

**Current behaviour**:
During raids both my wolves and fire elemental die to mechanics and aoe effects which warlocks and hunters pets survive.
Generally, my pets die way more often than theirs (and wolves are not taunting or pulling aggro).
Edit: Also, the fire elemental is the one dying, not the totem.

**Expected behaviour**: 
After patch 3.1, spirit wolves and the fire elemental, along with some other pets/guardians, should have aoe avoidance like hunter and warlock pets. They shouldn't be dying so frequently to mechanics.
https://wowpedia.fandom.com/wiki/Patch_3.1.0#General_2

**Comment by Aithne99** [comment]
Both of them seem to have avoidance for me.
![WoWScrnShot_071422_073530](https://user-images.githubusercontent.com/35006261/178907471-fa4d4a0d-11d0-4612-9f1a-6cbb9e4915b9.jpg)

**Comment by LautaroJMolina** [comment]
Sorry for dumping so many images.
I see from that screenshot that they have the passive, so I looked through some logs to make sure I wasn't imagining all this.
Many of these damage values seem weird.
Zym is demo warlock and Exorcista is affliction.
Snicklefritz frost dk and Arsinick UH.
Maybe it's just some hidden resistance I don't know about?, wouldn't be surprising.
These images are all from a couple hours ago.

![log1](https://user-images.githubusercontent.com/64675765/178917252-7cd9108d-a684-440a-99c6-a6757cca34c1.png)

![log2](https://user-images.githubusercontent.com/64675765/178917260-fe46fd3c-05cd-479b-bc39-92add3a8decb.png)

![log3](https://user-images.githubusercontent.com/64675765/178917263-1624f906-8288-438f-90e8-669f9344d85c.png)

![log4](https://user-images.githubusercontent.com/64675765/178917266-1353665c-dea2-4bae-9808-1f9114c3e685.png)

![log5](https://user-images.githubusercontent.com/64675765/178917268-de020e3a-1d1f-4753-9ffc-d71b0939c728.png)

![log6](https://user-images.githubusercontent.com/64675765/178917271-1a8becfc-0ade-4897-8915-1e55ac5bedb7.png)

The complete logs:
Sarth: https://legacyplayers.com/viewer/31517/event_log/to_actor

Grobb: https://legacyplayers.com/viewer/31518/event_log/to_actor

**Comment by LautaroJMolina** [comment]
In game logs with aoe spells hitting my pets for the same damage as me. Unless any of these don't count for avoidance or something.

![combatlog1](https://user-images.githubusercontent.com/64675765/179051209-e24fbd6c-b738-47af-b93e-aa8d53e25e39.jpg)
![combatlog2](https://user-images.githubusercontent.com/64675765/179051214-f13c3801-a30c-4353-8bfb-9169483bf285.jpg)
