### ISSUE TITLE
Wintrade in 1v1 arena

### ISSUE THREAD

**Issue by BiscuitMandatory** [Stormforge-gg/Bugtracker-Fordring#1686]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Characters named Botakk, Oldfather, Lichkiing was win tradeing in 1v1 arena at 5:30 am 14/7
**Current behaviour**:
just que and leave the 1v1
**Expected behaviour**: 
GET BANNED!

**Comment by Aithne99** [comment]
This is not a customer support platform, find a gm

**Comment by BiscuitMandatory** [comment]
HAHAHA if they only awnserd
