### ISSUE TITLE
[CORE] BackDraft vs Rain of Fire 

### ISSUE THREAD

**Issue by haephaistoss** [Stormforge-gg/Bugtracker-Fordring#1688]
Description: Backdraft should affect rain of fire channeling time

Current behaviour: Rain of Fire channeling time isn't affected by backdraft, only gcd.

Expected behaviour: Rain of Fire channeling time isn't affected by backdraft, only gcd.

Revision:

**Comment by NatsumeLily** [comment]
Not a bug. It shouldn't affect the channeling time of rain of fire. 

https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire

https://www.wowhead.com/forums/topic/two-odd-questions-about-destro-111336

https://github.com/SunwellTracker/issues/issues/2809

**Comment by Aithne99** [comment]
Casting time is not, and was not ever the same as channeling time.
