### ISSUE TITLE
[NPC] Risen Drakkari Soulmage 

### ISSUE THREAD

**Issue by Cheesedip** [Stormforge-gg/Bugtracker-Fordring#1694]
**Description**: 
NPC casts heal in ~0.5 seconds. 
According to: https://wowpedia.fandom.com/wiki/Risen_Drakkari_Soulmage this should be 2.5 seconds.

**Current behaviour**:
NPC casts heal in ~0.5 seconds. 

**Expected behaviour**: 
NPC casts heal in ~2.5 seconds.

**Comment by Aithne99** [comment]
https://www.youtube.com/watch?v=iyFFxdnCFlM&t=1m50s

Mind your sources. Wowpedia just links to the priest Heal ability, not the actual spell used by these mobs.

**Comment by Cheesedip** [comment]
Okay, didn't know thanks : )

**Comment by Cheesedip** [comment]
So warmane is like the go-to for verifying how things intended to work? I've been scrolling through youtube 13 year old videos but can't seem to find anything.
