### ISSUE TITLE
[Items] Inscription Pigments

### ISSUE THREAD

**Issue by MartinBrandstrup** [Stormforge-gg/Bugtracker-Fordring#1697]
**Description**: 
Currently only replicated this with northrend pigments, but they are unable to be mailed to other characters.

**Current behaviour**:
Trying to put a pigment in a mailbox gives the message "You cannot mail items with a limited duration".

**Expected behaviour**: 
Obviously there should be no reason for pigments to have a limited duration and you should be able to mail them.

**Comment by Aithne99** [comment]
Might need a cache clear after restart.
