### ISSUE TITLE
[Core] .spellqueuewindow command only works for channeled spells

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1699]
**Description**: 
You cannot queue hard cast spells (flash heal, greater heal, prayer of healing) even with this fancy new command, only channels (penance, mind flay) and instants (renew, power infusion, pain suppression) are affected by the command.
**Current behaviour**: 
Hard cast spells cannot be queued
**Expected behaviour**: 
You should be able to queue hard cast spells

**Comment by Kripp0** [comment]
True,also the delay is huge for channeling spells(like 1 sec).

**Comment by Weuyn** [comment]
Seems to have been fixed by relogging a few times

**Comment by Cold-Martijn** [comment]
Try to play a bit with the spellqueue command if you have troubles with this.
As you mentioned relogging a couple of times fixed the issue, i will close the report.
