### ISSUE TITLE
[Talent][Death Knight] Missing 2 talent points after core change.

### ISSUE THREAD

**Issue by kkashipl** [Stormforge-gg/Bugtracker-Fordring#1719]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Didn't played on this champ for more than week, today after i logged in my talents were reseted and i realised i have only 69 to spent instead of 71. After trainer reset still have 69 talents to spent. Name of character is Siusiak

**Current behaviour**: I have 69 talent points to spent on 80lv.

**Expected behaviour**: On 80 lvl should have 71 talents.

**Comment by Aithne99** [comment]
Should be fixed for all affected characters, if it isn't for some reason, just find a high ranking GM.
