### ISSUE TITLE
[NPC] Duronn the Runewrought, respawn timer

### ISSUE THREAD

**Issue by Lmdezorn** [Stormforge-gg/Bugtracker-Fordring#1729]
**Description**: The respawn timer of Duronn the Runewrought (npc=30353) seems far too long (at least 10 minutes).

**Current behaviour**: As stated in the description, the timer of this NPC seems far too long, especially compared to the respawn timers of Eisenfaust (npc=30341) and Halefnir the Windborn (npc=30376) who are the other mobs to kill in the quest "Locken's Lackeys" (quest=13035).

I suspect that this particular behavior is linked to the fix of https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1206#issue-1267244397 where his respawn timer was too fast.

**Expected behaviour**: I would expect his respawn timer to be in the same range than Eisenfaust and Halefnir the Windborn, which essentially a few minutes max.

**Comment by Lmdezorn** [comment]
To be completely honest, I haven't seen him yet (which would imply a respawn timer of a few tens of minutes!) so there's also the possibility that he isn't at the right place, but given the SS in the https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1206#issue-1267244397 report, I feel like that's unlikely.

**Comment by Lmdezorn** [comment]
Ok, now I've seen him: he's at the right place, so that leaves the duration of the respawn timer then.

**Comment by Lmdezorn** [comment]
Ok, after a few tests, I'm a bit confused: the respawn timer varies greatly, between less than 1 min to 5 min for the different tries I've done til now.

**Comment by Lmdezorn** [comment]
From the tests I've been doing, it seems that Duronn respawns shortly after his corpse vanishes (a matter of  seconds), which took around 5 minutes when I just waited things to happen "naturally". The times when the respawn timer was shorter seem to be related to an engineer skinning Duronn.

But I can't reproduce the conditions that made his corpse disappear but blocked his respawn...

**Comment by Cold-Martijn** [comment]
The respawn time is tied to loot. If there is loot in the corpse (in this case probably engineering loot) it will despawn much slower. This works for all NPC's in the open world :)
Unfortunately this is not something that can be fixed at this moment, so i will closr this report as "not planned".
