### ISSUE TITLE
[NPC]  High Chieftain Cliffwalker

### ISSUE THREAD

**Issue by RadisaMarkovic** [Stormforge-gg/Bugtracker-Fordring#1730]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:
Can't continue quest story line NPC High Chieftain Cliffwalker at Cliffwalker Post

**Current behaviour**:
He is teleporting high up in skies and moving back bellow the ground
![image](https://user-images.githubusercontent.com/19760844/179171793-dcd8f554-da69-41af-ae78-372b0c596080.png)

**Expected behaviour**: To accept quest from him

**Comment by Cold-Martijn** [comment]
Wrong bugtracker, this NPC is added in Cataclysm. You probably meant to make a bugreport for the Mists of Pandaria server. You can do so here: https://github.com/Stormforge-gg/Bugtracker-Mistblade/issues
