### ISSUE TITLE
[Quest][Zul'Drak] Infiltrating Voltarus

### ISSUE THREAD

**Issue by VirtualReign** [Stormforge-gg/Bugtracker-Fordring#1738]
After completing Drakuru's task and summoning Stefan Vadu to turn in the quest, you are unable to turn it in, despite it being marked as complete in the quest log.

**Comment by Cold-Martijn** [comment]
Are you able to turn it in to Stefan Vadu in the camp? If yes, still a bug but with workaround.

**Comment by VirtualReign** [comment]
Can't be turned in at the camp either.

**Comment by karserasl** [comment]
Things that worked perfectly on previous core.
Done the whole chain-quest and the pet in last part was working correctly. 1st time i saw it correct in any server

**Comment by Aithne99** [comment]
Can't reproduce. Got a screenshot or something?

**Comment by VirtualReign** [comment]
I think it was due to the transition to the new core, i started it on the old one, abandoning the quest and doing it again fixed it. 
I'll close this because it seems others were able to complete it with no issues bar the missing horn.
