### ISSUE TITLE
Wintergrasp win

### ISSUE THREAD

**Issue by Cold-Martijn** [Stormforge-gg/Bugtracker-Fordring#1739]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Since Nihao-retard doesn't care to report things anymore, but only complains.
Wintergrasp can be won instantly by logging out a character in the "vault". Log in when the battle starts and click the big orb.

**Expected behaviour**: 
Upon login during a WG battle, you should be teleported out instantly (to HS location for example).

**Comment by Vishiswaz** [comment]
Also, make it so the orb is not clickable until the fortress door is destroyed. This is what was done on the previous core, worked great.

**Comment by NatsumeLily** [comment]
If this can be done, then you can just texture glitch to instantly win every time. 
The orb shouldn't be interactable until the fortress door is destoryed, like Vishiswaz said. This would be Blizzlike. 

**Edit:** The only bug here is the orb not being locked behind the fortress doors destruction. Logging out in the room and not being teleported out when you log in is Blizzlike. 

https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/51627117?page=1
![image](https://user-images.githubusercontent.com/15247730/179300991-8fb4d5c2-fc7f-4167-b57e-d62a940f06ec.png)

**Comment by Aithne99** [comment]
Can't reproduce, upon start, the Titan Relic is set to "not selectable" when the fortress door is rebuilt (by the fortress door itself), and isn't clickable until the fortress door is destroyed.
