### ISSUE TITLE
[Quest][Zul'Drak] Infiltrating Voltarus

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1754]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The item provided for this quest, Stefan's Horn, should NOT disappear when handing this quest in. It is used for quick turn-ins for the rest of the quests in this chain. Players usually manually delete it after finishing the chain. There is no other way to get the horn, so with the way things currently are, once you hand in this quest, you have to walk all the way to Ebon Watch to hand in the rest of the quests in this chain. Very annoying.

**Comment by VirtualReign** [comment]
I hadn't even managed to turn in the quest:
[Ticket 1738](https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1738)

**Comment by Vishiswaz** [comment]
You have to walk all the way back to Ebon Watch.

**Comment by VirtualReign** [comment]
That did not work for me either.

**Comment by Vishiswaz** [comment]
Abandon and retake it, then do the quest

**Comment by Vishiswaz** [comment]
Only other thing I can think of is clearing your cache
