### ISSUE TITLE
[NPC][Dalaran] Jean Pierre Poulain

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#1756]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This NPC should not be here until at least 3.1. Possibly 3.2. Definitely not 3.0.

**Comment by netbean2** [comment]
https://wowpedia.fandom.com/wiki/Jean_Pierre_Poulain => says patch 3.1
