### ISSUE TITLE
In game Equipment manager unable to save new gear set

### ISSUE THREAD

**Issue by JaceEverwood** [Stormforge-gg/Bugtracker-Fordring#1763]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
https://fr.classic.wowhead.com/blue-tracker/topic/us/equipment-manager-set-not-saving-45540
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
after u create a new gear set in the equipment manager UI. it will get erased after logging out. similar to this Wowhead description:
https://fr.classic.wowhead.com/blue-tracker/topic/us/equipment-manager-set-not-saving-45540

**Current behaviour**:
After creating and hitting "save" for a new gear set in the equipment manager. it won't properly save. it will be erased after each logout.

**Expected behaviour**: 
it should save the new gear setup once the end user clicks "save". even after log out

**Comment by Aithne99** [comment]
Fix is live.
