### ISSUE TITLE
Frenzyheart Tribe - Sholazar Basin - No Dailys

### ISSUE THREAD

**Issue by Md-Knox** [Stormforge-gg/Bugtracker-Fordring#1777]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The Frenzyheart Tribe in Sholazar Basin are just not giving daily I guess if I redid the quest to pick sides would open them up but I would lose my rep with them which defeats the points.

**Current behaviour**:There are no daily quests.

**Expected behaviour**: There should be daily quests.

**Comment by Aithne99** [comment]
Character name?

**Comment by Md-Knox** [comment]
Andy

**Comment by Aithne99** [comment]
Find a GM and ask for http://wotlk-shoot-new.tauri.hu/?quest=12693
