### ISSUE TITLE
[World NPC's] Leaving Combat with Flying Mount when leaving ground!

### ISSUE THREAD

**Issue by PhobiaStormforged** [Stormforge-gg/Bugtracker-Fordring#1790]
Issue: World NPC's are leaving combat as soon as player leaves ground with it's flying mount.

Expected Behaviour: World NPC's should not leave combat when player leaves ground with it's flying mount but should follow player to its designed range for leaving combat!

**Comment by Vishiswaz** [comment]
https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1681

Already reported
