### ISSUE TITLE
[Talent][Death Knight] Rime + Chill of the Grave

### ISSUE THREAD

**Issue by MartinBrandstrup** [Stormforge-gg/Bugtracker-Fordring#1802]
**Description**: 
Howling Blasts cast with the Rime proc generates no runic power aside from whatever you gain from Chill of the Grave.

**Current behaviour**:
Howling Blasts cast with the Rime proc generates no runic power aside from whatever you gain from Chill of the Grave.

**Expected behaviour**: 
It is supposed to generate runic power as any other Howling Blast regardless of not spending runes.

**Comment by NatsumeLily** [comment]
Early patch, but sounds correct so far. 
https://www.wowhead.com/spell=59057/rime#comments
![image](https://user-images.githubusercontent.com/15247730/179429819-fb6ab150-3c35-489c-a605-2f7848aeaf75.png)

**Comment by Aithne99** [comment]
It still didn't in later expansions.
