### ISSUE TITLE
[NPC] Icecrown

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Fordring#181]
**Description**:  https://www.wowhead.com/npc=33687/chillmaw
![image](https://user-images.githubusercontent.com/62518101/163018003-9a6e2bc0-f104-485e-ae80-900e227c9752.png)

**Current behaviour**: 
he goes too much into the ground during the fight

**Expected behaviour**: 
https://youtu.be/S78zBtynyhc?t=12

------
**Description**: https://www.wowhead.com/npc=31139/pustulent-horror
![cccc](https://user-images.githubusercontent.com/62518101/163019131-57e524d1-c8f9-4f9b-88f6-57e0ca7c07ec.png)

![aaaaaaaa](https://user-images.githubusercontent.com/62518101/163018982-433b0150-2554-4703-af31-bd67bdc2aa27.png)
![bbbbb](https://user-images.githubusercontent.com/62518101/163019052-2bc02b58-a10e-4db3-a030-ee4385bfd96b.png)

**Current behaviour**: 
the position is bad / bad movement

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/62518101/163019506-a93222f0-2ba0-4a29-9d65-32f63bccffe1.png)
![image](https://user-images.githubusercontent.com/62518101/163019538-c3dc469c-5c9d-427f-b5b3-14c921a3c9a1.png)

**Comment by therealCrysis** [comment]
Confirmed in rev 1165
