### ISSUE TITLE
[Suggestion] Enable naxx10 skip

### ISSUE THREAD

**Issue by nevrozac** [Stormforge-gg/Bugtracker-Fordring#1813]
Running naxx10 is - for most players - pointless since most bosses reward items at most just as good (or not worth bothering for) as heroic ones. 
Since time is limited and content is/should be squished I think allowing people to go straight to to Sapphiron instead of spending 90 minutes on boring bosses and disenchanting purples would be very helpful and appreciated.

Again - I'm only suggesting this change be made for 10man version of Naxx, not 25.

**Comment by Vishiswaz** [comment]
no

**Comment by nevrozac** [comment]
This is not a discussion or a poll to ask for public opinion. It's a matter of content squish and activity on the server.

It's a suggestion; wether you like it or not it's up to server administration to accept/deny it.

**Comment by Vishiswaz** [comment]
It'll probably be changed with 3.1 anyways

**Comment by kekkerina** [comment]
casual alert

**Comment by Aithne99** [comment]
Was disabled on purpose.
