### ISSUE TITLE
[Obsidian Sanctum][Boss] Drakes pulled with Sartharion doesn't drop badge of Valor / Heroism

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1819]
**Description**: The drakes are supposed to give Emblem of Valor / Heroism when Sartharion dies, as part of OSxD encounter.
Currently they are giving Emblem of Conquest, which will hopefully be removed before they can be used for anything.
This means players are not getting their emblem of Valor / Heroism properly.

**Current behaviour**: Drakes drop Emblem of Conquest

**Expected behaviour**: Drakes should drop Emblem of Valor / Heroism

**Comment by Aithne99** [comment]
No, Sarth drops the extra emblems with more drakes pulled.

**Comment by Aithne99** [comment]
Getting Conquest is a separate issue.

**Comment by nikko8085** [comment]
It's a problem because it means we're getting less Emblem of Valor/Heroism than we should, while when the other bosses drop them it's not replacing the emblems we're supposed to get, but just something extra...
This is why it's a problem now, and not just related to the drakes dropping Conquest.

**Comment by Aithne99** [comment]
You're not getting fewer emblems.

Sarth 0d drops one emblem on 10 man. Sarth 1d drops two emblems, 2d three emblems, and 3d four emblems. The emblems that would have been dropped by the small drakes go into the boss instead.

**Comment by nikko8085** [comment]
You're getting fewer emblems of Valor because they are converted into Conquest.
Sarth 0d drops one emblem of Valor (correct, but guessed since we only kill Sarth 3d)
Sarth 1d drops one Emblem of Valor and one Emblem of Conquest (1 Emblem of Valor too littlet, but guessed since we only kill Sarth 3d)
Sarth 2d drops one Emblem of Valor and two Emblem of Conquest (2 Emblems of Valor too littlet, but guessed since we only kill Sarth 3d)
Sarth 3d drops one Emblem of Valor and three Emblem of Conquest (3 Emblems of Valor too little).
