### ISSUE TITLE
[Quest] Breadcrumb quests

### ISSUE THREAD

**Issue by VirtualReign** [Stormforge-gg/Bugtracker-Fordring#1821]
I'd abandoned a few breadcrumb quests in Borean Tundra, and when I'd come back to Valiance Keep to pick them up they weren't offered again. I don't remember the names, but it was the ones pointing to Farshire, Fizzcrank Airstrip and Death's Stand (the Thassarian chain).

**Comment by Aithne99** [comment]
If you already did the followup quests (it is possible to do them w/o the breadcrumbs), you won't be able to get the breadcrumbs anymore.
