### ISSUE TITLE
JC Design [Shifting Twilight Opal] - Missing at Jewelcrafting Vendor!

### ISSUE THREAD

**Issue by PhobiaStormforged** [Stormforge-gg/Bugtracker-Fordring#1828]
JC Design [Shifting Twilight Opal] - Missing at Jewelcrafting Vendor!

**Comment by Vishiswaz** [comment]
https://wowwiki-archive.fandom.com/wiki/Shifting_Twilight_Opal#:~:text=Shifting%20Twilight%20Opal%20is%20a,and%20a%20%5BSimple%20Grinder%5D.&text=The%20recipe%20for%20this%20item,for%203%20Dalaran%20Jewelcrafter's%20Tokens.

patch 3.1
