### ISSUE TITLE
[Item] Titan-forged Leather Helm of Salvation

### ISSUE THREAD

**Issue by BigOoga** [Stormforge-gg/Bugtracker-Fordring#1829]
https://wotlkdb.com/?item=44906
**Description**: 
[Titan-forged Leather Helm of Salvation] currently has two mods of spell power
**Current behaviour**:
[Titan-forged Leather Helm of Salvation] currently has two mods of spell power
**Expected behaviour**: 
[Titan-forged Leather Helm of Salvation] should only have one mod of spell power

**Comment by Godmatik** [comment]
looks fine to me. Close game and delete cache folder, to verify you don't have invalid item display data

**Comment by Aithne99** [comment]
http://wotlk-shoot-new.tauri.hu/?item=44906&skip_cache=1
