### ISSUE TITLE
Mobs respawning

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Fordring#1831]
When mobs respawn in the world, they have the level up animation + visual.

This should not exist.

**Comment by Vishiswaz** [comment]
I reported this on Crystalsong years ago, they can't prevent it.

**Comment by Godmatik** [comment]
Can't prevent it? Yet other core prevents it just fine? Also this new core is based on mangos I believe? Lights Hope vanilla was also able to fix it - same core

**Comment by Vishiswaz** [comment]
All I remember is reporting it, being told why it happens (mobs respawning at a different level than their previous instance), and that they couldn't fix it.

**Comment by Aithne99** [comment]
The fix for this would be too performance intensive if we did it the way most opensource cores do.
