### ISSUE TITLE
[Profession][Inscription] Milling herbs not giving correct amount of Icy Pigments

### ISSUE THREAD

**Issue by pkumar313** [Stormforge-gg/Bugtracker-Fordring#1836]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  As the title states, milling herbs (Adder's Tongue) maybe even Lichbloom and Icethorn are not giving the correct amount of Icy Pigments on the NEW core.

**Current behaviour**: I did two separate tests with Goldclover and Adder's Tongue with 200 of each and 215 of each and in each instance I got the same amounts of Icy Pigments when this is not supposed to be the case.

**Expected behaviour**:  According to WoWHead and every other wotlk database https://www.wowhead.com/item=36903/adders-tongue#milling and https://www.wowhead.com/item=36901/goldclover#milling. Adder's Tongue is supposed to return twice as much Icy Pigments rather than the same amount as Goldclover, Tiger Lily and Deadnettle. I have not tested with Icethorn and Lichbloom but they are supposed to return the same amount as Adder's Tongue

**Comment by Aithne99** [comment]
This ends up being a nerf to everything :)

**Comment by pkumar313** [comment]
Im so confused, You closed the ticket saying its fixed and i try again and 400 adders return 38 icy pigment and 400 goldclover returns 41 icy pigments

**Comment by Aithne99** [comment]
400 goldclover will return roughly 20 after restart fyi.
