### ISSUE TITLE
[Quest] [Dragonblight] The Chain Gun and You [Broken, Incompletable]

### ISSUE THREAD

**Issue by Napolarbear** [Stormforge-gg/Bugtracker-Fordring#1839]
**Description**: Quest is incompletable due to vehicle not doing damage.

**Current behaviour**: The Chain Gun vehicle is not hitting or doing damage to the Mindless Ghouls in the Wintergarde Mausoleum, making the quest incompletable. There might be a problem with phasing in the entire area, as Hungering Dead seem to spawn and despawn rapidly in the Carrion Fields, including on top of players, which I don't think is intended. I did the quest on a different character (I think before the core change) and that didn't happen.

**Expected behaviour**: The Chain Guns should do damage to Mindless Ghouls. Video of quest working as intended: https://www.youtube.com/watch?v=GWZTqs_Y1KQ

**Comment by Cold-Martijn** [comment]
This got fixed on MoP, probably just needs a backport.

**Comment by Drevil-Dion** [comment]
It can be completed I am doing it as of typing this how ever it requires you to have people with you
One person on the cannon calling the npc using atction button 2 and the other down with the mindless ghoul's killing them to stop them killing the npcs you need to sav
![WoWScrnShot_072922_110450](https://user-images.githubusercontent.com/13806368/181737230-718aac6c-de78-41be-bcbf-49c213984861.jpg)
![WoWScrnShot_072922_111245](https://user-images.githubusercontent.com/13806368/181737721-87a44693-245c-4581-987b-c3eae0ac0cf3.jpg)
e

**Comment by Aithne99** [comment]
Needs restart.
