### ISSUE TITLE
[Quest] [Dragonblight] Reborn From the Ashes [Quest Missing]

### ISSUE THREAD

**Issue by Napolarbear** [Stormforge-gg/Bugtracker-Fordring#1845]
The quest is completely missing, making the rest of the quest line unavailable.

**Comment by Vishiswaz** [comment]
If this is from the battle for the undercity quest chain then it's on purpose

**Comment by Napolarbear** [comment]
I see. Pretty anti-climatic but now that I check it's blizzlike apparently. Oh well.
