### ISSUE TITLE
[Ulduar][Boss] Razorscale is supposed to transition to phase 2 at 50%

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1846]
**Description**: Razorscale is supposed to break the "stun" from the chains when reaching 50%, not stay stunned past 50% until the chains expire. Proof:
https://youtu.be/p21xBLPTuUU?t=341

**Current behaviour**: Razorscale remains stunned for the full duration of the chains instead of breaking at 50%

**Expected behaviour**: Razorscale should break the stun at 50%

**Comment by Cold-Martijn** [comment]
fixed your link :) you can click "share" on youtube, and let it start from a specific time there. Just fyi :)
