### ISSUE TITLE
[Ulduar][Boss]Freya - pull range

### ISSUE THREAD

**Issue by T0mken** [Stormforge-gg/Bugtracker-Fordring#1850]
Can pull Freya without hitting her.

**Comment by Godmatik** [comment]
I believe this is intentional for her not to have an aggro proximity, unless you have proof showing otherwise

**Comment by Aithne99** [comment]
https://www.youtube.com/watch?v=R8YklIyXk1I
https://www.youtube.com/watch?v=4vG-44MIb7I


Very likely that she did not aggro just by proximity even on retail, or if she did, it was... not very large.
