### ISSUE TITLE
[Ulduar][Vezax]Trash 

### ISSUE THREAD

**Issue by T0mken** [Stormforge-gg/Bugtracker-Fordring#1851]
Trash does very low damage

**Comment by Cold-Martijn** [comment]
were you using the PTR buffs? They reduce damage taken significantly.
I remember raiding 25man and accidentially pulling 2 groups could cause a wipe.

**Comment by Aithne99** [comment]
https://docs.google.com/spreadsheets/d/1_z0Mko6M0xwAZKwSrAa1xvIKY5gSq5P1h7pybio76hU/edit#gid=0

For reference.
