### ISSUE TITLE
[Ulduar][Boss] Freyas Detonating Lashers are tankable and deal too much damage in 10 man

### ISSUE THREAD

**Issue by nikko8085** [Stormforge-gg/Bugtracker-Fordring#1852]
**Description**: The adds "Detonating Lashers" on the Freya encounter are supposed to run around attacking random targets, not follow regular threat mechanics. They currently follow regular threat mechanics. In addition, they are supposed to hit for 1k on cloth users, while they are currently hitting for up to 2.1k on a DK tank.
Proof of intended behaviour:
https://youtu.be/HJ1gxZZSRtI?t=51
Proof of current damage to tanks:
https://legacyplayers.com/viewer/32569/ability?history_state=6
(Filter to Detonating Lasher as Targets, Deathnaitt as source, switch to Damage Taken, click on Deathnaitt, and hover over "Auto-attack" to get a detailed breakdown)

**Current behaviour**: Detonating Lashers are tankable and deal too much damage

**Expected behaviour**: Detonating Lashers should be untankable and not deal too much damage

**Comment by Cold-Martijn** [comment]
Comment: this worked on the pre-nerf state on Crystalsong. It is one of the things that broke with the nerf application.

**Comment by Aithne99** [comment]
The melee damage is very near correct: that cloth user has Divine guardian to reduce dmg taken by 20%, and the adds melee for fire damage, so the pre-mitigation damage taken by the, ehm, cloth user (as if it's not completely irrelevant due to the fire damage) in question is ~1300-1600 from those four hits, and the damage that's set for them in db is 1,358 - 2,037.

**Comment by Cold-Martijn** [comment]
> The melee damage is very near correct: that cloth user has Divine guardian to reduce dmg taken by 20%, and the adds melee for fire damage, so the pre-mitigation damage taken by the, ehm, cloth user (as if it's not completely irrelevant due to the fire damage) in question is ~1300-1600 from those four hits, and the damage that's set for them in db is 1,358 - 2,037.

The damage is almost irrelevant anyway, its more about the movement and being tankable.

**Comment by Aithne99** [comment]
Well, nothing changed between the "pre-nerf" and the "post-nerf" state of this npc so if it worked on crystalsong it should also work here.

**Comment by Cold-Martijn** [comment]
> Well, nothing changed between the "pre-nerf" and the "post-nerf" state of this npc so if it worked on crystalsong it should also work here.

Then something else broke it, but it also broke somewhere on Crystalsong after the nerf. Or maybe has a chance to break, idk.
