### ISSUE TITLE
[PTR] [Hunter] Wolves do not accept meat as food

### ISSUE THREAD

**Issue by AlexandreLaforest** [Stormforge-gg/Bugtracker-Fordring#1853]
: # ([Spell][Hunter] Feed Pet)

**Description**: Getting the "Your pet doesn't like that food" message when trying to feed high-level meat.

**Current behaviour**: Getting the "Your pet doesn't like that food" message when trying to feed high-level meat.

**Expected behaviour**: Pet should eat the food :P

**Comment by Cold-Martijn** [comment]
Is this only on the PTR?

**Comment by Aithne99** [comment]
What meat? What wolf?

**Comment by AlexandreLaforest** [comment]
I tried for most of the lvel 80 meats on the PTR vendor.

Yes it is only on PTR.

**Comment by AlexandreLaforest** [comment]
Live is fine.

**Comment by Aithne99** [comment]
Exactly which meats, and where did you get your wolf, and does the same wolf eat those same meats on live?

**Comment by Aithne99** [comment]
Well alright, if it works on live then I guess it works.
