### ISSUE TITLE
[Ulduar] not yet reported stuff

### ISSUE THREAD

**Issue by Cold-Martijn** [Stormforge-gg/Bugtracker-Fordring#1854]
Some bugs I remember from raiding back on Crystalsong, that didn't get a touch anymore:
https://bug.tauriwow.com/index.php?do=details&task_id=37766
https://bug.tauriwow.com/index.php?do=details&task_id=34890
https://bug.tauriwow.com/index.php?do=details&task_id=34912
https://bug.tauriwow.com/index.php?do=details&task_id=34942
https://bug.tauriwow.com/index.php?do=details&task_id=34978
https://bug.tauriwow.com/index.php?do=details&task_id=35156 --> not sure, but since the mining one was 100% not yet fully fixed I assume this one might also still be valid.
https://bug.tauriwow.com/index.php?do=details&task_id=35426 same as https://bug.tauriwow.com/index.php?do=details&task_id=35510 most probably.

**Comment by nikko8085** [comment]
Can confirm the trash in front of Mimiron is missing

**Comment by Aithne99** [comment]
What a massive fucking issue.

**Comment by Aithne99** [comment]
And they actually weren't missing.

I'll close this report, please don't copypaste stuff from the old bugtracker anymore, I can read.
