### ISSUE TITLE
[New Core][Mining] Mine Nodes Under the Map

### ISSUE THREAD

**Issue by Exorcista** [Stormforge-gg/Bugtracker-Fordring#1860]
*Current behaviour**:  ![WoWScrnShot_072722_131745](https://user-images.githubusercontent.com/6818405/181340599-2eeb3c57-df40-48d5-a092-6b22f6ef8b17.jpg)

**Expected behaviour**:  Mining nodes not under the map please, it happens on almost every northend zone

**Comment by Aithne99** [comment]
This has to be fixed on a per node basis, unfortunately.

**Comment by Exorcista** [comment]
> This has to be fixed on a per node basis, unfortunately.

ill try to add more to this same report then when i encounter them :P  Coords for this one are 48,72 StormPeaks (u can see this under my char picture)

**Comment by Aithne99** [comment]
Do not add to closed reports.
