### ISSUE TITLE
Quest bugged in Dragonbligh 

### ISSUE THREAD

**Issue by lixii89** [Stormforge-gg/Bugtracker-Fordring#1863]
**Description**:  " The Chain Gun and You " quest is bugged and it doesn't allow to progress story for Wintegarde Keep in Dragonblight 

**Current behaviour**: Gun doesn't do any damage to ghouls hence you are not able to complete the quest.  

**Expected behaviour**: Gun should do damage to ghouls in order to complete it. Quest also worked on previous core and here it's bugged.

**Comment by Godmatik** [comment]
Duplicate
https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1839

**Comment by Cold-Martijn** [comment]
duplicate
