### ISSUE TITLE
[NPC][Naxxramas] 4 horsemen died instantly on pull in 25-man

### ISSUE THREAD

**Issue by BokChoyWarrior** [Stormforge-gg/Bugtracker-Fordring#1870]
In our 25man raid, we went to pull 4 horsemen and as soon as we pull, they all died instantly. We got the loot and achieve as if we killed them normally.

**Comment by Godmatik** [comment]
One of these bug fixes likely broke something big time.

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1856
https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1855
