### ISSUE TITLE
[Spells][Shaman] Spirit Wolves / Fire Elemental

### ISSUE THREAD

**Issue by Healweed** [Stormforge-gg/Bugtracker-Fordring#1873]
**Description**: 
With this weekly reset, i came to notice Spirit wolves and Fire elemental aren't elligible get party/raid wide buffs. It was working before this and even on previous core so i think it was some accidental change .

**Current behaviour**:
Summon Wolves and/or Fire Elemental aren't elligible to get party/raid wide buffs.

**Expected behaviour**: 
 Both pets should be elligible for party/raid wide buffs INCLUDING BLOODLUST/HEROISM!

**Comment by Aithne99** [comment]
Might be a PvP flag issue? By default they are eligible, it's controlled by a spell attribute.

**Comment by Healweed** [comment]
> Might be a PvP flag issue? By default they are eligible, it's controlled by a spell attribute.

I really doubt it's a PvP issue as i also tried to summon the wolves and the elemental on Dalaran and it can't be buffed or receiving any buffs. The only buff that wolves are getting is just the Draenei hit aura and only it

Both screenshots are while flagged on pvp and non pvp afterwards
![non-combat flag](https://user-images.githubusercontent.com/52166185/182043294-450a01ee-ab99-4156-b669-715e0e488ccf.png)
![combat flagged](https://user-images.githubusercontent.com/52166185/182043295-8b89e1b6-e7df-4cac-916c-2e527f6747de.png)
t

**Comment by Aithne99** [comment]
Worksforme, at least, as it did previously. It didn't change on this core.

Idk why you all capsed Bloodlust/Heroism, specifically those do get applied to pets, altho you're correct about totems, according to this https://www.youtube.com/watch?v=HhpQneM9enQ one beta video.

**Comment by Healweed** [comment]
> Worksforme, at least, as it did previously. It didn't change on this core.
> 
> Idk why you all capsed Bloodlust/Heroism, specifically those do get applied to pets, altho you're correct about totems, according to this https://www.youtube.com/watch?v=HhpQneM9enQ one beta video.

Just went to the ptr to test this again , but when i tried to lust both wolves and ele on dalaran and ironforge none of them would even get the buffs smh)

But totem issue still remains.

**Comment by Aithne99** [comment]
Really couldn't find the issue with BL, but fixed totems.
