### ISSUE TITLE
[core] batching

### ISSUE THREAD

**Issue by nevrozac** [Stormforge-gg/Bugtracker-Fordring#1874]
current: batching window too high

expected: set batching window lower (~10-30ms)

**Comment by Aithne99** [comment]
No.

**Comment by nevrozac** [comment]
as discussed the best examples i have at hand, and if youre willing to pursue this issue ill post more examples as i encounter them
https://imgur.com/a/ShN3pml
other undocumented events that i can recall:
-people landing autoattacks after theyve been stunned
-sap going off on a warrior who at the same time has revealed a rogue with shout
-finishing a heal cast on a player who died at the same time 

*please dont annoy me with cloak of shadows being 90% - this happens literally all the time in pvp with various cc abiltieis

**Comment by nevrozac** [comment]
Warlock aoe stun and priest fear (both instant casts) happening at the same time
https://imgur.com/a/IovsNO8
