### ISSUE TITLE
[ULDUAR] Flame Leviathan - Gathering Speed getting stacks too slowly

### ISSUE THREAD

**Issue by therealCrysis** [Stormforge-gg/Bugtracker-Fordring#1876]
**Description**: 
Gathering Speed is Flame Leviathan's speed buff, increasing his movement speed by 5%. It stacks every 5 seconds, stacking up to 20 times.

**Current behaviour**:
Right now FL seems to get stacks a bit too slow (like 8s), as reported by a player.

**Expected behaviour**: 
Gathering Speed should stack up every 5 seconds.

**Comment by Aithne99** [comment]
Well the correct behavior is once every 10 seconds, which is what currently happens.
