### ISSUE TITLE
[ULDUAR] Auriaya - Feral Defender

### ISSUE THREAD

**Issue by therealCrysis** [Stormforge-gg/Bugtracker-Fordring#1877]
Feral Defender is an add Auriaya summons to assist her. He has 4 abilities:

Feral Essence - Each essence increases the damage dealt by the Feral Defender by 50%. The Feral Defender can revive himself at the cost of one of his Feral Essences. This starts out stacked to 9. Work
Feral Pounce - The Feral Defender pounces the target stunning them for 4 seconds and inflicting Shadow damage every second. 
Feral Rush - Charges an enemy, dealing 1609 to 1691 Physical damage. Also interrupts casting.
Seeping Feral Essence - After death cat leaves a black circle on the floor. Works correctly.

Currently, Feral Defender does not cast Feral Pounce at all.

**Comment by Cold-Martijn** [comment]
@therealCrysis did you also have issues with feral defender always picking the same target over and over again?
i didnt test Ulduar recently, but i remember something like that happening.

**Comment by Aithne99** [comment]
This is not actually Crysis' experience, he just opened a report in the place of someone who was too lazy or too stupid to do so.

Feral Pounce has a minimum range, fyi.

**Comment by therealCrysis** [comment]
@Cold-Martijn I tried to reproduce report I've received, but yeah I did not verify FD's targetting.

**Comment by Aithne99** [comment]
Can't find any issues really.
