### ISSUE TITLE
[ULDUAR] Auriaya - Summon Swarming Guardian not being casted

### ISSUE THREAD

**Issue by therealCrysis** [Stormforge-gg/Bugtracker-Fordring#1878]
Auriaya should summon swarm of little panthers on random player every ~30 seconds.

Currently she does not summon it at all. I suspect that timers may be overlapped, since Terrifying Screech is also casted every 30seconds.

**Comment by Cold-Martijn** [comment]
used to work just fine on Crystalsong afaik... atleast i remember little panthers during our raids. any specific condition?

**Comment by Aithne99** [comment]
The only scenario I can think of is solo testing. She does not currently target a single player with Guardians.

**Comment by therealCrysis** [comment]
Closing.

**Comment by Aithne99** [comment]
Select "not planned" when it works correctly.
