### ISSUE TITLE
[Quest] Heated Battle [Zone] Dragonblight

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#188]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  The undeads should be attacking in waves, fight between undead and alliance NPCs should be more organized, but right now it's all over the place. It's still doable though, but a bit messy.

**Current behaviour**: The quest doesn't seem to be scripted.

**Expected behaviour**:  https://www.wowhead.com/quest=12416/heated-battle#videos

**Revision**:

**Comment by therealCrysis** [comment]
Confirmed in rev 1179. Quest is indeed doable yet kind of not as it should be

https://www.youtube.com/watch?v=FBWOnCshLe0   example of how it should look like imo

**Comment by reetarded** [comment]
Please at least increase the amount of geists spawning, I have spent 10+ minutes trying to do this quest, the geists only spawn 2 at a time every couple of minutes, and they die so fast to these mobs. Maybe decreasing the friendly mobs damage so you have more time to tag them would be helpful too.
