### ISSUE TITLE
[ULDUAR] Kologarn - Cannot enter instance after wipe

### ISSUE THREAD

**Issue by therealCrysis** [Stormforge-gg/Bugtracker-Fordring#1880]
After wiping on Kologarn only one member of raid was able to enter the instance after releasing his body and he was instantly targetted by Kologarn.

Rest of the raid saw notification that fight is in progress, therefore they could not enter. Repeated few times.

**Comment by Cold-Martijn** [comment]
We used to have this issue on Crystalsong aswell sometimes, but I don't think it was limited to Kologarn. (might be, but not too sure).

**Comment by Aithne99** [comment]
Would love to have a video of this. Not "not being able to enter", mind you, but the wipe before that.

**Comment by therealCrysis** [comment]
^I'll try to get something.

**Comment by Weuyn** [comment]
Had a weird bug happen on kologarn too. After a server crash midfight, on every subsequent pull he would use all three abilities at the same time. Breath, that raid cleave and eye lasers. Every time he did, someone got one shot.

**Comment by Aithne99** [comment]
Irrelevant, offtopic & insufficient info, please open a new report with proper documentation instead of commenting on unrelated reports. Since I haven't heard complaints since, I will assume that the thing I tried to do to fix a type of this encounter-in-progress issue, I will close this one.
