### ISSUE TITLE
[ULDUAR] Hodir - Singed buff too low chance to proc

### ISSUE THREAD

**Issue by therealCrysis** [Stormforge-gg/Bugtracker-Fordring#1881]
https://www.wowhead.com/wotlk/spell=65280/singed

As tooltip says - this buff should be applied to boss increasing magical damage/effects on Hodir bye 2% for 25 seconds stacking up to 30 stacks.
Player's spells should have 30% chance for this effect to proc while standing near Toasty Fires.

Right now the chance to proc seems to be drastically lower than 30% - we could not reach 30 stacks during entire fight.

**Comment by Cold-Martijn** [comment]
I believe Higi mentioned an issue with the aura generator that made the toasty fire buff sometimes "flicker" on and off. This might be the source of lower procs.

**Comment by Aithne99** [comment]
Currently set to 33% so it would be good to know if it flickered.

**Comment by adambcurrier** [comment]
I engaged Hodir on the PTR maybe 2 days ago and was only able to get signed to stack past 1 (to 2) a single time and I kept trying until all the NPCs actually died. It does not feel like it's a 33% chance on spell hit.

**Comment by Aithne99** [comment]
Does. It. Flicker?

**Comment by Cold-Martijn** [comment]
> Does. It. Flicker?

I don't think the person whose report this actually is, will ever read it :) I'll post it on discord, who knows the person will actually see it and give a reply.

**Comment by Aithne99** [comment]
Changed a tiny thing about it, it's live, check it and man, do I wish that people actually bothered opening their own reports instead of bothering the community manager...
