### ISSUE TITLE
[ULDUAR] Freya - Strengthened Iron Roots

### ISSUE THREAD

**Issue by therealCrysis** [Stormforge-gg/Bugtracker-Fordring#1882]
Strengthened Iron Roots on are being casted on players when Elder Ironbranch is alive stunning targeted player and causing ticking damage.
Raid should simply nuke these roots. Currently when roots are killed they still damage player for few ticks, and it should not happen. Damage should stop instantly after roots being nuked.

**Comment by Aithne99** [comment]
Can't reproduce.
