### ISSUE TITLE
Target Dummies and Weapon Skill

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Fordring#1886]
Target Dummies are currently giving weapon skill to players. They should not be able to.

https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/45790622
https://www.mmo-champion.com/threads/624592-Can-you-lvl-up-your-wep-skill-on-a-target-dummy

**Comment by Cold-Martijn** [comment]
Yeah that is known, but has been removed on purpose as QoL improvement.

**Comment by Godmatik** [comment]
If it is done on purpose which I assume is what you meant, then I will close this report

**Comment by Aithne99** [comment]
Well, there are other ways.
