### ISSUE TITLE
[Quest][Tirisfal Glades, Undercity] The Killing Time, Battle for Undercity

### ISSUE THREAD

**Issue by chehcheh** [Stormforge-gg/Bugtracker-Fordring#1888]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After completing "[The Killing Time](https://www.wowhead.com/wotlk/quest=13371/the-killing-time)," "[The Battle for The Undercity](https://www.wowhead.com/wotlk/quest=13377/the-battle-for-the-undercity)" (Alliance) can't be started, leaving your character in the wrong phase.
**Current behaviour**:
The character's version of the zones of Tirisfal Glades and Undercity are permanently phased into their empty "The Battle for The Undercity" versions. All normal NPCs and players are gone in these two zones.

**Comment by Aithne99** [comment]
#1677
