### ISSUE TITLE
[Spell][Warlock] Chaos Touch

### ISSUE THREAD

**Issue by Sanyei** [Stormforge-gg/Bugtracker-Fordring#1889]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Chaos touch should pierce magic damage reduction because its chaos damage 
**Current behaviour**:
Chaos damage is currently taken as magic damage and being reducen by dk anti magic shell as example or rogues shadow cloack , but i didnt tested against a rogue
**Expected behaviour**: 
As chaos damage , should pierce all reduction's 
https://www.youtube.com/watch?v=AQpqt1JZO8Q&t=1s (2:55)
https://www.youtube.com/watch?v=PkuOWdZs0IE
videos as proof

![WoWScrnShot_080222_011927](https://user-images.githubusercontent.com/110447109/182302308-620f7fca-2a5b-4add-813d-607293d6f9c1.jpg)
![WoWScrnShot_080222_011938](https://user-images.githubusercontent.com/110447109/182302333-d4147f33-c8c4-4ac3-b2b3-7c43310b7a85.jpg)
images from mistblade 2/8/2022

**Comment by Cold-Martijn** [comment]
Wrong bugtracker, this is the WotLK bugtracker.
Mistblade MoP issues go here: https://github.com/Stormforge-gg/Bugtracker-Mistblade/issues

**Comment by Sanyei** [comment]
thanks
