### ISSUE TITLE
Demonic Pact bugged?!?

### ISSUE THREAD

**Issue by zobimaru91** [Stormforge-gg/Bugtracker-Fordring#1890]
Hi, i noticed in Raid 25m Naxx today that i as a Demolock are not giving the right amount of SP with my Demonic Pact....

It should be 10% so i have about 3100 SP constant in raid and only give 40-50SP with my buff to the Raid....

Something isnt right there....

**Comment by nikko8085** [comment]
Did you also have an elemental shaman present? The Totem of Wrath gives 280 spell power and doesn't stack with Demonic Pact, so your demonic pact should give 0.1*3100-280 = 30 spell power buff total.

**Comment by Aithne99** [comment]
Looks just fine to me.
