### ISSUE TITLE
[Spell] [Warlock] Seed of Corruption

### ISSUE THREAD

**Issue by Xullu** [Stormforge-gg/Bugtracker-Fordring#1894]
**Current behaviour**:  Seed of Corruption does not damage the initial target that its applied on. Currently works like mind sear 

**Expected behaviour**:   The seed of corruption should also damage the main target its applied on. If there's 2 mobs and I seed on one, then the seed damage should hit both of 2 mobs instead of just one of them

![](https://user-images.githubusercontent.com/105716384/181019078-454b5afb-e9f2-4566-a50c-98c5fd3f72fd.png)

https://wowwiki-archive.fandom.com/wiki/Patch_3.3.0_(undocumented_changes)

**Comment by Aithne99** [comment]
#1808

Don't.
