### ISSUE TITLE
[Enginnering/Item] Gnomish Battle Cock

### ISSUE THREAD

**Issue by Healweed** [Stormforge-gg/Bugtracker-Fordring#1895]
**Description**: 
Ever since the core swap, i've been wondering as to why party group wasn't getting any battle chicken until i just came to noticed on a target dummy thatBattle Chicken isn't scaling with current enginnering level itself. This is quite a big deal especially when this trinket is highly value on melee/hunters side not to mention that being 20 levels below has a guarantee potential of pulling mobs due to level difference.

By standard Battle Chicken level will be mostly : Current Enginnering Level/5     ( example of 450/5 = 90 which makes battle chicken being lvl 90)

Also my enginnering skill is maxed out, so in practise chicken level should be level 90
**Proof:**

Patch 2.4.3 (2008-07-15): Level is scaled with the user's engineering skill again.
https://wowwiki-archive.fandom.com/wiki/Gnomish_Battle_Chicken#:~:text=The%20Gnomish%20Battle%20Chicken%20is,90%20at%20450%20engineering.).

**Edit**
On the other bugreport that another person made of this [#1772 ](https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1772) , i've also tested this to confirm on a level 60 dummy target none of both abilities were even being used.
The following abilites that the chicken should cast(and their respective spell ids) are the following:

__**Chicken Fury: Spell id**__ 13168
__**Battle Squawk**__ : 23060

**Current behaviour**:
Chicken isn't scaling with enginnering level therefore getting a flat non scalable lvl 60

**Expected behaviour**: 

Chicken Should scale with Current enginnering skill/5 = Battle Chicken level
![Battle_Chicken](https://user-images.githubusercontent.com/52166185/182962280-49e39cc2-0ee4-4049-8bd7-4af2e9eea0e5.png)
![Enginneringlvl](https://user-images.githubusercontent.com/52166185/182962283-bd0fc8c0-684d-4503-aa4b-f5ed9a3b1784.png)

**Comment by Healweed** [comment]
Yep cock

**Comment by Godmatik** [comment]
lol
