### ISSUE TITLE
[Talent] Can`t insert new talent points

### ISSUE THREAD

**Issue by Efemer2k** [Stormforge-gg/Bugtracker-Fordring#1902]
[//]: # ([Talent][Warrior])

**Description**: 
After i spent 10 talent points in the fury tree i can`t add more points to higher tier talents. For example the ones requiring 15 talent points
**Current behaviour**:
Can`t insert new talents
**Expected behaviour**:

**Comment by Godmatik** [comment]
> **Description**: After i spent 10 talent points in the fury tree i can`t add more points to higher tier talents. For example the ones requiring 15 talent points **Current behaviour**: Can`t insert new talents **Expected behaviour**:

Try disabling your addons. In particular - Zygor addon causes issues with putting in talent points.

**Comment by Cold-Martijn** [comment]
This is either an addon issue (99% sure, try to disable them all to see if it works) or a character specific issue, in that case you could ask a GM for help.

**Comment by Efemer2k** [comment]
It was the zygor addon !
