### ISSUE TITLE
Missing Emblems of conquest

### ISSUE THREAD

**Issue by Ac3x** [Stormforge-gg/Bugtracker-Fordring#1907]
**Description**: After fight in obsidium sanctum dragon 2D I got 2 Emblems of conquest.

**Current behaviour**:Now it shows me my Emblems of conquest are 0

**Expected behaviour**: Give back my Emblems!!! 
Account name: redacted, dont post your accountname -.-

**Comment by Exorcista** [comment]
You cannot have conquest since its an emblem for ulduar patch lmao, wait till 11 to get them from Ulduar :)

**Comment by Godmatik** [comment]
> **Description**: After fight in obsidium sanctum dragon 2D I got 2 Emblems of conquest.
> 
> **Current behaviour**:Now it shows me my Emblems of conquest are 0
> 
> **Expected behaviour**: Give back my Emblems!!! Account name: Looprunner

It was a bug and unintended for you to get conquest emblems before the Ulduar patch was released, so they removed them

**Comment by Ac3x** [comment]
Gotcha, Thx!
