### ISSUE TITLE
whatever

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Fordring#1911]
.

**Comment by Aithne99** [comment]
So... "taken from discord" means it only occurs sometimes, under some weird circumstances?

**Comment by Healweed** [comment]
> So... "taken from discord" means it only occurs sometimes, under some weird circumstances?

Can confirm this
After the first shutdown, the turrets will never spawn again for the whole duration of the fight. I didn't noticed this until someone on discord said this and had to check the replay to confirm and its exactlt what happened asweel

**Comment by Aithne99** [comment]
Could not reproduce. Loaded someone into a demolisher, shot that character up onto Leviathan, killed the turrets, and as soon as the overload debuff expired from the boss (or rather, exactly one second later), the two Flame Leviathan Defense Turret npcs were back.

**Comment by Aithne99** [comment]
I need to know what sort of idiotic thing you're doing to break the boss, because if I try to do the encounter properly, it works.

**Comment by Healweed** [comment]
> I need to know what sort of idiotic thing you're doing to break the boss, because if I try to do the encounter properly, it works.

Maybe try to reproduce the bugs through idiotic means. Maybe that will help

**Comment by Aithne99** [comment]
You've already killed (or attempted) the boss in a non-conventional way, so I assume that you do have information (verbal description or video recording) regarding the problem. It would save us both time if you provided it with regards to exactly what steps you took and when to break the boss.

So please just link the replay.
