### ISSUE TITLE
[NPC] Hodir

### ISSUE THREAD

**Issue by icyHunt** [Stormforge-gg/Bugtracker-Fordring#1912]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)

**Description**: 
Singed Buff applies too low (~3%, 3 out of 101 events)
singed(?):
https://www.wowhead.com/spell=65280/singed
logs:
Ulduar Hodir 11.08.22
https://legacyplayers.com/viewer/33615/base
vod:
https://streamable.com/4ws589

**Current behaviour**:
Singed buff too low (3/101)
**Expected behaviour**: 
Singed buff proc more (33/101)

**Comment by Aithne99** [comment]
For fuck's sake. I closed the other report on the 12th, and you post a log from the 11th. No. Don't do this shit.

**Comment by adambcurrier** [comment]
You posted your comment saying you made an adjustment in the other thread on August 11th at 10:44 PM EST and that it was live. We started to raid on August 11th at 8:30 PM EST. These Hodir pulls happened at 22:59:15 (10:59 PM EST) and 23:07:09 (11:07). There was no server restart in between, so was the change live or not?

You need to step back and rethink how you interact with players who are trying to help you. Your default position is insulting, dismissive and hostile. Pretty soon absolutely nobody is going to try and help you.

**Comment by Aithne99** [comment]
I made it live slightly later than my comment. Don't expect me to mindread your timezone off a random 3rd party website & a 480p video, please, there is NO way to know from your reports that what appears to be a 7-8 hour difference is actually just 15 minutes.

If this issue doesn't appear again during TONIGHT's raid, then consider it fixed.

**Comment by adambcurrier** [comment]
Good luck with your server.

**Comment by Cold-Martijn** [comment]
> So the fix you said was live was in fact actually not live for an undetermined amount of time after you asked people to please test it out?
> 
> Good luck with your server.

Hurr durr, goodluck with your server.
What happened was that in fact, the reload of that specific element of the code was done a tiny bit later.

**Comment by adambcurrier** [comment]
> Hurr durr, goodluck with your server. What happened was that in fact, the reload of that specific element of the code was done a tiny bit later.

I don't have to pretend to believe you when conveniently "it's live" turns out not to have been true after she got caught flat footed with time stamps.
