### ISSUE TITLE
[Zone] Ulduar tar doesnt slow flame leviathan

### ISSUE THREAD

**Issue by Pinnen123** [Stormforge-gg/Bugtracker-Fordring#1913]
[NPC] Flame leviathan
[Spell][Class] Tar (from choppers)

**Description**:  
Choppers' tar is not slowing flame leviathan, nothing happens.
**Current behaviour**:
Not slowing flame leviathan
**Expected behaviour**: 
Should slow flame leviathan

**Comment by Aithne99** [comment]
"Not slow" as in the debuff doesn't appear, or "not slow" as in the debuff appears but the boss is still fast?

**Comment by Pinnen123** [comment]
Sorry, was tired yday. It doesnt appear on flame nor does it slow him. It works perfectly on everything else, adds etc. And I'm not sure if it's intended, but slows from people killing turrets slow flame, for example cone of cold.
