### ISSUE TITLE
[NPC] Hodir

### ISSUE THREAD

**Issue by icyHunt** [Stormforge-gg/Bugtracker-Fordring#1915]
Description:
Singed Buff applies too low (~3%, 3 out of 101 events)
singed(?):
https://www.wowhead.com/spell=65280/singed
logs:
Ulduar Hodir 11.08.22
https://legacyplayers.com/viewer/33615/base
vod:
https://streamable.com/4ws589

Current behaviour:
Singed buff too low (3/101)
Expected behaviour:
Singed buff proc more (33/101)

**Comment by Godmatik** [comment]
The developer literally closed your old report and told you why, what was the purpose of making a new one that is identical?

Your data is from the 11th, a fix was put on on the 12th, therefore this report is pointless.

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1912

**Comment by Godmatik** [comment]
? 
Identical report was already closed

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1912
