### ISSUE TITLE
[NPC] Detonating Lasher

### ISSUE THREAD

**Issue by icyHunt** [Stormforge-gg/Bugtracker-Fordring#1920]
**Description**: 
Detonating lashers are immune to all taunts.
**Current behaviour**:
Detonating lashers are "immune" to AOE taunts challenging shout/roar.
**Expected behaviour**: 
Detonating lashers respond to AOE taunts.

**Comment by NatsumeLily** [comment]
This is correct. They are immune to taunt and don't have an aggro table.

**Comment by adambcurrier** [comment]
> This is correct. They are immune to taunt and don't have an aggro table.

No, it is not correct. On retail the lashers would obey aoe taunts for their entire duration.

The internet is absolutely full of videos and forum posts from 2009 showing that to be the case, not to mention the memories of people who played through Ulduar when it was released on retail. Here are just a few examples:

 https://www.youtube.com/watch?v=pBKctmDQeR8
https://www.warcraftmovies.com/movieview.php?id=124391&stream=69
https://rota.forumotion.net/t280-freya-25-man-strategy-guide

**Comment by Godmatik** [comment]
What adam says is correct. Taunt does work, they will attack the target while the taunt debuff is on them, then after it ends, they will return back to attacking random targets.

**Comment by adambcurrier** [comment]
Would be amazing if these mobs got scripted correctly.

**Comment by adambcurrier** [comment]
This may be marked as completed as of 4 days ago but it certainly is not live.

**Comment by Godmatik** [comment]
I think they need to restart the server
