### ISSUE TITLE
[Stormforgelogs.pt] Side bar blocking view of the main page

### ISSUE THREAD

**Issue by Pinnen123** [Stormforge-gg/Bugtracker-Fordring#1924]
When on stormforgelogs for fordring, the sidebar menu is blocking the main page, which blocks valuable information. See screenshot

![image](https://user-images.githubusercontent.com/106036315/185779091-b4d27af9-94b4-4c73-937a-17f76449cc93.png)

**Comment by Cold-Martijn** [comment]
Stormforgelogs.pt is by Query. Issues should be reported to Query. You can ping him on discord or something.
