### ISSUE TITLE
holy paladin mistake

### ISSUE THREAD

**Issue by Omnikng** [Stormforge-gg/Bugtracker-Fordring#1939]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Guardian of Ancient Kings/paladin/holy https://mop-shoot.tauri.hu/?spell=86669 the error that I found in the sacred branch of the paladin is in the buff of that skill in the description of it says that the guardian for each skill that we use will heal an extra 100% but when we activate the skill it says that it only increases it by 30% , which is clearly a mistake
**Current behaviour**:
the buff of that skill in the description of it says that the guardian for each skill that we use will heal an extra 100% but when we activate the skill it says that it only increases it by 30%, Other than that, it should heal for every healing skill you use, but it only triggers when you use holy shock https://mop-shoot.tauri.hu/?spell=20473 ignoring the use of other healing skills https://mop-shoot.tauri.hu/?spell=53563, https://mop-shoot.tauri.hu/?spell=82327, https://mop-shoot.tauri.hu/?spell=85222, https://mop-shoot.tauri.hu/?spell=114158, https://mop-shoot.tauri.hu/?spell=633, does not work with any of the last powers.
**Expected behaviour**: 
after using theability you gain 10% haste and any healing you do with any of your healing abilities is replicated by the guardian healing 100% of what you healed

![xd1](https://user-images.githubusercontent.com/112517808/188040828-805fdbce-de58-4485-a887-d8aae0ec64e8.png)

![xd2](https://user-images.githubusercontent.com/112517808/188040845-0b993a8e-8c6b-4e1f-8285-f53d60266f53.png)

**Comment by Godmatik** [comment]
This is the Wrath of the Lich King bugtracker, you at the wrong place
