### ISSUE TITLE
Trial of the Crusader - Gormok the Impaler Adds (Kobolds) not being hit by Fan of Knives

### ISSUE THREAD

**Issue by Tetrahydrx** [Stormforge-gg/Bugtracker-Fordring#1949]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The adds on Gormok the Impaler are not being hit by the rogue ability "Fan of Knives". 
**Current behaviour**:
The adds on Gormok the Impaler are not taking any damage from FoK.
**Expected behaviour**: 
The kobolds are supposed to get hit by Fan of Knives.

**Comment by Godmatik** [comment]
I believe intended that AoE spells do not hit them

**Comment by Tetrahydrx** [comment]
> I believe intended that AoE spells do not hit them

I have yet to play on a server where Snobolds are not affected by AoE spells. It worked on Frosthold, Sindragosa and Mograine. I found an old clip of a rogue doing TogC which shows him hitting mobs with FoK around the 1 minute mark: https://youtu.be/CyiUgMXnyKA?t=60

**Comment by Tetrahydrx** [comment]
The footage in the video is from Icecrown, Warmane.

**Comment by Aithne99** [comment]
This is completely intended behavior and it is always how it worked on retail.
