### ISSUE TITLE
[Quest]  The Noble Crypt / Secrets of the Scourge [Zone] Dragonblight

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#195]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  I have included 2 quests in this report, as one leads to the other. They are missing RP elements and possibly some spawns . 
 I can't find info on the buff "Call of the Duskbringer" but judging by the way it works it shouldn't be removable by Right Clicking on it, which is possible here.  It should be removed only by leaving the crypt.

**Current behaviour**:  Missing RP elements and possibly some spawns.  You can remove "Call of the Duskbringer" by Right Clicking on it.

**Expected behaviour**:  

The Noble Crypt :  

Killing Necrolord Amarion should trigger:

Shadow of Thel'zan the Duskbringer says : Impressive. The master said that you and your people would be a nuisance. No matter, your end draws near. Soon the combined might of Naxxramas will come down upon this place and shatter your meager existence.
                                         

The Secrets of the Scourge: 

Upon picking up the book:

Shadow of Thel'zan the Duskbringer says: Where do you think you're going with that, mortal? Put the tome down and I might spare you an eternity of anguish.

As soon as you pick up the quest, run! More mobs will spawn until you clear the buff "Call of the Duskbringer" by getting outside of the crypt. Some select quotes:

Mindless Ghoul says: Join us...
Mindless Ghoul says: Give... me... book...

Reaching topside:

< name > says: Thel'zan's enchantment is broken! I am safe!
or
< name > says: The curse is lifted!

As for the next quote, I'm not sure, but according to the videos I have seen it should follow the first one(the speech that Thel'zan gives after taking up the quest).

Shadow of Thel'zan the Duskbringer yells: Soldiers of the frozen wastes, rise and hear the call of your master! Do not let <name> escape with the tome! 

https://wowpedia.fandom.com/wiki/Shadow_of_Thel%27zan_the_Duskbringer 
https://wowpedia.fandom.com/wiki/Secrets_of_the_Scourge
https://www.wowhead.com/quest=12312/secrets-of-the-scourge#videos

**Revision**:

**Comment by therealCrysis** [comment]
https://www.youtube.com/watch?v=mHcdg1Q4f0E   thats how it should look like.
Bugged in rev 1179. Ghouls do not appear at all.
