### ISSUE TITLE
[Quest] Matchmaker [Icecrown]

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Fordring#207]
**Description**: 
Quest is missing a combat sequence between Umbral Brutes an Skeletal Runesmiths and NPC Umbral Brute missing quotes.
https://wotlkdb.com/?quest=13147
https://www.wowhead.com/quest=13147/matchmaker
**Current behaviour**:
As you use Throw Rock (https://wotlk.evowow.com/?spell=58283) on a Umbral Brute, regardless of the distance of him and the skeletons, it automatically counts as done. No combat sequence between them, no quotes, no actual distance calculation that Umbral Brute needs close within <  > yards from skeleton.
https://www.youtube.com/watch?v=dqx--ZQtB_w
**Expected behaviour**: 
Once Umbral Brute is close enough to Skeletal Runsmith, the player uses Throw Rock on Umbral Brute, then a combat sequence should start with Umbral Brute <quote >
https://www.youtube.com/watch?v=qSFGeqnUmaY
https://www.youtube.com/watch?v=YEY36e6zeoA- 2:08
**Revision**:

**Comment by therealCrysis** [comment]
Confirmed bug in rev 1179
