### ISSUE TITLE
[Quest] Goblin quests [Zone] Dragonblight

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#213]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Most the quests are available at the start, although most of them should be part of the quest chain.

**Current behaviour**:   7 quests are available at the start.

**Expected behaviour**:  At the start only 3 quests should be available : [Nozzlerust Defense](https://www.wowhead.com/quest=12043/nozzlerust-defense), [Stocking Up](https://www.wowhead.com/quest=12044/stocking-up) and [Shaved Ice](https://www.wowhead.com/quest=12045/shaved-ice).

Both [Nozzlerust Defense](https://www.wowhead.com/quest=12043/nozzlerust-defense) and [Stocking Up](https://www.wowhead.com/quest=12044/stocking-up) should be standalone quests, with exception of [Stocking Up](https://www.wowhead.com/quest=12044/stocking-up) being OPTIONAL follow up to [Return to Sender](https://wowwiki-archive.fandom.com/wiki/Quest:Return_to_Sender).

As for [Shaved Ice](https://www.wowhead.com/quest=12045/shaved-ice) , it should start quest chain in following order:

1.[Shaved Ice](https://www.wowhead.com/quest=12045/shaved-ice)
2.[Soft Packaging](https://www.wowhead.com/quest=12046/soft-packaging)
3.[Something That Doesn't Melt](https://www.wowhead.com/quest=12047/something-that-doesnt-melt) & [Hard to Swallow](https://www.wowhead.com/quest=12049/hard-to-swallow)
4.[Harp on This!](https://www.wowhead.com/quest=12052/harp-on-this) & [Lumber Hack](https://www.wowhead.com/quest=12050/lumber-hack)

https://wowwiki-archive.fandom.com/wiki/Quest:Stocking_Up?so=search
https://wowwiki-archive.fandom.com/wiki/Quest:Shaved_Ice

**Revision**:

**Comment by Amun12** [comment]
Edit:  Four quests should be available,   the 4th being [Stiff Negotiations](https://www.wowhead.com/quest=12112/stiff-negotiations), (Which starts another quest chain https://wowwiki-archive.fandom.com/wiki/Quest:Stiff_Negotiations?so=search), Some of the quests belonging this quest chain seem to be available as well, while they shouldn't be : [Worm Wrangler](https://www.wowhead.com/quest=12078/worm-wrangler) , [Really Big Worm](https://www.wowhead.com/quest=12080/really-big-worm) and [Stomping Grounds](https://www.wowhead.com/quest=12079/stomping-grounds) .

**Comment by therealCrysis** [comment]
Confirmed in rev 1165
