### ISSUE TITLE
[Zone] Uldaman 

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Fordring#219]
[//]: # ([NPC] Thoralius the Wise)

**Description**: https://www.wowhead.com/npc=4863/jadespine-basilisk
![image](https://user-images.githubusercontent.com/62518101/163272967-83065993-b82f-4954-a9d1-37a233783e1d.png)

**Current behaviour**: npc=4863 he does not enter into combat

**Expected behaviour**:  he must enter into combat
https://youtu.be/xu7q_G9WsKA?t=2656

-------

**Description**: https://www.wowhead.com/npc=4857
![image](https://user-images.githubusercontent.com/62518101/163273931-e63446d2-419c-425c-8069-4e754ee226a5.png)

**Current behaviour**: npc=4857 he does not enter into combat

**Expected behaviour**: 
https://youtu.be/xu7q_G9WsKA?t=4000

------

**Description**:
![image](https://user-images.githubusercontent.com/62518101/163275001-7f1ed54f-5b2b-4617-8107-2a7491acb07d.png)

**Current behaviour**: The door is open

**Expected behaviour**: The door must be opened by a player
https://youtu.be/xu7q_G9WsKA?t=4626

**Comment by therealCrysis** [comment]
Confirmed bugs in rev 1179
