### ISSUE TITLE
[Zone] Stratholme

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Fordring#223]
**Description**:  https://www.wowhead.com/npc=11054/risen-rifleman
![image](https://user-images.githubusercontent.com/62518101/163288022-09b25b98-7c08-42fd-92e4-30fd57f5b102.png)

**Current behaviour**: do not aggro NPCs

**Expected behaviour**: combat should aggro all npc
https://youtu.be/cL6aW30Y6S0?t=15

-----------

**Description**: https://www.wowhead.com/object=176217/scarlet-cannon
![image](https://user-images.githubusercontent.com/62518101/163286110-e8bd5574-d8ee-476f-b5bd-783267b8cfcb.png)

**Current behaviour**: the cannon does not work

**Expected behaviour**: 
https://youtu.be/ZmSRo8AUVrI?t=137

-------

**Description**: 
![image](https://user-images.githubusercontent.com/62518101/163286931-45911a53-8cc4-421a-bc99-f51784b0ad8e.png)

**Current behaviour**: the doors do not close and there is no rat that appears

**Expected behaviour**: 
https://youtu.be/7Koqfv5M7ZM?t=68

-----
**Description**: https://www.wowhead.com/npc=10516/the-unforgiven
![image](https://user-images.githubusercontent.com/62518101/163287119-f27b31c7-5cec-44f9-9348-1f95737d9479.png)

**Current behaviour**: NPCs 10516 not appearing

**Expected behaviour**: 
https://youtu.be/7Koqfv5M7ZM?t=100

-----
**Description**: https://www.wowhead.com/npc=10399

**Current behaviour**: no dialogue after death of NPC 10399

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/62518101/163292281-4fdd2a13-ef15-49c8-a56c-20224ea666d6.png)

https://wowpedia.fandom.com/wiki/Thuzadin_Acolyte
https://youtu.be/yxQYkUJ-Xww?t=74
https://youtu.be/yxQYkUJ-Xww?t=117

-----
**Description**: https://wotlkdb.com/?npc=10808
![TIMMYTIMMYTIMMYTIMMY](https://user-images.githubusercontent.com/62518101/163289708-48d1eb5d-d7d9-452c-9d9d-c628549c15e8.png)

**Current behaviour**: where is timmy ?!

**Expected behaviour**: 
https://youtu.be/wNAS2bIwmBg

-------

**Description**: https://www.wowhead.com/npc=10439/ramstein-the-gorger
![aaaaaaaaa](https://user-images.githubusercontent.com/62518101/163290058-13c8abed-6ca5-4af9-a82a-62f566ba4aa5.png)

**Current behaviour**:
1 -  The doors don't open
2 - NPC 10439 has no dialogue
3 - NPC 10439 does not go down the steps and sticks to the door

**Expected behaviour**: 

1- dialog
![image](https://user-images.githubusercontent.com/62518101/163290418-35125d8a-5df1-4990-b336-bf5e0a876bc8.png)
2- dialog
![image](https://user-images.githubusercontent.com/62518101/163290196-1594dd13-ec4c-496b-b643-79a301d9e544.png)

https://youtu.be/cS-qzOmkkFs

--------

**Description**:
![qsqdqsdqsdqd](https://user-images.githubusercontent.com/62518101/163290690-380e754e-a5b5-4813-9aac-fa39746e7a76.png)

**Current behaviour**: 
has no dialogue
the door remains closed

**Expected behaviour**:  
1 ![image](https://user-images.githubusercontent.com/62518101/163291350-8c9276ed-15ac-4d37-9a1a-8e956c8d42c5.png)

2 When the NPCs enter the doors should open
3 When the fight is over it must close

--------
**Description**: https://www.wowhead.com/npc=10394/black-guard-sentry
![xxxxxxx](https://user-images.githubusercontent.com/62518101/163290889-6b4a6567-f2a1-4750-a7f8-f3831bc1d8ba.png)

**Current behaviour**: 
NPC 10394 has no dialogue
NPC 10394 does not go down the steps 

**Expected behaviour**:  
![image](https://user-images.githubusercontent.com/62518101/163291388-1a661b43-17cd-41b9-b1c6-a5b7b2a7d7e7.png)

https://youtu.be/aJtLv8DLyTM?t=473

**Comment by therealCrysis** [comment]
Confirmed in rev 1179
