### ISSUE TITLE
[Zone] Dragonblight; Wyrmrest Temple; Rested Buff

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Fordring#235]
**Description**: 
Rested buff is incorrect

**Current behaviour**:
Rested buff is not present when on the bottom floor of Wyrmrest Temple
![image](https://user-images.githubusercontent.com/24845497/163628291-b5d3b947-6007-47ac-8fa3-29d9e3d61086.png)
It is present when "outside" the bottom floor
![image](https://user-images.githubusercontent.com/24845497/163628381-1b5043db-926d-41e5-96d3-c8e137e073e3.png)

**Expected behaviour**: 
Rested Buff is present inside Wyrmrest Temple

**Revision**: 
1048

**Comment by Dirtsleeper** [comment]
Yes, I will when server is back up

**Comment by Dirtsleeper** [comment]
https://streamable.com/20pycf

**Comment by FX-SF** [comment]
I confirm having the same issue. No rested XP in what people would expected it to occur (even standing in interacting distance to innkeeper).

Additionally, when speaking to the innkeeper, I clicked the option "make this inn my home" without accepting the follow up prompt that asks "Do you want to make Wyrmcrest your home?". It binded my hearthstone to this innkeeper, even though i did not confirm the action.
