### ISSUE TITLE
[Quests] [1] Fringe Science Benefits and [2] Amped for Revolt!

### ISSUE THREAD

**Issue by babayago** [Stormforge-gg/Bugtracker-Fordring#256]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Both quests are obtained from Fringe Engineer Tezzla (ID = 32430) (https://www.wowhead.com/quest=13373/fringe-science-benefits) (https://www.wowhead.com/quest=13374/amped-for-revolt) in Icecrown.

**Current behaviour**:
Quest can be picked up but it I'm unable to speak to Rizzy Ratchwiggle (ID = 31839). It doesn't matter if I only pick up one quest (tried both orders) or both at the same time.

![Unbenannt](https://user-images.githubusercontent.com/103358327/163881434-711126be-9636-4855-bd32-0428f1b71c3b.png)

**Expected behaviour**: 
It should be possible to talk to Rizzy Ratchwiggle after getting either quest and ask for a Bomber.

**Revision**:

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/497
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/496

Alliance equivalent on alpha test bugtracker, for info.

**Comment by asprintab** [comment]
Any further info needed on this? Trying to start the quest but theres no way to finish it after accepting it.

**Comment by Cold-Martijn** [comment]
> Any further info needed on this? Trying to start the quest but theres no way to finish it after accepting it.

basically, data. all available videos, sniffs, etc. etc.

**Comment by asprintab** [comment]
Not sure I have anything but the above screenshot, quest says talk to the NPC named, but if you go to the NPC, theres no option to take any action.

**Comment by Cold-Martijn** [comment]
No, it is known that it is not working :) but there is data needed on how exactly it should work, so that it can be implemented :D

**Comment by asprintab** [comment]
I found https://youtu.be/4SZJb0IzH00?t=62
