### ISSUE TITLE
[NPC][Spell][Warlock] Demonic Immolation Passive (infernal)

### ISSUE THREAD

**Issue by MildlyDampTowelette** [Stormforge-gg/Bugtracker-Fordring#287]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When the Infernal takes damage, it has a 15% chance of bursting into fire doing damage to all who strike it for until cancelled. (https://wotlkdb.com/?spell=4525. ) 

**Current behaviour**:
It does not appear to proc at all. I've had entire groups of mobs rail on the infernal and it did not proc once over infernal durations.

**Expected behaviour**: 
The infernal should burn things every now and then

**Revision**:

**Comment by MildlyDampTowelette** [comment]
https://www.youtube.com/watch?v=7cuyUfokGg8&ab_channel=SuliferCroft
Infernal in action, can't seem to find one from wotlk for now. I will keep looking.

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
