### ISSUE TITLE
[NPC[[SPELL][WARLOCK] Doomguard (3)

### ISSUE THREAD

**Issue by MildlyDampTowelette** [Stormforge-gg/Bugtracker-Fordring#293]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Doomguard seems a little weak, being both low level and having low stats/damage
**Current behaviour**:
Doomguard summoned through CoD appears to range somewhere from lvl 56-67, and having low stats and damage. The doomguard gains no stats from the master after enslave demon. 
https://imgur.com/a/kSiZ1US 
**Expected behaviour**: 
I have been trying to figure out the stat scaling of the Doomguard, but is has been difficult to find anything.  
Here is a discussion on the Doomguard dps on wowhead from way back.  https://www.wowhead.com/npc=11859/doomguard#comments  
'Dealing up to 1300 DPS the Doomguard is now a very viable pet to use in raids. Whenever the ritual is not on cooldown you can summon him for some extra DPS. Other than that he has great survivability, his HP pool seems to be around 40k. This is probably the most underrated tool in the warlock arsenal.'
 This is one of the few videos on the Doomguard and its taken in TBC, showing a Doomguard that is vastly stronger than the ones I summoned. I wish I could say what the proper scaling should be 
https://www.youtube.com/watch?v=3tYPzOyUPm4&ab_channel=abysswalker21

**Revision**:

**Comment by MildlyDampTowelette** [comment]
https://wowwiki-archive.fandom.com/wiki/Patch_3.0.8#Warlock_2
 'A Doomguard summoned with this spell will now scale properly from its master's stats.'

**Comment by MildlyDampTowelette** [comment]
Here is an old wotlk video seeing a bunch of doomguards summoned through CoD. All of them seem to be lvl 80 when summoned, have much more HP than the ones on the beta server and do way more damage (whilst hitting a tree form druid)
https://www.youtube.com/watch?v=EVZIKSmYyvs&ab_channel=MarieMasiello

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
