### ISSUE TITLE
[NPC] Blight Geist

### ISSUE THREAD

**Issue by CosminPOP** [Stormforge-gg/Bugtracker-Fordring#297]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
During the quest It Rolls Downhill(12673), you have to use Scepter of Suggestion (39157) on a Blight Geist(28750) and have him collect some crystals.
**Current behaviour**:
Clicking attack on pet bar will make the controlled geist rooted and in a attack stance but he won't move.
Like on #7 
![image](https://user-images.githubusercontent.com/7255825/166925141-0ef2b877-95c6-458f-9c52-33212ab205c3.png)

**Expected behaviour**: 
Pet should run to target and attack.
**Revision**: 
1094

Note that this bugged behavior applies on next quests 12686, 12690, and 12713, with the creatures that you have to control and with Bloated Abominations it only bugged sometimes and allows you to explode the abomination over and over without it despawning, however, dismissing the abomination will hide your pet bar but the abomination will still follow you around.

**Comment by FX-SF** [comment]
Reminds me of the Ravenger's lvl 70 daily quest in terrokar forest/HFP where you control a ravenger.

**Comment by therealCrysis** [comment]
Seems to be kind of tricky in rev 1184.
Geist works normally when you attack first mob after using scepter on him, but he will not move to attack the next until you bring mob next to him.
