### ISSUE TITLE
[Global] Quest Guardians attack critters

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#325]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://youtu.be/aWBFPql6YTw

**Comment by CosminPOP** [comment]
Constructs too
![image](https://user-images.githubusercontent.com/7255825/167239545-a7d6ae17-9f40-4c4d-8f97-787bd6898a0b.png)

**Comment by therealCrysis** [comment]
Kind of poor description. What exactly is wrong here?

**Comment by Vishiswaz** [comment]
Guardians shouldn't randomly aggro neutral critters. They should ignore them.

Guardians should attack aggressive mobs. I'm not sure if they would attack neutral npc mobs but definitely not critters.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
