### ISSUE TITLE
[PET][WARLOCK] Doomguard pet/auto attack

### ISSUE THREAD

**Issue by MildlyDampTowelette** [Stormforge-gg/Bugtracker-Fordring#328]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After dealing a killing blow with Curse of Doom, a doomguard will spawn that can be enslaved by warlocks.
**Current behaviour**:
The doomguard that spawns does not autoattack the warlock, despite showing up as hostile and following the warlock in an attempt to attack him. Similarly once the doomguard is succesfully enslaved, he won't autoattack mobs through the petattack ability. 
**Expected behaviour**: 
The doomguard should start attacking the warlock when summoned though CoD, and after enslavement, he should be able a auto attack mobs through the pettattack ability
**Revision**: 
1125

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
