### ISSUE TITLE
[PET][WARLOCK] Enslave Demon/ Soul Link

### ISSUE THREAD

**Issue by MildlyDampTowelette** [Stormforge-gg/Bugtracker-Fordring#330]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Warlocks are able to enslave demons in the open world as well as their own summons (Infernal and Doomguard.
Soul Link can share the damage taken by the caster with these enslaved demons.
**Current behaviour**:
In the case of the doomguard, I simply can't cast the Soul Link at all, similar to any demon under my control through the Enslave Demon ability. The game presents the error message: 'you do not have a pet'. 
I am able to cast Soul Link on the Infernal, but it does not apply the Soul Link effect.
**Expected behaviour**: 
After enslaving demons, I should be able to cast Soul Link and apply the Soul Link effect on enslaved demons as per the tooltip. 
**Revision**: 
1125

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
