### ISSUE TITLE
[Zone][Elwynn Forest] Mining Nodes

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#332]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I found two copper ore nodes at the same location at the same time, this should not be possible.

Location 1 where this happened:
![WoWScrnShot_050722_113850](https://user-images.githubusercontent.com/78314117/167261444-e917aef6-8f13-4577-ad94-8590e0e40e34.jpg)
![WoWScrnShot_050722_113855](https://user-images.githubusercontent.com/78314117/167261447-bbc3f85f-ca53-49b8-8a80-5446b7a499fb.jpg)

Location 2:
![WoWScrnShot_050722_114313](https://user-images.githubusercontent.com/78314117/167261637-c2591e6b-014c-4e61-b68a-904f38f576c7.jpg)
![WoWScrnShot_050722_114317](https://user-images.githubusercontent.com/78314117/167261638-98ee72a8-f777-4162-96e2-5f974c12998d.jpg)

Location 3:
![WoWScrnShot_050722_114505](https://user-images.githubusercontent.com/78314117/167261677-49d0682d-0051-40d3-b449-44090ad6b812.jpg)
![WoWScrnShot_050722_114518](https://user-images.githubusercontent.com/78314117/167261678-0554f2f2-3bb8-40e0-9b52-3d7314560684.jpg)
![WoWScrnShot_050722_114523](https://user-images.githubusercontent.com/78314117/167261679-2348bf3e-7449-40d6-b7b7-d9f0ad8c813b.jpg)

**Comment by Nuy** [comment]
Mining nodes seem to be broken in general, not just in some zones. I checked Un'goro and encountered similar issues with veins. The problem seems to be that in all POSSIBLE spawning spots veins are spawned what's not correct. In a spawn spots pool only a certain amount should be spawned at a time so if FOR EXAMPLE there's 100 possible thorium vein spawn points only 30-40 can be up at a time and currently 100/100 are up.

**Comment by Vishiswaz** [comment]
Yes, there are multiple issues here. Dynamic respawn isn't working at all, as you've mentioned. And there are also some nodes that have duplicates or are in the wrong place.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
