### ISSUE TITLE
[NPC][Movement] Bat Rider Guard in Terokkar Forest

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#337]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Flying Guards In Terokkar Forest (and possibly other locations) do not properly stay in combat range and will fall straight to the ground.

**Current behaviour**: Flying guards will target you and apply Guard's Mark (hunter mark). They will attempt to enter melee combat with the player, but will drop straight to the ground if the positioning of the mob and the player are under the right conditions

**Expected behaviour**:  Flying guards should target and apply the mark, They should attempt to chase player into melee combat and continue to reach the players melee range should the player move. They should also cast some form of fireball that once it hits the player, he is auto dismounted, often occuring in the players death to fall damage. The fireball spell I saw from Atlantiss TBC servers only, and do not recall the feature in vanilla TBC. 
**_They should not drop to the ground as seen in the video._**

**Revision**: 1125

https://user-images.githubusercontent.com/105084838/167263330-df49b7e4-84e3-404e-b07d-55dddea6cbea.mp4

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
