### ISSUE TITLE
[NPC] ZUL'FARRAK

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Fordring#35]
![position](https://user-images.githubusercontent.com/62518101/162461361-9114f58e-79fe-46d7-812f-97107b3ef903.png)
Current behaviour:  The out of combat position is bad

Expected behaviour:  https://youtu.be/I9dOA-PktnM?t=1176 

![Sans titre](https://user-images.githubusercontent.com/62518101/162462828-a8a64966-fdfc-447b-89bc-eb543bab890c.png)
Current behaviour:  Bad movement
Expected behaviour:  https://youtu.be/lTEYkfSTaPI?t=2312 

![position 2](https://user-images.githubusercontent.com/62518101/162464261-b9a04966-8e46-4052-9e34-14e07aa74175.png)

**Comment by duzyizly** [comment]
Pyramid event stops if NPCs/player get into combat "after unlocking cages / before talking to bly".
They just stay here, do nothing, there's no dialogue avabile.
![image](https://user-images.githubusercontent.com/43931626/162590163-49258989-daba-423e-8243-2a390d9165e4.png)
