### ISSUE TITLE
[Zone][Ragefire Chasm] Possible Incorrect NPC mechanics

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#355]
1) The Ragefire Shaman currently runs in fear at about 10% hp, but a video from 2009 (WotLK expansion era) shows Ragefire Shaman's not running in fear. 

   Evidence: https://www.youtube.com/watch?v=EO07iQl9M10&ab_channel=JoshStrifeHayes
   @5:35, @7:00, @7:15

2) The Voidwalker Minion currently casts a spell named "Void Drain" about 10-14 seconds after agro, but a video from 2009 (WotLK expansion era) shows Voidwalker Minion never stops or cassts Void Drain.

   Evidence: https://www.youtube.com/watch?v=6kj-Anvqw-k&t=311s&ab_channel=DarkspireStudios
   @3:30 @7:15 

3) If you kill a Searing Blade Warlock before the Voidwalker Minion is destroyed, the Voidwalker Minion will despawn, but a video from 2009 (WotLK expansion era) shows Voidwalker Minion does not despawn upon Searing Blade Warlock's death.

   Evidence: https://www.youtube.com/watch?v=6kj-Anvqw-k&t=311s&ab_channel=DarkspireStudios
   @7:45

**Comment by Godmatik** [comment]
> If you kill a Searing Blade Warlock before the Voidwalker Minion is destroyed, the Voidwalker Minion will despawn, but a video from 2009 (WotLK expansion era) shows Voidwalker Minion does not despawn upon Searing Blade Warlock's death.

This is a global issue that probably needs its own bug report as it affects a lot of mobs, not just the one inside RFC - and it is present in every stock Wrath server I have played on.

If a mob has a pet/minion/totem/companion/whatever - and you kill the mob, then that pet just despawns, when it should still stay alive and have to be be killed as well.

**Comment by Vishiswaz** [comment]
The thing is, some mobs are supposed to have their pets despawn if the owner dies, and some don't. It shouldn't be global, but it is.

**Comment by FX-SF** [comment]
I will gather some quick data for the pets and create a separate ticket for that, or check if there already is one

**Comment by Godmatik** [comment]
> The thing is, I think some mobs are supposed to have their pets despawn if the owner dies, and some don't. It shouldn't be global, but it is.

At least on classic - haven't run into a single one where this happens.

**Comment by Vishiswaz** [comment]
I could definitely be wrong. Years of poisoned memories from different pservers.
