### ISSUE TITLE
[NPC] Mannoroc Lasher

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#359]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: These mobs aren't spawning correctly. Only 1 or 2 spawn points are up in Demonfall Canyon while they should be at least 5.

**Current behaviour**: There almost no Mannoroc Lashers around the Demon Fall Canyon area in Ashenvale.

**Expected behaviour**: There should be plenty of Mannoroc Lashers around the Demon Fall Canyon area in Ashenvale. https://tbc.wowhead.com/npc=11697/mannoroc-lasher#comments

**Revision**: 1125

**Comment by FX-SF** [comment]
This was an issue on Atlantiss Karazhan as well. Only ~2 spawned outside the entrance of the Demon Fall Canyon area at any given time. It was annoying quest, but It might be Blizzlike.

**Comment by Nuy** [comment]
> This was an issue on Atlantiss Karazhan as well. Only ~2 spawned outside the entrance of the Demon Fall Canyon area at any given time. It was annoying quest, but It might be Blizzlike.
> 
> HOWEVER! The last 3 seconds of this video might have some info? (shows two very close to one another) https://www.youtube.com/watch?v=2eEOpGWVKWo&ab_channel=KingAbz

The ones outside the canyon share spawn points with other demons but ones inside it should have their own spawn points.

**Comment by FX-SF** [comment]
I will look first hand since i havent and check the places you are mentioning first before continuing

**Comment by Nuy** [comment]
I did this quest many times on other private servers and outside the canyon there was always very few of them but inside the canyon there were 4-5 constant spawn points so it was easy to do by just looking for them there. 

![opera_t89EQkO7f0](https://user-images.githubusercontent.com/4800827/167436606-94dd9b59-a519-4931-8b87-55bd56515771.png)

**Comment by therealCrysis** [comment]
Confirmed in rev 1184

**Comment by Nuy** [comment]
Sorry for being annoying, I know the devs are busy enough as it is but can this get fixed befor launch? It really turns good and viable quest into an annoying what can piss off a lot of people that gona do it.

**Comment by aglarcz** [comment]
Unfortunately its still bugged. Please fix.
