### ISSUE TITLE
[Quest][The Storm Peaks] Examples to be Made

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#368]
**Description**: The quest "Examples to be Made" asks the player to slay Garhal. The fight area consists two Hyldnir Overseers (friendlies), two Captive Vrykul (neutral), and Garhal (neutral).

**Current behaviour**: When attacking Garhal, a sequence occurs, with some following results:
a) Each Hyldnir Overseer and Captive Vrykul attack each other in a symmetric fashion, while you and Garhal begin to fight. 
b) Upon killing Garhal, the Overseers **will continue to outpower** the Vrykul, slay the Vrykul, and then end their combat cycle.

**Expected behaviour**: The Overseers and the Vrykul **will stop combat** and reset themselves upon the death of Garhal

**Revision**:  1125

Small detail:  
1) When attacking a single Captive Vrykul, no other NPC in the fight area enters combat. 
2) The Overseers will not attack Garhal, even after ending their combat cycle.
3) Did not investigate if these two details exhibit the intended behavior. 

Video Evidence of Current Behavior: https://user-images.githubusercontent.com/105084838/167321002-73f4c998-6e08-4c0f-9fa8-4ff224b51fe6.mp4
Video Evidence of Expected Behavior: https://youtu.be/vBIto09R7dI?t=20

**Comment by Wolffenstein** [comment]
1. and 2. are intended

**Comment by FX-SF** [comment]
Behavior 1 (Garhal instakilled)
https://www.youtube.com/watch?v=RnOAMgwaSXk&ab_channel=WorldOfWarcraftGuidesAndGameplay
](https://youtu.be/2UoJ9azBWBk?t=14)

Behavior 2 (Garhal Instakilled)
https://youtu.be/26SRgl3ZKK8?t=16

Behavior 3 (Slow Garhal Kill and mob add resets)
https://youtu.be/vBIto09R7dI?t=25

Behavior 4 (Overseer attack a single Vrykul, shows reset of mobs, but then Overseer attacks other Vrykul, who never entered combat)
https://youtu.be/RnOAMgwaSXk?t=15

Behavior 5 (No add agro period)
https://youtu.be/Wzzi2lZk0Ts?t=21

Behavior 6 (Expected behavior, except Captive Vrykul attack the Overseers first)
https://youtu.be/jt0uKtPJ0iw?t=12

Behavior 7 (No Overseers present upon pull, Captive Vrykul do not enter combat unless forced)
https://youtu.be/3glMMJEQfBY?t=12

Fuck it idk what to say, you can see often there is some sort of reset script occuring. But even over 7 videos spanning 12 years, the expected behavior seems bugged in general.
