### ISSUE TITLE
[NPC] Mobs with pets

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#373]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Currently when you kill a mob with pet/minion it just disappears.

**Current behaviour**: Mob's pet/minion disappears when its master dies,

**Expected behaviour**: Mob's pet/minion should still be alive after its master dies. It worked correctly on NW/Karazhan.

**Revision**: 1125

**Comment by therealCrysis** [comment]
It was mentioned in this issue - https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/355
