### ISSUE TITLE
[NPC] Library Guardian - Unpolished Placement/Pathing

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#374]
**Description**:  
There exists several mobs in the game named "Library Guardian" in the Storm Peaks, South of Ulduar on the Terrace of the Makers. Their positioning and pathing is somewhat unpolished compared to a video from 2013 (see expected behavior video).

**Current behaviour**: 
The Library Guardians have a general unpolished look to their placement/pathing in the game, mainly on the elevated portion named "The Inventor's Library". It currently looks like this:

- https://user-images.githubusercontent.com/105084838/167480399-241ad5f8-aa9c-4449-80de-1d2bbafd44d4.mp4

**Expected behaviour**: 
   The Library Guardians should have a more symmetrical and polished look, such as in this 2013 video:

- https://youtu.be/H9Hng8V7kWU?t=49

**Revision**:  
1125

Additional Notes: The Databanks, another type of NPC (friendly), also seem to be placed incorrectly, but this is less noticeable (for example, they do not move).
I feel there are more important quests to work on atm than this at the time of writing this.

**Comment by therealCrysis** [comment]
Minor issue, yet Confirmed in rev 1184
