### ISSUE TITLE
[Spell][NPC][Nagrand] Water Bolt (Not Casted)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#379]
**Description**: [Water Bolt](https://tbc.wowhead.com/spell=34425/water-bolt) is a spell casted by [Crashing Wave-Spirit](https://tbc.wowhead.com/npc=22309/crashing-wave-spirit) and [Lake Spirit](https://tbc.wowhead.com/npc=17153/lake-spirit)

**Current behaviour**: They melee attack, They do not cast Water Bolt

**Expected behaviour**: They melee attack, occasionally casting Water Bolt

**Revision**: 1138

hard to find a video pre-cata.
https://www.youtube.com/watch?v=9Tvln8ixG2Y&ab_channel=Protcow
(fire mage talents mess with the video :/)

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
