### ISSUE TITLE
[NPC][Isle of Quel'Danas] Abyssal Flamewalker (non-targetable)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#380]
**Description**: Abyssal Flamewalker is a mob that roams around the Dawning Square on the Isle of Quel'Danas. You may slay him as an optional mob for quest credit in The Battle Must Go On.

**Current behaviour**: You **CANNOT** target or attack Abyssal Flamewalker

**Expected behaviour**: You **CAN** target or attack Abyssal Flamewalker

**Revision**: 1138

Quest is completeable
![image](https://user-images.githubusercontent.com/105084838/167510127-b1d8d1d7-2c5d-4343-ba48-fc17a16d972a.png)
![image](https://user-images.githubusercontent.com/105084838/167510790-6e12fa4f-5c4a-49c8-9ada-346e5c378b43.png)

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
