### ISSUE TITLE
[NPC] Utgarde Pinnacle: Svala Sorrowgrave

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#381]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pathing on Svala is wrong in some places, causes a loop. https://youtu.be/PeZRK408SRA

**Comment by FX-SF** [comment]
Revision: 1138

**Comment by therealCrysis** [comment]
Confirmed in rev 1184

**Comment by Vishiswaz** [comment]
Closing due to new server core.
