### ISSUE TITLE
[Zone][Violet Hold] Violet Hold Guard

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#388]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Sometimes the Violet Hold Guards and their enemies just kinda chill and look at each other. https://youtu.be/7aF1FQCe_us

(worst instance of it at 1:00 in the video)

**Comment by therealCrysis** [comment]
minor issue, yet Confirmed in rev 1184

**Comment by Vishiswaz** [comment]
Closing due to new server core.
