### ISSUE TITLE
[NPC] Borean Tundra- Arcane Serpent 

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#391]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: Currently they are all following the same patrol path, stacked on top of each other (different Y axis).

**Expected behaviour**: They each should have difference spawn points around the Nexus. Static spawn points, no patrolling.

**Revision**: 1138

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/637
alpha report for easier closing.

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
