### ISSUE TITLE
Complete List of Errors Discovered Within The Wailing Caverns

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#399]
There is an Alpha Ticket somewhere similar to this one. I cannot find it (unsure where to look)
Here is a list of all unpolished issues we could find. There is plenty of video evidence, comments and guides from 12-14 years ago (WotLK expansion era). All with the exception of the Escort Quest at the end was not game breaking. Most are just in need of polish.

1) Disciple of Naralax gives buff upon speaking to him. He should give option to buff you.
2) Lady anacondra spawns in same spot every time. she should spawn in 1 of 4 random locations
3) Mad magglish spawns in the same spot every time. He should spawn in 1 of 3 random locations
4) Deviate guardians do not cry for help. They should cry for help
5) Kresh and some deviate crocodiles (mostly ones in water) have an accelerated move animation. They should have a much slower move animation
6) There is a tough 6 man pull with a snake right before Lord Cobrahn. The snake should move a bit in such a way where you can agro 3 of those 6 mobs.
7) lord cobrahn has 2 snake adds. he should have 3 snake adds.
8) There is no RP yell upon the deaths of the leaders of the fang, but instead upon talking to disciple after their deaths. He should immediately yell RP upon death of all 4 leaders of the fang
9) Serpentbloom snakes do not move or despawn ever. They should move some and eventually despawn over time.
10) Cloned ectoplasm does not immediately agro upon summon. It should agro upon summon.
11) Skum does not flee at low health. He should flee at low health
12) 3 of the 4 leaders of the fang do not cast healing touch. They should cast healing touch
13) The escort quest is a bit buggy and i will make a seperate ticket for that

I was unable to research this:
1) Verdan the Everliving's attack speed **_seemed_** slower than intended (known to hit super hard= 300damage on warrior)

**Revision 1138**

**Comment by therealCrysis** [comment]
rev 1184

1. Not a bug.
2. Minor issue, yet confirmed.
3. Confirmed Bug
4. Not sure about that, I did WC today on Classic and did not notice them calling for help.
5. Confirmed Bug
6. Confirmed Bug
7. Confirmed Bug
8. Not sure about that.
9. Not a bug.
10. Ectoplasm aggroes immediately. Deviate Moccasins and Mutanus the Devourer DO NOT while they should.
11. Not a bug.
12. Confirmed Bug
13. Seemed to work quite fine.
