### ISSUE TITLE
[Spell][Mage] Spellsteal + Spell Reflect 

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#400]
**Description**: In the past, I have always found that casting Spellsteal on a mob that has Spell Reflect active would cause a unique behavior.

**Current behaviour**: Casting Spellsteal on the mob does nothing

**Expected behaviour**: Casting Spellsteal on the mob transfers a seemingly random mage buff to the mob.

**Revision**: 1148

I am told Spellsteal has many more issues, all which are reported in the alpha bugtracker
Tested on Dragonblight Mage Hunters in Dragonblight.
Tested on a mob before 1st boss in AQ 40.

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
