### ISSUE TITLE
[Zone][Crystalsong Forest] ToC Tournament Music

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#403]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While idle in Crystalsong Forest, after a while of being afk in a background window, I randomly heard the quick ToC Tournament music that plays when you start each encounter in the 5-man dungeon. I then heard it again. And then again. And then it stopped.

This might be tied to some scripted event up in Dalaran above me. But it shouldn't be heard in Crystalsong Forest. And indeed it's possible this should be disabled entirely until 3.2.

Here's where my character is.
![WoWScrnShot_051022_210226](https://user-images.githubusercontent.com/78314117/167748583-21ad7f0a-45cc-4805-b6a9-2910937840bd.jpg)
![WoWScrnShot_051022_210237](https://user-images.githubusercontent.com/78314117/167748584-e9214a01-1bd5-48e9-9f28-b21908395ed9.jpg)

**Comment by FX-SF** [comment]
revision 1148

**Comment by Vishiswaz** [comment]
NOTE: I think this happens when the Argent Peacekeeper NPCs and Jaeren Sunsworn appear in Dalaran.

WHICH THEY SHOULD NOT BE DOING IN 3.0. I don't know if it's 3.1 or 3.2 but they should not be in Dal in 3.0.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
