### ISSUE TITLE
 [NPC][Shadowmoon Valley] Doomwalker

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#412]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Issue 1: Doomwalker doesn't appear to be using his Overrun ability.

Issue 2: Doomwalker's Sunder Armor shouldn't be dodge-able or parry-able, otherwise it's no threat to a tank at all even in TBC, as it will rarely get high in stacks at all.

Issue 3: Doomwalker doesn't appear to be using his Earthquake ability.

Issue 4: Doomwalker doesn't appear to be using his Chain Lightning ability on the primary aggro target. Not sure if bug.

Just like I mentioned on my Doom Lord Kazzak ticket, this world boss is often farmed by WotLK players for the hefty amount of gold it drops. Don't make it super easy for them!

**Comment by FX-SF** [comment]
revision 1148

**Comment by therealCrysis** [comment]
Confirmed in rev 1184

**Comment by Evolvee** [comment]
fixed in next rev
