### ISSUE TITLE
[Zone] Hellfire Peninsula - Infernal RP Event at Thrallmar - no script

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#420]
**Description**: There is an RP event that frequently occurs at the Supply Caravan just outside the entrance to Thrallmar in Hellfire Peninsula. Infernal Invaders attack a group of bloodmages, Arcanist Torseldori, and Sergeant Shatterskull.

**Current behaviour**: The Infernal Invader spawn as a group. They often just stand there and do nothing.

**Expected behaviour**: The Infernal Invaders will utilize a common infernal animation upon being spawned where a ball of felrock falls from the sky, lands on the ground and the infernal will spawn with a fire explosion of sorts. The Infernals will then attack the group of bloodmages and the other horde NPCs.

**Revision**: 1148
![image](https://user-images.githubusercontent.com/105084838/167963671-c2441b8c-e9a0-4e7d-9063-b5a857c07bfb.png)

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
