### ISSUE TITLE
[NPC] Fel Soldier

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#421]
**Description**: There is a mob named Fel Soldier in Hellfire Peninsula. 

**Current behaviour**: You can agro the mob and bring it all the way back to Thrallmar without attacking the mob, effectively killing all NPC givers in the city.

**Expected behaviour**: There should be some form of Leash to prevent the mob from traveling very far if it is not being hit

**Revision**:  1148

![image](https://user-images.githubusercontent.com/105084838/167966011-bd13bae5-9e85-4a6f-bd0b-f864a2b2260c.png)

https://user-images.githubusercontent.com/105084838/167967005-226dc72c-67c1-4598-b38f-48be70b4e132.mp4

**Comment by therealCrysis** [comment]
Confirmed in rev 1184
