### ISSUE TITLE
[Spell][Druid][Warrior] Charge/Feral Charge - Bear

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#435]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Right now it's possible to SOMETIMES (when charging path is at a certain angle) fall under textures. In arena it happened in Ruins of Lordaeron to druid using Feral Charge - Bear when we were testing. If it's not possible or it's very hard to COMPLETELY fix it then I think on arena there should be a system in place just in case so when it happens it will teleport/spawn a person who fell under textures in the middle of the arena, otherwise such arena is just lost for him.

**Current behaviour**: It's possible to SOMETIMES fall under textures using Charge/Feral Charge - Bear.

**Expected behaviour**: It shouldn't be possible to fall under textures using Charge/Feral Charge - Bear. If it can't be COMPLETELY fixed then a person who fell under textures in arena should be teleported/spawned in the middle of the arena. 

**Revision**: 1148

**Comment by Vishiswaz** [comment]
Any chance you can get some footage for them?

**Comment by Nuy** [comment]
![WoWScrnShot_051122_235439](https://user-images.githubusercontent.com/4800827/168136095-a0fe0deb-cd54-4a07-b5cf-4d43fc8a7001.jpg)

He was unable to get out until increasing his size.
