### ISSUE TITLE
[Object][Icecrown][Ogrim's Hammer] Warsong Cannon - Possible Improper Scripting

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#439]
**Description**: As an opposing member of the Horde, an Alliance player can somewhat interact with the Warsong Cannon located on Ogrim's Hammer in Icecrown.

**Current behaviour**:  The Warsong Cannons cannot be targeted. Cannons are stationary. If you enter melee range with the Cannon, it will melee attack. If you move outside Cannon's melee range, Cannon attempts to perform script combat (see combat log in picture below)

**Expected behaviour**: Personally do not know. I expect that the Cannon's will shoot at the player when not in melee range. I expect Cannon's do not melee attack.

**Revision**:  1148

![image](https://user-images.githubusercontent.com/105084838/168148824-22235f74-536f-44cb-bbca-bd2262aee8f9.png)

https://user-images.githubusercontent.com/105084838/168148876-a1434293-5ff3-443a-8a43-6655f970b773.mp4

**Comment by Vishiswaz** [comment]
Needs retail check
