### ISSUE TITLE
[Death Knight] Summon gargoyle and rune weapon

### ISSUE THREAD

**Issue by danniellos94** [Stormforge-gg/Bugtracker-Fordring#44]
Hello I wanna say that summon gargoyle and dancing rune weapon are hella bugged.

1. summon gargoyle with 0 haste and 0 haste buffs and blood pressence should cast gargoyle strike 12 times

30:2.5 = 12

But here I have icy talons + unholy presence +5% haste from items + engineering gloves and I've got 11 casts....

2. Dancing rune weapon is getting miss/parry/dodge with hit cap and expertise cap

Dots from rune weapon are hitting 30 while mine hits for 400-500
Other spells are not doing 50% of damage... Without items and with tyrannical beheader its doing 70% of damage and with all items its doing way less than 50% of damage.

**Expected behaviour**: 

Gargoyle have no gcd cap.
"Current status of gargoyle:
-scales with all physical haste benefits at the same rate as the player
-attack power coefficient is 0.4
-base damage per strike is 120
-does not inherit any crit from the player
-does not inherit any +damage % modifiers from the player, such as bone shield, desecration, or blood presence
-player stats are taken as a snapshot when the gargoyle is launched; that is, when you cast this spell, however much attack power and haste is the amount your gargoyle strikes will be basing themselves off of."

DRW damage should do 50% of deathknight's damage, crit chance and stats should be taken of dk for autoattacks.

**Revision**: 

https://www.wowhead.com/spell=49206/summon-gargoyle#comments
https://wowwiki-archive.fandom.com/wiki/Dancing_Rune_Weapon
https://www.wowhead.com/spell=49028/dancing-rune-weapon

**Comment by Wolffenstein** [comment]
1. should be fixed

**Comment by therealCrysis** [comment]
@danniellos94  Have you managed to test it once again?

**Comment by danniellos94** [comment]
DRW missing summon? How you can miss summon? Imagine missing summon gargoyle.... Dots hitting 13 mine 500. Yep not working.
https://prnt.sc/lnDIh3ewL5Qz

Gargoyle casting 12 times I've summonned him with icy talons unholy pressence and gloves.  He should cast 12 times in blood pressence...
https://prnt.sc/cEiOQBbA9VFS
