### ISSUE TITLE
[NPC][Wintergrasp] Alliance Brigadier General

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#452]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[In addition to there being two inside the fortress](https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/446) while Alliance controls WG, they are also selling Commendations of Service. This was not a thing until either 3.3 or 3.3.3 or 3.3.5, I'm not sure which.

The good news is, one of them correctly has a patrol path.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Cold-Martijn** [comment]
is this report still valid?

**Comment by Vishiswaz** [comment]
Closing due to new server core.
