### ISSUE TITLE
[Zone][Wintergrasp] Retaining WG Buffs upon exit.

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#457]
**Description**: Corporal is a buff obtainable in Wintergrasp.

**Current behaviour**: Leaving Wintergrasp does not remove Corporal buff.

**Expected behaviour**: Leaving Wintergrasp should remove all Wintergrasp related buff, (i.e., Corporal.

**Revision**:  1165

![image](https://user-images.githubusercontent.com/105084838/168189852-4bf4d580-a14f-4ff4-9136-fc40db36d64c.png)

**Comment by NatsumeLily** [comment]
Believe it or not this might be blizzlike. You just lose the rank buff if you log out or when the battles begins. Up to the Devs how to handle this one though. 

![image](https://user-images.githubusercontent.com/15247730/168399417-2a302c17-2d10-4bfa-968e-181fbbafd130.png)

**Comment by Cold-Martijn** [comment]
is this still valid?
