### ISSUE TITLE
[Zone][Wintergrasp] Mob Aggro

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#458]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Issue 1: Mob aggro radius looks low

Issue 2: If you aggro guards while in a vehicle by attacking from far, they run to you, but if you exit the vehicle, they reset. Instead, they should continue to attack the vehicle.

Issue 3: If guards are attacking an empty vehicle and you enter it, the mobs attacking it reset.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Cold-Martijn** [comment]
is this still valid?

**Comment by Vishiswaz** [comment]
Closing due to new server core.
