### ISSUE TITLE
[Zone][Wintergrasp] Wall Resets

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#459]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Not all of the walls are resetting when a new battle starts.
![WoWScrnShot_051222_205532](https://user-images.githubusercontent.com/78314117/168190405-b7de16d5-f848-4557-b054-9631b07e026e.jpg)
 

Okay, so for my friend, who's on horde side, he shows the wall as repaired on his end. I have no idea how this happened. But that's potentially a huge problem if the attacking faction just occasionally sees walls as not repaired and can waltz right in.

**Comment by FX-SF** [comment]
revision 1165

**Comment by Cold-Martijn** [comment]
is this still valid?

**Comment by Vishiswaz** [comment]
Closing due to new server core.
