### ISSUE TITLE
[NPC][Dalaran] Sunreaver Agent

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#479]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://youtu.be/QetUpOe48tM 

This mob is kiteable to the alliance area in Dalaran (and everywhere in Dalaran), and that's blizzlike. But what's not blizzlike, is that apparently the Silver Covenant Guardian Mages are supposed to teleport them out if you bring them into the alliance area, the same as they do to players. Not sure exactly how that works, but... 
![image](https://user-images.githubusercontent.com/78314117/168205472-c9381dbf-cf66-43af-8e7a-20b3582c0a8b.png)
Anyways, low priority but, lol

**Comment by FX-SF** [comment]
revision 1165

**Comment by Vishiswaz** [comment]
Closing due to new server core.
