### ISSUE TITLE
[Zone][Durotar] Mining Nodes

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#483]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
1. This mining node is in the wrong location.
![WoWScrnShot_051322_171157](https://user-images.githubusercontent.com/78314117/168390742-9d518662-14fe-4ba8-a05c-09b67952d57a.jpg)
![WoWScrnShot_051322_171205](https://user-images.githubusercontent.com/78314117/168390744-cfe1b805-1018-40ad-b465-042298fc0c7b.jpg)

This probably should be under this area, not on top of these spikey things. I'm almost sure.

2. I don't believe Durotar should have any Tin veins.
![WoWScrnShot_051322_172238](https://user-images.githubusercontent.com/78314117/168391364-566b4b71-599a-40a3-b39e-2ae36180f8ce.jpg)
![WoWScrnShot_051322_172327](https://user-images.githubusercontent.com/78314117/168391376-f4d56643-4ff3-45b0-8c8f-1471b9c90888.jpg)

3. Dynamic respawn of mining nodes is definitely not turned on in this zone. I could've sworn it was on in Elwynn forest?

4. Another tin node and a gold.
![WoWScrnShot_051322_172426](https://user-images.githubusercontent.com/78314117/168391494-45122e7f-a87e-44ed-826d-399628e20e07.jpg)
![WoWScrnShot_051322_172428](https://user-images.githubusercontent.com/78314117/168391497-ba55f61d-8568-44e0-aad4-1726f0b9dc05.jpg)
![WoWScrnShot_051322_172448](https://user-images.githubusercontent.com/78314117/168391500-7151e62c-e290-43b2-a1b6-133eca29e34c.jpg)

**Comment by FX-SF** [comment]
Revision 1165

**Comment by Vishiswaz** [comment]
Closing due to new server core.
