### ISSUE TITLE
[Zone][Wintergrasp] PvP Mob Respawn Location

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#486]
**Description**: Certain PvP mobs (i.e. Valiance Expedition Champion) respawn.

**Current behaviour**: Certain PvP mobs respawn at the spot they died last.

**Expected behaviour**: Uncertain. Assuming certain PvP mobs respawn at a fixed, designated respawn location.

**Revision**: 1165

![image](https://user-images.githubusercontent.com/105084838/168398521-ba9a9ddc-cf3a-429d-80ab-249eb7900ed4.png)
![image](https://user-images.githubusercontent.com/105084838/168398629-2a237d92-191b-496e-a761-8b6b628eac61.png)
![image](https://user-images.githubusercontent.com/105084838/168398725-ea52e7dc-9acf-40b4-be11-d682cfab5162.png)
![image](https://user-images.githubusercontent.com/105084838/168398838-88b79165-146d-4b3f-8ecf-da4e842e9e2b.png)

**Comment by Cold-Martijn** [comment]
is this still valid?
