### ISSUE TITLE
[NPC][Wintergrasp] Vehicle energy

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#488]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I noticed that the "energy"-like resource that the vehicles have appears to recharge weirdly, like the sync between the client and the server is incorrect and constantly fixing itself. https://youtu.be/93134FIsiRQ

Didn't check the other vehicles. And for all I know this is either clientside or blizzlike. But I figured I'd report it anyways in case it can be fixed.

I think maybe it's regenerating on the server side a little slower than it's supposed to?

**Comment by FX-SF** [comment]
Revision 1165

**Comment by Vishiswaz** [comment]
Closing due to new server core.
