### ISSUE TITLE
[Zone][Wintergrasp] Walls almost dead

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#489]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Walls that are almost dead (like 1 hit away from dying) show up as "Dead" in the tooltip even though they are not.
![WoWScrnShot_051322_192218](https://user-images.githubusercontent.com/78314117/168400869-2874170d-848b-477c-9e0c-3c47dbf9a100.jpg)

**Comment by FX-SF** [comment]
Revision 1165

**Comment by Cold-Martijn** [comment]
is this still valid?

**Comment by Vishiswaz** [comment]
Closing due to new server core.
