### ISSUE TITLE
[Zone][Wintergrasp] Siege Engine (round 2)

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#503]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Follow-Up to https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/471

The second part of what I reported here has not changed.

While in the driver's seat or the two passenger seats (not the cannon), you should be able to mouse over the cannon model on your siege engine (not talking about the grey diagram on the right side of your screen, I'm talking about the actual cannon on the actual siege engine) and get an icon indicating you can enter it, and then switch to that seat by right clicking.

**Comment by Cold-Martijn** [comment]
is this still valid?

**Comment by Vishiswaz** [comment]
Yes

**Comment by Vishiswaz** [comment]
Closing due to new server core.
