### ISSUE TITLE
[Zone][Wintergrasp] Missing Guards

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#504]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Possibly related: https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/461

There are now zero guards between Westspark and Broken Temple, Winter's Edge and the main fortress, or Eastspark and Sunken Ring.

Maybe I'm crazy and remembering incorrectly, but I'm pretty sure there are supposed to be quite a few guards on/near the bridges. I'm unsure if they are determined to be Horde or Alliance based off who is controlling which bases, or if they are just static spawns that exist regardless of who has what. But I'm pretty sure this isn't correct.

As I probably mentioned in a previous ticket, having the correct number of guards is crucial to Wintergrasp, to allow for ranking up, especially at off peak hours when there are fewer players.

Server Revision 1179

Before this server revision, we had this issue: https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/462

**Comment by Wolffenstein** [comment]
would need some source for this

**Comment by Vishiswaz** [comment]
Here's an example of it on the West bridge. https://youtu.be/e4s5HVt26pI?t=132

**Comment by Vishiswaz** [comment]
Oh, wow, there's even more I didn't realize are supposed to be there. Here's some outside the north entrance to Sunken Ring. https://youtu.be/675ZyT_tsoQ?t=91

**Comment by Vishiswaz** [comment]
Later in that same video, hard to see but there are corpses there of at least one of the NPCs, indicating that the north side of the east bridge should also have two pairs fighting each other. https://youtu.be/675ZyT_tsoQ?t=199

**Comment by Vishiswaz** [comment]
Two pairs of NPCs north of middle bridge: https://youtu.be/e_IREpb5rNg?t=11

**Comment by Vishiswaz** [comment]
https://youtu.be/e_IREpb5rNg?t=100

NPC should be patrolling in the tower, whichever side is attacking, on the second floor.

**Comment by Vishiswaz** [comment]
Another one patrolling 2nd floor of east tower. https://youtu.be/e_IREpb5rNg?t=193

**Comment by Vishiswaz** [comment]
Here's a picture of what wowhead thinks some of them are. As demonstrated by the video, though, this definitely isn't all of them. 
![image](https://user-images.githubusercontent.com/78314117/171761199-c8d3feb8-e973-49fe-a1b9-55e55ab652d8.png)

**Comment by Vishiswaz** [comment]
Closing due to new server core.
