### ISSUE TITLE
[NPC][Hellfire Peninsula] Shattered Hand ___________ Reputation Gain

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#509]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
All Shattered Hand orcs in The Path of Glory are giving 25 Honor Hold reputation as an Alliance player. I assume they will also give Thrallmar rep to Horde.

They should award 0 rep to either.

**Comment by Tereneckla** [comment]
Fixed soon™
