### ISSUE TITLE
[Class][Pet] Some pets missing Avoidance and behave incorrectly

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#510]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Right now pets don't stack on enemy's back when sent to attack like they're supposed to and some don't take reduced damage from AoE in PvE (missing Avoidance). 

**Current behaviour**: Pets don't stack on enemy's back when sent to attack like they're supposed to and some don't have Avoidance.

**Expected behaviour**: Pet should stack on enemy's back when sent to attack and take reduced damage from AoE in PvE (passive buff called "Avoidance")

https://wowwiki-archive.fandom.com/wiki/Avoidance_(passive)

**Revision**: 1179

**Comment by Wolffenstein** [comment]
Which pets? Because thats wrong

**Comment by Nuy** [comment]
> Which pets did you test? Because thats wrong

I tested for Spirit Wolves so it seems it doesn't work right for all pets.

https://wowpedia.fandom.com/wiki/Avoidance_(passive) - List of pets here should be accurate.

**Comment by Nuy** [comment]
> And how did you test it exactly? Because "AoE" is a very broad term

I tested it on [Twilight Worshipper](https://www.wowhead.com/npc=30111/twilight-worshipper) Spirit Wolves took full 3500 damage per Flamestrike tick. I tested hunter's pet also on same mob and it barely took any damage (around 350 per tick) so hunter's pet Avoidance is fine.
