### ISSUE TITLE
[Core] Unarmed Skill

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#519]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When disarmed by a spell like from Defias Looters in Westfall, your unarmed skill does not go up as you attempt to punchy punch things. It should, just as if you removed your weapon and started punching them.

Weapon skillup should not be determined by what you have equipped in the character screen. It should be determined by what skill is determining your hit chance at the time you attempt a melee hit.

**Comment by Cold-Martijn** [comment]
Does it properly calculate miss chance based on your unarmed skill?

**Comment by Vishiswaz** [comment]
Yes it was a lot of parry dodge miss, but the unarmed skill didn't go up

**Comment by Vishiswaz** [comment]
YES on miss, NO on Dodge and Parry. You can test easily on Classic if you don't believe me, I had a ton of back and forth with Tauri on this for Crystalsong haha

**Comment by haephaistoss** [comment]
I strongly advise to set wep skills to possible max each time a player gains a level and when they learn a new wep skills at a higher level set it to level based max by default too, leveling them up is a pain in the ass especially with increased XP rates

**Comment by Vishiswaz** [comment]
> I strongly advise to set wep skills to possible max each time a player gains a level and when they learn a new wep skills at a higher level set it to level based max by default too, leveling them up is a pain in the ass especially with increased XP rates

This is not Crystalsong, weapon skills are coded properly, people should be able to level them up on Missed swings, so it shouldn't be that bad.

On Crystalsong it took a while before they believed me when I said it should level up on Miss, so for the beginning of the server people were out leveling their weapon skill and then would not be able to level it up easily because it had to hit to level up. That won't be an issue here, no need to automate it.

**Comment by Cold-Martijn** [comment]
Retest please

**Comment by Vishiswaz** [comment]
Still happening.

**Comment by Vishiswaz** [comment]
Eh, nevermind.

**Comment by haephaistoss** [comment]
Mine got lvled up, and I'm not fist fighting 

![image](https://user-images.githubusercontent.com/67190649/172266034-49b336a8-4623-45e3-8a23-681435b198ad.png)

**Comment by Vishiswaz** [comment]
Yeah I finally got one. Still seems slower than it should be but I dunno. Closed regardless.

**Comment by haephaistoss** [comment]
if it was despicably slow I'd be the first one to bitch about it trust me :D
