### ISSUE TITLE
[Talent] PrimalFury [Class] Druid: The rank 2 of the “Primal Fury” talent doesn't always grant the extra combo point

### ISSUE THREAD

**Issue by Lmdezorn** [Stormforge-gg/Bugtracker-Fordring#525]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The rank 2 of the “Primal Fury” talent doesn't always grant the extra combo point in Cat form.

**Current behaviour**: For a cat talented with the rank 2/2 of Primal Fury, critical strikes on the abilities mentioned hereafter don't always lead to an additional combo point. It happens with Mangle (Cat) [spell=48566 for the rank 5], Shred [spell=48572 for the rank 9] and Rake (the initial direct hit, not the bleeding part) [spell=48574 for the rank 7]. 

Note 1: I didn't take the time to make a proper statistical study for the proportion of the event "extra combo point not granted" but some of the critical strikes still grant an extra combo point, although it's definitely not 100%.

Note 2: I get rid of the issue when I activate the other talent specialization, then swap back to my initial talent spec.

**Expected behaviour**: As the Primal Fury's tooltip (for the Rank 2) states: "your critical strikes from Cat Form abilities that add combo points have a 100% chance to add an additional combo point" (as one can see in the screenshot below). So basically, any critical strike of Mangle (Cat), Shred, Rake (not the bleed part) should give an extra combo point.

![image](https://user-images.githubusercontent.com/59399784/168488795-048a391f-7f4f-4671-a29e-51f5e1e69eb7.png)

**Steps to reproduce the issue**: Log a feral druid, with the Primary Fury talent (2/2), and hit a dummy. If you notice the same behavior as what I’m describing, activate the second talent spec, then reactivate your initial talent spec, and hit the dummy again.

**Revision**: 1184

**Comment by dalaraz** [comment]
still a thing,even with 2 combos it feels like its still 50% if not something else,another thing is that when an npc blocks an attack the combos still go through,is there any fix eta ?

**Comment by VirtualReign** [comment]
Can confirm this issue still exists.

**Comment by jhuerta13** [comment]
Still persists as of today Jun/17. I tried switching to secondary talents and back to feral tree with 2/2 Primal Fury and still not 100% chance to add 2 combo points per crit, this is a critical issue since it cripples cat damage by a lot, specially when you get 2 crits in a row that only add up 2 combo points each.

https://www.youtube.com/watch?v=fFM8OpPuM3k

"Primal Fury at 2/2 failing to add 2 combo points on critical strikes, bug happens at; [00:09], [00:58], [01:30]"

**Comment by zhorzhyordanov** [comment]
Still not working, unfortunately :(

**Comment by prosax** [comment]
This bug still ingame! Please fix....

**Comment by Cold-Martijn** [comment]
We are looking for a way to reproduce this. Videos available for this happening would help.

**Comment by Smokdacave** [comment]
here's some target dummy hitting
https://www.youtube.com/watch?v=8MpHHC8TwGU

**Comment by Wolffenstein** [comment]
Still cant reproduce it so im just gonna port my tbc fix, check again in rev 1595 (also good to reset talents beforehand).

**Comment by Therealtokar** [comment]
Primal Fury is definitely still not working. Especially critical hits with Mangle (Cat) rarely result in a second CP as the talent suggests.
Is there anything we can do to help reproduce this bug? It seems quite obvious to me and leaving it in the game makes feral dps pretty much unplayable.

**Comment by Godmatik** [comment]
@Therealtokar rest with the new core they just launched
