### ISSUE TITLE
[NPC][Shadowfang Keep] Shadowfang Darksoul

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#528]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This one acts a little funky. https://youtu.be/SbCVb7ZrrJ0

**Comment by Cold-Martijn** [comment]
You mean the fast respawn?

**Comment by NatsumeLily** [comment]
> You mean the fast respawn? Please do give some more info, preferably with NPC ID or WoWhead link + whats the actual issue :)

This mobs pathing breaks on the stairs. Strangely attacking it seems to fix the pathing, but if it aggros on you from range it will get stuck near the middle of the stairs.

**Comment by Vishiswaz** [comment]
Closing due to new server core.
