### ISSUE TITLE
[Quest] Where in the World is Hemet Nesingwary?

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#573]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**: When you get to Sholozar, a Venture Co. pilot enemy plane aggros on you when you fly by and melees your vehicle. 

**Expected behaviour**: When you get to Sholozar, a Venture Co. pilot enemy plane should appear and shoot you down with rockets. 

**Revision**: 1206

**Comment by Vishiswaz** [comment]
As a note, I took the quest right after him and the planes completely ignored me.

Pretty sure each person who takes this quest should cause their own set of enemy planes to spawn and attack them so it's irrelevant whoever recently took the quest

**Comment by Wolffenstein** [comment]
Fixed in rev 1214.

**Comment by TheRealestMcCoy** [comment]
When the copter drops you off you take a lot of fall damage. You should get a parachute and slow fall down

https://youtu.be/2YXu_vzrChE?t=55

**Comment by Vishiswaz** [comment]
> When the copter drops you off you take a lot of fall damage. You should get a parachute and slow fall down
> 
> https://youtu.be/2YXu_vzrChE?t=55

Open a new report for this, good catch
