### ISSUE TITLE
[Quest] The Exorcism of Colonel Jules - Infinite Adds Spawn

### ISSUE THREAD

**Issue by Ceago** [Stormforge-gg/Bugtracker-Fordring#580]
**Description**: 
If the anchorite is killed prior to the completion of this quest the Foul Purge mobs will spawn infinitely at a very fast rate.  

**Current behaviour**:
![Desktop Screenshot 2022 05 19 - 17 32 48 50](https://user-images.githubusercontent.com/43499757/169408504-410b5510-5891-4adb-9169-ae134f325634.png)

**Expected behaviour**: 
Quest should flag as failed if Anchorite Barada dies and cease spawning mobs.

**Revision**: 
1206

**Comment by Cold-Martijn** [comment]
C++...
