### ISSUE TITLE
[NPC][Scarlet Monastery Cathedral] Scarlet Commander Mograine

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#625]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Missing his Divine Shield spell and Lay on Hands spell.

**Revision**: 1217

**Comment by FX-SF** [comment]
Already reported #309

**Comment by FX-SF** [comment]
This ticket should be closed, as #309 has fixed this issue

**Comment by NatsumeLily** [comment]
That fix was only for divine shield. Lay on hands is still missing.
