### ISSUE TITLE
[Quest] Fresh Remounts [Zone] Dragonblight

### ISSUE THREAD

**Issue by HiKO0711** [Stormforge-gg/Bugtracker-Fordring#635]
After u mounted on the Horses via using Questitem and getting attacked by Mobs, u cant escape of them. The Horse will always run automatically to the attacking Mobs until it dies. So this Quest is nearly impossible to do
https://de.wowhead.com/quest=12214/ersatzpferde#english-comments

**Comment by Cold-Martijn** [comment]
horses spawn without rider?

**Comment by HiKO0711** [comment]
This was not the case on PTR.  You cant get the Horses away if they get attacked once, because they automatically charged to Enemies then.  Im not this far on Live Server now

**Comment by Cold-Martijn** [comment]
> 

Yeah, i've fixed the initial issue by rewriting a part of the quest and vehicle, but someone mentioned having issues that horses spawn without rider on them. I'm investigating and will see if I can reproduce (so far no luck reproducing yet)

**Comment by Cold-Martijn** [comment]
found the issue, sorry for screwing up.
