### ISSUE TITLE
[Quest][NPC][Howling Fjord] A Lesson in Fear, Winterskon Defender, Vengeance Bringer

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Fordring#636]
**Description**: 
[A Lesson in Fear](https://www.wowhead.com/quest=11282/a-lesson-in-fear) is a quest in which by killing [Winterskorn Defender](https://www.wowhead.com/npc=24015/winterskorn-defender) spawns randomly 3 other NPC [Oric the Baleful](https://www.wowhead.com/npc=24161/oric-the-baleful), [Ulf the Bloodletter](https://www.wowhead.com/npc=24016/ulf-the-bloodletter), [Gunnar Thorvardsson](https://www.wowhead.com/npc=24162/gunnar-thorvardsson).

**Current behaviour**:
 - I killed 2 of them got dc, after logging again I couldn't spawn last one, so I deleted the quest. After deleting quest I got only this 3rd one and this first two didn't spawn. So I deleted again and no1 spawned. After abandoning q and then relogging all of them has spawned, then I abandoned q took again and it worked, next time no one spawned. I don't know was it happened only to me due to this dc or so.
 - [Winterskorn Defender](https://www.wowhead.com/npc=24015/winterskorn-defender) some of them spawn on the hill.
 - There is 6 [Vengeance Bringer](https://www.wowhead.com/npc=23865/vengeance-bringer) at watch moving randomly killing more Defenders.

**Expected behaviour**: 
 - They should spawn always. In case if some1 got 2 and random person has stolen last one, to get him again we need to delete q, then any of them won't spawn at all.
 - Some defenders should spawn down the hill and run up the hill to this outpost then aggroing to this Forsakens. Rest of them should stand with /attack emote.
 - There shouldn't be 6 Bringers at watch. Only 2 of them should constantly run between center of vyrkul watch and outpost.
 - Also there should be some fire on the ground
[Video](https://youtu.be/D5cmNfyejZE?t=36) we see Defender whos running up the hill.
[Video](https://youtu.be/D5cmNfyejZE?t=49) here we see 2 Bringers who are running down the hill to the center.

**Revision**: 
1225

**Comment by Tereneckla** [comment]
Actually had fixed this place already. Spawn of the named npcs is random, no need to abandon the quest
