### ISSUE TITLE
[Quest][Howling Fjord] Baleheim Must Burn! flame effect

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Fordring#637]
**Description**: 
During [Baleheim Must Burn!](https://www.wowhead.com/quest=11285/baleheim-must-burn) we need to burn all listed places.

**Current behaviour**:
There is only one small flame in te center of building, bridge.

**Expected behaviour**: 
Whole building, bridge should burn instead of 1 small flame.

**Revision**: 
1225

**Comment by Tereneckla** [comment]
Fixed soon™
