### ISSUE TITLE
[NPC] Zul'Drak

### ISSUE THREAD

**Issue by drezzy958** [Stormforge-gg/Bugtracker-Fordring#66]
![image](https://user-images.githubusercontent.com/62518101/162543061-b5013e42-6670-4e15-84f4-b7fa113a07bc.png)

Description :
https://www.wowhead.com/npc=28879/shalewing
https://www.wowhead.com/npc=28669/flying-fiend

Current behaviour: 
npc=28879 unusual movement
npc=28669 unusual movement

------

![image](https://user-images.githubusercontent.com/62518101/162543649-e85e747f-8081-410b-b020-e1a3b00eb6e5.png)

Descriptif :
https://www.wowhead.com/npc=32471/griegen

Current behaviour: 
npc=32471 he dont move

Expected behaviour:
![image](https://user-images.githubusercontent.com/62518101/162543874-b9d3073d-ff64-4198-86b3-c7ed08fb7eed.png)

**Comment by therealCrysis** [comment]
Shalewing - confirmed
Flying Fiend - minor issue
Griegen - stays in one spot - minor issue
