### ISSUE TITLE
[Spell=Vanish][Class=Rogue] Vanish doesnt reset potions on bosses

### ISSUE THREAD

**Issue by mercy-byte** [Stormforge-gg/Bugtracker-Fordring#704]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Rogue Class mechanic, [Vanish](https://www.wowhead.com/spell=1856/vanish) doesnt put you out of combat on bosses.

**Current behaviour**: [Potions](https://www.wowhead.com/item=40211/potion-of-speed) doesnt reset after using vanish on bosses ( even non aura bosses)

**Expected behaviour**: [Potions](https://www.wowhead.com/item=40211/potion-of-speed)  should've a 1 min cd after using [Vanish](https://www.wowhead.com/spell=1856/vanish) on bosses

**Revision**:

**Comment by Wolffenstein** [comment]
Proof?

**Comment by NatsumeLily** [comment]
Not a bug. He might be mistaking this for bugmane. 
Vanish does not start the potion CD. Same thing for shadowmeld.

**Comment by mercy-byte** [comment]
It should reset because you get out of combat even if its for half second.
Shadomeld in the other hand doesn't put you out of combat

**Comment by NatsumeLily** [comment]
> It should reset because you get out of combat even if its for half second. Shadomeld in the other hand doesn't put you out of combat

Shadowmelds takes you out of combat the same way vanish does. 

Bosses apply a combat aura that keeps you in combat even if you vanish, shadowmeld, or feign death. The only time these abilities take you out of combat is if you are the last person alive, which resets the boss too.

**Comment by Godmatik** [comment]
Regardless of the wording - you need to provide proof from Wrath retail that such a mechanic actually exists, can't reference other private servers where it might have worked. I'm almost certain it does not exist though, the boss combat flag prevents this until he is dead or fully reset.

**Comment by Soufly** [comment]
https://wowpedia.fandom.com/wiki/Combat?so=search NO
Same goes for shadowmeld/feigh death:
''Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly).''
That was added at the end of TBC.
