### ISSUE TITLE
[Quest][Event][Howling Fjord] Sorlof's Booty - event doesn't exist

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Fordring#713]
**Description**: 
Quest [Sorlof's Booty](https://www.wowhead.com/quest=11529/sorlofs-booty) is offered by [Captain Ellis](https://www.wowhead.com/npc=24910/captain-ellis) we have to collect [Sorlof's Booty](https://www.wowhead.com/item=34468/sorlofs-booty) from [Sorlof](https://www.wowhead.com/npc=24914/sorlof)

**Current behaviour**:
Even doesn't exist, we can use [The Big Gun](https://www.wowhead.com/npc=24992/the-big-gun) but won't do anything. There in no Sorlof at the beach. Now he has to be killed by our own spells, its hard for 72lvl to kill 80 elite with 126k hp.

**Expected behaviour**: 
When ship reaches the beach event starts. Sorlof should be there, he throws stones to ship, crew shoot to him from guns and cannons. Some crew member are running on the ship. Ship sails along the beach as it follows Sorlof. After his death all crew members yells.
[Video1](https://youtu.be/gSbTj6YZAP0?t=26)
[Video2](https://youtu.be/_zoAEAdsoRY?t=35)

**Revision**: 
1263

**Comment by Ceago** [comment]
Is currently functioning correctly rev 1501.  Have read it is easy to bug out this quest though if you walk onto the ship with a mount or jump off at any point - per wowhead comments
