### ISSUE TITLE
[spell][class] Warriors Charge

### ISSUE THREAD

**Issue by Blimsquge** [Stormforge-gg/Bugtracker-Fordring#72]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: On target dummies, when you charge in, you end up right on top of the target and can't attack until you move out. This happens with numerous targets that get stunned by the charge as well.

**Current behaviour**:

**Expected behaviour**: The charge is supposed to stop you right in front of the target inside melee range so you can attack immediately 

**Revision**:

**Comment by Nuy** [comment]
I remember this bug back on Nostalrius. It was annoying as hell.

**Comment by duzyizly** [comment]
Same happens on critters.

**Comment by mythyrylfalcon** [comment]
Also occurs with Intercept "https://www.wowhead.com/spell=198304/intercept"

Need to test intervene, but that requires at least 2 people.
