### ISSUE TITLE
[NPC] Kael'thas Sunstrider

### ISSUE THREAD

**Issue by BobSemple** [Stormforge-gg/Bugtracker-Fordring#733]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Kael'thas Suntrider in Magister's Terrace heroic has his third phase wrong, as the spheres are stationary in the air phase.

**Current behaviour**: When Kael'thas Suntrider in Magister's Terrace heroic casts his magic to turn the world upside down (air phase) and summons his 3 spheres, the spheres are stationary on their summoned spots.

**Expected behaviour**: The  3 spheres should move erratically.

**Comment by Godmatik** [comment]
Wolf or another dev has been porting over the properly scripted dungeons from Atlantiss, I just don't think he has gotten to this one yet.
