### ISSUE TITLE
[NPC] Icebound Revenant (missing unknown interactions/buff)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#742]
**Description**: [Icebound Revenant](https://www.wowhead.com/npc=29844/icebound-revenant#comments) is an NPC {ID: 29844} located in The Frigid Tomb of The Storm Peaks. There are also many of an unknown Object.

**Current behaviour**: [Icebound Revenant](https://www.wowhead.com/npc=29844/icebound-revenant#comments) never interacts with Object, nor does it ever cast a buff on itself.

**Expected behaviour**: Occasionally, [Icebound Revenant](https://www.wowhead.com/npc=29844/icebound-revenant#comments) will interact with Object, creating some unknown channeled spell animation for a time, and then receive an unknown buff which increases attack and cast speed by 50%. This buff is not shown as an [Icebound Revenants](https://www.wowhead.com/npc=29844/icebound-revenant#comments) ability.

**Revision**: 1275

Evidence:

1) Video: [Shows the buff exists](https://youtu.be/Q27zWmAoEz8?t=54)
1) Video: [Shows Spell Interaction between Object and NPC](https://youtu.be/Q27zWmAoEz8?t=94)
Same as video above.
 From 1:31 - 1:38. You may need to slow it down to .25x playback speed. 

2) Wowhead comment
![image](https://user-images.githubusercontent.com/105084838/170616965-ff20fae9-57f7-4db9-90eb-b15b13d8aacb.png)

3) Picture of unknown Object:
![image](https://user-images.githubusercontent.com/105084838/170618833-6616d101-46c2-47d6-968d-fa5c3627b92e.png)

**Comment by FX-SF** [comment]
Need Spell ID for buff

**Comment by Drevil-Dion** [comment]
https://www.wowhead.com/spell=55350/siphoned-power
