### ISSUE TITLE
[NPC] High General Abbendis

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#76]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: She should be immune to CC but isn't here and is missing some quotes when player enters the room and attack mobs befor the boss. Admiral Barean Westwind next to her missing Protective Sphere ability.

**Current behaviour**: Isn't immune to CC and missing some quotes.

**Expected behaviour**: She should be immune to CC and say something when players enter the room and aggro the mobs befor her.

https://www.wowhead.com/npc=27210/high-general-abbendis#comments
https://www.wowhead.com/npc=27951/admiral-barean-westwind#comments

**Revision**: 1040

**Comment by Nuy** [comment]
![opera_bKs9rrKmtg](https://user-images.githubusercontent.com/4800827/167872850-a5624ab1-6b8b-4291-85d6-f0ad0aec9862.png)
![opera_np30EJr8iC]
![opera_VhlfjXskO4](https://user-images.githubusercontent.com/4800827/167872892-91c3fdfd-314a-418f-84f0-7fe56df149b1.png)
(https://user-images.githubusercontent.com/4800827/167872869-f20ee8a0-1e81-4271-affa-e6364b29ba79.png)

(https://www.youtube.com/watch?v=EwjXuZI4uOI)

**Comment by therealCrysis** [comment]
Admiral Westwind works correctly.

Abbendis should be immune to CC, but she is NOT. So it's wrong.
I did see their quotes though.

**Comment by Nuy** [comment]
> Admiral Westwind works correctly.
> 
> Abbendis should be immune to CC, but she is NOT. So it's wrong. I did see their quotes though.

When fight starts he loses his [Protective Sphere buff](https://www.wowhead.com/spell=50161/protection-sphere) but players are still unable to attack him so it's pretty much just visual that breaks immersion a bit.
