### ISSUE TITLE
[NPC] Grizzlemaw NPCs

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#78]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: NPCs there behave incorrectly, have incorrect spawn points and positions. Missing all quotes.

**Current behaviour**: NPCs in this area are broken.

**Expected behaviour**: Frostpaw furbolgs are supposed attack Redfang one that live in Grizzlemaw. Redfang furbolgs should be neutral to player if he kills Frostpaw furbolg and vice versa (buff). They should also say some things.

https://youtu.be/h8SNPSzzzHY?t=60
https://www.wowhead.com/npc=26428/frostpaw-shaman#comments
https://www.wowhead.com/npc=26357/frostpaw-warrior
https://www.wowhead.com/npc=26434/frostpaw-trapper
https://www.wowhead.com/npc=26356/redfang-hunter
https://www.wowhead.com/npc=26436/redfang-elder

https://www.wowhead.com/spell=47034/frostpaw-ally
https://www.wowhead.com/spell=47033/redfang-ally

**Revision**: 1040

**Comment by therealCrysis** [comment]
Confirmed in rev 1165

**Comment by Tereneckla** [comment]
Fixed soon™
