### ISSUE TITLE
[Core] Some Creature AI happens during combat

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#784]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Creature AI happens during combat with the player. For example wolves attacking stags. 

The wolves will kill stags while they are fighting the player. https://www.youtube.com/watch?v=TYSmomkk1_A

**Revision**: 1294

**Comment by Cold-Martijn** [comment]
Hi, this is something that should be fixed on a per-creature issue.
I will try to fix it for these creatures, but you'd need to report every single separate instance of this happening probably.

**Comment by Cold-Martijn** [comment]
can't seem to figure this one out, unassigned myself... im also decently wondering if this isn't blizzlike behaviour?
