### ISSUE TITLE
[Global][Wintergrasp] Enemy corpse visibility after release

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#791]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Sometimes an enemy's corpse is not consistently visible after they release.
https://youtu.be/3HigdLvS3nA

For the record, while I was unable to see his corpse after he released, Manolith (the 3rd person in the video) was able to see it. Bizarre.

**Comment by Cold-Martijn** [comment]
This might have already been fixed + might be Wintergrasp only, adding Wintergrasp to the title just to be sure.
