### ISSUE TITLE
[Zone][Wintergrasp] Spirit guide for main keep graveyard is missing

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#792]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: The spirit guide for the main keep graveyard is missing. This spirit guide should be the same as the others. 
Spirit guides should also give a teleport option for the main keep graveyard if your faction controls it.
![WoWScrnShot_052722_224737](https://user-images.githubusercontent.com/15247730/170810405-c7229a3b-d8fe-4e23-9648-3231a94e76dc.jpg)

**Revision**: 1294

**Comment by Vishiswaz** [comment]
Not missing for alliance. Only horde.
