### ISSUE TITLE
[NPC][Spell][Howling Fjord] Necro Overlord Mezhen

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Fordring#797]
**Current behaviour**:
 - [Necro Overlord Mezhen]( https://www.wowhead.com/npc=24018/necro-overlord-mezhen#comments) his spell [Raise Dead]( https://www.wowhead.com/spell=43559/raise-dead) doesn’t work.
 
**Expected behaviour**: 
 This spell should rise from dead. Body of his ally dissappears but there is no skeletal.

**Revision**: 
1294

**Comment by EtheriousNW** [comment]
Are you sure it's not working? There needs to be dead Necrolords around it won't summon anything. Might be incorrect behaviour but it does summon as long as there are dead mobs nearby.

**Comment by eryczek1615** [comment]
I killed all this necrolords around him, one body dissappeared but there was no skeleton.
