### ISSUE TITLE
[NPC][Movement][RP Event][Howling Fjord] Gjalerbron zone

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Fordring#799]
- There should be 1 [Gjalerbron Warrior]( https://www.wowhead.com/npc=23991/gjalerbron-warrior) riding horse around. [Video]( https://youtu.be/eTbVWZU0n90?t=58)
- All Vrykuls next to cages have random movement, due to this they are climbing on cages and wagons. Some of them should stand in one place with correct animation, some should move between cages.[Video1](https://youtu.be/eTbVWZU0n90?t=55), [Video2](https://youtu.be/eTbVWZU0n90?t=96).
![image](https://user-images.githubusercontent.com/4455568/170819555-934babbc-c354-4f73-95aa-ff38bd9ff884.png)
 - This one Vrykul in the basement has no waypoints
 - There is no RP event like on this [Video]( https://youtu.be/uwqcvQLg2gw?t=34) and [Here]( https://youtu.be/uwqcvQLg2gw?t=140) 
![image](https://user-images.githubusercontent.com/4455568/170819801-c0f2dc61-3610-4f5c-9f46-ae0f35c0bda8.png)

there is some [Necrolords]( https://www.wowhead.com/npc=24014/necrolord) in the basement:
 - This 2 they should have waypoints(now random movement). [Video]( https://youtu.be/9BH6h38S-Xo?t=155)can see him in the backround 
![image](https://user-images.githubusercontent.com/4455568/170819608-118c3495-e4d4-409e-a4b0-fda5bf24cf95.png)
 - Others who have waypoints walking around the circle should sometimes approach [Dormant Vrykul]( https://www.wowhead.com/npc=24669/dormant-vrykul) and cast beam to them. [Video]( https://youtu.be/9BH6h38S-Xo?t=104)can see him  in te background on the left.
![image](https://user-images.githubusercontent.com/4455568/170819641-89f096b5-0458-46a4-8f60-709907576f06.png)

**Revision**: 
1294

**Comment by Cold-Martijn** [comment]
data available if a dev is going to pick this up. let me know if needed.
