### ISSUE TITLE
[Quest][Zul'Drak] Bringing Down Heb'Jin

### ISSUE THREAD

**Issue by WeekendWarrior00** [Stormforge-gg/Bugtracker-Fordring#805]
**Description**:  You lure Heb'Jin with a drum and he comes to you flying in a bat. You need to trap the bat with a given item and kill him.

**Current behaviour**: When he is comming in your direction, you can't use the item. He even starts the animation of going to the ground but he despawns leaving only the bat to kill.

**Expected behaviour**:  https://www.youtube.com/watch?v=efSG_pUgKEw

**Revision**:

**Comment by WeekendWarrior00** [comment]
![WoWScrnShot_052822_160555](https://user-images.githubusercontent.com/61029488/170839590-a0dca0cd-cf79-4d8d-9633-ad6d792ebb65.jpg)
He is flying to me :D

**Comment by WeekendWarrior00** [comment]
![WoWScrnShot_052822_160556](https://user-images.githubusercontent.com/61029488/170839598-d8810010-2aa5-442b-b917-aec44973bbe2.jpg)
He is going to the ground now =D

**Comment by WeekendWarrior00** [comment]
![WoWScrnShot_052822_160559](https://user-images.githubusercontent.com/61029488/170839619-b8b34db8-b9f7-4a54-b7cb-ff766c35deb0.jpg)
Ops, not here anymore D:
(The can check there is not corpse of the mob and the quest is listed as not completed)

**Comment by KurtySuit** [comment]
Still bug on revision 1514

**Comment by adambcurrier** [comment]
I encountered this issue as well and what seems to happen is that Heb'Jin (riding the bat) despawns on the way down to the drum. If you move forward and throw the net before that happens you are able to complete the quest.
