### ISSUE TITLE
[NPC][Pet][Warlock] Imp

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Fordring#82]
**Description**:  Imp Fireball cast and attack mechanics not working properlly.

**Current behaviour**:  
**Combat state : Entering Combat. Range from the target 36 yards.**
Imp with full mana set to  Follow,Defensive when entering combat (If Fireball *36 yard range* is set to autocast ) runs into meele range, sometimes in the center of the targeted mob frame, then starts casting Fireball.  Same thing happens regardless if I send Imp to attack the target solo or if I trigger combat with my spells.
For example while moving away from the mob while in combat, Imp stops casting to run meele to cast Fireball and so on.
On the other hand, If I stay in range of the Imp's Fireball, turn of autocast and manually click Fireball on the pet bar to attack a target, Imp will cast it from that range without going meele. But as soon as I stop clicking manually and turn it back to autocast, again Imp goes meele and so on..
Tested both in meele range and in a range between 10-36 yards. 
https://streamable.com/6gxe0w
Tested also on a Training Dummy, same thing.
**Expected behaviour**: As long as Imp has mana and is in the range of the target that its attacking regardless of the targets and players movements, should keep casting Fireballs still in that place, unless the target moves out of of range or if the player decides to call the pet back or use other movement control functions on the pet bar.

**Revision**:

**Comment by kgms20** [comment]
Re-uploaded on Youtube.
https://www.youtube.com/watch?v=3_A9ilqQrXc

**Comment by therealCrysis** [comment]
Known issue on several cores.
