### ISSUE TITLE
[Basic Chemistry][Icecrown] Pustulant Spinal Fluid - Incorrect Cooldown

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#822]
**Description**: 
[Pustulant Spinal Fluid](https://www.wowhead.com/item=44010/pustulant-spinal-fluid) is an item {ID 44010}
It is used in the quest [Basic Chemistry](https://www.wowhead.com/quest=13295/basic-chemistry#comments) {ID 13295}

**Current behaviour**: [Pustulant Spinal Fluid](https://www.wowhead.com/item=44010/pustulant-spinal-fluid) has a 30s Cooldown

**Expected behaviour**: [Pustulant Spinal Fluid](https://www.wowhead.com/item=44010/pustulant-spinal-fluid) should have a 1min and 30s Cooldown.

**Revision**: 1294

Source: [Wowhead Comments](https://www.wowhead.com/quest=13295/basic-chemistry#comments) (theres plenty)
[Green Comment Link](https://www.wowhead.com/quest=13297/neutralizing-the-plague#comments)

Pre 4.0.3
![image](https://user-images.githubusercontent.com/105084838/170852312-b2d66ec6-fd82-4933-93c6-4d87e73e443b.png)
![image](https://user-images.githubusercontent.com/105084838/170852367-bdaf3d81-4fbb-4987-9b1e-d949bc6880bf.png)
![image](https://user-images.githubusercontent.com/105084838/170852425-0cd6864d-ed80-46b8-8e85-2b97993d3f2e.png)

------------------------------
Post 4.0.3
![image](https://user-images.githubusercontent.com/105084838/170854167-f6a3d351-3087-4d72-8f6a-9c0e2433fd5b.png)
![image](https://user-images.githubusercontent.com/105084838/170852453-f4b2e19a-028e-4494-a788-313d4c425d47.png)
![image](https://user-images.githubusercontent.com/105084838/170852468-7ee78196-786f-47f1-90ef-6b3f33e8eed4.png)

**Comment by Evolvee** [comment]
fixed in next rev, it wont be possible to do the quest solo from now on, so let me know if the timers are okay-ish even for more ppl, i scripted it based on the retail videos from cata+ so not sure if it changed even elsewhere other than the item cooldown...
