### ISSUE TITLE
[Neutralizing the Plague][Icecrown] Daily quest has no script

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#825]
**Description**: [Neutralizing the Plague](https://www.wowhead.com/quest=13297/neutralizing-the-plague) is a quest in Icecrown. {Quest ID: 13297}
It is unlocked after completing [Basic Chemisty](https://www.wowhead.com/?quest=13295) {Quest ID 13295}

**Current behaviour**: There is no script attached to this quest.

**Expected behaviour**: There should be an identical script similar to Basic Chemistry

**Revision**: 1294

Quest was updated in 4.0.3
[Video of post 4.0.3 scripted event](https://youtu.be/-7iS96rM_2o?t=75)

**Comment by Evolvee** [comment]
fixed in next rev
