### ISSUE TITLE
[Not a Bug][Icecrown] Rod of Siphoning - creates Qitem without VW corpse

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#828]
See vid below for quick overview.

**Description**:

- [Rod of Siphoning](https://www.wowhead.com/item=44433/rod-of-siphoning) is an item used in the quest [Not A Bug](https://www.wowhead.com/quest=13342/not-a-bug) {Item ID: 44433}{Quest ID: 13342}.
- Under the right circumstances, using Rod of Siphoning can gives quest item [Dark Matter](https://www.wowhead.com/item=44434/dark-matter) {Item ID: 44434}
- [Enslaved Minion](https://www.wowhead.com/npc=32260/enslaved-minion#comments) is an NPC located at Aldur'thar in Icecrown. {NPC ID: 32260}

**Current behaviour**:

-  You can use the Rod of Siphoning without targeting anything. Doing so will give you Dark Matter.
- Using Rod of Siphoning shows a "weird" buff, named [Rod of Siphoning](https://www.wowhead.com/spell=60528/rod-of-siphoning) {Spell ID: 60528}
- Using Rod of Siphoning shows a channeled bar titled "Rod of Siphoning"

**Expected behaviour**: 

- You should only be able to use the Rod of Siphoning when targeting the corpse of an Enslaved Minion. You should not obtain Dark Matter any other way.
- You should never see the "weird buff" [Rod of Siphoning {Spell ID: 60528}](https://www.wowhead.com/spell=60528/rod-of-siphoning). The "weird buff" is hidden.
- You should never see a channeled spell bar. The channeled spell bar is hidden.

**Revision**: 1294

https://user-images.githubusercontent.com/105084838/170858143-95ea4828-b51d-4500-a796-4ae2e3ae8a24.mp4

**Comment by FX-SF** [comment]
This quest has had an issue in the past:
#440

**Comment by Evolvee** [comment]
I fixed it but there seems to be a core issue, once its resolved, the quest will work fine.
