### ISSUE TITLE
[The Leaper][Icecrown] Slow movement / 'leap' animation / missing spells

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#834]
**Description**: [The Leaper](https://www.wowhead.com/npc=29840/the-leaper#comments) is an NPC {ID 29840}. It is known for his 'leaping' animation as he moves.

**Current behaviour**: 

- The Leaper moves slowly, not showing off his notable 'leap' animations (with the exception of entering combat)
- The Leaper not cast [Hunger For Blood](https://www.wowhead.com/spell=60177/hunger-for-blood) or [Sinister Strike]( https://www.wowhead.com/spell=60195/sinister-strike). It has no energy bar

**Expected behaviour**: 

- The Leaper should move quicker, showing off a notable 'leap' animation. 
- The Leaper should cast [Hunger For Blood](https://www.wowhead.com/spell=60177/hunger-for-blood) and [Sinister Strike]( https://www.wowhead.com/spell=60195/sinister-strike). It should have an energy bar.

**Revision**: 1294

Evidence:

- [Video from 2013](https://youtu.be/Az8flqwZ540?t=94): Shows The Leaper's faster movement and 'leap' animation. Show energy bar
- [Video from 2015](https://youtu.be/w_ARDRdFMwA?t=94). Shows The Leaper's faster movement and 'leap' animation. Shows energy bar
- [The Leaper Wowhead Comments](https://www.wowhead.com/npc=29840/the-leaper#comments):
![image](https://user-images.githubusercontent.com/105084838/170866550-b50056ea-6730-4577-91d5-76c9cf1a2eb7.png)
- Revision 1294 S.F. video:

https://user-images.githubusercontent.com/105084838/170866109-477b29a7-8eec-410d-a079-34bb66196918.mp4

**Comment by Evolvee** [comment]
fixed in next rev
