### ISSUE TITLE
[Vile] missing 'scavenge' animation / possible missing spell

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#835]
**Description**: [Vile](https://www.wowhead.com/npc=29769/vile) is an NPC {ID: 29769}. Located in Icecrown, he is needed for the quest Free Your Mind. He is known for standing by some boxes and performing a 'scavenge' animation.

**Current behaviour**: 
1. Vile performs no 'scavenge' animation. 
2. Vile does not perform [Enrage](https://www.wowhead.com/spell=56646/enrage) {Spell ID: 56636}

**Expected behaviour**:
1.  When not in combat, Vile will often perform a 'scavenge' animation. This animation is best shown in the videos below.
2. I am uncertain, but Vile should perform [Enrage](https://www.wowhead.com/spell=56646/enrage). See Evidence 1

**Revision**: 1294

Evidence:

1. [Wowhead ](https://www.wowhead.com/npc=29769/vile#abilities) - Vile's Abilities page.
2. [Video from 2015](https://www.youtube.com/watch?v=w_ARDRdFMwA&t=94s&ab_channel=GitGudGuides). Better quality, shows multiple 'scavenge' animations.
3. [Video from 2013](https://youtu.be/Az8flqwZ540?t=41). Shows 'scavenge' animation.

**Comment by Evolvee** [comment]
fixed in next rev
