### ISSUE TITLE
[Valiance Commando] missing spells

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#837]
**Description**:  [Valiance Commando](https://www.wowhead.com/npc=31414/valiance-commando#abilities) is an NPC located in Icecrown. {ID: 31414}

**Current behaviour**: Valiance Commando does not cast [Detterence](https://www.wowhead.com/spell=31567/deterrence) or [Puncture Armor](https://www.wowhead.com/spell=35918/puncture-armor) {Spell ID 31567 and 35918 respectively}

**Expected behaviour**: Valiance Commando should cast Deterrence and Puncture Armor

**Revision**: 1294

Evidence:
Wowhead Ability Page:
https://www.wowhead.com/npc=31414/valiance-commando#abilities

**Comment by Evolvee** [comment]
fixed in next rev
