### ISSUE TITLE
[Core] Quests that have you talk to an NPC don't show as (Complete) in the quest log

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Fordring#842]
Currently: Quests that have you talk to another NPC for completion (typically breadcrumb quests) don't show as (Complete) in the questlog next to the quest

How it should work: These quests should be marked as (Complete)

**Comment by Wolffenstein** [comment]
?

**Comment by Godmatik** [comment]
Example:
https://classic.wowhead.com/quest=6541/report-to-kadrak

This quest just has you talk to an NPC in the barrens, a breadcrumb to go to Ashenvale.

It should be marked as (complete) in your quest log after you pick it up, because the quest is complete, all you have to do is talk to the NPC.

But it doesn't show as (complete) in the log.

Best way I can explain it...

**Comment by Godmatik** [comment]
Closing, new core now
