### ISSUE TITLE
[Hungering Plaguehound][Icecrown] missing sleep animation

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#852]
**Description**: [Hungering Plaguehound](https://www.wowhead.com/npc=30952/hungering-plaguehound) is an NPC in the Weeping Quarry of Icecrown. There are two particular areas of the Weeping Quarry: The Far West End and the North-East Corner. In each area, there are multiple Plaguehound models that are completely un-targettable and do not attack.

**Current behaviour**: These specific models just stand and do nothing.

**Expected behaviour**: These specific models should be in sleep animation. They are meant to be untargetable.

**Revision**: 1294

Evidence:

-[ Hectic video from 2015.](https://youtu.be/FmJRsvaRo90?t=79). shows dogs sleeping

- SF picture:
![image](https://user-images.githubusercontent.com/105084838/170893639-da9802cc-71ad-4e92-836d-1ab21ec6710b.png)

**Comment by Cold-Martijn** [comment]
I don't think this is a bug, I rather think these dogs were fed some sleepy meat from the quest with the Eidolon watcher.

**Comment by FX-SF** [comment]
@Cold-Martijn: I'm certain some plaguehounds are meant to be untargetable and in sleeping animation, possibly to notify the player on how the mobs should look while doing the quest or to add flavor to the quest.

Some more Evidence and time stamps:

1. [Video 1 @2:34](https://youtu.be/TjbHF64-ERk?t=154) shows these to specific plaguehounds sleeping
2. [Video 2 @1:49]( https://youtu.be/TjbHF64-ERk?t=109) shows a couple more sleeping plaguehouds
3. [Video 3 @2:27](https://youtu.be/TjbHF64-ERk?t=147) shos another sleeping plaguehound. These things are actually littered across the quarry, untargetable and sleeping.

These plaguehounds are always the same untargettable, unfed NPCs. There are, of course, other plaguehounds that you cant interact with, fight, and give food, But these ones are specifically cosmetic. 

Here is another video:

1. [Video 4 @1:23](https://youtu.be/G1LcUWYyBlU?t=83) shows the ones in the Far West End corner.
2. [Video 5 @1:52](https://youtu.be/G1LcUWYyBlU?t=112) some more plaguehounds sleeping. These mobs ere not given quest food.
