### ISSUE TITLE
[The Fate of Bloodbane][Icecrown] multiple issues (quest is completable)

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#864]
**Description**: [The Fate of Bloodbane](https://www.wowhead.com/quest=13164/the-fate-of-bloodbane) is an elite, 5-man quest in Icecrown. During the quest, you are tasked with defeating [Orbaz Bloodbane](https://www.wowhead.com/npc=31283/orbaz-bloodbane#abilities). At some point, [Highlord Darion Mograine](https://www.wowhead.com/npc=31290/highlord-darion-mograine#abilities) enters the battle and just wrecks on Orbaz.

**Current behaviour**:

1. The spell effect of Dark Lightning is fixed to a location and does not move. 
2. Early in the fight, Orbaz casts [Empower Runeblade](https://www.wowhead.com/spell=61015/empower-runeblade)
3. The spell animation of Dark Lightning is very low to the ground, hiding most of the spells animation from the player.
4. All at the start of the battle, Orbaz yells his first 4 dialog's, one after the other, finally ending with the chuckle emote.
5. Upon the death of Orbaz, Mograine never runs to any specific location, eventually de-spawning.
6. After defeating Orbaz, Mograine will frequently engage nearby adds in combat.

**Expected behaviour**: 

1. The 'orb' spell effect of Dark Lightning moves very slowly in a straight line. On occasion, the 'orb' will change directions, usually heading straight towards a player (or pet, i.e.). (See [@2:47](https://youtu.be/WO-E2craHms?t=167))
2. Orbaz should only cast [Empower Runeblade](https://www.wowhead.com/spell=61015/empower-runeblade) at 60% (see [@2:19](https://youtu.be/WO-E2craHms?t=219))
3. The spell animation of Dark Lightning should be 3-4x higher above the ground than it is, showing off the spell in its intended glory. (see [@2:47](https://youtu.be/WO-E2craHms?t=167))
4. Orbaz should says his first 3 dialog's at intervals 100%, 80%, and 60% respectively. The rest of Orbaz's and Mograine's dialog should occur at 40%, starting with Orbaz's line "It all ends here." 
5. A few seconds after saying "Good riddance.", High Warlord Mograine will run to a specific location, not attacking anyone, and finally de-spawning at the specific location. (See [@0:52](https://youtu.be/03cAogE6fuU?t=52), different video than others)
6. Mograine should never engage nearby adds in combat.

**Revision**: 1309

Evidence:

-[Main Source](https://www.youtube.com/watch?v=03cAogE6fuU&ab_channel=GitGudGuides): Epic 2009 warlock solo video. Recommend :D

-[Orbaz Bloodbane](https://www.wowhead.com/npc=31283/orbaz-bloodbane#comments) Wowhead Comments:
![image](https://user-images.githubusercontent.com/105084838/170917358-b269f9b8-3a7a-48dd-95c4-5d23ac7fcdab.png)

**Comment by slicplaya** [comment]
I can't even get the area to phase in to fight him, and i have teh damn quest.

**Comment by Exorcista** [comment]
> I can't even get the area to phase in to fight him, and i have teh damn quest.

Can confirm, just encountered this phasing bug, 3/4 of my grp coudn't do it, they said they did the Arthas quest so maybe it caused a phasing issue, they can't see Bloodbane or any npc, meawhile i didn't do arthas chain and was able to do it
