### ISSUE TITLE
Weapon on display even though the weapon is red.

### ISSUE THREAD

**Issue by Pinnen123** [Stormforge-gg/Bugtracker-Fordring#880]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

It seems that the weapon is still on display when it is broken. Shouldn't it be tucked away/invisible and you hit with your fists? 

Adding a screenshot displaying the weapon and in the minimap the durability displays a broken weapon. 

![image](https://user-images.githubusercontent.com/106036315/171052376-6d2dac78-dcc9-4216-8995-52d2df62ffe5.png)

**Comment by Vishiswaz** [comment]
Confirmed.

Unarmed weapon skillup also happens despite me hitting things visually with my mace. So it's probably just a visual bug.
