### ISSUE TITLE
[NPC][Spell][Howling Fjord] Chillmere Coast

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Fordring#881]
**Expected behaviour**: 

 - [Necrotech](https://www.wowhead.com/npc=24540/necrotech) they shouldn't have random movement.
![image](https://user-images.githubusercontent.com/4455568/171057420-b382957f-7204-444d-a9e9-4ce7d892fac7.png)
 - [Old Icefin](https://www.wowhead.com/npc=24544/old-icefin)  When I took the quest, generally when we wanna talk to him he doesn't say the most common word "mrgl".
![image](https://user-images.githubusercontent.com/4455568/171057499-083fcfdc-c4fe-4886-a24f-62edb162f7e7.png)

**Revision**: 
1309

**Comment by Cold-Martijn** [comment]
Fixed: 
[Servitor Shade](https://www.wowhead.com/npc=24485/servitor-shade) should use [Blink Strike](https://www.wowhead.com/spell=49961/blink-strike).
[Mur’ghoul Flesheaster](https://www.wowhead.com/npc=23644/murghoul-flesheater#abilities) should use [Consume Flesh](https://www.wowhead.com/spell=37933/consume-flesh)

Works for me:
[Chillmere Oracle](https://www.wowhead.com/npc=24461/chillmere-oracle#comments) should use [Hex of the Murloc](https://www.wowhead.com/spell=49935/hex-of-the-murloc)

**Comment by eryczek1615** [comment]
![image](https://user-images.githubusercontent.com/4455568/171267506-65faab3c-ce0f-4a53-a9d4-64b0278c171e.png)
He have tried it again and no Hex in my case, i think there should be at least "Hex of the Murloc misses you"

**Comment by Cold-Martijn** [comment]
Try to run away from him, it will not use Hex of the murloc in melee distance. If you can find proof that it should fire in melee, please post it here so that an actual developer (i only do database stuff) can fix the spell itself.

**Comment by eryczek1615** [comment]
I'm confused now :D for me this spell doesn't work. I kept him even at distance and still no Hex. And what about mele, there is comment but this is Legion expansion, (and only model has been changed at 7.0.3) . There is written about letting Hati to tank to get Hex (he's mele).

![image](https://user-images.githubusercontent.com/4455568/171469564-ccb827ba-ec39-4d42-8b2e-3ec224d1b462.png)
