### ISSUE TITLE
[Not-So-Honorable Combat][Icecrown] incomplete RP

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#899]
**Description**:  [Not-So-Honorable Combat](https://www.wowhead.com/quest=13137/not-so-honorable-combat) is a 5-man quest located in Icecrown. During the quest, you will encounter [Possessed Iskalder](https://www.wowhead.com/npc=30924/possessed-iskalder), [Vardmadra](https://www.wowhead.com/npc=30945/vardmadra), and [Lady Nightswood](https://www.wowhead.com/npc=30955/lady-nightswood).

**Current behaviour**: Some dialog is missing in the encounter.

**Expected behaviour**:There should be additional dialog in the encounter (See [video](https://youtu.be/ejN0_H_6t6U))

**Revision**: 1330

Current Behavior:
![image](https://user-images.githubusercontent.com/105084838/171090334-0f40f0a1-e0d9-4da7-bd5e-14b8d5fe56e5.png)

Expected Behavior:
![image](https://user-images.githubusercontent.com/105084838/171091092-bd13bfb1-69be-408b-ba7e-fd6cd17d8518.png)

**Comment by FX-SF** [comment]
Needs more research

**Comment by Drevil-Dion** [comment]
https://youtu.be/ejN0_H_6t6U

The sections you have marked are not shown in the players chat box

**Comment by FX-SF** [comment]
Video is amazing!!! 2 of the dialog options are in the chat box. The 3 that are in brackets were not.
![image](https://user-images.githubusercontent.com/105084838/171107542-4703bdef-91cf-463c-8c24-c5e803bb53b3.png)
