### ISSUE TITLE
[Visual] Herbs sparkle when you don't have herbing

### ISSUE THREAD

**Issue by Godmatik** [Stormforge-gg/Bugtracker-Fordring#915]
Herbs give off the 'sparkling' animation like it is something for you to loot, however I think it only should do that if you have trained in herbalism

![Herbs sparkle](https://user-images.githubusercontent.com/37913400/171290458-33fc12fe-d05f-43b2-bf70-947b53ffbd4d.png)

**Comment by Vishiswaz** [comment]
Actually are they supposed to sparkle at all in wotlk? I thought that was a post-wotlk feature.

**Comment by Godmatik** [comment]
Yes Wrath added the sparkles in for quest items, herbs, etc. 

I just don't recall seeing the visual from herbs unless you picked up the profession. I could be wrong though.

**Comment by Vishiswaz** [comment]
If that's the case it should only be when you're tracking that node type.

**Comment by Godmatik** [comment]
Only the ones in Outland appear to do this, not the vanilla herb nodes.

**Comment by Vishiswaz** [comment]
I'm getting this with a Tin Vein in Redridge
![WoWScrnShot_060722_201845](https://user-images.githubusercontent.com/78314117/172505282-963315ab-ec31-47cd-83fa-c4d367dc59be.jpg)
.

**Comment by Godmatik** [comment]
Closing, new core now
