### ISSUE TITLE
[NPC][Northend] Rare spawns

### ISSUE THREAD

**Issue by eryczek1615** [Stormforge-gg/Bugtracker-Fordring#936]
I checked all rares and:
**This rare has no waypoints**:
 - [Grocklar](https://www.wowhead.com/npc=32422/grocklar) 
 - [Seething Hate](https://www.wowhead.com/npc=32429/seething-hate)
 - [Syreian the Bonecarver](https://www.wowhead.com/npc=32438/syreian-the-bonecarver)
 - [Griegen](https://www.wowhead.com/npc=32471/griegen) 
 - [Tukemuth](https://www.wowhead.com/npc=32400/tukemuth)
 - [Crazed Indu’le Survivor](https://www.wowhead.com/npc=32409/crazed-indule-survivor)
 - [Scarlet Highlord Daion](https://www.wowhead.com/npc=32417/scarlet-highlord-daion)
 - [Icehorn](https://www.wowhead.com/npc=32361/icehorn) 
 - [Old Crystalbark](https://www.wowhead.com/npc=32357/old-crystalbark)
 - [High Thane Jorfus](https://www.wowhead.com/npc=32501/high-thane-jorfus)
 - [Hildana Deathstealer](https://www.wowhead.com/npc=32495/hildana-deathstealer)
 - [Dirkee](https://www.wowhead.com/npc=32500/dirkee)
 - [Aotona](https://www.wowhead.com/npc=32481/aotona)
**Not sure about movement of this rares below**: now they have random movement, on videos it looks like more designed.
 - [Loque’nahak](https://www.wowhead.com/npc=32517/loquenahak)
 - [Arcturis](https://www.wowhead.com/npc=38453/arcturis) 
 - [Gondria](https://www.wowhead.com/npc=33776/gondria) 
 - [Terror Spinner](https://www.wowhead.com/npc=32475/terror-spinner)

**Doesn't use spells**:
 - [Zul’drak Snetinel](https://www.wowhead.com/npc=32447/zuldrak-sentinel) doesn’t use spell [Whammy](https://www.wowhead.com/spell=54565/whammy)
 - [Tukemuth](https://www.wowhead.com/npc=32400/tukemuth) doesn’t use spell [Trample](https://www.wowhead.com/spell=57066/trample).
 - [Arcturis](https://www.wowhead.com/npc=38453/arcturis) doesn’t use his spells, [Frozen Bite](https://www.wowhead.com/spell=61186/frozen-bite) and [Pounce](https://www.wowhead.com/spell=61184/pounce)
 - [Gondria](https://www.wowhead.com/npc=33776/gondria) doesn’t use spells [Frozen Bite](https://www.wowhead.com/spell=61186/frozen-bite) and [Pounce](https://www.wowhead.com/spell=61184/pounce)
 
**Other bugs**:
 - [Terror Spinner](https://www.wowhead.com/npc=32475/terror-spinner) seems to have one spawn location
 - [Syreian the Bonecarver](https://www.wowhead.com/npc=32438/syreian-the-bonecarver) sometimes she stops shooting and just stands in one place doesn’t even walk to us.
 - [Icehorn](https://www.wowhead.com/npc=32361/icehorn) should be rare-elite not just rare.
 - [Dirkee](https://www.wowhead.com/npc=32500/dirkee) has no quotes:
**I.am.a.robot.
Mulfunction. Error Code: .- .- .-**

**Couldn't find  [Skoll](https://www.wowhead.com/npc=35189/skoll) so idk how he works now.**

**Revision**: 
1358

**Comment by Vishiswaz** [comment]
That Vyragosa bug is really important, since its spawn is linked to Time-Lost Proto Drake.

**Comment by Cold-Martijn** [comment]
> 

this should be fixed already :) in fact, there is another report now that she isnt spawning at all haha

**Comment by Viryll** [comment]
Skoll exists. Saw it dead once.
As for Dirkee...
![image](https://user-images.githubusercontent.com/98886485/173181019-8a63aad9-40e0-427b-9033-78c19f77ab27.png)
Should he spawn down there??
