### ISSUE TITLE
Hunter's Explosive Trap not working

### ISSUE THREAD

**Issue by TheMisfist** [Stormforge-gg/Bugtracker-Fordring#947]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Hunter's Explosive Trap not working

**Current behaviour**: When triggered it dissapears and does nothing, 0 dmg

**Expected behaviour**: Working every time its triggered, duh

**Revision**:

**Comment by slicplaya** [comment]
It's not just explosive trap. Traps are getting eaten(just poof with no resist or combat log action). It's very common on fresh private servers.  Also, snake Trap doesn't ensnarement(SV talent) when a mob walks through it, but if you place it in a mob, ensnarement works.

**Comment by Awkakelen** [comment]
> It's not just explosive trap. Traps are getting eaten(just poof with no resist or combat log action). It's very common on fresh private servers. Also, snake Trap doesn't ensnarement(SV talent) when a mob walks through it, but if you place it in a mob, ensnarement works.

This is true, tried it

**Comment by therealCrysis** [comment]
I have problem with reproducing it. Explosive trap worked fine for me.

Need more details.

**Comment by slicplaya** [comment]
It's not just explosive trap, it's snake trap as well. The traps just disappear without any interaction/proc. If the trap is dropped directly at the feet of a target it works most of the time, but if i say place a snake/explosive trap at X location, and an npc at Y location is chasing me and runs through X location, it fails about 40% of the time. It's a problem I've come across on a few private servers over the years.

**Comment by Wolffenstein** [comment]
Fixed in rev 1463.
