### ISSUE TITLE
Scarlet Monastery

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#948]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The door to the cathedral (inside the instance) says it requires the Scarlet Key. I believe this was removed when the Dungeon Finder was made, or at least for groups that go in via RDF. Lots of groups getting stuck at the door at the moment.

Also, Herod's door in Scarlet Monastery Armory.

**Comment by NatsumeLily** [comment]
Same thing might be true for Stratholme's Scarlet Bastion. Haven't tested that one.

**Comment by Cold-Martijn** [comment]
Same for BRD Upper City

**Comment by Tereneckla** [comment]
Fixed in 1393
