### ISSUE TITLE
[Redrodge][NPC]Bellygrub

### ISSUE THREAD

**Issue by TheRealestMcCoy** [Stormforge-gg/Bugtracker-Fordring#949]
**Description**: 
Kill bellygrub 1 of them
**Current behaviour**:
Multiple spawned 
**Expected behaviour**: 
1 should only be spawned
**Revision**: 
1390

**Comment by Cold-Martijn** [comment]
Core issue, same for example for Hogger.

**Comment by Wolffenstein** [comment]
Fixed in rev 1413.
