### ISSUE TITLE
 [Not tested] Vote kick giving deserter

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#950]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  I personally haven't tested it but people on discord are reporting that getting vote kicked gives you dungeon deserter. We didn't see this on the beta ptr but might need to check in on it.

**Comment by Wolffenstein** [comment]
Fixed in rev 1471.
