### ISSUE TITLE
No heavy leather from mobs when skinning - only heavy hides.

### ISSUE THREAD

**Issue by bjacktrack** [Stormforge-gg/Bugtracker-Fordring#954]
**Description**: 
When you skin dead animals you get heavy hides only.
**Current behaviour**:
You get heavy hides only

**Expected behaviour**: 
You get a chance for heavy hides and usually you get heavy leathers.
**Revision**: 
139
![123](https://user-images.githubusercontent.com/45602341/171999353-b71c2d7e-a204-4dcc-b9d4-b2f9d2cfd1d9.jpg)
4

**Comment by Wolffenstein** [comment]
Should be fixed now. If not, please open a new one
