### ISSUE TITLE
Levelling inscription past 200 is impossible

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#955]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
blindweed/sungrass/firebloom tier herbs drop only crimson pigment when milled. 0 Violet pigment. This means no celestial inks and no inscription.

Prior herb tiers dropped all common inks and 0 rare inks. Other herb tiers should be checked as well.

**Comment by Wolffenstein** [comment]
Should be fixed now. If not, please open a new issue
