### ISSUE TITLE
Iron in Thousand Needles always dropping Jade

### ISSUE THREAD

**Issue by Ad0ntis** [Stormforge-gg/Bugtracker-Fordring#958]
[//]: # (Zone] Thousand Needles

Either I'm the luckiest person on the server, or mining Iron nodes in thousand needles always drops a Jade.

**Current Behavior**: 100% mining rate for Jade in Thousand needles

**Expected behaviour**: Chance of jade, but not 100%

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed now
