### ISSUE TITLE
[Skinning] Hide

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#960]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I can't be entirely sure of this issue without being able to look at loot tables, but it appears as if hides are either completely not in the loot tables or way too low. I've done a lot of skinning and gotten a total of 2 light hides..... from a chest. None from skinning. Usually on other servers you get _too many_, not too few.

**Comment by Godmatik** [comment]
Related:

https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/954

**Comment by Wolffenstein** [comment]
Should be fixed now. If not, please open a new one
