### ISSUE TITLE
[Dungeon][NPC] Arcanist Doan no drop

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Fordring#961]
**Description**: 
[Arcanist Doan ](https://classic.wowhead.com/npc=6487/arcanist-doan) npc=6487 didn't drop anything once we killed it in Scarlet Monastery Library in RDF group, and it was not after a crash, seems to not happen everytime

**Revision**: 
1394

**Comment by Wolffenstein** [comment]
Fixed now
