### ISSUE TITLE
[Item] Darkwater Clam (item=36781) [Drop] Siren's Tear:  drop chance probably too high

### ISSUE THREAD

**Issue by Lmdezorn** [Stormforge-gg/Bugtracker-Fordring#962]
**Description**: The drop chance of Siren's Tear (item=36784) by Darkwater Clams (item=36781) is probably too high, at least when the Darkwater Clam is dropped by a Mistwhisper Warrior (npc=28109) or a Mistwhisper Oracle (npc=28110).

**Current behaviour**: In a sample of 4 Darkwater Clams looted during my session this afternoon in the Mistwhisper camp in Sholazar Basin, every single one of those 4 clams dropped a Siren's Tear. 

The sample I used to draw my conclusion is unfortunately narrow. But the behaviour is exceptional enough to push me into writing this report without taking the time of expanding the sample of study (I'm too tired to log back into the game tonight anyway).

**Expected behaviour**: Tbh, I don't know what value should be the correct one (Wowhead's output is "??" so one may to dig far deeper to determine the exact number), but the value shouldn't be close to 100%. Granted, the probability that I have been witness to an insane lucky draw is not zero, so the possibility that I jumped the gun too soon is out there as well.

**Revision**: [Revision at 13:00-14:00 today for the server]

**Comment by Wolffenstein** [comment]
This should be fixed now
