### ISSUE TITLE
[NPC][Teldrassil] Young Thistle Boar

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Fordring#964]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
These mobs are currently skinnable. I believe all the mobs in the level 1-5 areas of the starting zones should not be skinnable.

Same thing for Thistle Boar.

**Comment by NatsumeLily** [comment]
Might not be a bug? 
The classic DB has a skinning tab for these. And I also found this comment but it's from a later point in time. 

https://www.wowhead.com/npc=1984/young-thistle-boar#comments:id=2060876

**Comment by NatsumeLily** [comment]
https://us.forums.blizzard.com/en/wow/t/cant-skin-boars-wolves-in-dwarf-starting-area/246070

**Comment by Evolvee** [comment]
fixed in next rev
