### ISSUE TITLE
[Core] Control Other Players .XPrate

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#967]
**Description**: 
Without fail, everytime I join a dungeon party, someone eventually complains that the XP is horrible (42xp per kill). 
I am the cause.

**Current behaviour**: By setting my XP rate to 0.5x in a dungeon, everyone will be forced to receive 0.5x rates as well.

**Expected behaviour**: Players should NOT BE ABLE to control other players XP rates

**Revision**: 1394

How to recreate:
Join RDF, have it pop and enter the dungeon.
Change your XP rate to a very low number,
Teammates will (possibly not right away) eventually receive low XP rates, and they will complain!! 😆

**Comment by FX-SF** [comment]
Pls fix people hate me now 😭

**Comment by Wolffenstein** [comment]
Well it's not necessarily controlling, the group xp reward is initiated based one of the players so if it happens to be the one with lowest rate it will drag everyone down. Still a bug

**Comment by FX-SF** [comment]
Ah your information is always eye opening 🗡️

**Comment by Wolffenstein** [comment]
Fixed in rev 1408.
