### ISSUE TITLE
[NPC][The Nexus] Anomalus

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Fordring#968]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Forgot to report this one in beta. 

**Current behaviour**: Anomalus can summon "fake" rifts. When he summons a rift that gives him Rift shield, you have to kill all the rifts to remove the shield. 

**Expected behaviour**: Anomalus summoning "fake" rifts that just do damage and summon adds is correct. But only killing the rift that gives him the shield should remove it. You shouldn't need to kill all the rifts. 

![image](https://user-images.githubusercontent.com/15247730/172029215-8ad9a49a-04a4-4b0e-aef5-479e0fd8ff51.png)
https://www.wowhead.com/npc=26763/anomalus#comments:id=456001

**Revision**: 1395

**Comment by Nihaobeachez** [comment]
Had no issues doing him, he summoned 1 Rift which gave him the Shield and another one which could be ignored, because Anomalus was targetable.

**Comment by Wolffenstein** [comment]
Idk about this one, need more info and proofs
