### ISSUE TITLE
[Razorfen Downs] 10-30 Mobs agroed out of nowhere

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#969]
**Description**: 

- 2 times I have done Razorfen Downs as tank. 
- Upon Mordresh Fire Eye's death, the party becomes overwhelmed by a pack of agroed mobs, especially if they begin the next pull before they notice the pack is coming. 

**Current behaviour**: 

- Occasionally, after engaging and defeating Mordresh Fire Eye, a large group of mobs appear. 
- They appear agroed from a very far distance.
- The second time I noticed Glutton as part of the pack.

**Expected behaviour**: 

- Entering combat with Mordresh should only agro the non-elite skeletons that are within a set distance from him (within 100 yards, for example)
- Entering combat with Mordresh should not agro other mobs, including Glutton or any other elite mob.

**Revision**: 1394

How to Reproduce:

- Enter Razorfen Downs and work your way to Mordresh Fire Eye.
- Engage combat with Mordresh Fire Eye and kill him.
- Notice the character still in combat
- After about 1 minute max, the pack of agroed mobs will appear.
-

**Comment by NatsumeLily** [comment]
Reported #681.

**Comment by FX-SF** [comment]
Closing since this is reported in #681
