### ISSUE TITLE
[Hammer of Wrath][Paladin] shows reactive spell on UI for dead npc.

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#971]
**Description**: A person in discord states that Hammer of Wrath is showing a reactive spell emote on his UI, even while targeting a dead mob. Another person in disc points that this is a blizzlike bug. To be safe, the ticket is written:

**Current behaviour**: Paladin's Hammer of Wrath reactive spell occurs when targeting a dead mob.

**Expected behaviour**: Paladin's Hammer of Wrath reactive spell should not occur when targeting a dead mob.

**Revision**: 1394

![image](https://user-images.githubusercontent.com/105084838/172035253-b407a847-230b-4520-b6ea-6fd7748ac20e.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 1409.
