### ISSUE TITLE
Quest "Load'er Up!" Doesn't give credit for completion

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#973]
**Description**: Quest "Load'er Up!" Doesn't give credit

**Current behaviour**: Upon returning the Mule 'Jenny' to the NPC at the town where directed, the mule npc turns from green tagged to blue and slowly moves to the npc and disappears without giving credit of completion for the quest.

**Expected behaviour**: All of the above things should happen except the credit for quest completion should be given.

**Revision**:

**Comment by Evolvee** [comment]
Fixed in next rev
