### ISSUE TITLE
The Shining Light

### ISSUE THREAD

**Issue by maiksten** [Stormforge-gg/Bugtracker-Fordring#974]
https://www.wowhead.com/quest=11288/the-shining-light

[//]: # ([Quest][Zone] The Shining Light / Howling Fjord
[//]: # ([NPC] Ares the Oathbound
[//]: # ([Spell][Class] Shining Light

**Description**:  When running into the Ghouls they still attack me shortly and dont explode. I have the Buff Shining Light which should protect me from them. I cant run through to get the Sacred Artifact because theres to many. 

**Current behaviour**: Ghouls aggro me and hit me. No way to get through.

**Expected behaviour**: Ghouls explode or run away in fear

**Revision**: 1394

**Comment by Evolvee** [comment]
fixed in next rev
