### ISSUE TITLE
[Item][Quest] Arcanum of Torment

### ISSUE THREAD

**Issue by Lmdezorn** [Stormforge-gg/Bugtracker-Fordring#975]
**Description**: Duchess Mynx (npc=32538) is selling 2 versions of Arcanum of Torment (item=50367 and item=44879) instead of one, and one of them (item=44879) is literally free (no cost, no reputation required).

**Current behaviour**: As stated above. Here are pictures to support my report:
![image](https://user-images.githubusercontent.com/59399784/172038815-79c15316-3823-419e-8bf9-9a3f22aa7899.png)
![image](https://user-images.githubusercontent.com/59399784/172038820-7507458f-c194-4342-869d-37747755ede6.png)

As you can see, the version [item=44879] can be seen in my bags (I ofc deleted right after ;D): first colum from the left, third row from the top.

**Expected behaviour**: Only the version [item=50367] should be sold by the quatermaster.

**Revision**: Behaviour noticed on the revision of June 5, 2022, at 8:30 am (CET)

**Comment by Evolvee** [comment]
fixed
