### ISSUE TITLE
[NPC] Onslaught Harbor Guard: stuck in a wall

### ISSUE THREAD

**Issue by Lmdezorn** [Stormforge-gg/Bugtracker-Fordring#976]
**Description**: One Onslaught Harbor Guard (npc=29330) is stuck in a wall.

**Current behaviour**: As stated in the description. Here are a few pictures of the guy (or lack thereof ^^), from various angles:
![image](https://user-images.githubusercontent.com/59399784/172039131-7fc15c65-84d0-4ba3-93f6-4475b77fd381.png)
![image](https://user-images.githubusercontent.com/59399784/172039140-9ac5cda8-06fb-49f9-bf55-ad692d9c7314.png)

One note: I may have aggroed him (body pull while flying), which made him follow me while I was going on the opposite bank of the river, before losing aggro on him. May it have been his return path that made him stuck in that wall?

**Expected behaviour**: I believe he should be patroling just above. 

**Revision**: Revision of the server at 7:51am (CET) on June 5, 2022.

**Comment by Evolvee** [comment]
fixed in next rev
