### ISSUE TITLE
Kill Command only works for one attack

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#978]
**Description**: Kill command Should give pet special attacks 60% increased damage reducing that buff by 20% per special attack.

**Current behaviour**: Upon initiating a special attack by the pet removes the Kill Command buff entirely after 1 successful attack.

**Expected behaviour**:  It should be 60% 1 special attack 40% 1 special attack 20% 1 special attack and the buff dissipates.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1410.

**Comment by slicplaya** [comment]
Author: Wolffenstein
Summary: [1410][Core] Spell Fixes
[Core/Hunter]:
- Fixed an issue with Kill Command being removed after just one proc
- Auto-Shot will no longer fire while channeling Volley
Today at 10:24 AM

Neither one of those is fixed yet. I just tested both.

**Comment by slicplaya** [comment]
I also just tested with Growl. Growl removes 1 stack(it shouldn't), and Bite from a Ravager removes the other 2 or all stacks when it has 3 left(Kill Command buff).
