### ISSUE TITLE
 Hunter Pets are using their NPC attributed attacks while tamed

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#979]
**Description**:  Hunter pets are using their NPC attributed attacks as if they weren't tamed.

**Current behaviour**: Example, The Ravager Hatchling in Hellfire Peninsula casts Ravage(knock down stun) every 10 seconds. The pet does this automatically, and doesn't consume/use the Player given pet special attack "ravage". There are 2 versions of "Ravage", the player's and the NPC attributed attack.

**Expected behaviour**: NPC tameable beasts should not attack with their special attacks once tamed. lol..

**Revision**:

**Comment by Cold-Martijn** [comment]
fixed with incoming restart.
