### ISSUE TITLE
[Quest][Zone]Of Keys and Cages 11231, Howling Fjord

### ISSUE THREAD

**Issue by Nihaobeachez** [Stormforge-gg/Bugtracker-Fordring#980]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  During this Quest you have to kill NPC's to loot keys, so you're able to free the Prisoners. There's 1 big Cage with several prisoners in it, which you can unlock by using [Large Gjalerbron Cage Key] 33290

**Current behaviour**: Using [Large Gjalerbron Cage Key] 33290 to free the prisoners from the big cage doesnt give credit to the quest

**Expected behaviour**: You should get credit using [Large Gjalerbron Cage Key] 33290 

**Revision**:

**Comment by Tereneckla** [comment]
Fixed in a soon-ish revision
