### ISSUE TITLE
Traps are not proccing and disappearing with no interaction based on range of target acquisition.

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#981]
**Description**:  Traps are not proccing and disappearing with no interaction based on range of target acquisition.

**Current behaviour**: Traps seem to disappear/poof/get eaten with no resist or hit or interaction depending on the range targeting acquisition. Even having Ensnarement talent doesn't help the acquisition of a target. Forcing players to set traps directly on targets with a chance of it failing still.

**Expected behaviour**: Traps should successfully find a target given within their range and activate the trap's behavior.

**Revision**:

**Comment by FX-SF** [comment]
revision: 1394

Similar issue: #92

**Comment by Cold-Martijn** [comment]
duplicate? https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/947

**Comment by slicplaya** [comment]
Might be related to those posts, but this is more explicit on traps in general, not just explosive trap.

**Comment by Wolffenstein** [comment]
This should have been resolved in revision 1395. Is it still happening?

**Comment by slicplaya** [comment]
Yes

**Comment by slicplaya** [comment]
It's very testable with Snake trap as well as explosive trap. Ensnarement doesn't proc on mobs, but snakes still spawn because of the way it's coded. But explosive traps just poof.

**Comment by Kuszki** [comment]
I can confirm that Ensnarement effects occurs only sometimes. For now i didn't found out how to reproduce right and bad trigger scenario.

**Comment by slicplaya** [comment]
> I can confirm that Ensnarement effects occurs only sometimes. For now i didn't found out how to reproduce right and bad trigger scenario.

I get the same thing, with snake and frost traps. If the trap is placed on a mob it works, if it's placed and you kite a mob through it, it fails almost 8/10 times to ensare. Been having issues reproducing explosive traps poofing lately tho.

**Comment by Wolffenstein** [comment]
Should be fixed in rev 1463.
