### ISSUE TITLE
Hunter Volley and Auto Shot

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#982]
**Description**:  Auto Shot continues while channeling Volley.

**Current behaviour**: Currently, if Auto Shot is active/toggled on, Channeling Volley does not "pause" the shot timer, and allows a player to successfully Auto Shot while channeling Volley. This is insanely incorrect.

**Expected behaviour**: While Channeling Volley, Auto Shot Timer should continue, but the Shot action should pause while the channeling is active.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1410.

**Comment by slicplaya** [comment]
Author: Wolffenstein
Summary: [1410][Core] Spell Fixes
[Core/Hunter]:
- Fixed an issue with Kill Command being removed after just one proc
- Auto-Shot will no longer fire while channeling Volley
Today at 10:24 AM

Neither one of those is fixed yet. I just tested both.
