### ISSUE TITLE
[Quest][HellfirePeninsula] From the Abyss

### ISSUE THREAD

**Issue by Grimtwo** [Stormforge-gg/Bugtracker-Fordring#983]
**Description**:  When I use the item Warp Rift Generator Use : Activate near the void stones in Void Ridge. The item is instant cast as its suppose to be. However when I use the item it does not summon Void Baron Galaxis or his minions as its suppose to. I have tried about 15 times and have had no luck spawning it. 

**Current behaviour**: using Item does not summon Void Baron Galaxis 

**Expected behaviour**: Suppose to summon Galaxis so you can kill him for his soul shard

**Revision**:

**Comment by FX-SF** [comment]
Quest has had issue in the past:  #594

**Comment by Cold-Martijn** [comment]
fixed with restart.
