### ISSUE TITLE
[Quest][Dragonblight] In Service of the Unholy

### ISSUE THREAD

**Issue by csacsaa** [Stormforge-gg/Bugtracker-Fordring#984]
Description: The quest NPC in the Ruby Dragonshrine (Dragonblight), Duke Vallenhal is not working as intended,you can't attack him.  

Current behaviour: Can't engage in combat with Duke Vallenhal, it says: You cannot attack that target.
![bug](https://user-images.githubusercontent.com/106911773/172048186-2f46cfab-9304-4557-a9c1-a79bcc742446.PNG)

Expected behaviour: You need to get Duke Vallenhal below 35% to use the Unholy Gem (its provided) on him to complete the quest.

**Comment by therealCrysis** [comment]
Fixed.
