### ISSUE TITLE
[Quest] In Service of the Unholy

### ISSUE THREAD

**Issue by Tyaljz** [Stormforge-gg/Bugtracker-Fordring#985]
**Description**: 
Mob can't be hit

**Current behaviour**: 
The mob is immune to attacks, abilities, the stone is not used on it

**Expected behaviour**: I would like the mob to be active and be susceptible to attacks

**Revision**: 
![image](https://user-images.githubusercontent.com/106912010/172048175-52c363e7-2fc3-463d-98ba-07478a9f6614.png)
https://www.wowhead.com/quest=12126/in-service-of-the-unholy

**Comment by therealCrysis** [comment]
Fixed.
