### ISSUE TITLE
NPCs and Shaman Totems 

### ISSUE THREAD

**Issue by Thatweirdguy2** [Stormforge-gg/Bugtracker-Fordring#986]
[Core] [Shaman]

Description: Inappropriate Hostile NPC interaction with Totems and the Shaman who deployed them

Current behaviour: After destroying the totem that entered their aggro range the NPC  go "Understandable, have a good day" mode and ignore the Shaman

Expected behaviour: The NPC should chase the Shaman and daze him until the day he dies in real life

Revision:

**Comment by Cold-Martijn** [comment]
https://github.com/Stormforge-gg/Bugtracker-Wotlk/issues/358

note to dev for easier closing.

**Comment by Wolffenstein** [comment]
Fixed in rev 1415.
