### ISSUE TITLE
[Talent][Paladin] Sanctified Retribution

### ISSUE THREAD

**Issue by Pinstripelli** [Stormforge-gg/Bugtracker-Fordring#987]
**Description**: Visual bug only, related to Retribution Aura display in the buff bar

**Current behaviour**: Retribution Aura displays the damage as if it was without the talent.

**Expected behaviour**: Should take the value from when you have the talent (50% increase)

**Revision**:

**Comment by haephaistoss** [comment]
In wotlk buffs don't update, client side, not server side. Most buffs behave this way.
