### ISSUE TITLE
Bugged quest: Dragonblight Fresh Remounts

### ISSUE THREAD

**Issue by eldewall** [Stormforge-gg/Bugtracker-Fordring#988]
**Description**: 

([Quest][Dragonblight] Fresh Remounts)

https://www.wowhead.com/quest=12214/fresh-remounts

**Current behaviour**:

Horses spawns without [Onslaught Knight](https://www.wowhead.com/npc=27206/onslaught-knight)

**Expected behaviour**: 

Should spawn Onslaught Knigth ontop of the horse so the riding crop can be lootable

**Comment by Cold-Martijn** [comment]
This is fixed with the next update, fix already uploaded just needs a restart.
