### ISSUE TITLE
Race:  Draenei have 0 Shadow resist

### ISSUE THREAD

**Issue by hederob** [Stormforge-gg/Bugtracker-Fordring#989]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)

[//]: # ([Player][Race:  Draenei] 0 Shadow resist)

**Description**: 
Draenei players have 0 shadow resist
**Current behaviour**:
Draenei have 0 shadow resist
**Expected behaviour**: 
Draenei should have 10 shadow resist
**Revision**:

**Comment by Cold-Martijn** [comment]
https://wowwiki-archive.fandom.com/wiki/Shadow_Resistance_(draenei_ability)

not in WotLK.
