### ISSUE TITLE
Verdant Pigment not created from milling

### ISSUE THREAD

**Issue by hederob** [Stormforge-gg/Bugtracker-Fordring#990]
**Description**: 
Milling 5 Briarthorn, Mageroyal, Bruiseweed, or Stranglekelp have no chance to create Verdant Pigment.
**Current behaviour**:
Milling these herbs have no chance to create Verdant Pigment.
**Expected behavior**: 
Milling these herbs have a 25-50% chance to create Verdant Pigment.
**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1409.
