### ISSUE TITLE
Quest: "Loot'er Up!" Doesn't complete when turned in

### ISSUE THREAD

**Issue by slicplaya** [Stormforge-gg/Bugtracker-Fordring#993]
**Description**: The quest "Loot'er Up!" In Borean Tundra doesn't complete when The mule Jenny is returned from the crash site with all cargo in tact.

**Current behaviour**: The npc mule moves to the NPC goblin in the town once turned in, and goes from a tagged green state to blue, and disappears without giving credit.

**Expected behaviour**: Once Jenny the Mule is turned in, the quest should give completion credit so it can be turned in. I, as well as others had this problem last night.

**Revision**:

**Comment by Tereneckla** [comment]
Fixed in a revision soon to come
