### ISSUE TITLE
[Drak'Tharon Keep HC] Trollgore Consume stacks won't reset

### ISSUE THREAD

**Issue by Vaash** [Stormforge-gg/Bugtracker-Fordring#994]
[Zone] Drak'Tharon Keep HC)
([NPC] Trollgore)
([Spell] Consume)

**Description**: 
The boss doesnt reset "Consume" stacks after a wipe.

**Current behaviour**:
Consume stacks arn't reseted on party wipe.

**Expected behaviour**: 
Consume stacks should be reseted on party wipe.

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1407.
