### ISSUE TITLE
[Dungeons] - WotLK heroic dungeon bosses can be slowed / stunned

### ISSUE THREAD

**Issue by Dopp0** [Stormforge-gg/Bugtracker-Fordring#995]
**Description**:  Bosses are not immune to snares/stuns (DTK Bosses confirmed - other dungeon bosses not tested but I guess if it's one its like others)

Nothing else needed to be added here.

**Comment by Wolffenstein** [comment]
Which boss specifically did you test it on and with what abilities? I see they have snare/stun immunity in the database so not sure why they wouldn't be

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/172061461-b45bf87f-b5e6-4933-ad9c-352e5e31f2e5.png)

**Comment by Wolffenstein** [comment]
Cannot reproduce either snares nor stuns, closing
