### ISSUE TITLE
[Death Knight] Gargoyle: Does not despawn after death pact

### ISSUE THREAD

**Issue by Dopp0** [Stormforge-gg/Bugtracker-Fordring#997]
**Description**: When using death pact with an active gargoyle it does not despawn and instead follows you around afk

**Current behaviour**: ^

**Expected behaviour**: The gargoyle should be destroyed / despawn and the death knight should be healed

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1412.
