### ISSUE TITLE
[Death Knight] Gargoyle: Does not / can not switch target after the initial target dies

### ISSUE THREAD

**Issue by Dopp0** [Stormforge-gg/Bugtracker-Fordring#998]
**Description**: If the target the gargoyle is summoned on dies, it cannot attack any future targets

**Current behaviour**: ^

**Expected behaviour**: The gargoyle should be commandable with /petattack | follow the death knight's target

https://clips.twitch.tv/HumbleOutstandingHumanTheRinger-HGIyR-4wr2a5Af8q

**Comment by Wolffenstein** [comment]
Fixed in rev 1412.
