### ISSUE TITLE
[Quest] Halls of Lightning

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#999]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  Quests https://wowwiki-archive.fandom.com/wiki/Quest:Whatever_it_Takes! and https://wowwiki-archive.fandom.com/wiki/Quest:Diametrically_Opposed aren't in the game at the moment. I have done the last prequest in the quest chain they are part of and they are still not available.
**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 1414.
